const lg6Sentences = [
  { original: "I have been studying English for 5 years.", chunks: ["I have been", "studying English", "for 5 years."] },
  { original: "She has been riding her bicycle since 2 o’clock.", chunks: ["She has been", "riding her bicycle", "since 2 o’clock."] },
  { original: "Has he ever been to China?", chunks: ["Has he", "ever been", "to China?"] },
  { original: "Korean is spoken in Korea.", chunks: ["Korean is", "spoken in", "Korea."] },
  { original: "I wish I could fly a helicopter.", chunks: ["I wish", "I could fly", "a helicopter."] },
  { original: "How long have you been playing soccer?", chunks: ["How long", "have you been", "playing soccer?"] },
  { original: "Have you already gone to the store?", chunks: ["Have you", "already gone", "to the store?"] },
  { original: "No, I haven’t gone to the store yet.", chunks: ["No, I haven’t", "gone to the store", "yet."] },
  { original: "What do you wish you could do?", chunks: ["What do you", "wish you could", "do?"] },
  { original: "I wish I could run a marathon.", chunks: ["I wish", "I could run", "a marathon."] },
  { original: "How long has she been talking on the phone?", chunks: ["How long", "has she been", "talking on the phone?"] },
  { original: "She has been talking on the phone for fifteen minutes.", chunks: ["She has been", "talking on the phone", "for fifteen minutes."] },
  { original: "When did you learn how to read? I learned how to read when I was six.", chunks: ["When did you learn", "how to read?", "I learned how to read", "when I was six."] },
  { original: "What are they like? They are cheerful.", chunks: ["What are they like?", "They are cheerful."] },
  { original: "Should I get my sister earrings or a scarf?", chunks: ["Should I get", "my sister", "earrings or", "a scarf?"] },
  { original: "You should get her earrings.", chunks: ["You should get", "her earrings."] },
  { original: "How do I get to the park?", chunks: ["How do I get", "to the park?"] },
  { original: "Cross the street and turn right.", chunks: ["Cross the street", "and turn right."] },
  { original: "Yes, I have.", chunks: ["Yes,", "I have."] },
  { original: "Has he washed his hands yet?", chunks: ["Has he", "washed his hands", "yet?"] },
  { original: "No, he hasn’t.", chunks: ["No,", "he hasn’t."] },
  { original: "Where are burritos eaten?", chunks: ["Where are", "burritos eaten?"] },
  { original: "Burritos are eaten in Mexico and the United States.", chunks: ["Burritos are eaten", "in Mexico", "and the United States."] },
  { original: "Where is English spoken?", chunks: ["Where is", "English spoken?"] },
  { original: "English is spoken in many countries like the USA, the UK, Canada, and Australia.", chunks: ["English is spoken", "in many countries", "like the USA,", "the UK, Canada,", "and Australia."] },
  { original: "What food is eaten in Korea?", chunks: ["What food is", "eaten in Korea?"] },
  { original: "Kimchi is eaten in Korea.", chunks: ["Kimchi is eaten", "in Korea."] },
  { original: "What language is spoken in Korea? Korean is spoken in Korea.", chunks: ["What language is spoken", "in Korea?", "Korean is spoken", "in Korea."] },
  { original: "I wish I could fly an airplane.", chunks: ["I wish", "I could fly", "an airplane."] },
  { original: "What could you do when you were 5 years old?", chunks: ["What could you do", "when you were", "5 years old?"] },
  { original: "I could ride a bike when I was 5 years old.", chunks: ["I could ride a bike", "when I was", "5 years old."] },
  { original: "When did you learn how to write Korean?", chunks: ["When did you learn", "how to write Korean?"] },
  { original: "I learned how to write Korean when I was in first grade.", chunks: ["I learned how to write Korean", "when I was in", "first grade."] },
  { original: "How long have you been studying English?", chunks: ["How long have you been", "studying English?"] }
];

export default lg6Sentences;