const eb4Sentences = [
  { original: "I have some tape.", chunks: ["I", "have", "some tape."] },
  { original: "I don’t have any glue.", chunks: ["I", "don’t have", "any glue."] },
  { original: "Do you have any markers?", chunks: ["Do you", "have", "any markers?"] },
  { original: "No, I don’t.", chunks: ["No,", "I", "don’t."] },
  { original: "What does he/she do on Mondays?", chunks: ["What does", "he/she", "do", "on Mondays?"] },
  { original: "He/She goes to computer class.", chunks: ["He/She", "goes to", "computer class."] },
  { original: "Does he go shopping on the weekend?", chunks: ["Does he", "go shopping", "on the weekend?"] },
  { original: "Yes, he does.", chunks: ["Yes,", "he", "does."] },
  { original: "No, he doesn’t.", chunks: ["No,", "he", "doesn’t."] },
  { original: "Whose towel is this?", chunks: ["Whose towel", "is this?"] },
  { original: "It’s Adam’s towel.", chunks: ["It’s", "Adam’s towel."] },
  { original: "Whose sneakers are these?", chunks: ["Whose sneakers", "are these?"] },
  { original: "They’re Peter’s sneakers.", chunks: ["They’re", "Peter’s sneakers."] },
  { original: "Is this Lisa’s raincoat?", chunks: ["Is this", "Lisa’s raincoat?"] },
  { original: "Yes, it is.", chunks: ["Yes,", "it", "is."] },
  { original: "No, it isn’t.", chunks: ["No,", "it", "isn’t."] },
  { original: "Are these Lisa’s rain boots?", chunks: ["Are these", "Lisa’s rain boots?"] },
  { original: "Yes, they are.", chunks: ["Yes,", "they", "are."] },
  { original: "No, they aren’t.", chunks: ["No,", "they", "aren’t."] },
  { original: "What’s wrong?", chunks: ["What’s", "wrong?"] },
  { original: "I have a headache.", chunks: ["I", "have", "a headache."] },
  { original: "You should go to the doctor.", chunks: ["You should", "go to", "the doctor."] },
  { original: "The fire station is across from the bank.", chunks: ["from the bank.,", "is across from", "The fire station,"] },
  { original: "Where’s the restaurant?", chunks: ["Where’s", "the restaurant?"] },
  { original: "It’s next to the supermarket.", chunks: ["It’s", "next to", "the supermarket."] },
  { original: "How do I get there?", chunks: ["How do", "I get", "there?"] },
  { original: "Go straight.", chunks: ["Go", "straight."] },
  { original: "What’s his/her job?", chunks: ["What’s", "his/her job?"] },
  { original: "He’s/She’s a baker.", chunks: ["He’s", "a", "baker."] },
  { original: "What does a photographer do?", chunks: ["What does", "a photographer", "do?"] },
  { original: "A photographer takes pictures.", chunks: ["A photographer", "takes", "pictures."] },
  { original: "How is the weather today?", chunks: ["How is", "the weather", "today?"] },
  { original: "It is sunny.", chunks: ["It is", "sunny."] },
  { original: "How was the weather yesterday?", chunks: ["How was", "the weather", "yesterday?"] },
  { original: "It was windy.", chunks: ["It", "was", "windy."] },
  { original: "Was it stormy on Sunday?", chunks: ["Was it", "stormy", "on Sunday?"] },
  { original: "Yes, it was.", chunks: ["Yes,", "it", "was."] },
  { original: "No, it wasn’t.", chunks: ["No,", "it", "wasn’t."] },
  { original: "What’s your favorite season?", chunks: ["What’s", "your favorite", "season?"] },
  { original: "My favorite season is spring.", chunks: ["My favorite", "season is", "spring."] },
  { original: "I like warm weather.", chunks: ["I like", "warm weather."] },
  { original: "What do you do in spring?", chunks: ["What do", "you do", "in spring?"] },
  { original: "I plant flowers.", chunks: ["I", "plant", "flowers."] }
];

export default eb4Sentences;
