(function(global){
'use strict';
function keyFor(activity){var m=activity&&activity.metadata||{};if(activity&&activity.skill==='grammar'&&m.mastery_content_id)return String(m.mastery_content_type||'pattern')+'|'+String(m.mastery_content_id)+'|grammar';return String(activity&&activity.sourceType||'activity')+'|'+String(activity&&activity.sourceId||'')+'|'+String(activity&&activity.skill||'');}
function stateKey(item){return String(item.content_type||'activity')+'|'+String(item.content_id||'')+'|'+String(item.skill||'');}
function parseDate(v){var n=Date.parse(v||'');return Number.isFinite(n)?n:0;}
function buildStateMap(state){var map={};((state&&state.items)||[]).forEach(function(item){map[stateKey(item)]=item;});return map;}
function sourceKind(activity){var m=activity&&activity.metadata||{};if(m.adaptive_review)return'review';if(m.assessment_bank)return'bank';if(m.same_level_extension)return'extension';if(m.current_curriculum)return'current';return'curriculum';}
function scoreActivity(activity,stateMap,options){options=options||{};var s=stateMap[keyFor(activity)]||null,meta=activity.metadata||{},score=0,now=Date.now();var mastery=s&&Number(s.mastery_score),due=!s||!s.next_review_at||parseDate(s.next_review_at)<=now,focused=!!(options.focusSkill||options.focusUnitId);if(!s){score+=36;}else{if(due)score+=110;if(Number.isFinite(mastery))score+=(100-mastery)*.55;score+=Math.min(30,Number(s.lapses||0)*8);if(s.review_state==='learning')score+=18;if(s.review_state==='mastered')score+=6;if(!due&&!focused)score-=100;if(!due&&focused)score-=12;}if(options.currentBookId&&String(meta.book_id)===String(options.currentBookId))score+=20;if(options.currentUnitId&&String(meta.unit_id)===String(options.currentUnitId))score+=28;if(meta.current_curriculum)score+=18;if(meta.adaptive_review)score+=34;if(meta.same_level_extension)score-=12;if(meta.assessment_bank)score-=16;if(options.focusSkill&&activity.skill===options.focusSkill)score+=80;if(options.focusUnitId&&String(meta.unit_id)===String(options.focusUnitId))score+=90;score+=Math.random()*7;return{score:score,state:s,due:due};}
function chooseFocusedGrammar(rows,target){var groups={},keys=[],chosen=[];rows.forEach(function(row){var k=keyFor(row.activity);if(!groups[k]){groups[k]=[];keys.push(k);}groups[k].push(row);});keys.forEach(function(k){groups[k].sort(function(a,b){return b.score-a.score;});});keys.sort(function(){return Math.random()-.5;});var perPattern=4,progress=true;while(chosen.length<target&&progress){progress=false;for(var i=0;i<keys.length&&chosen.length<target;i++){var k=keys[i],used=chosen.filter(function(a){return keyFor(a)===k;}).length;if(used>=perPattern||!groups[k].length)continue;chosen.push(groups[k].shift().activity);progress=true;}}return chosen;}
function chooseSession(activities,state,options){options=options||{};var target=Number(options.target||12),stateMap=buildStateMap(state),seenContent={},skillCounts={},sourceCounts={},chosen=[];var rows=(activities||[]).filter(function(a){if(!a||!a.id)return false;if(options.focusSkill&&a.skill!==options.focusSkill)return false;if(options.focusUnitId&&String(a.metadata&&a.metadata.unit_id)!==String(options.focusUnitId))return false;return true;}).map(function(a){var ranked=scoreActivity(a,stateMap,options);return{activity:a,score:ranked.score,state:ranked.state,due:ranked.due};}).sort(function(a,b){return b.score-a.score;});if(options.focusSkill==='grammar')return chooseFocusedGrammar(rows,target);while(rows.length&&chosen.length<target){var pickIndex=-1;for(var i=0;i<rows.length;i++){var row=rows[i],a=row.activity,content=keyFor(a),skill=a.skill||'practice',kind=sourceKind(a);var duplicate=seenContent[content]||0,sameSkill=skillCounts[skill]||0,sameSource=sourceCounts[kind]||0;if(duplicate>=1)continue;if(chosen.length>=3&&sameSkill>=Math.ceil((chosen.length+1)*.5))continue;if(!options.focusSkill&&kind==='bank'&&sameSource>=4)continue;if(!options.focusSkill&&kind==='extension'&&sameSource>=3)continue;pickIndex=i;break;}if(pickIndex<0)pickIndex=0;var picked=rows.splice(pickIndex,1)[0],pa=picked.activity,pcontent=keyFor(pa),pskill=pa.skill||'practice',pkind=sourceKind(pa);seenContent[pcontent]=(seenContent[pcontent]||0)+1;skillCounts[pskill]=(skillCounts[pskill]||0)+1;sourceCounts[pkind]=(sourceCounts[pkind]||0)+1;chosen.push(pa);}return chosen;}
function retryPosition(queue){if(!queue||!queue.length)return 0;return Math.min(queue.length,Math.max(3,Math.floor(3+Math.random()*3)));}
function insertRetry(queue,activity){var idx=retryPosition(queue);queue.splice(idx,0,activity);return idx;}
function stateFor(activity,state){return buildStateMap(state)[keyFor(activity)]||null;}
global.WillenaAdaptiveStudy={version:'adaptive-v2-patterns',chooseSession:chooseSession,insertRetry:insertRetry,stateFor:stateFor,keyFor:keyFor,buildStateMap:buildStateMap,sourceKind:sourceKind};
})(window);
