(function(global){
'use strict';
function keyFor(activity){var m=activity&&activity.metadata||{};if(activity&&activity.skill==='grammar'&&m.mastery_content_id)return String(m.mastery_content_type||'pattern')+'|'+String(m.mastery_content_id)+'|grammar';if(activity&&activity.skill==='grammar'&&m.pattern_id)return'pattern|'+String(m.pattern_id)+'|grammar';return String(activity&&activity.sourceType||'activity')+'|'+String(activity&&activity.sourceId||'')+'|'+String(activity&&activity.skill||'');}
function exactKeyFor(activity){if(activity&&activity.skill==='grammar')return'grammar_activity|'+String(activity.id||'')+'|grammar';return String(activity&&activity.sourceType||'activity')+'|'+String(activity&&activity.sourceId||'')+'|'+String(activity&&activity.skill||'');}
function stateKey(item){return String(item.content_type||'activity')+'|'+String(item.content_id||'')+'|'+String(item.skill||'');}
function parseDate(v){var n=Date.parse(v||'');return Number.isFinite(n)?n:0;}
function buildStateMap(state){var map={};((state&&state.items)||[]).forEach(function(item){map[stateKey(item)]=item;});return map;}
function sourceKind(activity){var m=activity&&activity.metadata||{};if(m.adaptive_review)return'review';if(m.assessment_bank)return'bank';if(m.same_level_extension)return'extension';if(m.current_curriculum)return'current';return'curriculum';}
function scoreActivity(activity,stateMap,options){options=options||{};var patternState=stateMap[keyFor(activity)]||null,exactState=activity&&activity.skill==='grammar'?(stateMap[exactKeyFor(activity)]||null):patternState,s=activity&&activity.skill==='grammar'?exactState:patternState,meta=activity.metadata||{},score=0,now=Date.now();var mastery=s&&Number(s.mastery_score),due=!s||!s.next_review_at||parseDate(s.next_review_at)<=now,focused=!!(options.focusSkill||options.focusUnitId);if(!s){score+=36;}else{if(due)score+=110;if(Number.isFinite(mastery))score+=(100-mastery)*.55;score+=Math.min(30,Number(s.lapses||0)*8);if(s.review_state==='learning')score+=18;if(s.review_state==='mastered')score+=6;if(!due&&!focused)score-=100;if(!due&&focused)score-=12;}if(activity&&activity.skill==='grammar'&&patternState){var pm=Number(patternState.mastery_score);if(Number.isFinite(pm))score+=(100-pm)*.25;if(Number(patternState.lapses||0)>0)score+=Math.min(18,Number(patternState.lapses||0)*3);}if(options.currentBookId&&String(meta.book_id)===String(options.currentBookId))score+=20;if(options.currentUnitId&&String(meta.unit_id)===String(options.currentUnitId))score+=28;if(meta.current_curriculum)score+=18;if(meta.adaptive_review)score+=34;if(meta.same_level_extension)score-=12;if(meta.assessment_bank)score-=16;if(options.focusSkill&&activity.skill===options.focusSkill)score+=80;if(options.focusUnitId&&String(meta.unit_id)===String(options.focusUnitId))score+=90;score+=Math.random()*7;return{score:score,state:s,exactState:exactState,patternState:patternState,due:due};}
function fastFocusedEligible(row){if(!row.state)return true;var mastery=Number(row.state.mastery_score||0);return mastery<80||row.due;}
function grammarFocusedEligible(row){if(!row.exactState)return true;var mastery=Number(row.exactState.mastery_score||0),due=!row.exactState.next_review_at||parseDate(row.exactState.next_review_at)<=Date.now();return mastery<80||due;}
function chooseFocusedGrammar(rows,target){var groups={},keys=[],chosen=[];rows.forEach(function(row){var k=keyFor(row.activity);if(!groups[k]){groups[k]=[];keys.push(k);}groups[k].push(row);});keys.forEach(function(k){groups[k].sort(function(a,b){return b.score-a.score;});});keys.sort(function(a,b){var aa=groups[a]&&groups[a][0],bb=groups[b]&&groups[b][0];return (bb?bb.score:0)-(aa?aa.score:0)+(Math.random()-.5)*6;});var progress=true;while(chosen.length<target&&progress){progress=false;for(var i=0;i<keys.length&&chosen.length<target;i++){var group=groups[keys[i]];if(!group||!group.length)continue;chosen.push(group.shift().activity);progress=true;}}return chosen;}
function conversationCycleKey(options){return'willena-conversation-cycle-v1|'+String(options.currentBookId||'')+'|'+String(options.focusUnitId||options.currentUnitId||'');}
function readConversationCycle(key){try{var v=JSON.parse(sessionStorage.getItem(key)||'[]');return Array.isArray(v)?v:[];}catch(_){return[];}}
function writeConversationCycle(key,ids){try{sessionStorage.setItem(key,JSON.stringify(ids));}catch(_){}}
function chooseVariedConversation(rows,target,options){var desired=Math.min(6,Math.max(1,target),rows.length),cycleKey=conversationCycleKey(options),served=readConversationCycle(cycleKey),servedSet={};served.forEach(function(id){servedSet[id]=true;});var unused=rows.filter(function(r){return !servedSet[r.activity.id];});var chosen=[];
 function takeVaried(candidates,limit){var byForm={},forms=[];candidates.forEach(function(r){var form=String((r.activity.metadata||{}).question_form||(r.activity.metadata||{}).conversation_form||'other');if(!byForm[form]){byForm[form]=[];forms.push(form);}byForm[form].push(r);});forms.forEach(function(f){byForm[f].sort(function(a,b){return b.score-a.score;});});forms.sort(function(){return Math.random()-.5;});var progress=true;while(chosen.length<limit&&progress){progress=false;for(var i=0;i<forms.length&&chosen.length<limit;i++){var list=byForm[forms[i]];if(!list||!list.length)continue;chosen.push(list.shift().activity);progress=true;}}}
 takeVaried(unused,Math.min(desired,unused.length));
 if(chosen.length<desired){served=[];servedSet={};var chosenIds={};chosen.forEach(function(a){chosenIds[a.id]=true;});var refill=rows.filter(function(r){return !chosenIds[r.activity.id];});takeVaried(refill,desired);}
 var nextServed=served.concat(chosen.map(function(a){return a.id;}));var allIds={};rows.forEach(function(r){allIds[r.activity.id]=true;});nextServed=nextServed.filter(function(id,i,a){return allIds[id]&&a.indexOf(id)===i;});if(nextServed.length>=rows.length)nextServed=[];writeConversationCycle(cycleKey,nextServed);return chosen.slice(0,desired);}
function chooseSession(activities,state,options){options=options||{};var target=Number(options.target||12),stateMap=buildStateMap(state),seenContent={},skillCounts={},sourceCounts={},chosen=[];var rows=(activities||[]).filter(function(a){if(!a||!a.id)return false;if(options.focusSkill&&a.skill!==options.focusSkill)return false;if(options.focusUnitId&&String(a.metadata&&a.metadata.unit_id)!==String(options.focusUnitId))return false;return true;}).map(function(a){var ranked=scoreActivity(a,stateMap,options);return{activity:a,score:ranked.score,state:ranked.state,exactState:ranked.exactState,patternState:ranked.patternState,due:ranked.due};}).filter(function(row){if(options.focusSkill==='grammar')return grammarFocusedEligible(row);if(options.focusSkill&&['conversation','listening'].indexOf(options.focusSkill)>=0)return fastFocusedEligible(row);return true;}).sort(function(a,b){return b.score-a.score;});if(options.focusSkill==='grammar')return chooseFocusedGrammar(rows,target);if(options.focusSkill==='conversation')return chooseVariedConversation(rows,target,options);while(rows.length&&chosen.length<target){var pickIndex=-1;for(var i=0;i<rows.length;i++){var row=rows[i],a=row.activity,content=keyFor(a),skill=a.skill||'practice',kind=sourceKind(a);var duplicate=seenContent[content]||0,sameSkill=skillCounts[skill]||0,sameSource=sourceCounts[kind]||0;if(duplicate>=1)continue;if(chosen.length>=3&&sameSkill>=Math.ceil((chosen.length+1)*.5))continue;if(!options.focusSkill&&kind==='bank'&&sameSource>=4)continue;if(!options.focusSkill&&kind==='extension'&&sameSource>=3)continue;pickIndex=i;break;}if(pickIndex<0)pickIndex=0;var picked=rows.splice(pickIndex,1)[0],pa=picked.activity,pcontent=keyFor(pa),pskill=pa.skill||'practice',pkind=sourceKind(pa);seenContent[pcontent]=(seenContent[pcontent]||0)+1;skillCounts[pskill]=(skillCounts[pskill]||0)+1;sourceCounts[pkind]=(sourceCounts[pkind]||0)+1;chosen.push(pa);}return chosen;}
function retryPosition(queue){if(!queue||!queue.length)return 0;return Math.min(queue.length,Math.max(3,Math.floor(3+Math.random()*3)));}
function insertRetry(queue,activity){var idx=retryPosition(queue);queue.splice(idx,0,activity);return idx;}
function stateFor(activity,state){var map=buildStateMap(state);return activity&&activity.skill==='grammar'?(map[exactKeyFor(activity)]||map[keyFor(activity)]||null):(map[keyFor(activity)]||null);}
global.WillenaAdaptiveStudy={version:'adaptive-v4.3-activity-fast-pass',chooseSession:chooseSession,insertRetry:insertRetry,stateFor:stateFor,keyFor:keyFor,exactKeyFor:exactKeyFor,buildStateMap:buildStateMap,sourceKind:sourceKind};
})(window);
