(function(global){
'use strict';
function displayText(value){return String(value==null?'':value).replace(/\\n/g,'\n');}
function textValue(value){return String(value==null?'':value).trim();}
function el(tag,className,text){var node=document.createElement(tag);if(className)node.className=className;if(text!=null)node.textContent=text;return node;}
function multilineEl(tag,className,text){var node=el(tag,className,displayText(text));node.style.whiteSpace='pre-line';return node;}
function shuffle(items){return items.slice().sort(function(){return Math.random()-.5;});}
function isKo(){var b=document.getElementById('languageBtn');return !b||textValue(b.textContent)==='English';}
function localized(obj,base){if(!obj)return'';var ko=textValue(obj[base+'_ko']),en=textValue(obj[base+'_en']);return isKo()?(ko||en):(en||ko);}
function choiceFeedback(map,key){if(!map||typeof map!=='object')return'';var value=map[key];return typeof value==='string'?value:'';}
function specificWrongFeedback(feedback,selected){if(!feedback||selected==null)return'';var key=String(selected),map=isKo()?feedback.wrong_choice_explanations_ko:feedback.wrong_choice_explanations_en;var fallback=isKo()?feedback.wrong_choice_explanations_en:feedback.wrong_choice_explanations_ko;return choiceFeedback(map,key)||choiceFeedback(fallback,key);}
function feedbackStages(feedback){var raw=Array.isArray(feedback&&feedback.stages)?feedback.stages:[],out=[];raw.forEach(function(stage){var body=localized(stage,'')||textValue(isKo()?stage&&stage.ko:stage&&stage.en)||textValue(isKo()?stage&&stage.en:stage&&stage.ko);if(!body)return;var label=isKo()?textValue(stage.label_ko||stage.label_en):textValue(stage.label_en||stage.label_ko);out.push({label:label,body:body});});if(!out.length&&feedback){var general=isKo()?textValue(feedback.explanation_ko||feedback.explanation_en):textValue(feedback.explanation_en||feedback.explanation_ko);if(general)out.push({label:isKo()?'해설':'Explanation',body:general});}return out;}
function ActivityEngine(root,options){this.root=root;this.options=options||{};this.current=null;this.selected=null;this.startedAt=0;}
ActivityEngine.prototype.setActivity=function(raw){var schema=global.WillenaActivitySchema;if(!schema)throw new Error('WillenaActivitySchema is not loaded');this.current=schema.normalize(raw);this.selected=null;this.startedAt=(global.performance&&performance.now)?performance.now():Date.now();this.render();return this.current;};
ActivityEngine.prototype.renderDialogue=function(card,stimulus){var lines=Array.isArray(stimulus.lines)?stimulus.lines:[],target=Number.isInteger(stimulus.targetIndex)?stimulus.targetIndex:-1;if(!lines.length)return;var wrap=el('div','activity-dialogue');lines.forEach(function(line,index){var row=el('div','activity-dialogue-line'+(index===target?' is-target':''));var speaker=el('span','activity-dialogue-speaker',String(line&&line.speaker||''));var text=index===target?'…':displayText(line&&line.text||'');row.appendChild(speaker);row.appendChild(multilineEl('div','activity-dialogue-text',text));wrap.appendChild(row);});card.appendChild(wrap);};
ActivityEngine.prototype.render=function(){var a=this.current;if(!a||!this.root)return;this.root.innerHTML='';var meta=a.metadata||{},isConversationOrder=a.skill==='conversation'&&(meta.conversation_form==='dialogue_order'||meta.question_form==='dialogue_order');var card=el('section','activity-card'+(isConversationOrder?' is-conversation-order':''));card.dataset.activityId=a.id;var context=a.stimulus&&a.stimulus.context;if(context)card.appendChild(multilineEl('div','activity-context',context));if(a.stimulus&&a.stimulus.type==='dialogue')this.renderDialogue(card,a.stimulus);else card.appendChild(multilineEl('h2','activity-prompt',a.stimulus&&a.stimulus.prompt||a.q||''));if(a.stimulus&&a.stimulus.type==='audio'){var listen=el('button','activity-audio');listen.type='button';listen.setAttribute('aria-label','음성 듣기');listen.innerHTML='<svg class="activity-audio-icon" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true" focusable="false"><path d="M4 14v-2a8 8 0 0 1 16 0v2"></path><path d="M18 19h1a2 2 0 0 0 2-2v-3a2 2 0 0 0-2-2h-1z"></path><path d="M6 19H5a2 2 0 0 1-2-2v-3a2 2 0 0 0-2-2h1z"></path></svg><span>Play audio</span>';listen.addEventListener('click',function(){var text=a.stimulus.text||a.stimulus.prompt;if(!text||!global.speechSynthesis)return;global.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(displayText(text));u.lang='en-US';u.rate=.9;global.speechSynthesis.speak(u);});card.appendChild(listen);}var response=a.response||{},type=response.type;if(type==='letter_order')this.renderLetterOrder(card,response.tokens||[],response.wordLengths||[]);else if(type==='sentence_unscramble'||type==='token_order'||type==='chunk_order')this.renderTokenOrder(card,response.tokens||[]);else if(type==='typed_answer'||type==='gap_fill_text')this.renderTextInput(card,type);else this.renderChoices(card,response.choices||[]);var footer=el('div','activity-result-footer');var feedback=el('div','activity-feedback is-empty');feedback.setAttribute('aria-live','polite');footer.appendChild(feedback);var actions=el('div','activity-actions');var check=el('button','activity-check','Check');check.type='button';check.disabled=true;actions.appendChild(check);footer.appendChild(actions);card.appendChild(footer);var teaching=el('section','activity-teaching');teaching.hidden=true;teaching.setAttribute('aria-live','polite');card.appendChild(teaching);var self=this;check.addEventListener('click',function(){self.check(feedback,check);});this.root.appendChild(card);};
ActivityEngine.prototype.setCheckEnabled=function(card,enabled){var check=card.querySelector('.activity-check');if(check)check.disabled=!enabled;};
ActivityEngine.prototype.renderChoices=function(card,choices){var wrap=el('div','activity-choices'),self=this;shuffle(choices).forEach(function(choice){var b=multilineEl('button','activity-choice',choice);b.type='button';b.addEventListener('click',function(){wrap.querySelectorAll('button').forEach(function(x){x.classList.remove('is-selected');});b.classList.add('is-selected');self.selected=choice;self.setCheckEnabled(card,true);});wrap.appendChild(b);});card.appendChild(wrap);};
ActivityEngine.prototype.renderTextInput=function(card,type){var input=el('input','activity-input');input.type='text';input.autocomplete='off';input.setAttribute('autocorrect','off');input.setAttribute('autocapitalize','none');input.spellcheck=false;input.placeholder=type==='gap_fill_text'?'Type the missing word or phrase':'Type your answer';var self=this;input.addEventListener('input',function(){self.selected=input.value;self.setCheckEnabled(card,!!input.value.trim());});input.addEventListener('keydown',function(e){var check=card.querySelector('.activity-check');if(e.key==='Enter'&&check&&!check.disabled)check.click();});card.appendChild(input);};
ActivityEngine.prototype.renderTokenOrder=function(card,tokens){var self=this,chosen=[],bank=shuffle(tokens.map(function(t,i){return{text:String(t),id:i+'-'+Math.random()};}));var answer=el('div','activity-token-answer'),pool=el('div','activity-token-bank');card.appendChild(answer);card.appendChild(pool);function draw(){answer.innerHTML='';pool.innerHTML='';chosen.forEach(function(item,index){var b=el('button','activity-token is-chosen',item.text);b.type='button';b.addEventListener('click',function(){chosen.splice(index,1);draw();});answer.appendChild(b);});bank.filter(function(item){return chosen.indexOf(item)<0;}).forEach(function(item){var b=el('button','activity-token',item.text);b.type='button';b.addEventListener('click',function(){chosen.push(item);draw();});pool.appendChild(b);});self.selected=chosen.map(function(item){return item.text;});self.setCheckEnabled(card,chosen.length===bank.length);}draw();};
ActivityEngine.prototype.renderLetterOrder=function(card,tokens,wordLengths){var self=this,chosen=[],bank=shuffle(tokens.map(function(t,i){return{text:String(t),id:i+'-'+Math.random()};}));var wrap=el('div','activity-letter-order'),slots=el('div','activity-letter-slots'),pool=el('div','activity-letter-bank');wrap.appendChild(slots);wrap.appendChild(pool);card.appendChild(wrap);var lengths=Array.isArray(wordLengths)&&wordLengths.length?wordLengths.slice():[tokens.length];function drawSlots(){slots.innerHTML='';var cursor=0;lengths.forEach(function(length,wordIndex){var row=el('div','activity-letter-word');for(var i=0;i<Number(length||0);i++){var slot=el('button','activity-letter-slot',chosen[cursor]?chosen[cursor].text.toUpperCase():'');slot.type='button';slot.disabled=!chosen[cursor];(function(index){slot.addEventListener('click',function(){if(chosen[index]){chosen.splice(index,1);draw();}});})(cursor);row.appendChild(slot);cursor++;}slots.appendChild(row);if(wordIndex<lengths.length-1)slots.appendChild(el('span','activity-letter-space',' '));});}function draw(){drawSlots();pool.innerHTML='';bank.filter(function(item){return chosen.indexOf(item)<0;}).forEach(function(item){var b=el('button','activity-letter-tile',item.text.toUpperCase());b.type='button';b.addEventListener('click',function(){chosen.push(item);draw();});pool.appendChild(b);});self.selected=chosen.map(function(item){return item.text;});self.setCheckEnabled(card,chosen.length===bank.length);}draw();};
ActivityEngine.prototype.showTeaching=function(card,feedbackData,selected){var teaching=card&&card.querySelector('.activity-teaching');if(!teaching)return;var specific=specificWrongFeedback(feedbackData,selected),stages=feedbackStages(feedbackData);if(!specific&&!stages.length){teaching.hidden=true;teaching.innerHTML='';return;}var generalShown=specific?0:Math.min(1,stages.length),self=this;teaching.hidden=false;function draw(){teaching.innerHTML='';var head=el('div','activity-teaching-head');head.appendChild(el('span','activity-teaching-level',specific?(isKo()?'왜 틀렸을까요?':'Why this answer is wrong'):(stages[0]&&stages[0].label|| (isKo()?'핵심 이유':'Quick reason'))));teaching.appendChild(head);if(specific)teaching.appendChild(multilineEl('div','activity-teaching-copy',specific));for(var i=0;i<generalShown;i++){var st=stages[i];if(!st)continue;var block=el('div','activity-teaching-block');if(specific||i>0)block.appendChild(el('strong','activity-teaching-block-label',st.label|| (isKo()?'해설':'Explanation')));block.appendChild(multilineEl('div','activity-teaching-copy',st.body));teaching.appendChild(block);}var controls=el('div','activity-teaching-controls');var canMore=generalShown<stages.length;if(canMore){var more=el('button','activity-explain-more',isKo()?'더 설명해 주세요 ↓':'Explain more ↓');more.type='button';more.addEventListener('click',function(){generalShown++;draw();});controls.appendChild(more);}if(specific||generalShown>0){var hide=el('button','activity-explain-hide',isKo()?'설명 숨기기':'Hide explanation');hide.type='button';hide.addEventListener('click',function(){teaching.hidden=true;});controls.appendChild(hide);}if(controls.childNodes.length)teaching.appendChild(controls);}draw();};
ActivityEngine.prototype.check=function(feedback,button){var scoring=global.WillenaActivityScoring;if(!scoring)throw new Error('WillenaActivityScoring is not loaded');var result=scoring.score(this.current,this.selected);var now=(global.performance&&performance.now)?performance.now():Date.now();result.responseTimeMs=Math.max(0,Math.round(now-this.startedAt));feedback.className='activity-feedback '+(result.correct?'is-correct':'is-wrong');feedback.innerHTML='';if(result.correct){feedback.appendChild(el('strong','activity-feedback-title',isKo()?'정답이에요!':'Correct!'));}else{var answerText=Array.isArray(result.answer)?result.answer.join(' '):String(result.answer==null?'':result.answer);var answerRow=el('div','activity-feedback-answer');answerRow.appendChild(el('strong','',isKo()?'정답 · ':'Answer · '));answerRow.appendChild(document.createTextNode(displayText(answerText)));feedback.appendChild(answerRow);}var card=feedback.closest('.activity-card');var teaching=card&&card.querySelector('.activity-teaching');if(result.correct){if(teaching){teaching.hidden=true;teaching.innerHTML='';}}else this.showTeaching(card,this.current&&this.current.feedback||null,this.selected);button.disabled=true;var detail={activity:this.current,result:result,responseTimeMs:result.responseTimeMs};if(typeof this.options.onAnswer==='function')this.options.onAnswer(detail);try{global.dispatchEvent(new CustomEvent('willena:activity-answer',{detail:detail}));}catch(_){};};
global.WillenaActivityEngine=ActivityEngine;
})(window);
