(function(){
'use strict';
const root=document.querySelector('#app');
const ENDPOINT='https://fiieuiktlsivwfgyivai.supabase.co/functions/v1/prospective-level-test';
const ADMIN_ENDPOINT='https://willena-proxy.willena.workers.dev/.netlify/functions/admin_classes';
const CURRICULUM_URL='https://gxwfsqxyuufqtitspfqg.supabase.co';
const CURRICULUM_KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const params=new URLSearchParams(location.search),attemptId=params.get('attempt_id')||'',token=params.get('report_token')||params.get('session_token')||'',teacherMode=params.get('teacher')==='1',adminMode=params.get('admin')==='1',adminSource=params.get('source')||'';
const evidence=[];let profiles=new Map(),reportData=null;const MAX_LEVEL=12;
const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
const levelNames={1:'Starter 1',2:'Starter 2',3:'Level 1',4:'Level 2',5:'Level 3',6:'Level 4',7:'Level 5',8:'Level 6',9:'Level 7',10:'Level 8',11:'Level 9',12:'Level 10'};
const levelNamesKo={1:'스타터 1',2:'스타터 2',3:'레벨 1',4:'레벨 2',5:'레벨 3',6:'레벨 4',7:'레벨 5',8:'레벨 6',9:'레벨 7',10:'레벨 8',11:'레벨 9',12:'레벨 10'};
const shortNames={1:'S1',2:'S2',3:'1',4:'2',5:'3',6:'4',7:'5',8:'6',9:'7',10:'8',11:'9',12:'10'};
const skillFor=t=>({vocabulary:'vocabulary',grammar:'grammar',grammar_error:'grammar',question_response:'grammar',listening:'listening',reading:'reading',sentence_unscramble:'sentence_building',speaking:'speaking',writing:'writing'}[t]||null);
const skillLabels={vocabulary:{en:'Vocabulary',ko:'어휘'},grammar:{en:'Grammar',ko:'문법'},listening:{en:'Listening',ko:'듣기'},reading:{en:'Reading',ko:'읽기'},sentence_building:{en:'Sentence building',ko:'문장 만들기'},speaking:{en:'Speaking',ko:'말하기'},writing:{en:'Writing',ko:'쓰기'}};
const assessed=['vocabulary','grammar','listening','reading','sentence_building'],all=[...assessed,'speaking','writing'];
function sentenceText(value){if(typeof value==='string'){const encoded=value.trim();if(encoded[0]==='['&&encoded[encoded.length-1]===']'){try{const decoded=JSON.parse(encoded);if(Array.isArray(decoded))value=decoded}catch(_){}}}const text=Array.isArray(value)?value.map(clean).join(' '):clean(value);return text.normalize('NFKC').toLocaleLowerCase('en-US').replace(/[.,!?;:。！？、，；：]+$/gu,'').replace(/\s+/g,' ').trim()}
function repairSentenceResponse(row){if(!row||typeof row!=='object')return row;const type=row.question_type||row.item_type||row.type;if(type!=='sentence_unscramble')return row;const selected=row.selected_answer??row.student_answer??row.selected??row.response,correct=row.correct_answer??row.answer??row.expected_answer;if(selected===undefined||correct===undefined)return row;row.is_correct=sentenceText(selected)===sentenceText(correct);return row}
function installPrintStyles(){if(document.querySelector('#teacherPrintStyles'))return;const s=document.createElement('style');s.id='teacherPrintStyles';s.textContent=`.teacher-report-tools{position:sticky;top:10px;z-index:50;width:min(860px,calc(100% - 24px));margin:10px auto;display:flex;justify-content:flex-end;gap:8px}.teacher-print-btn{border:0;border-radius:15px;padding:12px 17px;background:#244f59;color:#fff;font:700 14px Poppins,system-ui;cursor:pointer;box-shadow:0 8px 22px rgba(28,75,84,.2)}.print-report-heading{display:none}@page{size:A4;margin:12mm}@media print{html,body{background:#fff!important}.app-header,footer,.teacher-report-tools,.report-actions,.language-segmented,.header-button{display:none!important}.app-shell,.app-main{display:block!important;width:100%!important;max-width:none!important;margin:0!important;padding:0!important;background:#fff!important}.report-screen{max-width:none!important;width:100%!important;padding:0!important;border:0!important;border-radius:0!important;box-shadow:none!important}.print-report-heading{display:flex!important;align-items:center;justify-content:space-between;border-bottom:2px solid #67d8df;padding:0 0 7mm;margin-bottom:7mm}.print-report-heading strong{font-size:18pt}.print-report-heading span{color:#748b92;font-size:9pt}.report-hero,.report-card,.report-level-guide,.report-level-guide__row,.report-skill{break-inside:avoid;page-break-inside:avoid}.report-card{box-shadow:none!important;margin-top:5mm!important}.report-level-guide{break-before:page;page-break-before:always}.report-level{width:42mm!important;border-width:3mm!important}.level-journey{margin-bottom:4mm}.report-method{font-size:8pt}.report-level-guide__list{overflow:visible!important}}`;document.head.appendChild(s)}
async function load(){const adminHeaders={'content-type':'application/json'};if(adminMode){try{const access=localStorage.getItem('sb_access_token');if(access&&access.includes('.')&&access.length>50)adminHeaders.Authorization=`Bearer ${access}`}catch(_){}}const reportRequest=adminMode?fetch(ADMIN_ENDPOINT,{method:'POST',credentials:'include',headers:adminHeaders,body:JSON.stringify({action:'level_test_detail',attempt_id:attemptId,source:adminSource}),cache:'no-store'}):fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'report',attempt_id:attemptId,session_token:token}),cache:'no-store'});const [rr,pr]=await Promise.all([reportRequest,fetch(`${CURRICULUM_URL}/rest/v1/assessment_report_profiles?select=level_id,skill,summary_en,summary_ko,next_step_en,next_step_ko&status=eq.published&order=level_id.asc,sort_order.asc`,{headers:{apikey:CURRICULUM_KEY,Authorization:`Bearer ${CURRICULUM_KEY}`},cache:'no-store'})]);const d=await rr.json().catch(()=>({}));if(!rr.ok||!d.success)throw new Error(d.error||'Could not load report');if(pr.ok){const rows=await pr.json();profiles=new Map(rows.map(r=>[`${r.level_id}:${r.skill}`,r]));}return d}
function probabilities(rows,maxLevel=MAX_LEVEL){if(!rows.length)return[];const ceiling=Math.max(1,Math.min(MAX_LEVEL,Number(maxLevel)||MAX_LEVEL)),scores=[];for(let level=1;level<=ceiling;level++){let log=0;for(const row of rows){const p=1/(1+Math.exp((row.level-level)*1.12));log+=Math.log(Math.max(.025,Math.min(.975,row.correct?p:1-p)))}scores.push({level,log})}const max=Math.max(...scores.map(x=>x.log)),weighted=scores.map(x=>({...x,w:Math.exp(x.log-max)})),total=weighted.reduce((s,x)=>s+x.w,0)||1;return weighted.map(x=>({level:x.level,pct:x.w/total*100})).sort((a,b)=>b.pct-a.pct)}
function levelFromRows(rows){if(!rows.length)return Number(reportData?.attempt?.display_level)||1;const highest=Math.min(MAX_LEVEL,Math.max(...rows.map(x=>Number(x.level)||1),1));return probabilities(rows,highest)[0]?.level||1}
const overall=()=>levelFromRows(evidence);
function estimate(skill){const rows=evidence.filter(x=>skillFor(x.type)===skill);if(rows.length<3)return{assessed:false,rows};const others=evidence.filter(x=>skillFor(x.type)!==skill),anchor=others.length>=4?levelFromRows(others):overall(),highest=Math.min(MAX_LEVEL,Math.max(...rows.map(x=>x.level))),prior=[{level:anchor,correct:true},{level:Math.min(MAX_LEVEL,anchor+1),correct:false}],fit=probabilities(rows.concat(prior),Math.max(highest,anchor+1))[0]||{level:anchor,pct:0},accuracy=rows.filter(x=>x.correct).length/rows.length,cap=Math.min(MAX_LEVEL,anchor+(rows.length>=5?2:1));let level=Math.min(fit.level,highest,cap);if(accuracy<.5)level=Math.min(level,anchor);if(accuracy<.34)level=Math.min(level,Math.max(1,anchor-1));level=Math.max(1,level);const top=rows.filter(x=>x.level===highest),plus=rows.length>=5&&top.length>=3&&top.every(x=>x.correct)&&level===highest,confidence=Math.round(Math.min(92,42+rows.length*7+fit.pct*.15));return{assessed:true,rows,level,plus,confidence}}
const profile=(l,s)=>profiles.get(`${l}:${s}`)||null;
const txt=(r,f,ko,fb='')=>clean(r?.[`${f}_${ko?'ko':'en'}`])||fb;
function fallback(level,skill,ko){const p=level<=2?level:level-2;return ko?`레벨 ${p}에서 익숙한 ${skillLabels[skill]?.ko||'영어'}를 이해하고 사용할 수 있습니다.`:`Can understand and use familiar ${skillLabels[skill]?.en.toLowerCase()||'English'} at Level ${p}.`}
function journey(best,ko){const nodes=Array.from({length:MAX_LEVEL},(_,i)=>{const l=i+1,c=l<best?'is-complete':l===best?'is-current':'';return `<div class="level-node ${c}"><div class="level-node__marker">${shortNames[l]}</div><span class="level-node__label">${ko?levelNamesKo[l]:levelNames[l]}</span></div>`}).join(''),left=((best-.5)/MAX_LEVEL)*100;return `<div class="level-journey"><div class="level-journey__here" style="left:${left}%">${ko?'현재 레벨':'You are here'}</div><div class="level-journey__track"><div class="level-journey__fill" style="width:${left}%"></div></div><div class="level-journey__nodes">${nodes}</div></div>`}
function skillRow(skill,ko){const r=estimate(skill),name=skillLabels[skill][ko?'ko':'en'];if(!r.assessed){const note=skill==='speaking'||skill==='writing'?(ko?'현재 버전의 테스트에는 이 영역을 평가할 문항이 아직 충분하지 않습니다.':'This version does not yet include enough tasks to assess this skill.'):(ko?'이 영역은 최소 세 문항이 필요합니다.':'At least three questions are needed to estimate this skill.');return `<div class="report-skill is-unassessed"><div class="report-skill__head"><strong>${name}</strong><span class="report-skill__level">${ko?'평가되지 않음':'Not assessed'}</span></div><p class="report-skill__note">${note}</p></div>`}const note=txt(profile(r.level,skill),'summary',ko,fallback(r.level,skill,ko));return `<div class="report-skill"><div class="report-skill__head"><strong>${name}</strong><span class="report-skill__level">${ko?levelNamesKo[r.level]:levelNames[r.level]}${r.plus?'+':''}</span></div><div class="report-skill__track"><i style="width:${r.confidence}%"></i></div><p class="report-skill__note">${note}</p></div>`}
function canDo(best,ko){const arr=assessed.map(skill=>({skill,r:estimate(skill)})).filter(x=>x.r.assessed).slice(0,4).map(x=>txt(profile(x.r.level,x.skill),'summary',ko,fallback(x.r.level,x.skill,ko)));if(arr.length<2)arr.unshift(txt(profile(best,'overall'),'summary',ko,fallback(best,'grammar',ko)));return [...new Set(arr)].slice(0,4).map(x=>`<li>${x}</li>`).join('')}
function nextStep(best,ko){const weak=assessed.map(skill=>({skill,r:estimate(skill)})).filter(x=>x.r.assessed).sort((a,b)=>a.r.level-b.r.level)[0];if(weak){const t=txt(profile(weak.r.level,weak.skill),'next_step',ko,'');if(t)return t}return txt(profile(best,'overall'),'next_step',ko,ko?'다음 단계의 영어를 정확하게 사용할 수 있도록 꾸준히 연습해 주세요.':'Continue practising the next level with growing accuracy and independence.')}
function updateHeader(ko){const logo=document.querySelector('.brand-logo');if(logo)logo.src='/Assets/Images/Logo.png';const subtitle=document.querySelector('#brandSubtitle');if(subtitle)subtitle.textContent=ko?'학생 리포트':'Student Report';document.querySelectorAll('[data-language-choice]').forEach(b=>b.classList.toggle('is-active',b.dataset.languageChoice===(ko?'ko':'en')))}
function render(){const ko=document.documentElement.lang==='ko',best=overall(),summary=txt(profile(best,'overall'),'summary',ko,fallback(best,'grammar',ko)),c=reportData?.candidate||{};updateHeader(ko);const tools=teacherMode?`<div class="teacher-report-tools"><button id="printReport" class="teacher-print-btn">${ko?'인쇄 / PDF 저장':'Print / Save PDF'}</button></div>`:'';root.innerHTML=tools+`<section class="screen screen-safe-in report-screen screen-safe-ready" data-enhanced-report="1"><div class="print-report-heading"><strong>Willena English</strong><span>${clean(c.student_name)} · ${clean(c.school_name)} · ${clean(c.school_grade)}</span></div><section class="report-hero"><span class="report-kicker">${ko?'추천 시작 레벨':'Estimated starting level'}</span><div class="report-level"><span>${ko?(best<=2?'스타터':'레벨'):(best<=2?'Starter':'Level')}</span><strong>${best<=2?best:best-2}</strong></div><p class="report-summary">${summary}</p>${journey(best,ko)}</section><section class="report-card"><h3>${ko?'현재 할 수 있는 것':'What your child can do'}</h3><ul class="report-can-do">${canDo(best,ko)}</ul></section><section class="report-card is-next"><h3>${ko?'앞으로 연습하면 좋은 것':'Ready to work on'}</h3><p>${nextStep(best,ko)}</p></section><section class="report-card"><h3>${ko?'영역별 예상 레벨':'Estimated level by skill'}</h3>${all.map(s=>skillRow(s,ko)).join('')}</section><section class="report-card"><h3>${ko?'이 결과는 무엇을 의미하나요?':'What does this result mean?'}</h3><p>${ko?'이 결과는 합격이나 불합격을 판단하는 점수가 아닙니다. 가장 편안하게 학습을 시작할 수 있는 단계를 보여주는 참고 자료입니다.':'This is not a pass-or-fail score. It guides you to the level where the learner is most likely to begin comfortably and successfully.'}</p></section><p class="report-method">${ko?'영역별 레벨은 해당 유형의 문항이 세 개 이상 출제된 경우에만 표시됩니다. +는 최고 출제 레벨을 충분한 문항에서 안정적으로 통과한 경우에만 표시됩니다.':'A skill estimate appears only after at least three questions. A + requires sustained success at the highest tested level.'}</p><div class="actions report-actions"><button class="btn btn-primary" id="closeReport">${ko?'보고서 닫기':'Close report'}</button></div></section>`;document.querySelector('#closeReport')?.addEventListener('click',()=>window.close());document.querySelector('#printReport')?.addEventListener('click',()=>window.print())}
document.addEventListener('click',e=>{const b=e.target.closest('[data-language-choice]');if(!b)return;document.documentElement.lang=b.dataset.languageChoice==='en'?'en':'ko';render()},true);
(async()=>{try{installPrintStyles();if(!attemptId||(!token&&!adminMode))throw new Error('Missing report access.');if(adminMode&&!adminSource)throw new Error('Missing test source.');reportData=await load();if(window.WillenaLevelTestScoring)window.WillenaLevelTestScoring.repairPayload(reportData);else(reportData.responses||[]).forEach(repairSentenceResponse);const lang=String(reportData.candidate?.metadata?.language||reportData.attempt?.setup?.language||reportData.attempt?.metadata?.language||'ko').toLowerCase().startsWith('en')?'en':'ko';document.documentElement.lang=lang;(reportData.responses||[]).forEach(r=>evidence.push({id:r.question_id,level:Number(r.question_level)||1,type:r.question_type||r.item_type,correct:r.is_correct===true}));render()}catch(e){root.innerHTML=`<section class="screen report-screen"><p class="report-summary">${clean(e.message)||'Could not load report.'}</p></section>`}})();
})();
