(function(){
'use strict';
const root=document.querySelector('#app');
const ENDPOINT='https://fiieuiktlsivwfgyivai.supabase.co/functions/v1/prospective-level-test';
const ADMIN_ENDPOINT='/.netlify/functions/admin_classes';
const CURRICULUM_URL='https://gxwfsqxyuufqtitspfqg.supabase.co';
const CURRICULUM_KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const params=new URLSearchParams(location.search),attemptId=params.get('attempt_id')||'',token=params.get('report_token')||params.get('session_token')||'',teacherMode=params.get('teacher')==='1',adminMode=params.get('admin')==='1',adminSource=params.get('source')||'';
const evidence=[];let profiles=new Map(),reportData=null;const MAX_LEVEL=12;
const clean=s=>String(s??'').replace(/\s+/g,' ').trim();
const esc=s=>clean(s).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const apiFetch=(url,options)=>window.WillenaAPI?.fetch?window.WillenaAPI.fetch(url,options):fetch(url,options);
const levelNames={1:'Starter 1',2:'Starter 2',3:'Level 1',4:'Level 2',5:'Level 3',6:'Level 4',7:'Level 5',8:'Level 6',9:'Level 7',10:'Level 8',11:'Level 9',12:'Level 10'};
const levelNamesKo={1:'스타터 1',2:'스타터 2',3:'레벨 1',4:'레벨 2',5:'레벨 3',6:'레벨 4',7:'레벨 5',8:'레벨 6',9:'레벨 7',10:'레벨 8',11:'레벨 9',12:'레벨 10'};
const shortNames={1:'S1',2:'S2',3:'1',4:'2',5:'3',6:'4',7:'5',8:'6',9:'7',10:'8',11:'9',12:'10'};
const skillFor=value=>{const t=String(value||'').trim().toLowerCase();if(t.includes('unscramble')||t.includes('sentence_build')||t==='sentence_making')return'sentence_building';return({vocabulary:'vocabulary',grammar:'grammar',grammar_error:'grammar',question_response:'grammar',listening:'listening',reading:'reading',speaking:'speaking',writing:'writing'}[t]||null)};
const skillLabels={vocabulary:{en:'Vocabulary',ko:'어휘'},grammar:{en:'Grammar',ko:'문법'},listening:{en:'Listening',ko:'듣기'},reading:{en:'Reading',ko:'읽기'},sentence_building:{en:'Sentence building',ko:'문장 구조 파악 능력'},speaking:{en:'Speaking',ko:'말하기'},writing:{en:'Writing',ko:'쓰기'}};
const assessed=['vocabulary','grammar','listening','reading','sentence_building'],all=[...assessed,'speaking','writing'];
function sentenceText(value){if(typeof value==='string'){const encoded=value.trim();if(encoded[0]==='['&&encoded[encoded.length-1]===']'){try{const decoded=JSON.parse(encoded);if(Array.isArray(decoded))value=decoded}catch(_){}}}const text=Array.isArray(value)?value.map(clean).join(' '):clean(value);return text.normalize('NFKC').toLocaleLowerCase('en-US').replace(/[.,!?;:。！？、，；：]+$/gu,'').replace(/\s+/g,' ').trim()}
function repairSentenceResponse(row){if(!row||typeof row!=='object')return row;const type=row.question_type||row.item_type||row.type;if(type!=='sentence_unscramble')return row;const selected=row.selected_answer??row.student_answer??row.selected??row.response,correct=row.correct_answer??row.answer??row.expected_answer;if(selected===undefined||correct===undefined)return row;row.is_correct=sentenceText(selected)===sentenceText(correct);return row}
function installPrintStyles(){if(document.querySelector('#teacherPrintStyles'))return;const s=document.createElement('style');s.id='teacherPrintStyles';s.textContent=`.teacher-report-tools{position:sticky;top:10px;z-index:50;width:min(860px,calc(100% - 24px));margin:10px auto;display:flex;justify-content:flex-end;gap:8px}.teacher-print-btn{border:0;border-radius:15px;padding:12px 17px;background:#244f59;color:#fff;font:700 14px Poppins,system-ui;cursor:pointer;box-shadow:0 8px 22px rgba(28,75,84,.2)}.print-report-heading{display:none}@page{size:A4;margin:12mm}@media print{html,body{background:#fff!important}.app-header,footer,.teacher-report-tools,.report-actions,.language-segmented,.header-button{display:none!important}.app-shell,.app-main{display:block!important;width:100%!important;max-width:none!important;margin:0!important;padding:0!important;background:#fff!important}.report-screen{max-width:none!important;width:100%!important;padding:0!important;border:0!important;border-radius:0!important;box-shadow:none!important}.print-report-heading{display:flex!important;align-items:center;justify-content:space-between;border-bottom:2px solid #67d8df;padding:0 0 7mm;margin-bottom:7mm}.print-report-heading strong{font-size:18pt}.print-report-heading span{color:#748b92;font-size:9pt}.report-hero,.report-card,.report-level-guide,.report-level-guide__row,.report-skill{break-inside:avoid;page-break-inside:avoid}.report-card{box-shadow:none!important;margin-top:5mm!important}.report-level-guide{break-before:page;page-break-before:always}.report-level{width:42mm!important;border-width:3mm!important}.level-journey{margin-bottom:4mm}.report-method{font-size:8pt}.report-level-guide__list{overflow:visible!important}}`;document.head.appendChild(s)}
async function refreshAdminSession(){if(!adminMode)return;const options={credentials:'include',cache:'no-store'};let response=await apiFetch('/.netlify/functions/supabase_auth?action=whoami&_='+Date.now(),options),session=await response.json().catch(()=>({}));if(response.ok&&session.user_id)return;response=await apiFetch('/.netlify/functions/supabase_auth?action=refresh&_='+Date.now(),options);session=await response.json().catch(()=>({}));if(response.ok&&session.access_token&&window.WillenaAPI?.setLocalTokens)window.WillenaAPI.setLocalTokens(session.access_token,session.refresh_token)}
async function load(){await refreshAdminSession();const adminHeaders={'content-type':'application/json'};if(adminMode){try{const access=localStorage.getItem('sb_access_token');if(access&&access.includes('.')&&access.length>50)adminHeaders.Authorization=`Bearer ${access}`}catch(_){}}const reportRequest=adminMode?apiFetch(ADMIN_ENDPOINT,{method:'POST',credentials:'include',headers:adminHeaders,body:JSON.stringify({action:'level_test_detail',attempt_id:attemptId,source:adminSource}),cache:'no-store'}):fetch(ENDPOINT,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({action:'report',attempt_id:attemptId,session_token:token}),cache:'no-store'});const [rr,pr]=await Promise.all([reportRequest,fetch(`${CURRICULUM_URL}/rest/v1/assessment_report_profiles?select=level_id,skill,summary_en,summary_ko,next_step_en,next_step_ko&status=eq.published&order=level_id.asc,sort_order.asc`,{headers:{apikey:CURRICULUM_KEY,Authorization:`Bearer ${CURRICULUM_KEY}`},cache:'no-store'})]);const d=await rr.json().catch(()=>({}));if(!rr.ok||!d.success)throw new Error(d.error||'Could not load report');if(pr.ok){const rows=await pr.json();profiles=new Map(rows.map(r=>[`${r.level_id}:${r.skill}`,r]));}return d}
let calculation=null;
function overall(){return calculation.overall()}
function estimate(skill){return calculation.estimate(skill)}
const profile=(l,s)=>profiles.get(`${l}:${s}`)||null;
const txt=(r,f,ko,fb='')=>clean(r?.[`${f}_${ko?'ko':'en'}`])||fb;
function fallback(level,skill,ko){const p=level<=2?level:level-2;return ko?`레벨 ${p}에서 익숙한 ${skillLabels[skill]?.ko||'영어'}를 이해하고 사용할 수 있습니다.`:`Can understand and use familiar ${skillLabels[skill]?.en.toLowerCase()||'English'} at Level ${p}.`}
function journey(best,ko){const current=Math.max(1,Math.min(MAX_LEVEL,Number(best)||1)),starter=`<i class="report-skill__segment is-starter ${current<=2?'is-current':'is-complete'}"></i>`,numbered=Array.from({length:12},(_,i)=>{const internal=i+3;return `<i class="report-skill__segment ${internal<current?'is-complete':internal===current?'is-current':''}"></i>`}).join(''),label=ko?`${current<=2?'스타터':levelNamesKo[current]} 배치 결과`:`${current<=2?'Starter':levelNames[current]} placement result`,stages=ko?['스타터','기초','초급','중급','고급','숙련']:['Starter','Foundation','Elementary','Intermediate','Advanced','Proficient'];return `<div class="report-placement-scale"><div class="report-placement-pips" role="img" aria-label="${label}">${starter}${numbered}</div><div class="report-placement-stages">${stages.map(stage=>`<span>${stage}</span>`).join('')}</div></div>`}
function skillRow(skill,ko){const r=estimate(skill),name=skillLabels[skill][ko?'ko':'en'];if(!r.assessed){const teacherAssessed=skill==='speaking'||skill==='writing',note=teacherAssessed?(ko?'이 영역은 원어민 원장님이 직접 평가합니다.':'This skill will be assessed by the native-speaking director.'):(ko?'이 영역은 최소 세 문항이 필요합니다.':'At least three questions are needed to estimate this skill.');return `<div class="report-skill is-unassessed"><div class="report-skill__head"><strong>${name}</strong><span class="report-skill__level">${teacherAssessed?(ko?'원어민 원장님 평가':'Director assessment'):(ko?'평가되지 않음':'Not assessed')}</span></div><p class="report-skill__note">${note}</p></div>`}const note=txt(profile(r.level,skill),'summary',ko,fallback(r.level,skill,ko));return `<div class="report-skill"><div class="report-skill__head"><strong>${name}</strong><span class="report-skill__level">${ko?levelNamesKo[r.level]:levelNames[r.level]}${r.plus?'+':''}</span></div><div class="report-skill__track"><i style="width:${r.confidence}%"></i></div><p class="report-skill__note">${note}</p></div>`}
function overallSummary(level,ko){return txt(profile(level,'overall'),'summary',ko,fallback(level,'grammar',ko))}
function overallSummaryMarkup(level,ko){const raw=overallSummary(level,ko),parts=raw.split(/(?=【|\[)/).map(clean).filter(Boolean);if(parts.length<2)return `<span>${esc(raw)}</span>`;return parts.map(part=>{const match=part.match(/^(【[^】]+】|\[[^\]]+\])\s*/);return match?`<span><strong>${esc(match[1])}</strong>${esc(part.slice(match[0].length))}</span>`:`<span>${esc(part)}</span>`}).join('')}
function canDo(best,ko){const arr=assessed.map(skill=>({skill,r:estimate(skill)})).filter(x=>x.r.assessed).slice(0,4).map(x=>txt(profile(x.r.level,x.skill),'summary',ko,fallback(x.r.level,x.skill,ko)));if(arr.length<2)arr.unshift(txt(profile(best,'overall'),'summary',ko,fallback(best,'grammar',ko)));return [...new Set(arr)].slice(0,4).map(x=>`<li>${x}</li>`).join('')}
function nextStep(best,ko){const weak=assessed.map(skill=>({skill,r:estimate(skill)})).filter(x=>x.r.assessed).sort((a,b)=>a.r.level-b.r.level)[0];if(weak){const t=txt(profile(weak.r.level,weak.skill),'next_step',ko,'');if(t)return t}return txt(profile(best,'overall'),'next_step',ko,ko?'다음 단계의 영어를 정확하게 사용할 수 있도록 꾸준히 연습해 주세요.':'Continue practising the next level with growing accuracy and independence.')}
function updateHeader(ko){const logo=document.querySelector('.brand-logo');if(logo)logo.src='/Assets/Images/Logo.png';const subtitle=document.querySelector('#brandSubtitle');if(subtitle)subtitle.textContent=ko?'학생 리포트':'Student Report';document.querySelectorAll('[data-language-choice]').forEach(b=>b.classList.toggle('is-active',b.dataset.languageChoice===(ko?'ko':'en')))}
function render(){const ko=document.documentElement.lang==='ko',best=overall(),c=reportData?.candidate||{};updateHeader(ko);const tools=teacherMode?`<div class="teacher-report-tools"><button id="printReport" class="teacher-print-btn">${ko?'PDF 열기':'Open PDF'}</button></div>`:'';root.innerHTML=tools+`<section class="screen screen-safe-in report-screen screen-safe-ready" data-enhanced-report="1"><div class="print-report-heading"><strong>Willena English</strong><span>${clean(c.student_name)} · ${clean(c.school_name)} · ${clean(c.school_grade)}</span></div><section class="report-hero"><span class="report-kicker">${ko?'추천 시작 레벨':'Estimated starting level'}</span><div class="report-level"><span>${ko?(best<=2?'스타터':'레벨'):(best<=2?'Starter':'Level')}</span><strong>${best<=2?best:best-2}</strong></div>${journey(best,ko)}</section><section class="report-card report-current-level"><h3>${ko?'현재 레벨':'Current level'}</h3><div class="report-current-level__copy">${overallSummaryMarkup(best,ko)}</div></section><section class="report-card"><h3>${ko?'영역별 레벨':'Skill levels'}</h3>${all.map(s=>skillRow(s,ko)).join('')}</section><p class="report-method">${ko?'영역별 레벨은 해당 유형의 문항이 세 개 이상 출제된 경우에만 표시됩니다. +는 최고 출제 레벨을 충분한 문항에서 안정적으로 통과한 경우에만 표시됩니다.':'A skill estimate appears only after at least three questions. A + requires sustained success at the highest tested level.'}</p><div class="actions report-actions"><button class="btn btn-primary" id="closeReport">${ko?'보고서 닫기':'Close report'}</button></div></section>`;document.querySelector('#closeReport')?.addEventListener('click',()=>window.close());document.querySelector('#printReport')?.addEventListener('click',()=>window.print())}
document.addEventListener('click',e=>{const b=e.target.closest('[data-language-choice]');if(!b)return;document.documentElement.lang=b.dataset.languageChoice==='en'?'en':'ko';render()},true);
(async()=>{try{installPrintStyles();if(!attemptId||(!token&&!adminMode))throw new Error('Missing report access.');if(adminMode&&!adminSource)throw new Error('Missing test source.');reportData=await load();if(window.WillenaLevelTestScoring)window.WillenaLevelTestScoring.repairPayload(reportData);else(reportData.responses||[]).forEach(repairSentenceResponse);const lang=String(reportData.candidate?.metadata?.language||reportData.attempt?.setup?.language||reportData.attempt?.metadata?.language||'ko').toLowerCase().startsWith('en')?'en':'ko';document.documentElement.lang=lang;calculation=window.WillenaLevelReportCalculation.create({attempt:reportData.attempt,responses:reportData.responses});calculation.evidence.forEach(r=>evidence.push(r));window.WillenaSharedReportModel={data:reportData,profiles,evidence,MAX_LEVEL,assessed,all,skillFor,overall,estimate,calculation};window.dispatchEvent(new CustomEvent('willena:shared-report-ready',{detail:window.WillenaSharedReportModel}));render()}catch(e){root.innerHTML=`<section class="screen report-screen"><p class="report-summary">${clean(e.message)||'Could not load report.'}</p></section>`}})();
})();
