(function(global){
'use strict';
var CONTENT_URL='https://gxwfsqxyuufqtitspfqg.supabase.co';
var CONTENT_KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
var HEADERS={apikey:CONTENT_KEY,Authorization:'Bearer '+CONTENT_KEY};
var TARGET=15,FOCUS_TARGET=8,engine=null,pool=[],queue=[],baseIds=new Set(),settled=new Set(),current=null,answered=false,previousScroll=0,sessionTarget=TARGET,sessionMode='daily',adaptiveState={items:[]},currentContext=null;
var card=document.querySelector('.unit-progress-card'),ring=document.querySelector('.progress-ring'),title=document.getElementById('smartProgressTitle'),copy=document.getElementById('smartProgressCopy'),pctEl=document.getElementById('smartDailyPct');
var panel=document.getElementById('smartPracticePanel'),root=document.getElementById('smartActivityRoot'),closeBtn=document.getElementById('smartClose'),countEl=document.getElementById('smartCount');
var headerEyebrow=panel&&panel.querySelector('.practice-toolbar .eyebrow'),headerTitle=panel&&panel.querySelector('.practice-toolbar h2');
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function shuffle(a){return(a||[]).slice().sort(function(){return Math.random()-.5;});}
function dateKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function heroContext(){var b=document.getElementById('bookTitle'),u=document.getElementById('unitTitle');return{bookTitle:String(b&&b.textContent||'').trim(),unitText:String(u&&u.textContent||'').trim()};}
function unitNumber(text){var m=String(text||'').match(/Unit\s*(\d+)/i);return m?Number(m[1]):null;}
function dailyKey(){return'willena-daily-workout-v1|'+dateKey();}
function readNumber(k){try{var n=Number(localStorage.getItem(k)||0);return Number.isFinite(n)?n:0;}catch(_){return 0;}}
function dailyCount(){return readNumber(dailyKey());}
function addDaily(){try{localStorage.setItem(dailyKey(),String(dailyCount()+1));}catch(_){}paint();}
function ready(){var c=heroContext();return c.bookTitle&&!/^Loading/i.test(c.bookTitle)&&unitNumber(c.unitText);}
function paint(){if(!ring)return;var done=dailyCount(),pct=Math.min(100,Math.round(done/TARGET*100)),extra=Math.max(0,done-TARGET);ring.style.background='conic-gradient(var(--pink) 0 '+pct+'%,#dff5f7 '+pct+'% 100%)';if(pctEl)pctEl.textContent=done>=TARGET?'✓':done+'/'+TARGET;if(title)title.textContent='Daily Workout';if(copy)copy.textContent=done>=TARGET?(extra?'오늘 목표 완료 · 추가 '+extra+'문항':'오늘 목표 완료 ✓'):'오늘의 최소 학습 · '+done+'/'+TARGET;}
async function get(path){var r=await fetch(CONTENT_URL+'/rest/v1/'+path,{headers:HEADERS,cache:'no-store'});if(!r.ok)throw new Error('Content DB '+r.status);return r.json();}
async function resolveHeroContext(){var c=heroContext(),n=unitNumber(c.unitText);if(!c.bookTitle||!n)throw new Error('Book/unit not ready');var books=await get('content_books?select=id,title,internal_level_id,public_level,metadata&title=eq.'+encodeURIComponent(c.bookTitle)+'&status=in.(review,published)&limit=1');if(!books.length)throw new Error('Book not found');var units=await get('content_units?select=id,unit_number,title,internal_level_id,public_level&book_id=eq.'+encodeURIComponent(books[0].id)+'&unit_number=eq.'+n+'&status=in.(review,published)&limit=1');if(!units.length)throw new Error('Unit not found');return{bookId:books[0].id,bookTitle:books[0].title,internalLevelId:units[0].internal_level_id||books[0].internal_level_id||null,publicLevel:units[0].public_level||books[0].public_level||null,unitId:units[0].id,unitNumber:Number(units[0].unit_number),unitTitle:units[0].title};}
async function resolveContextByIds(bookId,unitId){var both=await Promise.all([get('content_books?select=id,title,internal_level_id,public_level,metadata&id=eq.'+encodeURIComponent(bookId)+'&status=in.(review,published)&limit=1'),get('content_units?select=id,book_id,unit_number,title,internal_level_id,public_level&id=eq.'+encodeURIComponent(unitId)+'&book_id=eq.'+encodeURIComponent(bookId)+'&status=in.(review,published)&limit=1')]);if(!both[0].length||!both[1].length)throw new Error('Focused book/unit not found');var b=both[0][0],u=both[1][0];return{bookId:b.id,bookTitle:b.title,internalLevelId:u.internal_level_id||b.internal_level_id||null,publicLevel:u.public_level||b.public_level||null,unitId:u.id,unitNumber:Number(u.unit_number),unitTitle:u.title};}
function contentKeyFromActivity(a){return String(a.sourceType||'activity')+'|'+String(a.sourceId||'')+'|'+String(a.skill||'');}
function contentKeyFromState(s){return String(s.content_type||'activity')+'|'+String(s.content_id||'')+'|'+String(s.skill||'');}
function mistakeKey(m){return String(m.contentType||m.content_type||'activity')+'|'+String(m.contentId||m.content_id||'')+'|'+String(m.skill||'');}
function stateWorthLoading(s){if(!s)return false;var due=!s.next_review_at||Date.parse(s.next_review_at)<=Date.now();return due||Number(s.lapses||0)>0;}
function labelActivity(a,label,extra){a.metadata=Object.assign({},a.metadata||{},extra||{},{source_label:label});return a;}
async function loadCurrentPool(ctx){var pack=await global.WillenaPracticePool.loadUnitPool({bookId:ctx.bookId,unitId:ctx.unitId,language:'ko'});return pack.activities.map(function(a){return labelActivity(a,'Current unit',{current_curriculum:true});});}
async function loadDuePools(ctx,state){var reviewItems=(state.items||[]).filter(stateWorthLoading).sort(function(a,b){var ad=Date.parse(a.next_review_at||0)||0,bd=Date.parse(b.next_review_at||0)||0;if(ad!==bd)return ad-bd;return Number(a.mastery_score||0)-Number(b.mastery_score||0);});var unitKeys=[],unitMap={};reviewItems.forEach(function(s){var k=s.book_id+'|'+s.unit_id;if(k===ctx.bookId+'|'+ctx.unitId)return;if(!unitMap[k]&&unitKeys.length<5){unitMap[k]=[];unitKeys.push(k);}if(unitMap[k])unitMap[k].push(s);});var result=[];for(var i=0;i<unitKeys.length;i++){var parts=unitKeys[i].split('|'),bookId=parts[0],unitId=parts[1];try{var pack=await global.WillenaPracticePool.loadUnitPool({bookId:bookId,unitId:unitId,language:'ko'}),wanted={};unitMap[unitKeys[i]].forEach(function(s){wanted[contentKeyFromState(s)]=true;});pack.activities.forEach(function(a){if(wanted[contentKeyFromActivity(a)])result.push(labelActivity(a,'Spaced review',{adaptive_review:true}));});}catch(_){}}
return result;}
async function loadSameLevelCurriculum(ctx){try{if(!ctx.internalLevelId)return[];var books=await get('content_books?select=id,title,internal_level_id&internal_level_id=eq.'+encodeURIComponent(ctx.internalLevelId)+'&status=in.(review,published)&id=neq.'+encodeURIComponent(ctx.bookId)+'&order=title.asc');if(!books.length)return[];var book=books[Math.floor(Math.random()*books.length)],units=await global.WillenaPracticePool.loadBookUnits(book.id);if(!units.length)return[];var unit=units.find(function(u){return Number(u.unit_number)===ctx.unitNumber;})||units[Math.floor(Math.random()*units.length)];var pack=await global.WillenaPracticePool.loadUnitPool({bookId:book.id,unitId:unit.id,language:'ko'});return shuffle(pack.activities).slice(0,16).map(function(a){return labelActivity(a,'Same-level curriculum',{same_level_extension:true,internal_level_id:ctx.internalLevelId});});}catch(_){return[];}}
async function loadAuthoredBank(ctx){try{if(!global.WillenaStudyQuestionBank||!ctx.internalLevelId)return[];var rows=await global.WillenaStudyQuestionBank.loadLevel(ctx.internalLevelId,{bookId:ctx.bookId,unitId:ctx.unitId});return shuffle(rows).slice(0,30).map(function(a){return labelActivity(a,'Approved level bank',{assessment_bank:true});});}catch(e){console.debug('[DailyWorkout] authored bank',e);return[];}}
async function buildAdaptivePool(options){options=options||{};if(!global.WillenaPracticePool||!global.WillenaAdaptiveStudy)throw new Error('Adaptive study modules unavailable');adaptiveState=global.WillenaStudyProgress?await global.WillenaStudyProgress.getAdaptiveState():{items:[]};if(options.focusUnitId&&options.focusBookId){var focusContext=await resolveContextByIds(options.focusBookId,options.focusUnitId),focusPack=await global.WillenaPracticePool.loadUnitPool({bookId:options.focusBookId,unitId:options.focusUnitId,language:'ko'});pool=focusPack.activities.map(function(a){return labelActivity(a,'Focused unit practice',{focused_practice:true});});if(options.focusSkill==='grammar'||options.focusSkill==='conversation'||(options.mistakeItems||[]).some(function(m){return String(m.contentType||m.content_type)==='assessment_item';})){var bank=await loadAuthoredBank(focusContext);pool=pool.concat(bank.filter(function(a){return !options.focusSkill||a.skill===options.focusSkill;}));}
 if(Array.isArray(options.mistakeItems)&&options.mistakeItems.length){var wanted={};options.mistakeItems.forEach(function(m){wanted[mistakeKey(m)]=true;});pool=pool.filter(function(a){return wanted[contentKeyFromActivity(a)];}).map(function(a){return labelActivity(a,'Your previous mistake',{mistake_review:true});});if(!pool.length)throw new Error('Those previous mistakes are not available as practice questions anymore.');}
 return;}currentContext=await resolveHeroContext();var parts=await Promise.all([loadCurrentPool(currentContext),loadDuePools(currentContext,adaptiveState),loadSameLevelCurriculum(currentContext),loadAuthoredBank(currentContext)]);pool=parts[0].concat(parts[1]).concat(parts[2]).concat(parts[3]);}
function showSmartScreen(){previousScroll=window.scrollY||0;panel.hidden=false;panel.style.position='fixed';panel.style.inset='0';panel.style.zIndex='10000';panel.style.margin='0';panel.style.borderRadius='0';panel.style.width='100vw';panel.style.height='100dvh';panel.style.maxHeight='100dvh';panel.style.overflowY='auto';panel.style.overflowX='hidden';panel.style.boxSizing='border-box';panel.style.background='linear-gradient(180deg,#dff7f8 0,#effafb 34%,#f7fafb 100%)';panel.style.padding='clamp(12px,3.5vw,34px)';panel.scrollTop=0;}
function closeSmartScreen(){panel.hidden=true;paint();window.scrollTo({top:previousScroll,left:0,behavior:'auto'});}
function setHeader(mode,detail){if(!headerEyebrow||!headerTitle)return;if(mode==='focus'){headerEyebrow.textContent=(detail.skillLabel||detail.skill||'SKILL').toUpperCase();headerTitle.textContent=detail.mistakeItems&&detail.mistakeItems.length?'틀린 문제 다시 풀기':'약한 부분 집중 연습';}else{headerEyebrow.textContent='DAILY WORKOUT';headerTitle.textContent='오늘의 학습';}}
function makeSession(options){options=options||{};var selectorOptions={target:options.target||TARGET,currentBookId:currentContext&&currentContext.bookId,currentUnitId:currentContext&&currentContext.unitId,focusSkill:options.focusSkill||null,focusUnitId:options.focusUnitId||null};var chosen=global.WillenaAdaptiveStudy.chooseSession(pool,adaptiveState,selectorOptions);sessionTarget=chosen.length;if(!sessionTarget)throw new Error('No useful activities are available yet');queue=chosen.slice();baseIds=new Set(chosen.map(function(a){return a.id;}));settled=new Set();renderNext();}
function addSourceBadge(activity){var cardEl=root.querySelector('.activity-card');if(!cardEl)return;var m=activity&&activity.metadata||{},label=m.source_label||m.pool_source||'Study';var badge=document.createElement('div');badge.className='activity-source-badge';badge.textContent='Source · '+label;cardEl.insertBefore(badge,cardEl.firstChild);}
function renderNext(){if(!queue.length){finish();return;}current=queue.shift();answered=false;countEl.textContent=Math.min(sessionTarget,settled.size+1)+' / '+sessionTarget;engine=new WillenaActivityEngine(root,{onAnswer:function(){}});engine.setActivity(current);addSourceBadge(current);panel.scrollTop=0;}
function turnCheckIntoNext(){var check=root.querySelector('.activity-check');if(!check)return;var replacement=check.cloneNode(true);replacement.disabled=false;replacement.textContent=queue.length?'다음':'완료';check.replaceWith(replacement);replacement.addEventListener('click',renderNext,{once:true});}
function onAnswer(e){if(panel.hidden||!current||answered)return;var d=e.detail||{},a=d.activity||{},r=d.result||{};if(a.id!==current.id)return;answered=true;if(r.correct){if(baseIds.has(current.id)&&!settled.has(current.id)){settled.add(current.id);if(sessionMode==='daily')addDaily();}}else{global.WillenaAdaptiveStudy.insertRetry(queue,current);}turnCheckIntoNext();}
function finish(){countEl.textContent='완료';var msg=sessionMode==='focus'?'약한 부분을 집중해서 연습했어요.':'오늘 필요한 복습과 새 학습을 끝냈어요.';root.innerHTML='<div class="activity-card smart-finish"><div class="smart-confetti" aria-hidden="true"></div><span class="eyebrow">'+(sessionMode==='focus'?'FOCUSED PRACTICE':'DAILY WORKOUT')+'</span><h2>잘했어요!</h2><p>'+sessionTarget+'개 활동을 끝냈어요.</p><p class="smart-finish-note">'+msg+'</p><button type="button" class="activity-check smart-home-button">학습 화면으로 돌아가기</button></div>';var back=root.querySelector('.smart-home-button');if(back)back.addEventListener('click',closeSmartScreen,{once:true});paint();}
async function startDaily(e){if(e){e.preventDefault();e.stopPropagation();}if(!ready())return;sessionMode='daily';setHeader('daily',{});showSmartScreen();root.innerHTML='<div class="study-loading">오늘 가장 도움이 되는 문제를 고르는 중…</div>';countEl.textContent='— / '+TARGET;try{currentContext=await resolveHeroContext();await buildAdaptivePool({});makeSession({target:TARGET});}catch(err){root.innerHTML='<div class="study-loading">Daily Workout을 불러오지 못했습니다. '+esc(err.message||err)+'</div>';}}
async function startFocus(detail){detail=detail||{};if(!detail.bookId||!detail.unitId||!detail.skill)return;sessionMode='focus';setHeader('focus',detail);showSmartScreen();root.innerHTML='<div class="study-loading">'+(detail.mistakeItems&&detail.mistakeItems.length?'실제로 틀린 문제를 찾는 중…':'약한 '+esc(detail.skillLabel||detail.skill)+' 문제를 찾는 중…')+'</div>';countEl.textContent='—';try{currentContext=await resolveContextByIds(detail.bookId,detail.unitId).catch(function(){return resolveHeroContext().catch(function(){return null;});});await buildAdaptivePool({focusBookId:detail.bookId,focusUnitId:detail.unitId,focusSkill:detail.skill,mistakeItems:detail.mistakeItems||null});makeSession({target:detail.mistakeItems&&detail.mistakeItems.length?Math.min(FOCUS_TARGET,detail.mistakeItems.length):FOCUS_TARGET,focusSkill:detail.skill,focusUnitId:detail.unitId});}catch(err){root.innerHTML='<div class="study-loading">집중 연습을 준비하지 못했습니다. '+esc(err.message||err)+'</div>';}}
if(!card||!panel)return;card.setAttribute('role','button');card.setAttribute('tabindex','0');card.setAttribute('aria-label','Start Daily Workout');card.style.cursor='pointer';card.addEventListener('click',startDaily,true);card.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){startDaily(e);}},true);closeBtn.addEventListener('click',closeSmartScreen);global.addEventListener('willena:activity-answer',onAnswer);global.addEventListener('willena:smart-study-focus',function(e){startFocus(e.detail||{});});paint();var tries=0,t=setInterval(function(){tries++;paint();if((ready()&&tries>5)||tries>30)clearInterval(t);},350);window.addEventListener('pageshow',function(){setTimeout(paint,100);});
})(window);
