(function(global){
'use strict';
var URL='https://gxwfsqxyuufqtitspfqg.supabase.co';
var KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
var HEADERS={apikey:KEY,Authorization:'Bearer '+KEY};
var ctx=null,units=[];
function text(v){return String(v==null?'':v).trim();}
function el(tag,cls,txt){var n=document.createElement(tag);if(cls)n.className=cls;if(txt!=null)n.textContent=txt;return n;}
function unitNumber(v){var m=text(v).match(/Unit\s*(\d+)/i);return m?Number(m[1]):null;}
async function get(path){var r=await fetch(URL+'/rest/v1/'+path,{headers:HEADERS,cache:'no-store'});if(!r.ok)throw new Error('Content DB '+r.status);return r.json();}
async function resolve(){var title=text(document.getElementById('bookTitle')&&document.getElementById('bookTitle').textContent),n=unitNumber(document.getElementById('unitTitle')&&document.getElementById('unitTitle').textContent);if(!title||!n||/^Loading/i.test(title))return null;var books=await get('content_books?select=id,title,internal_level_id&title=eq.'+encodeURIComponent(title)+'&status=in.(review,published)&limit=1');if(!books.length)return null;units=await get('content_units?select=id,unit_number,title&book_id=eq.'+encodeURIComponent(books[0].id)+'&status=in.(review,published)&order=unit_number.asc');var u=units.find(function(x){return Number(x.unit_number)===n;})||units[0];ctx={bookId:books[0].id,bookTitle:books[0].title,levelId:books[0].internal_level_id,currentUnitId:u&&u.id,currentUnitNumber:n};return ctx;}
function chooseUnit(number){var change=document.getElementById('changeUnitBtn');if(!change)return;change.click();var tries=0,t=setInterval(function(){tries++;var picks=Array.prototype.slice.call(document.querySelectorAll('.unit-pick'));var target=picks.find(function(b){return unitNumber(b.textContent)===Number(number);});if(target){clearInterval(t);target.click();setTimeout(function(){ctx=null;mount(true);},250);return;}if(tries>25)clearInterval(t);},40);}
function drawUnits(){var title=document.getElementById('unitTitle');if(!title||!ctx||!units.length)return;var old=document.getElementById('studyHomeUnits');if(old)old.remove();var wrap=el('div','study-home-units');wrap.id='studyHomeUnits';var lab=el('div','study-home-units-label');lab.appendChild(el('span','', 'Choose a unit to study'));lab.appendChild(el('span','', 'Current · Unit '+ctx.currentUnitNumber));wrap.appendChild(lab);var strip=el('div','study-home-unit-strip');units.forEach(function(u){var b=el('button','study-home-unit'+(Number(u.unit_number)===Number(ctx.currentUnitNumber)?' is-current':''),'Unit '+u.unit_number);b.type='button';b.addEventListener('click',function(){chooseUnit(u.unit_number);});strip.appendChild(b);});wrap.appendChild(strip);title.insertAdjacentElement('afterend',wrap);}
function skillLabel(skill){return{vocabulary:'Vocabulary',spelling:'Spelling',grammar:'Grammar',sentence_building:'Sentence Builder',conversation:'Conversation',listening:'Listening'}[skill]||skill;}
function recommendCards(progress,adaptive){var out=[],skills=Array.isArray(progress&&progress.skill_summary)?progress.skill_summary.slice():[];skills.sort(function(a,b){return Number(a.mastery_score||0)-Number(b.mastery_score||0);});skills.filter(function(s){return Number(s.attempts||0)>0&&Number(s.mastery_score||0)<80;}).slice(0,2).forEach(function(s){out.push({type:'skill',skill:s.skill,title:'Practice '+skillLabel(s.skill),copy:Math.round(Number(s.mastery_score||0))+'% mastery · this is one of your weakest areas.',action:'Practice weak items →'});});var due=(adaptive&&adaptive.items||[]).filter(function(x){return String(x.book_id)===String(ctx.bookId)&&x.due;});if(due.length)out.push({type:'daily',title:'Review what is due',copy:due.length+' items are ready for spaced review.',action:'Start Daily Workout →'});var vocab=skills.find(function(s){return s.skill==='vocabulary';}),next=units.find(function(u){return Number(u.unit_number)===Number(ctx.currentUnitNumber)+1;});if(out.length<3&&vocab&&Number(vocab.mastery_score||0)>=80&&next)out.push({type:'unit',unitNumber:next.unit_number,title:'Preview Unit '+next.unit_number+' words',copy:'Your current vocabulary is strong, so you can safely look ahead.',action:'Open Unit '+next.unit_number+' →'});return out.slice(0,3);}
function renderCoach(progress,adaptive){var hero=document.querySelector('.book-hero');if(!hero||!ctx)return;var old=document.getElementById('studyCoach');if(old)old.remove();var section=el('section','study-coach');section.id='studyCoach';var head=el('div','study-coach-head'),left=el('div');left.appendChild(el('span','eyebrow','RECOMMENDED PRACTICE'));left.appendChild(el('h2','','What should I study next?'));head.appendChild(left);head.appendChild(el('span','study-coach-note','Based on your mastery + spaced review'));section.appendChild(head);var grid=el('div','study-coach-grid'),cards=recommendCards(progress,adaptive);if(!cards.length)cards=[{type:'daily',title:'Keep your knowledge fresh',copy:'Your current weak areas are under control. Do today’s adaptive review.',action:'Start Daily Workout →'}];cards.forEach(function(r){var b=el('button','study-coach-card');b.type='button';b.appendChild(el('span','coach-kicker',r.type==='skill'?'Weak area':r.type==='unit'?'Ready to explore':'Due review'));b.appendChild(el('strong','',r.title));b.appendChild(el('small','',r.copy));b.appendChild(el('span','coach-action',r.action));b.addEventListener('click',function(){if(r.type==='skill')global.dispatchEvent(new CustomEvent('willena:smart-study-focus',{detail:{bookId:ctx.bookId,unitId:ctx.currentUnitId,skill:r.skill,skillLabel:skillLabel(r.skill)}}));else if(r.type==='unit')chooseUnit(r.unitNumber);else{var card=document.querySelector('.unit-progress-card');if(card)card.click();}});grid.appendChild(b);});section.appendChild(grid);hero.insertAdjacentElement('afterend',section);}
async function hydrateCoach(){if(!ctx||!global.WillenaStudyProgress)return;try{var both=await Promise.all([global.WillenaStudyProgress.getProgress(ctx.bookId,ctx.currentUnitId),global.WillenaStudyProgress.getAdaptiveState()]);renderCoach(both[0],both[1]);}catch(e){console.debug('[StudyCoach]',e);}}
async function mount(force){try{if(force)ctx=null;if(!ctx)ctx=await resolve();if(!ctx)return false;drawUnits();hydrateCoach();return true;}catch(e){console.debug('[StudyCoach]',e);return false;}}
function wait(){var tries=0,t=setInterval(function(){tries++;mount(false).then(function(ok){if(ok||tries>40)clearInterval(t);});},250);}
global.addEventListener('willena:study-recording',function(e){if(e&&e.detail&&e.detail.status==='recorded')setTimeout(hydrateCoach,180);});global.addEventListener('willena:study-progress-updated',function(){setTimeout(hydrateCoach,120);});document.addEventListener('click',function(e){if(e.target.closest('.unit-pick'))setTimeout(function(){mount(true);},250);},true);if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait,{once:true});else wait();
})(window);
