(function(global){
'use strict';
var CONTENT_URL='https://gxwfsqxyuufqtitspfqg.supabase.co';
var CONTENT_KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
var CONTENT_HEADERS={apikey:CONTENT_KEY,Authorization:'Bearer '+CONTENT_KEY};
var SKILLS=[['vocabulary','Vocabulary'],['spelling','Spelling'],['grammar','Grammar'],['sentence_building','Sentence Builder'],['conversation','Conversation'],['listening','Listening']];
var bookId=null,units=[],selectedUnitId=null,currentUnitNumber=null,refreshTimer=0,progressCache={};
function pct(value){var n=Number(value);return Number.isFinite(n)?Math.round(n)+'%':'—';}
function accuracy(value){var n=Number(value);return Number.isFinite(n)?Math.round(n*100)+'%':'—';}
function num(value){var n=Number(value);return Number.isFinite(n)?String(n):'0';}
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
async function contentGet(path){var r=await fetch(CONTENT_URL+'/rest/v1/'+path,{headers:CONTENT_HEADERS,cache:'no-store'});if(!r.ok)throw new Error('Content DB '+r.status);return r.json();}
function unitNumberFromHero(){var text=String(document.getElementById('unitTitle')&&document.getElementById('unitTitle').textContent||'');var m=text.match(/Unit\s*(\d+)/i);return m?Number(m[1]):null;}
async function loadUnits(){var title=String(document.getElementById('bookTitle')&&document.getElementById('bookTitle').textContent||'').trim();if(!title||/^Loading/i.test(title)||/^Could not/i.test(title))return false;var books=await contentGet('content_books?select=id,title&title=eq.'+encodeURIComponent(title)+'&status=in.(review,published)&limit=1');if(!books.length)return false;bookId=books[0].id;units=await contentGet('content_units?select=id,unit_number,title&book_id=eq.'+encodeURIComponent(bookId)+'&status=in.(review,published)&order=unit_number.asc');progressCache={};currentUnitNumber=unitNumberFromHero();var current=units.find(function(u){return Number(u.unit_number)===Number(currentUnitNumber);})||units[0];selectedUnitId=current&&current.id||null;drawUnitCards();return true;}
function mount(){var hero=document.querySelector('.book-hero');if(!hero||document.getElementById('studyStats'))return;var section=el('section','study-stats');section.id='studyStats';var head=el('div','study-stats-head');var left=el('div');left.appendChild(el('span','eyebrow','UNIT PROGRESS'));left.appendChild(el('h2','','단원 학습 현황'));head.appendChild(left);head.appendChild(el('span','study-stats-note','Canonical study-v1'));section.appendChild(head);var unitsWrap=el('div','study-unit-strip');unitsWrap.id='studyUnitStrip';unitsWrap.innerHTML='<span class="study-stats-message">Loading units…</span>';section.appendChild(unitsWrap);var body=el('div','study-stats-message','Loading progress…');body.id='studyStatsBody';section.appendChild(body);hero.insertAdjacentElement('afterend',section);waitForUnitContext();}
function waitForUnitContext(){var tries=0;var timer=setInterval(async function(){tries++;try{if(await loadUnits()){clearInterval(timer);preloadAllProgress();refreshSelected();return;}}catch(_){}if(tries>40){clearInterval(timer);var strip=document.getElementById('studyUnitStrip');if(strip)strip.innerHTML='';refreshSelected();}},250);}
function drawUnitCards(){var strip=document.getElementById('studyUnitStrip');if(!strip)return;strip.innerHTML='';units.forEach(function(u){var b=el('button','study-unit-card'+(u.id===selectedUnitId?' is-active':'')+(Number(u.unit_number)===Number(currentUnitNumber)?' is-current':''));b.type='button';b.dataset.unitId=u.id;b.textContent='Unit '+u.unit_number;b.addEventListener('click',function(){selectedUnitId=u.id;drawUnitCards();var cached=progressCache[u.id];if(cached){render(cached);return;}refreshSelected();});strip.appendChild(b);});var active=strip.querySelector('.is-active');if(active&&active.scrollIntoView)active.scrollIntoView({behavior:'auto',block:'nearest',inline:'center'});}
function render(data){var body=document.getElementById('studyStatsBody');if(!body)return;if(!data||data.preview){body.className='study-stats-message';body.textContent='Preview mode · real progress is not changed.';return;}var s=data.summary||{},skills=Array.isArray(data.skill_summary)?data.skill_summary:[],by={};skills.forEach(function(x){by[x.skill]=x;});body.className='';body.innerHTML='';var selected=units.find(function(u){return u.id===selectedUnitId;});if(selected){var context=el('div','study-unit-context');context.appendChild(el('strong','', 'Unit '+selected.unit_number));context.appendChild(el('span','',Number(selected.unit_number)===Number(currentUnitNumber)?'Current unit':'Progress view'));body.appendChild(context);}var kpis=el('div','study-stats-kpis');[['Mastery',pct(s.mastery_score)],['Accuracy',accuracy(s.accuracy)],['Attempts',num(s.attempts)],['Extra study',num(s.independent_attempts)]].forEach(function(row){var card=el('div','study-stat-kpi');card.appendChild(el('strong','',row[1]));card.appendChild(el('span','',row[0]));kpis.appendChild(card);});body.appendChild(kpis);var grid=el('div','study-skill-stats');SKILLS.forEach(function(def){var row=by[def[0]],card=el('div','study-skill-stat'+(row?'':' study-skill-empty')),top=el('div','study-skill-top');top.appendChild(el('span','',def[1]));top.appendChild(el('strong','',row?pct(row.mastery_score):'Not studied'));card.appendChild(top);var bar=el('div','study-skill-bar'),fill=el('i');fill.style.width=row&&Number.isFinite(Number(row.mastery_score))?Math.max(0,Math.min(100,Number(row.mastery_score)))+'%':'0%';bar.appendChild(fill);card.appendChild(bar);grid.appendChild(card);});body.appendChild(grid);}
async function fetchUnitProgress(unitId,force){if(!global.WillenaStudyProgress)throw new Error('Progress service unavailable');if(!force&&progressCache[unitId])return progressCache[unitId];var data=await global.WillenaStudyProgress.getProgress(bookId,unitId);progressCache[unitId]=data;return data;}
function preloadAllProgress(){units.forEach(function(u){fetchUnitProgress(u.id,false).then(function(data){if(u.id===selectedUnitId)render(data);}).catch(function(){});});}
async function refreshSelected(force){var body=document.getElementById('studyStatsBody');if(!selectedUnitId)return;try{var data=await fetchUnitProgress(selectedUnitId,!!force);if(selectedUnitId&&progressCache[selectedUnitId]===data)render(data);}catch(error){if(body&&!progressCache[selectedUnitId]){body.className='study-stats-message';body.textContent='Progress will appear after your next saved practice.';}}}
function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(function(){if(selectedUnitId)delete progressCache[selectedUnitId];refreshSelected(true);},180);}
global.addEventListener('willena:study-recording',function(e){if(e&&e.detail&&e.detail.status==='recorded'){var unitId=e.detail.payload&&e.detail.payload.unit_id;if(unitId)delete progressCache[unitId];if(unitId===selectedUnitId)scheduleRefresh();else if(unitId)fetchUnitProgress(unitId,true).catch(function(){});}});global.addEventListener('auth:changed',function(){progressCache={};preloadAllProgress();refreshSelected(true);});global.addEventListener('willena:study-progress-updated',function(){scheduleRefresh();});if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(window);