(function(global){
'use strict';
var SKILLS={vocabulary:{label:'Vocabulary',ko:'어휘',icon:'Aa',index:0},spelling:{label:'Spelling',ko:'철자',icon:'ABC',index:1},grammar:{label:'Grammar',ko:'문법',icon:'✓',index:2},sentence_building:{label:'Sentence Builder',ko:'문장 만들기',icon:'↔',index:3},conversation:{label:'Conversation',ko:'회화',icon:'💬',index:4},listening:{label:'Listening',ko:'듣기',icon:'♪',index:5}};
var progressData=null,lang='ko';
var COPY={ko:{back:'← 학습 홈',eyebrow:'오늘의 학습',title:'연습할 준비 됐나요?',intro:'현재 수업 + 복습하면 좋은 내용',start:'연습 시작',startNote:'필요한 내용부터 시작할게요.',needs:'복습 추천',work:'무엇을 연습할까요?',saved:'저장된 학습 기록 기준',course:'내 교재',lesson:'현재 수업',book:'교재',loading:'불러오는 중…',finding:'단원을 찾는 중',study:'이 단원 공부',choose:'연습 선택',browse:'단원 보기',checking:'학습 기록을 확인하는 중…',clear:'지금 특별히 약한 영역은 없어요. 계속 연습하면 확인할게요.',empty:'몇 문제를 풀면 약한 영역이 여기에 나타나요.',worth:'한 번 더 연습하면 좋아요',starting:'부터 시작할게요.'},en:{back:'← Study home',eyebrow:"TODAY'S STUDY",title:'Ready to practice?',intro:'Current lesson + things worth reviewing',start:'Start Practice',startNote:'I’ll start with what needs attention.',needs:'NEEDS PRACTICE',work:'What to work on',saved:'From your saved progress',course:'MY COURSE',lesson:'Current lesson',book:'BOOK',loading:'Loading…',finding:'Finding your unit',study:'Study this unit',choose:'Choose practice',browse:'Browse units',checking:'Checking your progress…',clear:'Nothing is standing out right now. Keep practising and I’ll keep checking.',empty:'Do a few practice questions and your weak areas will start appearing here.',worth:'Worth another practice round',starting:'Starting with'}};
function c(k){return COPY[lang][k]||k;}
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
function pct(v){var n=Number(v);return Number.isFinite(n)?Math.round(n)+'%':'—';}
function mount(){
 var app=document.getElementById('app'),hero=document.querySelector('.book-hero');if(!app||!hero||document.getElementById('studentStudyHome'))return;
 document.body.classList.add('study-home-enhanced');
 var back=el('button','study-home-return',c('back'));back.type='button';back.id='studyHomeReturn';app.insertBefore(back,hero);
 var home=el('section','study-home');home.id='studentStudyHome';
 home.innerHTML='<article class="study-home-hero"><span id="studyHomeEyebrow" class="eyebrow"></span><h1 id="studyHomeTitle"></h1><p id="studyHomeIntro"></p><button id="studyHomeStart" class="study-home-start" type="button"><span><span id="studyHomeStartText"></span><small id="studyHomeStartNote"></small></span><b>→</b></button></article><div class="study-home-grid"><article class="study-home-card"><div class="study-home-card-head"><div><span id="studyHomeNeedsEyebrow" class="eyebrow"></span><h2 id="studyHomeNeedsTitle"></h2></div><span id="studyHomeNeedsNote" class="study-home-note"></span></div><div id="studyHomeNeeds" class="study-home-needs"></div></article><article class="study-home-card study-course-card"><div class="study-home-card-head"><div><span id="studyHomeCourseEyebrow" class="eyebrow"></span><h2 id="studyHomeCourseTitle"></h2></div></div><div class="study-course-book"><div id="studyHomeCover" class="study-course-cover"></div><div class="study-course-copy"><strong id="studyHomeBook"></strong><span id="studyHomeUnit"></span></div></div><div class="study-course-actions"><button id="studyHomeStudy" type="button"></button><button id="studyHomeSkills" type="button"></button><button id="studyHomeUnits" type="button"></button></div></article></div>';
 app.insertBefore(home,back);
 back.addEventListener('click',showHome);
 document.getElementById('studyHomeStart').addEventListener('click',startRecommended);
 document.getElementById('studyHomeStudy').addEventListener('click',function(){showCourse();var b=document.getElementById('continueBtn');if(b&&!b.disabled)b.click();});
 document.getElementById('studyHomeSkills').addEventListener('click',function(){showCourse('.section-block');});
 document.getElementById('studyHomeUnits').addEventListener('click',function(){showCourse();var b=document.getElementById('changeUnitBtn');if(b)b.click();});
 var languageBtn=document.getElementById('languageBtn');if(languageBtn)languageBtn.addEventListener('click',function(){lang=lang==='ko'?'en':'ko';renderCopy();renderNeeds(progressData);});
 renderCopy();syncCourse();setTimeout(syncCourse,700);setTimeout(syncCourse,1600);loadProgress();
}
function renderCopy(){document.getElementById('studyHomeReturn').textContent=c('back');document.getElementById('studyHomeEyebrow').textContent=c('eyebrow');document.getElementById('studyHomeTitle').textContent=c('title');document.getElementById('studyHomeIntro').textContent=c('intro');document.getElementById('studyHomeStartText').textContent=c('start');document.getElementById('studyHomeNeedsEyebrow').textContent=c('needs');document.getElementById('studyHomeNeedsTitle').textContent=c('work');document.getElementById('studyHomeNeedsNote').textContent=c('saved');document.getElementById('studyHomeCourseEyebrow').textContent=c('course');document.getElementById('studyHomeCourseTitle').textContent=c('lesson');document.getElementById('studyHomeCover').textContent=c('book');document.getElementById('studyHomeStudy').textContent=c('study');document.getElementById('studyHomeSkills').textContent=c('choose');document.getElementById('studyHomeUnits').textContent=c('browse');var hb=document.getElementById('studyHomeBook'),hu=document.getElementById('studyHomeUnit');if(hb&&!hb.textContent)hb.textContent=c('loading');if(hu&&!hu.textContent)hu.textContent=c('finding');updateStartNote();}
function syncCourse(){var b=document.getElementById('bookTitle'),u=document.getElementById('unitTitle'),hb=document.getElementById('studyHomeBook'),hu=document.getElementById('studyHomeUnit');if(hb&&b&&b.textContent)hb.textContent=b.textContent;if(hu&&u&&u.textContent)hu.textContent=u.textContent;}
function showCourse(selector){document.body.classList.add('study-course-open');setTimeout(function(){var target=selector?document.querySelector(selector):document.querySelector('.book-hero');if(target)target.scrollIntoView({behavior:'smooth',block:'start'});},40);}
function showHome(){document.body.classList.remove('study-course-open');var home=document.getElementById('studentStudyHome');if(home)home.scrollIntoView({behavior:'smooth',block:'start'});}
function weakestAvailable(){var rows=progressData&&Array.isArray(progressData.skill_summary)?progressData.skill_summary.slice():[];rows=rows.filter(function(r){return SKILLS[r.skill]&&Number.isFinite(Number(r.mastery_score));}).sort(function(a,b){return Number(a.mastery_score)-Number(b.mastery_score);});for(var i=0;i<rows.length;i++){var def=SKILLS[rows[i].skill],buttons=document.querySelectorAll('#skillGrid .skill-card');if(buttons[def.index]&&!buttons[def.index].disabled)return rows[i].skill;}return null;}
function openSkill(skill){var def=SKILLS[skill],buttons=document.querySelectorAll('#skillGrid .skill-card');if(def&&buttons[def.index]&&!buttons[def.index].disabled){showCourse();setTimeout(function(){buttons[def.index].click();},90);return true;}return false;}
function startRecommended(){var skill=weakestAvailable();if(skill&&openSkill(skill))return;showCourse('.section-block');}
function updateStartNote(){var note=document.getElementById('studyHomeStartNote');if(!note)return;var s=weakestAvailable();if(!s||!SKILLS[s]){note.textContent=c('startNote');return;}var name=lang==='ko'?SKILLS[s].ko:SKILLS[s].label.toLowerCase();note.textContent=lang==='ko'?name+c('starting'):c('starting')+' '+name+'.';}
function renderNeeds(data){var host=document.getElementById('studyHomeNeeds');if(!host)return;var rows=data&&Array.isArray(data.skill_summary)?data.skill_summary.slice():[];rows=rows.filter(function(r){return SKILLS[r.skill]&&Number.isFinite(Number(r.mastery_score))&&Number(r.mastery_score)<80;}).sort(function(a,b){return Number(a.mastery_score)-Number(b.mastery_score);}).slice(0,3);host.innerHTML='';if(!rows.length){host.appendChild(el('div','study-home-empty',data&&data.summary&&Number(data.summary.attempts)>0?c('clear'):c('empty')));updateStartNote();return;}rows.forEach(function(row){var def=SKILLS[row.skill],btn=el('button','study-home-need');btn.type='button';var label=lang==='ko'?def.ko:def.label;btn.innerHTML='<span class="study-home-need-icon">'+def.icon+'</span><span class="study-home-need-copy"><strong>'+label+'</strong><small>'+c('worth')+'</small></span><span class="study-home-need-score">'+pct(row.mastery_score)+'</span>';btn.addEventListener('click',function(){openSkill(row.skill);});host.appendChild(btn);});updateStartNote();}
async function loadProgress(){var host=document.getElementById('studyHomeNeeds');if(host)host.innerHTML='<div class="study-home-empty study-home-loading">'+c('checking')+'</div>';try{if(!global.WillenaStudyProgress)throw new Error('Progress unavailable');progressData=await global.WillenaStudyProgress.getProgress();renderNeeds(progressData);}catch(_){progressData=null;renderNeeds(null);}}
global.addEventListener('willena:study-recording',function(e){if(e&&e.detail&&e.detail.status==='recorded')setTimeout(loadProgress,180);});
global.addEventListener('auth:changed',function(){setTimeout(loadProgress,300);});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(window);
