(function(){
'use strict';
var CONTENT_URL='https://gxwfsqxyuufqtitspfqg.supabase.co';
var CONTENT_KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
var CONTENT_HEADERS={apikey:CONTENT_KEY,Authorization:'Bearer '+CONTENT_KEY};
var OP_URL='https://fiieuiktlsivwfgyivai.supabase.co';
var OP_KEY='sb_publishable_e-K50PquV9gHdfmefG6tmg_o-vVSl0e';
var AUTH_ENDPOINT='/.netlify/functions/supabase_auth';
var lang='ko',engine=null,activityIndex=0,activeMode='vocabulary',studyTab='overview';
var vocabActivities=[],spellingActivities=[],grammarActivities=[],sentenceActivities=[];
var vocab=[],patterns=[],sentences=[],units=[],assignment=null,currentUnit=null,student=null,classInfo=null;
var grid=document.getElementById('skillGrid'),panel=document.getElementById('practicePanel'),root=document.getElementById('activityRoot'),langBtn=document.getElementById('languageBtn'),skillLabel=document.getElementById('practiceSkill'),title=document.getElementById('practiceTitle');
var copy={
 ko:{continue:'단원 공부하기',practice:'연습하기',browse:'단원 보기',choose:'연습할 영역을 선택하세요',vocabulary:'어휘',spelling:'철자',grammar:'문법',sentence:'문장 만들기',sentences:'핵심 문장',conversation:'회화',next:'다음',back:'뒤로',meaning:'뜻 고르기',spell:'단어 만들기',grammarFill:'빈칸 채우기',sentenceBuild:'문장 만들기',chooseKo:'한국어 뜻을 고르세요.',spellEn:'글자를 눌러 영어 단어를 만드세요.',grammarHelp:'질문을 보고 알맞은 문법 표현을 완성하세요.',sentenceHelp:'단어를 올바른 순서로 배열하세요.',loading:'불러오는 중…',coming:'곧 연결 예정',words:'개 단어',items:'문항',whatLearn:'이번 단원에서 배울 내용',studyUnit:'단원 공부',studyIntro:'먼저 내용을 살펴보고 준비가 되면 연습해 보세요.',practiceThis:'이 내용 연습하기',showKorean:'한국어 보기',hideKorean:'한국어 숨기기',hear:'듣기',keySentences:'핵심 문장',conversationTitle:'회화 표현',grammarTitle:'문법 포인트',vocabTitle:'단어와 표현'},
 en:{continue:'Study this unit',practice:'Practice',browse:'Browse units',choose:'Choose a skill',vocabulary:'Vocabulary',spelling:'Spelling',grammar:'Grammar',sentence:'Sentence Building',sentences:'Key Sentences',conversation:'Conversation',next:'Next',back:'Back',meaning:'Choose the meaning',spell:'Build the word',grammarFill:'Fill the gap',sentenceBuild:'Build the sentence',chooseKo:'Choose the Korean meaning.',spellEn:'Tap the letters to build the English word.',grammarHelp:'Read the question and complete the grammar pattern.',sentenceHelp:'Put the words in the correct order.',loading:'Loading…',coming:'Coming next',words:'words',items:'items',whatLearn:'What you’ll learn',studyUnit:'Study Unit',studyIntro:'Look through the lesson first, then practice when you are ready.',practiceThis:'Practice this',showKorean:'Show Korean',hideKorean:'Hide Korean',hear:'Listen',keySentences:'Key sentences',conversationTitle:'Conversation',grammarTitle:'Grammar points',vocabTitle:'Words & expressions'}
};
function t(k){return copy[lang][k]||k;}
function esc(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function shuffle(items){return items.slice().sort(function(){return Math.random()-.5;});}
function unique(items){var out=[];items.forEach(function(x){if(x&&out.indexOf(x)<0)out.push(x);});return out;}
function signin(){location.replace('/students/signin.html?next='+encodeURIComponent('/students/study/'));}
function speak(text){if(!text||!window.speechSynthesis)return;window.speechSynthesis.cancel();var u=new SpeechSynthesisUtterance(text);u.lang='en-US';u.rate=.9;window.speechSynthesis.speak(u);}
async function authRequest(action,params){var query=new URLSearchParams(Object.assign({action:action,_:Date.now()},params||{}));var response=await WillenaAPI.fetch(AUTH_ENDPOINT+'?'+query.toString(),{credentials:'include',cache:'no-store'});var data=await response.json().catch(function(){return{}});return{response:response,data:data};}
async function refreshSession(){var result=await authRequest('refresh');if(!result.response.ok||!result.data.success)return null;if(result.data.access_token&&window.WillenaAPI&&WillenaAPI.setLocalTokens)WillenaAPI.setLocalTokens(result.data.access_token,result.data.refresh_token);return result.data.access_token||null;}
async function currentUser(){var result=await authRequest('whoami');if(result.response.ok&&result.data.success&&(result.data.user_id||result.data.id))return result.data;if(!await refreshSession())return null;result=await authRequest('whoami');return result.response.ok&&result.data.success&&(result.data.user_id||result.data.id)?result.data:null;}
async function accessToken(){var token=window.WillenaAPI&&WillenaAPI.getLocalAccessToken?WillenaAPI.getLocalAccessToken():null;if(token&&token.split('.').length===3)return token;return refreshSession();}
async function rpcStudyContext(token){return fetch(OP_URL+'/rest/v1/rpc/get_student_study_context',{method:'POST',headers:{apikey:OP_KEY,Authorization:'Bearer '+token,'Content-Type':'application/json'},body:'{}',cache:'no-store'});}
async function loadStudentAssignment(){var token=await accessToken();if(!token)throw new Error('Could not establish student session.');var response=await rpcStudyContext(token);if(response.status===401||response.status===403){token=await refreshSession();if(token)response=await rpcStudyContext(token);}var data=await response.json().catch(function(){return{}});if(response.status===401||response.status===403){signin();throw new Error('Sign in required');}if(!response.ok||!data.success)throw new Error(data.error||data.message||'Could not load your class book.');return data;}
async function contentGet(path){var response=await fetch(CONTENT_URL+'/rest/v1/'+path,{headers:CONTENT_HEADERS,cache:'no-store'});if(!response.ok)throw new Error('Content DB request failed ('+response.status+').');return response.json();}
function resolveUnit(rows,unitHint){if(!rows.length)return null;var hint=String(unitHint||'').trim().toLowerCase();if(hint){var number=(hint.match(/\d+/)||[])[0];var matched=rows.find(function(u){return String(u.unit_number)===number||String(u.title||'').trim().toLowerCase()===hint;});if(matched)return matched;}return rows[0];}
async function loadUnits(bookId){return contentGet('content_units?select=id,unit_number,title,source_key,status,metadata&book_id=eq.'+encodeURIComponent(bookId)+'&status=in.(review,published)&order=unit_number.asc');}
async function loadVocabulary(unitId){var occ=await contentGet('source_content_occurrences?select=id,lexical_entry_id,source_text,status&unit_id=eq.'+encodeURIComponent(unitId)+'&occurrence_type=eq.lexical_entry&status=in.(review,published)');var ids=unique(occ.map(function(o){return o.lexical_entry_id;}).filter(Boolean));if(!ids.length)return[];var rows=await contentGet('lexical_entries?select=id,canonical_text,translation_ko,emoji,status&id=in.'+encodeURIComponent('('+ids.join(',')+')')+'&status=in.(review,published)');var by={};rows.forEach(function(r){by[r.id]=r;});return occ.map(function(o){var e=by[o.lexical_entry_id];if(!e)return null;return{id:e.id,occurrenceId:o.id,word:String(e.canonical_text||o.source_text||'').trim(),ko:String(e.translation_ko||'').trim(),emoji:e.emoji||null};}).filter(function(x){return x&&x.word;});}
async function loadPatterns(unitId){var occ=await contentGet('source_content_occurrences?select=id,pattern_id,source_text&unit_id=eq.'+encodeURIComponent(unitId)+'&occurrence_type=eq.pattern&status=in.(review,published)');var ids=unique(occ.map(function(o){return o.pattern_id;}).filter(Boolean));if(!ids.length)return[];var rows=await contentGet('patterns?select=id,name,grammar_category,prompt_pattern,response_pattern,explanation_en,explanation_ko,status&id=in.'+encodeURIComponent('('+ids.join(',')+')')+'&status=in.(review,published)');var by={};rows.forEach(function(r){by[r.id]=r;});return occ.map(function(o){var p=by[o.pattern_id];return p?Object.assign({},p,{occurrenceId:o.id}):null;}).filter(Boolean);}
async function loadSentences(unitId){var occ=await contentGet('source_content_occurrences?select=id,sentence_id,source_text,skill,activity_label&unit_id=eq.'+encodeURIComponent(unitId)+'&occurrence_type=eq.sentence&status=in.(review,published)');var ids=unique(occ.map(function(o){return o.sentence_id;}).filter(Boolean));if(!ids.length)return[];var rows=await contentGet('sentences?select=id,text,translation_ko,status&id=in.'+encodeURIComponent('('+ids.join(',')+')')+'&status=in.(review,published)');var by={};rows.forEach(function(r){by[r.id]=r;});return occ.map(function(o){var s=by[o.sentence_id];if(!s)return null;return{id:s.id,occurrenceId:o.id,text:s.text||o.source_text||'',ko:s.translation_ko||'',skill:o.skill||'',label:o.activity_label||''};}).filter(function(s){return s.text;});}
function distractorsFor(item){return shuffle(unique(vocab.filter(function(v){return v.id!==item.id;}).map(function(v){return v.ko;}).filter(Boolean))).slice(0,3);}
function spellingTokens(word){return String(word||'').toLowerCase().replace(/[^a-z]/g,'').split('');}
function wordLengths(word){return String(word||'').trim().split(/\s+/).map(function(part){return part.replace(/[^a-z]/gi,'').length;}).filter(Boolean);}
function grammarGap(pattern){var r=String(pattern.response_pattern||'').trim(),cat=String(pattern.grammar_category||''),rules=[];if(/[\/]/.test(r))return null;if(cat==='comparatives')rules=[/\bfaster\b/i,/\bslower\b/i,/\bbigger\b/i,/\bsmaller\b/i];else if(cat==='superlatives')rules=[/\bthe fastest\b/i,/\bthe slowest\b/i,/\bthe biggest\b/i,/\bthe smallest\b/i];else if(cat==='simple_past')rules=[/\bswam\b/i,/\bhad\b/i,/\bwent\b/i,/\bdidn't\b/i,/\bdid\b/i];else if(cat==='verb_patterns')rules=[/\blikes to\b/i,/\blike to\b/i,/\bwant to be\b/i,/\bwant to\b/i];else if(cat==='be_going_to')rules=[/\bgoing to\b/i];else if(cat==='dates')rules=[/\bin\b/i,/\b1st\b/i];for(var i=0;i<rules.length;i++){var m=r.match(rules[i]);if(m)return{prompt:r.replace(rules[i],'____'),answer:m[0]};}return null;}
function sentenceTokens(text){return String(text||'').trim().replace(/[.!?]+$/,'').split(/\s+/).filter(Boolean);}
function isCleanBuilderSentence(text){var s=String(text||'').trim();if(/[\/]/.test(s))return false;var endings=(s.match(/[.!?](?=\s|$)/g)||[]).length;if(endings>1)return false;var tokens=sentenceTokens(s);return tokens.length>=3&&tokens.length<=12;}
function fallbackExplanation(pattern){var c=pattern.grammar_category;if(c==='comparatives')return lang==='ko'?'두 대상을 비교할 때 형용사에 -er를 붙입니다.':'Use adjective + -er to compare two things.';if(c==='superlatives')return lang==='ko'?'여럿 중 가장 높은 정도는 the + 형용사-est로 말합니다.':'Use the + adjective + -est for the highest degree.';if(c==='simple_past')return lang==='ko'?'끝난 과거의 일은 과거형으로 말합니다.':'Use the past tense for finished past actions.';if(c==='be_going_to')return lang==='ko'?'미래의 계획은 be going to + 동사원형으로 말합니다.':'Use be going to + base verb for future plans.';if(c==='verb_patterns')return lang==='ko'?'동사 뒤에 to + 동사원형이 오는 표현을 익혀 보세요.':'Notice the verb + to + base verb pattern.';if(c==='dates')return lang==='ko'?'월과 날짜를 말하는 표현을 익혀 보세요.':'Practice expressions for months and dates.';return'';}
function buildActivities(){vocabActivities=[];spellingActivities=[];grammarActivities=[];sentenceActivities=[];shuffle(vocab).forEach(function(item){var choices=shuffle(unique([item.ko].concat(distractorsFor(item)))).filter(Boolean).slice(0,4);if(choices.length>=2)vocabActivities.push({title:t('meaning'),activity:{id:'vocab-meaning-'+item.occurrenceId,sourceType:'lexical_entry',sourceId:item.id,skill:'vocabulary',usage:['practice'],stimulus:{type:'text',prompt:(item.emoji?item.emoji+'  ':'')+item.word,context:t('chooseKo')},response:{type:'multiple_choice',choices:choices},answer:item.ko,metadata:{unit_id:currentUnit.id,book_id:assignment.book_id,occurrence_id:item.occurrenceId}}});var tokens=spellingTokens(item.word);if(tokens.length&&item.ko)spellingActivities.push({title:t('spell'),activity:{id:'spell-'+item.occurrenceId,sourceType:'lexical_entry',sourceId:item.id,skill:'spelling',usage:['practice'],stimulus:{type:'text',prompt:(item.emoji?item.emoji+'  ':'')+item.ko,context:t('spellEn')},response:{type:'letter_order',tokens:tokens,wordLengths:wordLengths(item.word)},answer:item.word,metadata:{unit_id:currentUnit.id,book_id:assignment.book_id,occurrence_id:item.occurrenceId}}});});patterns.forEach(function(p){var gap=grammarGap(p);if(gap)grammarActivities.push({title:t('grammarFill'),activity:{id:'grammar-'+p.occurrenceId,sourceType:'pattern',sourceId:p.id,skill:'grammar',usage:['practice'],stimulus:{type:'text',prompt:gap.prompt,context:(p.prompt_pattern?p.prompt_pattern+'\n':'')+t('grammarHelp')},response:{type:'gap_fill_text'},answer:gap.answer,metadata:{unit_id:currentUnit.id,book_id:assignment.book_id,occurrence_id:p.occurrenceId,grammar_category:p.grammar_category}}});});sentences.forEach(function(s){if(!isCleanBuilderSentence(s.text))return;var tokens=sentenceTokens(s.text);sentenceActivities.push({title:t('sentenceBuild'),activity:{id:'sentence-'+s.occurrenceId,sourceType:'sentence',sourceId:s.id,skill:'sentence_building',usage:['practice'],stimulus:{type:'text',prompt:s.ko||t('sentenceHelp'),context:s.ko?t('sentenceHelp'):''},response:{type:'token_order',tokens:tokens},answer:s.text,metadata:{unit_id:currentUnit.id,book_id:assignment.book_id,occurrence_id:s.occurrenceId,source_skill:s.skill}}});});activityIndex=0;}
function lessonCounts(){return{vocab:vocab.length,grammar:patterns.length,sentences:sentences.filter(function(s){return s.skill==='grammar';}).length,conversation:sentences.filter(function(s){return s.skill==='speaking';}).length};}
function drawLearningMap(){var c=lessonCounts(),map=document.getElementById('learningMap');if(!map)return;var cards=[['vocabulary','Aa',t('vocabulary'),c.vocab,vocab.slice(0,3).map(function(v){return v.word;}).join(' · ')],['grammar','✓',t('grammar'),c.grammar,patterns.slice(0,2).map(function(p){return p.name;}).join(' · ')],['sentences','↔',t('sentences'),c.sentences,sentences.filter(function(s){return s.skill==='grammar';}).slice(0,2).map(function(s){return s.text;}).join(' · ')],['conversation','💬',t('conversation'),c.conversation,sentences.filter(function(s){return s.skill==='speaking';}).slice(0,2).map(function(s){return s.text;}).join(' · ')]];map.innerHTML=cards.map(function(x){return '<button class="learn-map-card" type="button" data-study-tab="'+x[0]+'"><span class="learn-map-icon">'+x[1]+'</span><span><strong>'+esc(x[2])+'</strong><b>'+x[3]+'</b><small>'+esc(x[4]||t('coming'))+'</small></span><i>→</i></button>';}).join('');map.querySelectorAll('[data-study-tab]').forEach(function(b){b.addEventListener('click',function(){openStudy(b.dataset.studyTab);});});}
function drawStudyTabs(){var tabs=document.getElementById('studyTabs');if(!tabs)return;var rows=[['overview',t('whatLearn')],['vocabulary',t('vocabulary')],['grammar',t('grammar')],['sentences',t('sentences')],['conversation',t('conversation')]];tabs.innerHTML=rows.map(function(r){return '<button type="button" class="study-tab '+(studyTab===r[0]?'is-active':'')+'" data-tab="'+r[0]+'">'+esc(r[1])+'</button>';}).join('');tabs.querySelectorAll('[data-tab]').forEach(function(b){b.addEventListener('click',function(){studyTab=b.dataset.tab;renderStudyTab();});});}
function wordCard(v){return '<article class="lesson-word"><button class="speak-mini" type="button" data-speak="'+esc(v.word)+'">🔊</button><div><strong>'+esc(v.word)+'</strong>'+(v.ko?'<span>'+esc(v.ko)+'</span>':'')+'</div></article>';}
function patternCard(p){var expl=lang==='ko'?(p.explanation_ko||fallbackExplanation(p)):(p.explanation_en||fallbackExplanation(p));return '<article class="grammar-lesson-card"><div class="lesson-badge">'+esc(p.name||t('grammar'))+'</div><div class="pattern-line"><span>Q</span><strong>'+esc(p.prompt_pattern||'')+'</strong><button class="speak-mini" type="button" data-speak="'+esc(p.prompt_pattern||'')+'">🔊</button></div><div class="pattern-line answer"><span>A</span><strong>'+esc(p.response_pattern||'')+'</strong><button class="speak-mini" type="button" data-speak="'+esc(String(p.response_pattern||'').split('/')[0].trim())+'">🔊</button></div>'+(expl?'<p class="lesson-explanation">'+esc(expl)+'</p>':'')+'</article>';}
function sentenceCard(s){return '<article class="sentence-study-card"><button class="speak-mini" type="button" data-speak="'+esc(s.text)+'">🔊</button><div><strong>'+esc(s.text)+'</strong>'+(s.ko?'<span class="ko-line">'+esc(s.ko)+'</span>':'')+'</div></article>';}
function bindSpeakers(host){host.querySelectorAll('[data-speak]').forEach(function(b){b.addEventListener('click',function(){speak(b.dataset.speak);});});}
function renderStudyTab(){drawStudyTabs();var host=document.getElementById('studyContent');if(!host)return;var html='';if(studyTab==='overview'){html='<div class="study-overview-copy"><span class="eyebrow">'+esc(t('studyUnit'))+'</span><h2>'+esc(currentUnit?'Unit '+currentUnit.unit_number+' · '+currentUnit.title:t('studyUnit'))+'</h2><p>'+esc(t('studyIntro'))+'</p></div><div class="study-summary-grid"><button type="button" data-jump="vocabulary"><b>'+vocab.length+'</b><span>'+esc(t('vocabulary'))+'</span></button><button type="button" data-jump="grammar"><b>'+patterns.length+'</b><span>'+esc(t('grammar'))+'</span></button><button type="button" data-jump="sentences"><b>'+sentences.filter(function(s){return s.skill==='grammar';}).length+'</b><span>'+esc(t('sentences'))+'</span></button><button type="button" data-jump="conversation"><b>'+sentences.filter(function(s){return s.skill==='speaking';}).length+'</b><span>'+esc(t('conversation'))+'</span></button></div>';}else if(studyTab==='vocabulary'){html='<div class="lesson-section-head"><div><span class="eyebrow">'+esc(t('vocabTitle'))+'</span><h2>'+esc(t('vocabulary'))+'</h2></div><button class="practice-this" type="button" data-practice="vocabulary">'+esc(t('practiceThis'))+'</button></div><div class="lesson-word-grid">'+vocab.map(wordCard).join('')+'</div>';}else if(studyTab==='grammar'){html='<div class="lesson-section-head"><div><span class="eyebrow">'+esc(t('grammarTitle'))+'</span><h2>'+esc(t('grammar'))+'</h2></div><button class="practice-this" type="button" data-practice="grammar">'+esc(t('practiceThis'))+'</button></div><div class="grammar-lesson-list">'+patterns.map(patternCard).join('')+'</div>';}else if(studyTab==='sentences'){var key=sentences.filter(function(s){return s.skill==='grammar';});html='<div class="lesson-section-head"><div><span class="eyebrow">'+esc(t('keySentences'))+'</span><h2>'+esc(t('sentences'))+'</h2></div><button class="practice-this" type="button" data-practice="sentence">'+esc(t('practiceThis'))+'</button></div><div class="sentence-study-list">'+key.map(sentenceCard).join('')+'</div>';}else{var conv=sentences.filter(function(s){return s.skill==='speaking';});html='<div class="lesson-section-head"><div><span class="eyebrow">'+esc(t('conversationTitle'))+'</span><h2>'+esc(t('conversation'))+'</h2></div><button class="practice-this" type="button" data-practice="sentence">'+esc(t('practiceThis'))+'</button></div><div class="conversation-study-list">'+conv.map(function(s,i){return '<article class="conversation-line"><span class="speaker-dot">'+(i%2?'B':'A')+'</span>'+sentenceCard(s)+'</article>';}).join('')+'</div>';}host.innerHTML=html;bindSpeakers(host);host.querySelectorAll('[data-jump]').forEach(function(b){b.addEventListener('click',function(){studyTab=b.dataset.jump;renderStudyTab();});});host.querySelectorAll('[data-practice]').forEach(function(b){b.addEventListener('click',function(){openPractice(b.dataset.practice,0);});});}
function openStudy(tab){studyTab=tab||'overview';var s=document.getElementById('studyPanel');s.hidden=false;renderStudyTab();s.scrollIntoView({behavior:'smooth',block:'start'});}
function drawSkills(){var rows=[{id:'vocabulary',icon:'Aa',label:t('vocabulary'),desc:vocab.length?vocab.length+' '+t('words'):t('loading'),enabled:vocabActivities.length>0},{id:'spelling',icon:'ABC',label:t('spelling'),desc:vocab.length?vocab.length+' '+t('words'):t('loading'),enabled:spellingActivities.length>0},{id:'grammar',icon:'✓',label:t('grammar'),desc:grammarActivities.length?grammarActivities.length+' '+t('items'):t('loading'),enabled:grammarActivities.length>0},{id:'sentence',icon:'↔',label:t('sentence'),desc:sentenceActivities.length?sentenceActivities.length+' '+t('items'):t('loading'),enabled:sentenceActivities.length>0},{id:'listening',icon:'♪',label:lang==='ko'?'듣기':'Listening',desc:t('coming')},{id:'reading',icon:'¶',label:lang==='ko'?'읽기':'Reading',desc:t('coming')}];grid.innerHTML='';rows.forEach(function(skill){var b=document.createElement('button');b.type='button';b.className='skill-card'+(skill.enabled?'':' is-disabled');b.disabled=!skill.enabled;b.innerHTML='<span class="skill-icon">'+skill.icon+'</span><span><strong>'+esc(skill.label)+'</strong><small>'+esc(skill.desc)+'</small></span>';if(skill.enabled)b.addEventListener('click',function(){openPractice(skill.id,0);});grid.appendChild(b);});}
function renderPreview(){var holder=document.getElementById('vocabPreview');if(!vocab.length){holder.innerHTML='<div class="study-loading">No vocabulary found for this unit.</div>';return;}holder.innerHTML=vocab.slice(0,8).map(function(v){return '<div class="review-row static"><span class="review-icon">'+esc(v.emoji||'Aa')+'</span><span><strong>'+esc(v.word)+'</strong><small>'+esc(v.ko||'')+'</small></span></div>';}).join('');}
function updateHero(){document.getElementById('studentGreeting').textContent=(student&&student.name?student.name+' · ':'')+(classInfo&&(classInfo.display_name||classInfo.name)||'Willena');document.getElementById('bookTitle').textContent=assignment&&assignment.book_title||'No book assigned';document.getElementById('unitTitle').textContent=currentUnit?'Unit '+currentUnit.unit_number+' · '+(currentUnit.title||''):'No unit available';document.getElementById('vocabCount').textContent=String(vocab.length);document.getElementById('progressTitle').textContent=lang==='ko'?'학습 내용 준비 완료':'Unit ready to study';document.getElementById('progressCopy').textContent=vocab.length+' '+t('words')+' · '+patterns.length+' '+t('grammar')+' · '+sentences.length+' '+t('sentences');document.getElementById('unitWordCount').textContent=String(vocab.length);document.getElementById('unitNumberStat').textContent=currentUnit?String(currentUnit.unit_number):'—';document.getElementById('classStat').textContent=classInfo?(classInfo.display_name||classInfo.name||'—').slice(0,8):'—';document.getElementById('connectionTitle').textContent=lang==='ko'?'교재 내용 연결됨':'Live curriculum connected';document.getElementById('contentStatus').textContent=(assignment.book_title||'')+' · Unit '+currentUnit.unit_number;document.getElementById('continueBtn').disabled=false;drawLearningMap();}
function rowsForMode(mode){if(mode==='spelling')return spellingActivities;if(mode==='grammar')return grammarActivities;if(mode==='sentence')return sentenceActivities;return vocabActivities;}
function openPractice(mode,index){activeMode=mode||'vocabulary';var rows=rowsForMode(activeMode);if(!rows.length)return;activityIndex=Number(index)||0;var row=rows[activityIndex%rows.length];skillLabel.textContent=t(activeMode).toUpperCase();title.textContent=row.title;panel.hidden=false;if(!window.WillenaActivityEngine){root.innerHTML='<p>Activity engine failed to load.</p>';return;}engine=new WillenaActivityEngine(root,{onAnswer:function(){}});engine.setActivity(row.activity);panel.scrollIntoView({behavior:'smooth',block:'start'});}
function next(){var rows=rowsForMode(activeMode);if(!rows.length)return;activityIndex=(activityIndex+1)%rows.length;openPractice(activeMode,activityIndex);}
async function loadUnitContent(unit){currentUnit=unit;panel.hidden=true;document.getElementById('contentStatus').textContent='Loading Unit '+unit.unit_number+'…';var all=await Promise.all([loadVocabulary(unit.id),loadPatterns(unit.id),loadSentences(unit.id)]);vocab=all[0];patterns=all[1];sentences=all[2];buildActivities();updateHero();drawSkills();renderPreview();document.getElementById('studyPanel').hidden=true;}
function browseUnits(){var holder=document.getElementById('vocabPreview');holder.innerHTML=units.map(function(u){return '<button class="unit-pick" type="button" data-unit-id="'+esc(u.id)+'"><strong>Unit '+esc(u.unit_number)+'</strong><span>'+esc(u.title||'')+'</span></button>';}).join('');holder.querySelectorAll('.unit-pick').forEach(function(b){b.addEventListener('click',function(){var unit=units.find(function(u){return u.id===b.dataset.unitId;});if(unit)loadUnitContent(unit).catch(showError);});});holder.scrollIntoView({behavior:'smooth',block:'center'});}
function showError(error){console.error('[WillenaStudy]',error);document.getElementById('bookTitle').textContent='Could not load study content';document.getElementById('unitTitle').textContent=error&&error.message||'Please try again.';document.getElementById('contentStatus').textContent='Connection failed';document.getElementById('connectionTitle').textContent='Connection error';document.getElementById('progressCopy').textContent=error&&error.message||'Study data could not be loaded.';}
async function init(){try{drawSkills();var who=await currentUser();if(!who){signin();return;}var data=await loadStudentAssignment();student=data.student;classInfo=data.class;assignment=data.assignment;if(!assignment||!assignment.book_id)throw new Error('No active book is assigned to this student.');units=await loadUnits(assignment.book_id);if(!units.length)throw new Error('No available units were found for '+assignment.book_title+'.');await loadUnitContent(resolveUnit(units,assignment.current_unit||assignment.starting_unit));}catch(error){showError(error);}}
document.getElementById('continueBtn').addEventListener('click',function(){openStudy('overview');});
document.getElementById('practiceHeroBtn').addEventListener('click',function(){document.querySelector('.section-block').scrollIntoView({behavior:'smooth'});});
document.getElementById('changeUnitBtn').addEventListener('click',browseUnits);
document.getElementById('closeStudy').addEventListener('click',function(){document.getElementById('studyPanel').hidden=true;document.querySelector('.learning-map-section').scrollIntoView({behavior:'smooth'});});
document.getElementById('closePractice').addEventListener('click',function(){panel.hidden=true;document.querySelector('.section-block').scrollIntoView({behavior:'smooth'});});
document.getElementById('nextActivity').addEventListener('click',next);
langBtn.addEventListener('click',function(){lang=lang==='ko'?'en':'ko';langBtn.textContent=lang==='ko'?'English':'한국어';document.getElementById('continueBtn').textContent=t('continue');document.getElementById('practiceHeroBtn').textContent=t('practice');document.getElementById('changeUnitBtn').textContent=t('browse');document.getElementById('learnMapHeading').textContent=t('whatLearn');document.querySelector('.section-heading h2').textContent=t('choose');document.getElementById('nextActivity').textContent=t('next');document.getElementById('closePractice').textContent='← '+t('back');document.getElementById('closeStudy').textContent='← '+t('back');buildActivities();updateHero();drawSkills();if(!document.getElementById('studyPanel').hidden)renderStudyTab();if(!panel.hidden)openPractice(activeMode,activityIndex);});
init();
})();