(function(global){
'use strict';
var URL='https://gxwfsqxyuufqtitspfqg.supabase.co';
var KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
var HEADERS={apikey:KEY,Authorization:'Bearer '+KEY};
var ctx=null,units=[],switching=false;
function text(v){return String(v==null?'':v).trim();}
function el(tag,cls,txt){var n=document.createElement(tag);if(cls)n.className=cls;if(txt!=null)n.textContent=txt;return n;}
function unitNumber(v){var m=text(v).match(/Unit\s*(\d+)/i);return m?Number(m[1]):null;}
async function get(path){var r=await fetch(URL+'/rest/v1/'+path,{headers:HEADERS,cache:'no-store'});if(!r.ok)throw new Error('Content DB '+r.status);return r.json();}
function runtimeContext(){var r=global.WillenaStudyRuntime&&global.WillenaStudyRuntime.getContext&&global.WillenaStudyRuntime.getContext();if(!r)return null;return{bookId:r.bookId,bookTitle:r.bookTitle,currentUnitId:r.unitId,currentUnitNumber:Number(r.unitNumber)};}
async function resolve(){var rt=runtimeContext();if(rt){ctx=rt;if(global.WillenaStudyRuntime&&global.WillenaStudyRuntime.getUnits)units=global.WillenaStudyRuntime.getUnits();return ctx;}var title=text(document.getElementById('bookTitle')&&document.getElementById('bookTitle').textContent),n=unitNumber(document.getElementById('unitTitle')&&document.getElementById('unitTitle').textContent);if(!title||!n||/^Loading/i.test(title))return null;var books=await get('content_books?select=id,title,internal_level_id&title=eq.'+encodeURIComponent(title)+'&status=in.(review,published)&limit=1');if(!books.length)return null;units=await get('content_units?select=id,unit_number,title&book_id=eq.'+encodeURIComponent(books[0].id)+'&status=in.(review,published)&order=unit_number.asc');var u=units.find(function(x){return Number(x.unit_number)===n;})||units[0];ctx={bookId:books[0].id,bookTitle:books[0].title,currentUnitId:u&&u.id,currentUnitNumber:n};return ctx;}
function ensureUnitControls(){var title=document.getElementById('unitTitle');if(!title||!ctx||!units.length)return null;var wrap=document.getElementById('studyHomeUnits');if(!wrap){wrap=el('div','study-home-units');wrap.id='studyHomeUnits';var lab=el('div','study-home-units-label');lab.appendChild(el('span','study-home-units-title','Choose a unit to study'));lab.appendChild(el('span','study-home-units-current',''));wrap.appendChild(lab);var strip=el('div','study-home-unit-strip');strip.id='studyHomeUnitStrip';units.forEach(function(u){var b=el('button','study-home-unit','Unit '+u.unit_number);b.type='button';b.dataset.unitId=u.id;b.dataset.unitNumber=String(u.unit_number);b.addEventListener('click',function(){chooseUnit(u.unit_number);});strip.appendChild(b);});wrap.appendChild(strip);title.insertAdjacentElement('afterend',wrap);}return wrap;}
function updateUnitControls(){var wrap=ensureUnitControls();if(!wrap||!ctx)return;var current=wrap.querySelector('.study-home-units-current');if(current)current.textContent='Current · Unit '+ctx.currentUnitNumber;wrap.querySelectorAll('.study-home-unit').forEach(function(b){var active=Number(b.dataset.unitNumber)===Number(ctx.currentUnitNumber);b.classList.toggle('is-current',active);b.setAttribute('aria-pressed',active?'true':'false');b.disabled=false;});}
function chooseUnit(number){if(switching||!ctx||!global.WillenaStudyRuntime||!global.WillenaStudyRuntime.selectUnit)return;var unit=units.find(function(u){return Number(u.unit_number)===Number(number);});if(!unit||Number(ctx.currentUnitNumber)===Number(number))return;switching=true;ctx.currentUnitNumber=Number(unit.unit_number);ctx.currentUnitId=unit.id;updateUnitControls();global.WillenaStudyRuntime.selectUnit(unit.id).catch(function(e){console.debug('[StudyCoach] unit switch',e);switching=false;var rt=runtimeContext();if(rt)ctx=rt;updateUnitControls();});}
function skillLabel(skill){return{vocabulary:'Vocabulary',spelling:'Spelling',grammar:'Grammar',sentence_building:'Sentence Builder',conversation:'Conversation',listening:'Listening'}[skill]||skill;}
function recoverableMistake(item){if(!item||Number(item.lapses||0)<=0||Number(item.mastery_score||0)>=80)return false;var type=String(item.content_type||''),skill=String(item.skill||'');if(type==='lexical_entry')return skill==='vocabulary'||skill==='spelling'||skill==='listening';if(type==='sentence')return skill==='sentence_building'||skill==='listening'||skill==='conversation';if(type==='pattern'&&skill==='grammar')return true;if(type==='assessment_item')return skill!=='grammar';return false;}
function mistakeGroups(adaptive){var groups={};(adaptive&&adaptive.items||[]).forEach(function(item){if(String(item.book_id)!==String(ctx.bookId)||String(item.unit_id)!==String(ctx.currentUnitId)||!recoverableMistake(item))return;(groups[item.skill]||(groups[item.skill]=[])).push(item);});return groups;}
function recommendCards(progress,adaptive){var out=[],groups=mistakeGroups(adaptive),skills=Object.keys(groups).sort(function(a,b){var aa=groups[a],bb=groups[b],al=aa.reduce(function(n,x){return n+Number(x.lapses||0);},0),bl=bb.reduce(function(n,x){return n+Number(x.lapses||0);},0);if(al!==bl)return bl-al;var am=aa.reduce(function(n,x){return n+Number(x.mastery_score||0);},0)/aa.length,bm=bb.reduce(function(n,x){return n+Number(x.mastery_score||0);},0)/bb.length;return am-bm;});skills.slice(0,2).forEach(function(skill){var items=groups[skill],lapses=items.reduce(function(n,x){return n+Number(x.lapses||0);},0);out.push({type:'mistakes',skill:skill,items:items,title:'Fix '+skillLabel(skill)+' mistakes',copy:items.length+' concept'+(items.length===1?'':'s')+' need more practice'+(lapses?' · '+lapses+' misses total':'')+'.',action:'Practise these mistakes →'});});var due=(adaptive&&adaptive.items||[]).filter(function(x){return String(x.book_id)===String(ctx.bookId)&&String(x.unit_id)===String(ctx.currentUnitId)&&x.due&&Number(x.lapses||0)===0;});if(due.length)out.push({type:'daily',title:'Review what is due',copy:due.length+' previously learned items are ready for spaced review.',action:'Start Daily Workout →'});var summarySkills=Array.isArray(progress&&progress.skill_summary)?progress.skill_summary:[],vocab=summarySkills.find(function(s){return s.skill==='vocabulary';}),next=units.find(function(u){return Number(u.unit_number)===Number(ctx.currentUnitNumber)+1;});if(out.length<3&&vocab&&Number(vocab.mastery_score||0)>=80&&next)out.push({type:'unit',unitNumber:next.unit_number,title:'Preview Unit '+next.unit_number+' words',copy:'This is new material, not a weak area. Your current vocabulary is strong enough to look ahead.',action:'Open Unit '+next.unit_number+' →'});return out.slice(0,3);}
function renderCoach(progress,adaptive){var hero=document.querySelector('.book-hero');if(!hero||!ctx)return;var old=document.getElementById('studyCoach');if(old)old.remove();var section=el('section','study-coach');section.id='studyCoach';var head=el('div','study-coach-head'),left=el('div');left.appendChild(el('span','eyebrow','RECOMMENDED PRACTICE'));left.appendChild(el('h2','','What should I study next?'));head.appendChild(left);head.appendChild(el('span','study-coach-note','Based on mistakes + spaced review'));section.appendChild(head);var grid=el('div','study-coach-grid'),cards=recommendCards(progress,adaptive);if(!cards.length)cards=[{type:'daily',title:'Keep your knowledge fresh',copy:'No unresolved mistakes are available right now. Do today’s adaptive review.',action:'Start Daily Workout →'}];cards.forEach(function(r){var b=el('button','study-coach-card');b.type='button';b.appendChild(el('span','coach-kicker',r.type==='mistakes'?'Your mistakes':r.type==='unit'?'New material':'Due review'));b.appendChild(el('strong','',r.title));b.appendChild(el('small','',r.copy));b.appendChild(el('span','coach-action',r.action));b.addEventListener('click',function(){if(r.type==='mistakes')global.dispatchEvent(new CustomEvent('willena:smart-study-focus',{detail:{bookId:ctx.bookId,unitId:ctx.currentUnitId,skill:r.skill,skillLabel:skillLabel(r.skill),mistakeItems:r.items.map(function(x){return{contentType:x.content_type,contentId:x.content_id,skill:x.skill};})}}));else if(r.type==='unit')chooseUnit(r.unitNumber);else{var card=document.querySelector('.unit-progress-card');if(card)card.click();}});grid.appendChild(b);});section.appendChild(grid);hero.insertAdjacentElement('afterend',section);}
async function hydrateCoach(progress){if(!ctx||!global.WillenaStudyProgress)return;try{if(progress){var adaptive=await global.WillenaStudyProgress.getAdaptiveState();renderCoach(progress,adaptive);return;}var both=await Promise.all([global.WillenaStudyProgress.getProgress(ctx.bookId,ctx.currentUnitId),global.WillenaStudyProgress.getAdaptiveState()]);renderCoach(both[0],both[1]);}catch(e){console.debug('[StudyCoach]',e);}}
async function mount(force){try{if(force)ctx=null;if(!ctx)ctx=await resolve();if(!ctx)return false;if(global.WillenaStudyRuntime&&global.WillenaStudyRuntime.getUnits)units=global.WillenaStudyRuntime.getUnits();updateUnitControls();hydrateCoach();return true;}catch(e){console.debug('[StudyCoach]',e);return false;}}
function wait(){var tries=0,t=setInterval(function(){tries++;mount(false).then(function(ok){if(ok||tries>40)clearInterval(t);});},250);}
global.addEventListener('willena:study-unit-changing',function(e){var d=e.detail||{};if(!d.unitId)return;ctx={bookId:d.bookId,bookTitle:d.bookTitle,currentUnitId:d.unitId,currentUnitNumber:Number(d.unitNumber)};if(global.WillenaStudyRuntime&&global.WillenaStudyRuntime.getUnits)units=global.WillenaStudyRuntime.getUnits();updateUnitControls();});
global.addEventListener('willena:study-unit-changed',function(){switching=false;var rt=runtimeContext();if(rt)ctx=rt;updateUnitControls();hydrateCoach();});
global.addEventListener('willena:study-progress-updated',function(e){if(e&&e.detail)setTimeout(function(){hydrateCoach(e.detail);},120);});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',wait,{once:true});else wait();
})(window);