(function(global){
'use strict';
var SKILLS={vocabulary:{label:'Vocabulary',ko:'어휘',icon:'Aa',index:0},spelling:{label:'Spelling',ko:'철자',icon:'ABC',index:1},grammar:{label:'Grammar',ko:'문법',icon:'✓',index:2},sentence_building:{label:'Sentence Builder',ko:'문장 만들기',icon:'↔',index:3},conversation:{label:'Conversation',ko:'회화',icon:'💬',index:4},listening:{label:'Listening',ko:'듣기',icon:'♪',index:5}};
var progressData=null;
function el(tag,cls,text){var n=document.createElement(tag);if(cls)n.className=cls;if(text!=null)n.textContent=text;return n;}
function pct(v){var n=Number(v);return Number.isFinite(n)?Math.round(n)+'%':'—';}
function mount(){
 var app=document.getElementById('app'),hero=document.querySelector('.book-hero');if(!app||!hero||document.getElementById('studentStudyHome'))return;
 document.body.classList.add('study-home-enhanced');
 var back=el('button','study-home-return','← Study home');back.type='button';back.id='studyHomeReturn';app.insertBefore(back,hero);
 var home=el('section','study-home');home.id='studentStudyHome';
 home.innerHTML='<article class="study-home-hero"><span class="eyebrow">TODAY\'S STUDY</span><h1>Ready to practice?</h1><p id="studyHomeIntro">Current lesson + things worth reviewing</p><button id="studyHomeStart" class="study-home-start" type="button"><span>Start Practice<small id="studyHomeStartNote">I’ll start with what needs attention.</small></span><b>→</b></button></article><div class="study-home-grid"><article class="study-home-card"><div class="study-home-card-head"><div><span class="eyebrow">NEEDS PRACTICE</span><h2>What to work on</h2></div><span class="study-home-note">From your saved progress</span></div><div id="studyHomeNeeds" class="study-home-needs"><div class="study-home-empty study-home-loading">Checking your progress…</div></div></article><article class="study-home-card study-course-card"><div class="study-home-card-head"><div><span class="eyebrow">MY COURSE</span><h2>Current lesson</h2></div></div><div class="study-course-book"><div class="study-course-cover">BOOK</div><div class="study-course-copy"><strong id="studyHomeBook">Loading…</strong><span id="studyHomeUnit">Finding your unit</span></div></div><div class="study-course-actions"><button id="studyHomeStudy" type="button">Study this unit</button><button id="studyHomeSkills" type="button">Choose practice</button><button id="studyHomeUnits" type="button">Browse units</button></div></article></div>';
 app.insertBefore(home,back);
 back.addEventListener('click',showHome);
 document.getElementById('studyHomeStart').addEventListener('click',startRecommended);
 document.getElementById('studyHomeStudy').addEventListener('click',function(){showCourse();var b=document.getElementById('continueBtn');if(b&&!b.disabled)b.click();});
 document.getElementById('studyHomeSkills').addEventListener('click',function(){showCourse('.section-block');});
 document.getElementById('studyHomeUnits').addEventListener('click',function(){showCourse();var b=document.getElementById('changeUnitBtn');if(b)b.click();});
 syncCourse();setTimeout(syncCourse,700);setTimeout(syncCourse,1600);loadProgress();
}
function syncCourse(){var b=document.getElementById('bookTitle'),u=document.getElementById('unitTitle'),hb=document.getElementById('studyHomeBook'),hu=document.getElementById('studyHomeUnit');if(hb&&b&&b.textContent)hb.textContent=b.textContent;if(hu&&u&&u.textContent)hu.textContent=u.textContent;}
function showCourse(selector){document.body.classList.add('study-course-open');setTimeout(function(){var target=selector?document.querySelector(selector):document.querySelector('.book-hero');if(target)target.scrollIntoView({behavior:'smooth',block:'start'});},40);}
function showHome(){document.body.classList.remove('study-course-open');var home=document.getElementById('studentStudyHome');if(home)home.scrollIntoView({behavior:'smooth',block:'start'});}
function weakestAvailable(){var rows=progressData&&Array.isArray(progressData.skill_summary)?progressData.skill_summary.slice():[];rows=rows.filter(function(r){return SKILLS[r.skill]&&Number.isFinite(Number(r.mastery_score));}).sort(function(a,b){return Number(a.mastery_score)-Number(b.mastery_score);});for(var i=0;i<rows.length;i++){var def=SKILLS[rows[i].skill],buttons=document.querySelectorAll('#skillGrid .skill-card');if(buttons[def.index]&&!buttons[def.index].disabled)return rows[i].skill;}return null;}
function openSkill(skill){var def=SKILLS[skill],buttons=document.querySelectorAll('#skillGrid .skill-card');if(def&&buttons[def.index]&&!buttons[def.index].disabled){showCourse();setTimeout(function(){buttons[def.index].click();},90);return true;}return false;}
function startRecommended(){var skill=weakestAvailable();if(skill&&openSkill(skill))return;showCourse('.section-block');}
function renderNeeds(data){var host=document.getElementById('studyHomeNeeds');if(!host)return;var rows=data&&Array.isArray(data.skill_summary)?data.skill_summary.slice():[];rows=rows.filter(function(r){return SKILLS[r.skill]&&Number.isFinite(Number(r.mastery_score))&&Number(r.mastery_score)<80;}).sort(function(a,b){return Number(a.mastery_score)-Number(b.mastery_score);}).slice(0,3);host.innerHTML='';if(!rows.length){host.appendChild(el('div','study-home-empty',data&&data.summary&&Number(data.summary.attempts)>0?'Nothing is standing out right now. Keep practising and I’ll keep checking.':'Do a few practice questions and your weak areas will start appearing here.'));return;}rows.forEach(function(row){var def=SKILLS[row.skill],btn=el('button','study-home-need');btn.type='button';btn.innerHTML='<span class="study-home-need-icon">'+def.icon+'</span><span class="study-home-need-copy"><strong>'+def.label+'</strong><small>Worth another practice round</small></span><span class="study-home-need-score">'+pct(row.mastery_score)+'</span>';btn.addEventListener('click',function(){openSkill(row.skill);});host.appendChild(btn);});}
async function loadProgress(){try{if(!global.WillenaStudyProgress)throw new Error('Progress unavailable');progressData=await global.WillenaStudyProgress.getProgress();renderNeeds(progressData);var s=weakestAvailable(),note=document.getElementById('studyHomeStartNote');if(note&&s&&SKILLS[s])note.textContent='Starting with '+SKILLS[s].label.toLowerCase()+'.';}catch(_){renderNeeds(null);}}
global.addEventListener('willena:study-recording',function(e){if(e&&e.detail&&e.detail.status==='recorded')setTimeout(loadProgress,180);});
global.addEventListener('auth:changed',function(){setTimeout(loadProgress,300);});
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',mount,{once:true});else mount();
})(window);
