(function(){
'use strict';
const API='https://fiieuiktlsivwfgyivai.supabase.co/functions/v1/test-prep-group-delete';
const KEY='sb_publishable_e-K50PquV9gHdfmefG6tmg_o-vVSl0e';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
function token(){return window.WillenaAPI?.getLocalAccessToken?.()||localStorage.getItem('sb_access_token')||''}
function styles(){if($('#naDeleteStyles'))return;const s=document.createElement('style');s.id='naDeleteStyles';s.textContent=`#view-naesin .na-btn.delete-test{border-color:#efb2c7!important;color:#ad4c70!important;background:#fff7fa!important}#view-naesin .na-btn.delete-test:hover{background:#fff0f5!important}`;document.head.appendChild(s)}
async function removeGroup(id,btn){const t=token();if(!t)throw new Error('로그인이 필요합니다.');btn.disabled=true;const r=await fetch(API,{method:'POST',headers:{Authorization:`Bearer ${t}`,apikey:KEY,'Content-Type':'application/json'},credentials:'omit',cache:'no-store',body:JSON.stringify({group_id:id})});const j=await r.json().catch(()=>({}));if(!r.ok||j.success===false)throw new Error(j.error||`Request failed (${r.status})`)}
function enhance(){styles();$$('#view-naesin .na-exam').forEach(card=>{if(card.querySelector('.delete-test'))return;const actions=card.querySelector('.na-actions');if(!actions)return;const id=card.dataset.group;if(!id)return;const b=document.createElement('button');b.className='na-btn delete-test';b.textContent='시험 삭제';b.onclick=async e=>{e.stopPropagation();const title=card.querySelector('.na-exam-title')?.textContent?.trim()||'이 시험';if(!confirm(`${title}을(를) 삭제할까요?\n\n학생들의 기존 학습 기록은 보존되고, 이 시험과 연결된 활성 계획/과제만 종료됩니다.`))return;const old=b.textContent;b.textContent='삭제 중…';try{await removeGroup(id,b);card.remove();const box=$('#naFreshGroups');if(box&&!box.querySelector('.na-exam'))box.innerHTML='<div class="na-empty"><h3 style="margin-top:0;color:var(--ink)">아직 시험 대비가 없습니다.</h3><p>첫 시험을 만들고 학생과 범위를 연결하세요.</p></div>';}catch(err){alert(err.message||err);b.disabled=false;b.textContent=old}};actions.appendChild(b)})}
function boot(){enhance();new MutationObserver(enhance).observe(document.body,{childList:true,subtree:true})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();