(()=>{'use strict';
const U='https://gxwfsqxyuufqtitspfqg.supabase.co';
const K=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const H={apikey:K,Authorization:`Bearer ${K}`};
const $=id=>document.getElementById(id);
const filters={grade:$('grade'),book:$('book'),unit:$('unit'),section:$('section'),pattern:$('pattern'),from:$('from'),to:$('to'),source:$('sourceMode'),usable:$('usable')};
let books=[],units=[],active={};
function apiBase(){const h=location.hostname;if(h==='staging.willenaenglish.com'||h==='cf.willenaenglish.com'||h==='teachers.willenaenglish.com'||h.endsWith('.pages.dev'))return'https://api.willenaenglish.com';if(h==='students.willenaenglish.com'||h==='willenaenglish.netlify.app'||h==='localhost'||h==='127.0.0.1')return'';return'https://students.willenaenglish.com'}
async function auth(){const base=apiBase();try{const r=await fetch(`${base}/.netlify/functions/supabase_auth?action=whoami&_=${Date.now()}`,{credentials:'include',cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||!d.user_id)throw Error('AUTH');const rr=await fetch(`${base}/.netlify/functions/supabase_auth?action=get_role&user_id=${encodeURIComponent(d.user_id)}&_=${Date.now()}`,{credentials:'include',cache:'no-store'}),rd=await rr.json().catch(()=>({}));const role=String(rd.role||'').toLowerCase();if(!rr.ok||!['teacher','admin','owner','director','manager','instructor'].includes(role))throw Error('ROLE');$('who').textContent=`${d.email||'Teacher'} · ${rd.role||'teacher'}`;$('gate').hidden=true;$('qcApp').hidden=false;return true}catch(e){if(e.message==='AUTH'){location.replace('/Teachers/signin.html?redirect='+encodeURIComponent('/qc/test-prep/'));return false}$('gateText').textContent='이 페이지는 교사 역할 계정만 사용할 수 있습니다.';$('spinner').hidden=true;return false}}
async function get(table,select,extra=''){const r=await fetch(`${U}/rest/v1/${table}?select=${encodeURIComponent(select)}${extra}`,{headers:H,cache:'no-store'});if(!r.ok)throw Error(await r.text());return r.json()}
function opt(sel,v,t){const o=document.createElement('option');o.value=v;o.textContent=t;sel.appendChild(o)}
function grade(b){const m=String(b.title||'').match(/중\s*([123])/);return m?`중${m[1]}`:''}
function fillBooks(){const g=filters.grade.value,old=filters.book.value;filters.book.innerHTML='<option value="">전체 교재</option>';books.filter(b=>!g||grade(b)===g).forEach(b=>opt(filters.book,b.id,b.title));if([...filters.book.options].some(o=>o.value===old))filters.book.value=old;fillUnits()}
function fillUnits(){const b=filters.book.value,old=filters.unit.value;filters.unit.innerHTML='<option value="">전체 Lesson</option>';units.filter(u=>!b||u.book_id===b).sort((a,b)=>(a.unit_number||0)-(b.unit_number||0)).forEach(u=>opt(filters.unit,u.id,`L${u.unit_number||'?'} · ${u.title||''}`));if([...filters.unit.options].some(o=>o.value===old))filters.unit.value=old}
async function initFilters(){[books,units]=await Promise.all([get('content_books','id,title,created_at,status','&order=title.asc'),get('content_units','id,book_id,unit_number,title','&order=unit_number.asc')]);[...new Set(books.map(grade).filter(Boolean))].sort().forEach(g=>opt(filters.grade,g,g));fillBooks();const types=await get('test_prep_questions','question_type','&question_type=not.is.null&limit=5000');[...new Set(types.map(x=>x.question_type).filter(Boolean))].sort().forEach(x=>opt(filters.pattern,x,x))}
function shuffle(a){return[...a].sort(()=>Math.random()-.5)}
function isW(q){return q.content_status==='willena_published'||/^Willena/i.test(q.student_source_label||'')}
function rotate(rows){const r=shuffle(rows.filter(q=>!isW(q))),w=shuffle(rows.filter(isW)),out=[];let i=0,j=0,t=0;while((i<r.length||j<w.length)&&out.length<20){if((t%2===0&&i<r.length)||j>=w.length)out.push(r[i++]);else out.push(w[j++]);t++}return out}
window.WillenaAssignedTestPrep={get selection(){return{plan:{id:'qc'},lesson:'QC',reviewMode:false}},questionQuery(){let q='';if(active.book)q+=`&book_id=eq.${encodeURIComponent(active.book)}`;if(active.unit)q+=`&unit_id=eq.${encodeURIComponent(active.unit)}`;return q}};
window.WillenaTestPrepSession={async smartSelect(bank){let rows=[...bank];if(active.pattern)rows=rows.filter(q=>q.question_type===active.pattern);if(active.from)rows=rows.filter(q=>new Date(q.created_at)>=new Date(active.from+'T00:00:00'));if(active.to)rows=rows.filter(q=>new Date(q.created_at)<=new Date(active.to+'T23:59:59'));if(active.usable==='true')rows=rows.filter(q=>q.student_usable!==false);if(active.usable==='false')rows=rows.filter(q=>q.student_usable===false);if(active.source==='reference')rows=rows.filter(q=>!isW(q));if(active.source==='willena')rows=rows.filter(isW);if(active.source==='rotate')return rotate(rows);return shuffle(rows).slice(0,20)}};
window.WillenaTestPrepAuth={recordAttempt(){},completeSession(){},beginStudyActivity(){},state:{plans:[]}};
const nativeFetch=window.fetch.bind(window);
window.fetch=async function(input,init){let url=typeof input==='string'?input:input?.url||'';if(url.includes('/rest/v1/test_prep_questions?')){const u=new URL(url,location.href);u.searchParams.delete('student_usable');const select=u.searchParams.get('select')||'';if(!select.includes('created_at'))u.searchParams.set('select',select+',created_at,student_usable');const res=await nativeFetch(u.toString(),init);if(!res.ok)return res;let rows=await res.json();if(active.pattern)rows=rows.filter(q=>q.question_type===active.pattern);if(active.from)rows=rows.filter(q=>new Date(q.created_at)>=new Date(active.from+'T00:00:00'));if(active.to)rows=rows.filter(q=>new Date(q.created_at)<=new Date(active.to+'T23:59:59'));if(active.usable==='true')rows=rows.filter(q=>q.student_usable!==false);if(active.usable==='false')rows=rows.filter(q=>q.student_usable===false);if(active.source==='reference')rows=rows.filter(q=>!isW(q));if(active.source==='willena')rows=rows.filter(isW);return new Response(JSON.stringify(rows),{status:200,headers:{'Content-Type':'application/json'}})}return nativeFetch(input,init)};
function script(src){return new Promise((resolve,reject)=>{const s=document.createElement('script');s.src=src;s.onload=resolve;s.onerror=reject;document.body.appendChild(s)})}
async function loadEngine(){if(window.WillenaTestPrepQuestionEngine)return;await script('/students/test-prep-app/question-engine.js?v=20260829-width1');await script('/students/test-prep-app/question-render-fixes.js?v=20260829-width1').catch(()=>{});await script('/students/test-prep-app/student-display-polish.js?v=20260829-width1').catch(()=>{})}
async function start(){active={book:filters.book.value,unit:filters.unit.value,section:filters.section.value||'communication',pattern:filters.pattern.value,from:filters.from.value,to:filters.to.value,source:filters.source.value,usable:filters.usable.value};$('summary').textContent=`${filters.book.options[filters.book.selectedIndex]?.text||'전체 교재'} · ${filters.unit.options[filters.unit.selectedIndex]?.text||'전체 Lesson'} · ${active.section} · ${filters.source.options[filters.source.selectedIndex]?.text||''}`;$('playPane').hidden=false;$('filtersPane').classList.add('compact');await loadEngine();await window.WillenaTestPrepQuestionEngine.loadSection(active.section);document.getElementById('playPane').scrollIntoView({behavior:'smooth',block:'start'})}
$('start').addEventListener('click',start);$('reset').addEventListener('click',()=>{Object.values(filters).forEach(x=>{if(x.tagName==='SELECT')x.selectedIndex=0;else x.value=''});filters.source.value='rotate';filters.usable.value='all';fillBooks();$('playPane').hidden=true;$('filtersPane').classList.remove('compact')});filters.grade.addEventListener('change',fillBooks);filters.book.addEventListener('change',fillUnits);
(async()=>{if(!await auth())return;await initFilters()})().catch(e=>{$('gateText').textContent='QC를 불러오지 못했습니다: '+e.message;$('spinner').hidden=true});
})();