(()=>{'use strict';
const U='https://gxwfsqxyuufqtitspfqg.supabase.co',K=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join(''),H={apikey:K,Authorization:`Bearer ${K}`};
const $=id=>document.getElementById(id),gate=$('gate'),app=$('app'),qel=$('question'),meta=$('meta'),crumb=$('crumb'),pos=$('position'),count=$('count');
const F=['grade','book','unit','section','pattern','from','to','sourceMode','usable','search'].reduce((o,k)=>(o[k]=$(k),o),{});
let books=[],units=[],all=[],view=[],index=0,passages=new Map();
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function norm(v){let s=String(v??'').replace(/\r\n?/g,'\n');for(let i=0;i<4;i++)s=s.replace(/\\+n/g,'\n');return s}
function markedLine(v,spans=[]){const src=String(v??'');if(!Array.isArray(spans))spans=[spans];const ss=[...new Set(spans.map(String).filter(Boolean))];if(!src||!ss.length)return esc(src);const hits=[];for(const x of ss){let from=0;while(from<src.length){const p=src.indexOf(x,from);if(p<0)break;hits.push([p,p+x.length]);from=p+x.length}}if(!hits.length)return esc(src);hits.sort((a,b)=>a[0]-b[0]||b[1]-a[1]);const merged=[];for(const h of hits){const last=merged[merged.length-1];if(!last||h[0]>=last[1])merged.push([...h]);else last[1]=Math.max(last[1],h[1])}let out='',p=0;for(const [a,b] of merged){out+=esc(src.slice(p,a))+`<span class="u">${esc(src.slice(a,b))}</span>`;p=b}return out+esc(src.slice(p))}
function text(v,spans=[]){return norm(v).split('\n').map(x=>`<span class="line">${markedLine(x,spans)}</span>`).join('')}
function spans(c){const a=[];if(c?.underlined)a.push(c.underlined);if(Array.isArray(c?.underlined_spans))a.push(...c.underlined_spans);return [...new Set(a.map(String).filter(Boolean))]}
function block(title,v,u=[]){if(v==null||v==='')return'';return `<div class="context">${title?`<div class="context-title">${esc(title)}</div>`:''}${text(v,u)}</div>`}
function arr(title,a,u=[]){if(!Array.isArray(a)||!a.length)return'';return `<div class="context">${title?`<div class="context-title">${esc(title)}</div>`:''}<div class="items">${a.map(x=>`<div class="item">${Array.isArray(x)?x.map(y=>text(y,u)).join('<hr>'):text(x,u)}</div>`).join('')}</div></div>`}
function obj(title,o,cls='segment',u=[]){if(!o||typeof o!=='object'||Array.isArray(o))return'';return `<div class="context"><div class="context-title">${esc(title)}</div><div class="${cls==='claim'?'claims':'segments'}">${Object.entries(o).map(([k,v])=>`<div class="${cls}"><b>${esc(k)}</b> ${text(v,u)}</div>`).join('')}</div></div>`}
function contextHtml(q){const c=q.context||{},u=spans(c);let o='';
 if(c.passage_id&&passages.has(c.passage_id))o+=block(passages.get(c.passage_id).title||'본문',passages.get(c.passage_id).body,u);
 if(c.sentence)o+=block('',c.sentence,u);if(c.passage)o+=block('',c.passage,u);if(c.passage_start)o+=block('',c.passage_start,u)+obj('A–D',c.segments,'segment',u)+block('',c.passage_end,u);if(c.source_passage)o+=block('원문',c.source_passage,u);if(c.rewritten)o+=block('바꿔 쓴 글',c.rewritten,u);if(c.dialogue)o+=block('대화',c.dialogue,u);if(c.dialogue_start)o+=block('',c.dialogue_start,u)+obj('A–D',c.segments,'segment',u)+block('',c.dialogue_end,u);if(c.dialogue_a)o+=block('대화 A',c.dialogue_a,u);if(c.dialogue_b)o+=block('대화 B',c.dialogue_b,u);if(c.dialogue1)o+=block('대화 1',c.dialogue1,u);if(c.dialogue2)o+=block('대화 2',c.dialogue2,u);if(c.given_sentence)o+=block('<보기>',c.given_sentence,u);if(c.bank)o+=Array.isArray(c.bank)?arr('<보기>',c.bank,u):typeof c.bank==='object'?obj('<보기>',c.bank,'segment',u):block('<보기>',c.bank,u);o+=arr('',c.items,u);o+=arr('',c.pairs,u);o+=arr('문제 단서',c.clues,u);o+=arr('',c.statements,u);o+=obj('설명',c.claims,'claim',u);if(c.table)o+=obj('표',c.table,'segment',u);if(c.definition)o+=block('정의',c.definition,u);if(c.korean)o+=block('우리말',c.korean,u);if(c.pattern)o+=block('형식',c.pattern,u);if(c.target)o+=block('대상',c.target,u);if(c.source)o+=block('',c.source,u);if(c.source_sentence)o+=block('',c.source_sentence,u);if(c.source_phrase)o+=block('',c.source_phrase,u);if(c.phrase)o+=block('',c.phrase,u);if(c.example)o+=block('',c.example,u);if(c.incorrect)o+=block('',c.incorrect,u);if(c.original)o+=block('원문',c.original,u);if(c.comparison)o+=block('비교',c.comparison,u);if(c.word)o+=block('',c.word,u);if(c.A)o+=block('(A)',c.A,u);if(c.B)o+=block('(B)',c.B,u);if(c.a)o+=block('(A)',c.a,u);if(c.b)o+=block('(B)',c.b,u);if(c.proposed_pairs)o+=arr('',c.proposed_pairs,u);return o}
function gradeOf(b){const m=String(b?.title||'').match(/중\s*([123])/);return m?`중${m[1]}`:(b?.metadata?.grade||'')}
function isWillena(q){return q.content_status==='willena_published'||/^Willena/i.test(q.student_source_label||'')}
function sourceClass(q){if(isWillena(q))return'w';if(/^Z/i.test(q.student_source_label||''))return'z';if(/^B/i.test(q.student_source_label||''))return'b';return''}
function option(sel,val,label){const x=document.createElement('option');x.value=val;x.textContent=label;sel.appendChild(x)}
async function auth(){try{const r=await fetch('/.netlify/functions/supabase_auth?action=whoami&_='+Date.now(),{credentials:'include',cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||!d.user_id)throw Error('AUTH');const rr=await fetch('/.netlify/functions/supabase_auth?action=get_role&user_id='+encodeURIComponent(d.user_id)+'&_='+Date.now(),{credentials:'include',cache:'no-store'});const rd=await rr.json().catch(()=>({}));const role=String(rd.role||'').toLowerCase();const allowed=['teacher','admin','owner','director','manager','instructor'];if(!rr.ok||!allowed.includes(role))throw Error('ROLE');$('teacherBadge').textContent=`${d.email||'Teacher'} · ${rd.role||'teacher'}`;gate.classList.add('hidden');app.classList.remove('hidden');return true}catch(e){$('spinner').classList.add('hidden');$('gateText').innerHTML=e.message==='ROLE'?'이 페이지는 교사 역할 계정만 사용할 수 있습니다.':'먼저 Willena 교사 계정으로 로그인해 주세요.<br><small>로그인 후 이 페이지를 다시 열면 됩니다.</small>';return false}}
async function fetchAll(table,select,extra=''){let out=[],from=0;while(true){const r=await fetch(`${U}/rest/v1/${table}?select=${encodeURIComponent(select)}${extra}`,{headers:{...H,Range:`${from}-${from+999}`},cache:'no-store'});if(!r.ok)throw Error(await r.text());const a=await r.json();out.push(...a);if(a.length<1000)break;from+=1000}return out}
async function load(){qel.innerHTML='<div class="empty">전체 문제 DB를 불러오는 중…</div>';[books,units,all]=await Promise.all([
 fetchAll('content_books','id,title,book_number,public_level,metadata,created_at,status','&order=title.asc'),
 fetchAll('content_units','id,book_id,unit_number,title,public_level,created_at,status','&order=unit_number.asc'),
 fetchAll('test_prep_questions','id,book_id,unit_id,source_id,source_question_number,source_page,section,content_status,student_usable,replacement_needed,transcription_status,question_type,prompt_text,context,choices,correct_answer,targets,answer_mode,context_type,difficulty,qa_status,student_source_label,metadata,created_at,updated_at','&order=created_at.desc')]);
 const pids=[...new Set(all.map(q=>q.context?.passage_id).filter(Boolean))];if(pids.length){for(let i=0;i<pids.length;i+=100){const chunk=pids.slice(i,i+100).join(',');const ps=await fetchAll('passages','id,title,body,translation_ko,status',`&id=in.(${chunk})`);ps.forEach(p=>passages.set(p.id,p))}}
 hydrate();apply()}
function hydrate(){const grades=[...new Set(books.map(gradeOf).filter(Boolean))].sort();grades.forEach(g=>option(F.grade,g,g));books.forEach(b=>option(F.book,b.id,b.title));refreshUnits();const pats=[...new Set(all.map(q=>q.question_type).filter(Boolean))].sort();pats.forEach(p=>option(F.pattern,p,p))}
function refreshUnits(){const keep=F.unit.value;F.unit.innerHTML='<option value="">전체 Lesson</option>';units.filter(u=>!F.book.value||u.book_id===F.book.value).sort((a,b)=>(a.unit_number||0)-(b.unit_number||0)).forEach(u=>option(F.unit,u.id,`L${u.unit_number||'?'} · ${u.title||''}`));if([...F.unit.options].some(o=>o.value===keep))F.unit.value=keep}
function rotateRows(rows){const r=rows.filter(q=>!isWillena(q)),w=rows.filter(isWillena),out=[];let i=0,j=0,t=0;while(i<r.length||j<w.length){if((t%2===0&&i<r.length)||j>=w.length)out.push(r[i++]);else out.push(w[j++]);t++}return out}
function apply(){const bmap=new Map(books.map(b=>[b.id,b])),needle=F.search.value.trim().toLowerCase();let a=all.filter(q=>{
 const b=bmap.get(q.book_id);if(F.grade.value&&gradeOf(b)!==F.grade.value)return false;if(F.book.value&&q.book_id!==F.book.value)return false;if(F.unit.value&&q.unit_id!==F.unit.value)return false;if(F.section.value&&q.section!==F.section.value)return false;if(F.pattern.value&&q.question_type!==F.pattern.value)return false;if(F.from.value&&new Date(q.created_at)<new Date(F.from.value+'T00:00:00'))return false;if(F.to.value&&new Date(q.created_at)>new Date(F.to.value+'T23:59:59'))return false;if(F.usable.value!=='all'&&String(!!q.student_usable)!==F.usable.value)return false;if(F.sourceMode.value==='reference'&&isWillena(q))return false;if(F.sourceMode.value==='willena'&&!isWillena(q))return false;if(needle){const hay=[q.prompt_text,q.question_type,q.student_source_label,JSON.stringify(q.context),JSON.stringify(q.choices),...(q.targets||[])].join(' ').toLowerCase();if(!hay.includes(needle))return false}return true});
 a.sort((x,y)=>new Date(x.created_at)-new Date(y.created_at)||String(x.id).localeCompare(String(y.id)));if(F.sourceMode.value==='rotate')a=rotateRows(a);view=a;index=0;count.textContent=`${view.length.toLocaleString()} questions · 전체 DB ${all.length.toLocaleString()}`;render()}
function render(){if(!view.length){qel.innerHTML='<div class="empty">조건에 맞는 문제가 없습니다.</div>';crumb.textContent='No results';pos.textContent='0 / 0';meta.innerHTML='';return}index=Math.max(0,Math.min(index,view.length-1));const q=view[index],b=books.find(x=>x.id===q.book_id),u=units.find(x=>x.id===q.unit_id),us=spans(q.context||{}),ans=(q.correct_answer||[]).map(String);crumb.textContent=`${b?.title||'Unknown book'} · L${u?.unit_number||'?'} · ${q.section||'-'} · ${q.question_type||'-'}`;pos.textContent=`${index+1} / ${view.length}`;
 const choices=Array.isArray(q.choices)?q.choices:[];qel.innerHTML=`<div class="qhead"><span class="source ${sourceClass(q)}">${esc(q.student_source_label||q.content_status||'Unknown source')}</span><span class="source usable ${q.student_usable?'':'no'}">${q.student_usable?'student usable':'NOT usable'}</span></div><div class="prompt">${esc(q.prompt_text||'')}</div>${contextHtml(q)}<div class="choices">${choices.map((x,i)=>`<div class="choice ${ans.includes(String(i+1))?'answer':''}"><span class="n">${['①','②','③','④','⑤','⑥','⑦'][i]||i+1}</span><span>${text(typeof x==='string'?x:(x?.text??JSON.stringify(x)),us)}</span></div>`).join('')}</div><div class="answerbox"><b>정답</b> ${ans.length?ans.join(', ')+'번':'—'}${q.metadata?.source_explanation_ko?`<br><b>해설</b> ${text(q.metadata.source_explanation_ko)}`:q.metadata?.explanation_ko?`<br><b>해설</b> ${text(q.metadata.explanation_ko)}`:''}</div>`;
 const rows=[['Book',b?.title],['Grade',gradeOf(b)],['Lesson',u?`L${u.unit_number} ${u.title||''}`:'—'],['Skill',q.section],['Pattern',q.question_type],['Source',q.student_source_label],['Created',fmt(q.created_at)],['Updated',fmt(q.updated_at)],['QA',q.qa_status],['Status',q.content_status],['Usable',String(q.student_usable)],['Difficulty',q.difficulty],['Source page',q.source_page],['Source Q',q.source_question_number],['Targets',(q.targets||[]).join(', ')],['Question ID',q.id]];meta.innerHTML=rows.map(([k,v])=>`<div class="metarow"><div class="k">${esc(k)}</div><div class="v ${k==='Question ID'?'qid':''}">${esc(v??'—')}</div></div>`).join('')}
function fmt(v){if(!v)return'—';try{return new Intl.DateTimeFormat('ko-KR',{dateStyle:'medium',timeStyle:'short'}).format(new Date(v))}catch{return v}}
$('prev').onclick=()=>{if(view.length){index=(index-1+view.length)%view.length;render()}};$('next').onclick=()=>{if(view.length){index=(index+1)%view.length;render()}};$('apply').onclick=apply;$('reset').onclick=()=>{Object.values(F).forEach(x=>{if(x.tagName==='SELECT')x.selectedIndex=0;else x.value=''});F.sourceMode.value='rotate';F.usable.value='all';refreshUnits();apply()};$('random').onclick=()=>{if(view.length){index=Math.floor(Math.random()*view.length);render()}};F.book.onchange=refreshUnits;F.grade.onchange=()=>{const g=F.grade.value,old=F.book.value;F.book.innerHTML='<option value="">전체 교재</option>';books.filter(b=>!g||gradeOf(b)===g).forEach(b=>option(F.book,b.id,b.title));if([...F.book.options].some(o=>o.value===old))F.book.value=old;refreshUnits()};document.addEventListener('keydown',e=>{if(['INPUT','SELECT','TEXTAREA'].includes(document.activeElement?.tagName))return;if(e.key==='ArrowRight')$('next').click();if(e.key==='ArrowLeft')$('prev').click()});
(async()=>{if(await auth())try{await load()}catch(e){console.error(e);qel.innerHTML=`<div class="empty">DB를 불러오지 못했습니다.<br><small>${esc(e.message)}</small></div>`}})();
})();