(function(){
'use strict';
const DB='https://gxwfsqxyuufqtitspfqg.supabase.co';
const KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const HEADERS={apikey:KEY,Authorization:'Bearer '+KEY};
const ADMIN=DB+'/functions/v1/curriculum_admin';
const $=s=>document.querySelector(s);
let uid='',books=[],units=[],activities=[],rawById={},index=0,currentBook=null;
const reviewedKey='willena-content-review:v1';
let reviewed=new Set(JSON.parse(localStorage.getItem(reviewedKey)||'[]'));
function text(v){return String(v==null?'':v).trim()}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg,bad){const t=$('#toast');t.textContent=msg;t.style.background=bad?'#912018':'#101828';t.style.display='block';clearTimeout(t._x);t._x=setTimeout(()=>t.style.display='none',2600)}
function seriesName(title){title=text(title);if(/^English Bus Starter/i.test(title))return'English Bus Starter';if(/^English Bus/i.test(title))return'English Bus';if(/^Let[’']?s Begin/i.test(title))return"Let's Begin";if(/^Let[’']?s Go/i.test(title))return"Let's Go";if(/^Come On Everyone/i.test(title))return'Come On Everyone';return title.replace(/\s+\d+$/,'')||'Other'}
async function rest(path){const r=await fetch(DB+'/rest/v1/'+path,{headers:HEADERS,cache:'no-store'});if(!r.ok)throw Error('Database '+r.status);return r.json()}
async function admin(body){const r=await fetch(ADMIN,{method:'POST',headers:{'Content-Type':'application/json','x-user-id':uid},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw Error(j.error||'Update failed');return j}
async function verify(){uid=localStorage.getItem('userId')||'';if(!uid){location.href='/Teachers/login.html?redirect='+encodeURIComponent(location.pathname);return}try{const r=await WillenaAPI.fetch('/.netlify/functions/supabase_auth?action=get_profile&user_id='+encodeURIComponent(uid));const j=await r.json();if(!j.success||j.approved!==true){location.href='/Teachers/components/access-denied.html';return}$('#auth').style.display='none';await loadBooks()}catch(e){$('#authMsg').textContent='Could not verify this account.'}}
async function loadBooks(){books=await rest('content_books?select=id,title,public_level,internal_level_id,status&status=in.(published,review)&order=title.asc');const series=[...new Set(books.map(b=>seriesName(b.title)))].sort();$('#series').innerHTML='<option value="">All series</option>'+series.map(s=>`<option>${esc(s)}</option>`).join('');renderBookOptions()}
function renderBookOptions(){const s=$('#series').value;const list=books.filter(b=>!s||seriesName(b.title)===s);$('#book').innerHTML='<option value="">Choose book</option>'+list.map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join('');$('#unit').innerHTML='<option value="">All units</option>';activities=[];rawById={};index=0;window._reviewFiltered=[];render()}
async function chooseBook(){const id=$('#book').value;if(!id){activities=[];window._reviewFiltered=[];render();return}currentBook=books.find(b=>b.id===id)||null;units=await rest('content_units?select=id,book_id,unit_number,title,status&book_id=eq.'+encodeURIComponent(id)+'&status=in.(published,review)&order=unit_number.asc');$('#unit').innerHTML='<option value="">All units</option>'+units.map(u=>`<option value="${u.id}">Unit ${u.unit_number}${u.title?' · '+esc(u.title):''}</option>`).join('');await loadActivities()}
async function loadActivities(){if(!currentBook)return;$('#app').classList.add('loading');try{const chosen=$('#unit').value;const targets=chosen?units.filter(u=>u.id===chosen):units;const chunks=[];for(const u of targets){const ctx={bookId:currentBook.id,bookTitle:currentBook.title,unitId:u.id,unitNumber:u.unit_number};const rows=await window.WillenaStudyQuestionBank.loadUnit(Number(currentBook.public_level)||1,ctx);rows.forEach(a=>{a.__unit=u;chunks.push(a)})}activities=chunks;const ids=activities.filter(a=>a.sourceType==='assessment_item').map(a=>a.sourceId);rawById={};for(let p=0;p<ids.length;p+=150){const set=ids.slice(p,p+150);if(!set.length)continue;const path='assessment_items?select=id,prompt_text,context_text,correct_answer,choices,status,item_type,metadata,is_flagged&id=in.'+encodeURIComponent('('+set.join(',')+')');const rows=await rest(path);rows.forEach(r=>rawById[r.id]=r)}applyType();index=0;render()}catch(e){toast(e.message,true);activities=[];window._reviewFiltered=[];render()}finally{$('#app').classList.remove('loading')}}
function applyType(){const t=$('#type').value;window._reviewFiltered=t?activities.filter(a=>a.skill===t):activities.slice()}
function list(){return window._reviewFiltered||[]}
function current(){return list()[index]||null}
function render(){const arr=list();$('#count').textContent=arr.length+' questions';$('#reviewed').textContent=arr.filter(a=>reviewed.has(a.sourceId||a.id)).length+' reviewed';if(!arr.length){$('#position').textContent='—';$('#card').innerHTML='<div class="empty">'+($('#book').value?'No matching questions.':'Choose a book to begin.')+'</div>';return}index=Math.max(0,Math.min(index,arr.length-1));const a=arr[index],u=a.__unit||{};$('#position').textContent=(index+1)+' / '+arr.length;const done=reviewed.has(a.sourceId||a.id);$('#card').innerHTML=`<div class="review-head"><div><h2>${esc(currentBook&&currentBook.title||'Book')} · Unit ${esc(u.unit_number||'—')}</h2><div class="meta">${esc(a.skill)} · ${esc(a.metadata&&a.metadata.question_form||'')} · ${esc(a.sourceId||a.id)}</div></div><span class="pill ${done?'good':''}">${done?'Reviewed':'Unreviewed'}</span></div><div class="engine-wrap" id="activityRoot"></div><div class="review-actions"><button class="btn good" data-action="good">✓ Good</button><button class="btn primary" data-action="edit">✎ Edit</button><button class="btn flag" data-action="flag">⚑ Flag</button><button class="btn archive" data-action="archive">Archive</button></div>`;const engine=new window.WillenaActivityEngine($('#activityRoot'),{onAnswer:function(){}});engine.setActivity(a);$('#card').querySelector('[data-action="good"]').onclick=markGood;$('#card').querySelector('[data-action="edit"]').onclick=openEdit;$('#card').querySelector('[data-action="flag"]').onclick=flagCurrent;$('#card').querySelector('[data-action="archive"]').onclick=archiveCurrent}
function next(){if(index<list().length-1)index++;render()}
function prev(){if(index>0)index--;render()}
function markGood(){const a=current();if(!a)return;reviewed.add(a.sourceId||a.id);localStorage.setItem(reviewedKey,JSON.stringify([...reviewed]));next();toast('Marked reviewed')}
async function flagCurrent(){const a=current();if(!a||a.sourceType!=='assessment_item')return toast('Generated fallback item — no DB row to flag',true);const msg=prompt('Flag note','Needs manual review');if(msg===null)return;try{await admin({action:'update',table:'assessment_items',id:a.sourceId,data:{is_flagged:true,flag_message:msg}});toast('Flagged');await loadActivities()}catch(e){toast('Flag update failed — use Curriculum Editor',true)}}
async function archiveCurrent(){const a=current();if(!a||a.sourceType!=='assessment_item')return toast('Generated fallback item — no DB row to archive',true);if(!confirm('Archive this question?'))return;try{await admin({action:'update',table:'assessment_items',id:a.sourceId,data:{status:'archived'}});toast('Archived');await loadActivities()}catch(e){toast('Archive failed — use Curriculum Editor',true)}}
function openEdit(){const a=current();if(!a||a.sourceType!=='assessment_item')return toast('Generated fallback items are read-only here',true);const r=rawById[a.sourceId];if(!r)return toast('Could not load raw item',true);$('#editPrompt').value=r.prompt_text||'';$('#editContext').value=r.context_text||'';$('#editAnswer').value=typeof r.correct_answer==='string'?r.correct_answer:JSON.stringify(r.correct_answer||'');$('#editChoices').value=(Array.isArray(r.choices)?r.choices:[]).map(x=>typeof x==='string'?x:(x&&x.text)||'').join('\n');$('#editStatus').value=r.status||'published';$('#rawMeta').textContent=JSON.stringify(r.metadata||{},null,2);$('#drawerBack').classList.add('open')}
async function saveEdit(){const a=current();if(!a)return;const choices=$('#editChoices').value.split(/\n+/).map(text).filter(Boolean);const data={prompt_text:$('#editPrompt').value,context_text:$('#editContext').value||null,correct_answer:$('#editAnswer').value,choices,status:$('#editStatus').value};try{await admin({action:'update',table:'assessment_items',id:a.sourceId,data});$('#drawerBack').classList.remove('open');toast('Saved');await loadActivities()}catch(e){toast('Save failed: '+e.message,true)}}
$('#series').addEventListener('change',renderBookOptions);$('#book').addEventListener('change',chooseBook);$('#unit').addEventListener('change',loadActivities);$('#type').addEventListener('change',()=>{applyType();index=0;render()});$('#refresh').onclick=loadActivities;$('#next').onclick=next;$('#prev').onclick=prev;$('#good').onclick=markGood;$('#openEditor').onclick=()=>location.href='/Teachers/tools/curriculum-editor/';$('#closeDrawer').onclick=$('#cancelEdit').onclick=()=>$('#drawerBack').classList.remove('open');$('#drawerBack').addEventListener('click',e=>{if(e.target===$('#drawerBack'))$('#drawerBack').classList.remove('open')});$('#saveEdit').onclick=saveEdit;
verify();
})();