(function(){
'use strict';
const DB='https://gxwfsqxyuufqtitspfqg.supabase.co';
const KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const HEADERS={apikey:KEY,Authorization:'Bearer '+KEY};
const ADMIN=DB+'/functions/v1/curriculum_admin';
const $=s=>document.querySelector(s);
let uid='',books=[],units=[],activities=[],rawById={},index=0,currentBook=null;
const reviewedKey='willena-content-review:v1';
let reviewed=new Set(JSON.parse(localStorage.getItem(reviewedKey)||'[]'));
function text(v){return String(v==null?'':v).trim()}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(msg,bad){const t=$('#toast');t.textContent=msg;t.style.background=bad?'#912018':'#101828';t.style.display='block';clearTimeout(t._x);t._x=setTimeout(()=>t.style.display='none',2600)}
function seriesName(title){title=text(title);if(/^English Bus Starter/i.test(title))return'English Bus Starter';if(/^English Bus/i.test(title))return'English Bus';if(/^Let[’']?s Begin/i.test(title))return"Let's Begin";if(/^Let[’']?s Go/i.test(title))return"Let's Go";if(/^Come On Everyone/i.test(title))return'Come On Everyone';return title.replace(/\s+\d+$/,'')||'Other'}
async function rest(path){const r=await fetch(DB+'/rest/v1/'+path,{headers:HEADERS,cache:'no-store'});if(!r.ok)throw Error('Database '+r.status);return r.json()}
async function admin(body){const r=await fetch(ADMIN,{method:'POST',headers:{'Content-Type':'application/json','x-user-id':uid},body:JSON.stringify(body)});const j=await r.json().catch(()=>({error:'Invalid response'}));if(!r.ok)throw Error(j.error||'Update failed');return j}
async function verify(){uid=localStorage.getItem('userId')||'';if(!uid){location.href='/Teachers/login.html?redirect='+encodeURIComponent(location.pathname);return}try{const r=await WillenaAPI.fetch('/.netlify/functions/supabase_auth?action=get_profile&user_id='+encodeURIComponent(uid));const j=await r.json();if(!j.success||j.approved!==true){location.href='/Teachers/components/access-denied.html';return}$('#auth').style.display='none';await loadBooks()}catch(e){$('#authMsg').textContent='Could not verify this account.'}}
async function loadBooks(){books=await rest('content_books?select=id,title,public_level,internal_level_id,status&status=in.(published,review)&order=title.asc');const series=[...new Set(books.map(b=>seriesName(b.title)))].sort();$('#series').innerHTML='<option value="">All series</option>'+series.map(s=>`<option>${esc(s)}</option>`).join('');renderBookOptions()}
function renderBookOptions(){const s=$('#series').value;const list=books.filter(b=>!s||seriesName(b.title)===s);$('#book').innerHTML='<option value="">Choose book</option>'+list.map(b=>`<option value="${b.id}">${esc(b.title)}</option>`).join('');$('#unit').innerHTML='<option value="">All units</option>';activities=[];rawById={};index=0;window._reviewFiltered=[];render()}
async function chooseBook(){const id=$('#book').value;if(!id){activities=[];window._reviewFiltered=[];render();return}currentBook=books.find(b=>b.id===id)||null;units=await rest('content_units?select=id,book_id,unit_number,title,status&book_id=eq.'+encodeURIComponent(id)+'&status=in.(published,review)&order=unit_number.asc');$('#unit').innerHTML='<option value="">All units</option>'+units.map(u=>`<option value="${u.id}">Unit ${u.unit_number}${u.title?' · '+esc(u.title):''}</option>`).join('');await loadActivities()}
async function loadActivities(){if(!currentBook)return;$('#app').classList.add('loading');try{const chosen=$('#unit').value;const targets=chosen?units.filter(u=>u.id===chosen):units;const chunks=[];for(const u of targets){const ctx={bookId:currentBook.id,bookTitle:currentBook.title,unitId:u.id,unitNumber:u.unit_number};const rows=await window.WillenaStudyQuestionBank.loadUnit(Number(currentBook.public_level)||1,ctx);rows.forEach(a=>{a.__unit=u;chunks.push(a)})}activities=chunks;const ids=activities.filter(a=>a.sourceType==='assessment_item').map(a=>a.sourceId);rawById={};for(let p=0;p<ids.length;p+=150){const set=ids.slice(p,p+150);if(!set.length)continue;const path='assessment_items?select=id,prompt_text,context_text,correct_answer,choices,status,item_type,metadata,is_flagged,flag_message&id=in.'+encodeURIComponent('('+set.join(',')+')');const rows=await rest(path);rows.forEach(r=>rawById[r.id]=r)}applyType();index=0;render()}catch(e){toast(e.message,true);activities=[];window._reviewFiltered=[];render()}finally{$('#app').classList.remove('loading')}}
function applyType(){const t=$('#type').value;window._reviewFiltered=t?activities.filter(a=>a.skill===t):activities.slice()}
function list(){return window._reviewFiltered||[]}
function current(){return list()[index]||null}
function render(){const arr=list();$('#count').textContent=arr.length+' questions';$('#reviewed').textContent=arr.filter(a=>reviewed.has(a.sourceId||a.id)).length+' reviewed';if(!arr.length){$('#position').textContent='—';$('#card').innerHTML='<div class="empty">'+($('#book').value?'No matching questions.':'Choose a book to begin.')+'</div>';return}index=Math.max(0,Math.min(index,arr.length-1));const a=arr[index],u=a.__unit||{},raw=rawById[a.sourceId]||{};$('#position').textContent=(index+1)+' / '+arr.length;const done=reviewed.has(a.sourceId||a.id);$('#card').innerHTML=`<div class="review-head"><div><h2>${esc(currentBook&&currentBook.title||'Book')} · Unit ${esc(u.unit_number||'—')}</h2><div class="meta">${esc(a.skill)} · ${esc(a.metadata&&a.metadata.question_form||'')} · ${esc(a.sourceId||a.id)}</div></div><span class="pill ${done?'good':''}">${done?'Reviewed':'Unreviewed'}</span></div><div class="engine-wrap" id="activityRoot"></div><div class="review-actions"><button class="btn good" data-action="good">✓ Good</button><button class="btn primary" data-action="edit">✎ Edit</button><button class="btn flag" data-action="flag">${raw.is_flagged?'⚑ Flagged':'⚑ Flag'}</button><button class="btn archive" data-action="archive">Archive</button></div>`;const engine=new window.WillenaActivityEngine($('#activityRoot'),{onAnswer:function(){}});engine.setActivity(a);$('#card').querySelector('[data-action="good"]').onclick=markGood;$('#card').querySelector('[data-action="edit"]').onclick=openEdit;$('#card').querySelector('[data-action="flag"]').onclick=flagCurrent;$('#card').querySelector('[data-action="archive"]').onclick=archiveCurrent}
function next(){if(index<list().length-1)index++;render()}
function prev(){if(index>0)index--;render()}
function markGood(){const a=current();if(!a)return;reviewed.add(a.sourceId||a.id);localStorage.setItem(reviewedKey,JSON.stringify([...reviewed]));next();toast('Marked reviewed')}
function ensureFlagSheet(){if($('#reviewFlagSheet'))return $('#reviewFlagSheet');const style=document.createElement('style');style.id='reviewFlagStyles';style.textContent='.review-flag-shade{position:fixed;inset:0;z-index:120;background:#10182866;display:grid;place-items:end center;padding:12px}.review-flag-sheet{width:min(520px,100%);background:#fff;border-radius:20px;padding:15px;box-shadow:0 20px 60px #0003}.review-flag-sheet h3{margin:0 0 4px;font-size:17px}.review-flag-sheet p{margin:0 0 12px;color:#667085;font-size:12px}.review-flag-quick{display:grid;grid-template-columns:1fr 1fr;gap:7px}.review-flag-quick button{border:1px solid #fedf89;background:#fff8eb;color:#934b00;border-radius:11px;padding:11px 8px;font-weight:800}.review-flag-sheet textarea{width:100%;min-height:70px;margin-top:9px;border:1px solid #d8e0ec;border-radius:11px;padding:10px;resize:none}.review-flag-foot{display:flex;gap:7px;margin-top:9px}.review-flag-foot button{flex:1;border:0;border-radius:11px;padding:11px;font-weight:800}.review-flag-cancel{background:#e9eef6;color:#172033}.review-flag-save{background:#b54708;color:#fff}@media(max-width:520px){.review-flag-shade{padding:7px}.review-flag-sheet{border-radius:17px;padding:12px}.review-flag-quick button{padding:10px 5px;font-size:12px}}';document.head.appendChild(style);const shade=document.createElement('div');shade.id='reviewFlagSheet';shade.className='review-flag-shade';shade.hidden=true;shade.innerHTML='<section class="review-flag-sheet"><h3>What is wrong?</h3><p>Tap a quick reason or write your own note.</p><div class="review-flag-quick"><button data-flag-reason="Bad cue / setup">Bad cue / setup</button><button data-flag-reason="Ambiguous answer">Ambiguous answer</button><button data-flag-reason="Wrong answer">Wrong answer</button><button data-flag-reason="Awkward / useless question">Awkward / useless</button></div><textarea id="reviewFlagNote" placeholder="Optional note…"></textarea><div class="review-flag-foot"><button class="review-flag-cancel" type="button">Cancel</button><button class="review-flag-save" type="button">Flag question</button></div></section>';document.body.appendChild(shade);return shade}
async function submitFlag(message){const a=current();if(!a||a.sourceType!=='assessment_item')return toast('Generated fallback item — no DB row to flag',true);message=text(message)||'Needs manual review';try{await admin({action:'bulk_flag',table:'assessment_items',ids:[a.sourceId],message});if(rawById[a.sourceId]){rawById[a.sourceId].is_flagged=true;rawById[a.sourceId].flag_message=message}const oldId=a.sourceId;activities=activities.filter(x=>x.sourceId!==oldId);applyType();if(index>=list().length)index=Math.max(0,list().length-1);render();toast('Flagged · '+message)}catch(e){toast('Flag failed: '+e.message,true)}}
function flagCurrent(){const a=current();if(!a||a.sourceType!=='assessment_item')return toast('Generated fallback item — no DB row to flag',true);const sheet=ensureFlagSheet(),note=sheet.querySelector('#reviewFlagNote');note.value='';sheet.hidden=false;sheet.querySelectorAll('[data-flag-reason]').forEach(b=>b.onclick=()=>{note.value=b.dataset.flagReason;sheet.querySelectorAll('[data-flag-reason]').forEach(x=>x.style.outline='');b.style.outline='2px solid #b54708'});sheet.querySelector('.review-flag-cancel').onclick=()=>{sheet.hidden=true};sheet.onclick=e=>{if(e.target===sheet)sheet.hidden=true};sheet.querySelector('.review-flag-save').onclick=async()=>{const msg=note.value;sheet.hidden=true;await submitFlag(msg)}}
async function archiveCurrent(){const a=current();if(!a||a.sourceType!=='assessment_item')return toast('Generated fallback item — no DB row to archive',true);if(!confirm('Archive this question?'))return;try{await admin({action:'bulk_update',table:'assessment_items',ids:[a.sourceId],payload:{status:'archived'}});activities=activities.filter(x=>x.sourceId!==a.sourceId);applyType();if(index>=list().length)index=Math.max(0,list().length-1);render();toast('Archived')}catch(e){toast('Archive failed: '+e.message,true)}}
function openEdit(){const a=current();if(!a||a.sourceType!=='assessment_item')return toast('Generated fallback items are read-only here',true);const r=rawById[a.sourceId];if(!r)return toast('Could not load raw item',true);$('#editPrompt').value=r.prompt_text||'';$('#editContext').value=r.context_text||'';$('#editAnswer').value=typeof r.correct_answer==='string'?r.correct_answer:JSON.stringify(r.correct_answer||'');$('#editChoices').value=(Array.isArray(r.choices)?r.choices:[]).map(x=>typeof x==='string'?x:(x&&x.text)||'').join('\n');$('#editStatus').value=r.status||'published';$('#rawMeta').textContent=JSON.stringify(r.metadata||{},null,2);$('#drawerBack').classList.add('open')}
async function saveEdit(){const a=current();if(!a)return;const r=rawById[a.sourceId]||{},choices=$('#editChoices').value.split(/\n+/).map(text).filter(Boolean),answer=$('#editAnswer').value.trim();if(!choices.length||!answer)return toast('Answer and choices are required',true);const options=choices.map((option_text,i)=>({option_text,is_correct:option_text===answer,distractor_type:option_text===answer?null:'contextually_incorrect'}));if(!options.some(x=>x.is_correct))options[0].is_correct=true;const payload={prompt_text:$('#editPrompt').value.trim(),context_text:$('#editContext').value.trim()||null,correct_answer:answer,choices,status:$('#editStatus').value,metadata:r.metadata||{},item_type:r.item_type,is_flagged:!!r.is_flagged,flag_message:r.flag_message||null};try{await admin({action:'save_assessment',table:'assessment_items',id:a.sourceId,payload,options,patternId:a.metadata&&a.metadata.pattern_id||null});$('#drawerBack').classList.remove('open');toast('Saved');await loadActivities()}catch(e){toast('Save failed: '+e.message,true)}}
$('#series').addEventListener('change',renderBookOptions);$('#book').addEventListener('change',chooseBook);$('#unit').addEventListener('change',loadActivities);$('#type').addEventListener('change',()=>{applyType();index=0;render()});$('#refresh').onclick=loadActivities;$('#next').onclick=next;$('#prev').onclick=prev;$('#good').onclick=markGood;$('#openEditor').onclick=()=>location.href='/Teachers/tools/curriculum-editor/';$('#closeDrawer').onclick=$('#cancelEdit').onclick=()=>$('#drawerBack').classList.remove('open');$('#drawerBack').addEventListener('click',e=>{if(e.target===$('#drawerBack'))$('#drawerBack').classList.remove('open')});$('#saveEdit').onclick=saveEdit;
verify();
})();