(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const AUTH='/.netlify/functions/supabase_auth';
const SKILL_ORDER=['phonics','vocabulary','grammar','listening','reading','sentence_building','writing','speaking'];
let bank=[],filtered=[],currentId='',showAnswer=false;
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function text(v){return String(v??'').trim()}
function label(v){return text(v).replace(/[_-]+/g,' ').replace(/\b\w/g,c=>c.toUpperCase())}
function sourceKey(q){return text(q?.metadata?.source_key||q?.id)}
function typeName(q){return text(q?.type||q?.metadata?.database_item_type||q?.renderKind||'question')}
function skillRank(v){const i=SKILL_ORDER.indexOf(text(v));return i<0?99:i}
function isVisual(q){return !!window.WillenaAssessmentRendererContract?.hasVisualChoices?.(window.WillenaAssessmentRendererContract.questionView(q))}
function qSearch(q){return[sourceKey(q),q?.prompt,q?.q,q?.context,q?.meaning,q?.answerValue,q?.a,q?.stimulus?.text,q?.metadata?.transcript,q?.skill,typeName(q)].map(text).join(' ').toLowerCase()}
async function api(url){const resolved=window.WillenaAPI?.getApiUrl?window.WillenaAPI.getApiUrl(url):url;const r=await fetch(resolved,{credentials:'include',cache:'no-store'});let j={};try{j=await r.json()}catch{}if(!r.ok)throw Error(j.error||`Request failed (${r.status})`);return j}
async function requireTeacher(){try{const who=await api(AUTH+'?action=whoami');if(!who.user_id)throw Error();const role=await api(AUTH+'?action=get_role&user_id='+encodeURIComponent(who.user_id));if(!['teacher','admin'].includes(text(role.role).toLowerCase()))throw Error();return true}catch{location.href='/Teachers/login.html?redirect='+encodeURIComponent(location.pathname+location.search);return false}}
function fillSelect(el,values,all){el.innerHTML='<option value="all">'+esc(all)+'</option>'+values.map(v=>'<option value="'+esc(v)+'">'+esc(label(v))+'</option>').join('')}
function setupFilters(){const levels=[...new Set(bank.map(q=>Number(q.level)).filter(Number.isFinite))].sort((a,b)=>a-b);$('#levelFilter').innerHTML='<option value="all">All levels</option>'+levels.map(n=>`<option value="${n}">Internal ${n}</option>`).join('');fillSelect($('#skillFilter'),[...new Set(bank.map(q=>text(q.skill)).filter(Boolean))].sort((a,b)=>skillRank(a)-skillRank(b)||a.localeCompare(b)),'All skills');fillSelect($('#typeFilter'),[...new Set(bank.map(typeName).filter(Boolean))].sort(),'All types')}
function sortBank(items){return items.slice().sort((a,b)=>Number(a.level)-Number(b.level)||skillRank(a.skill)-skillRank(b.skill)||Number(a.difficulty||0)-Number(b.difficulty||0)||sourceKey(a).localeCompare(sourceKey(b),undefined,{numeric:true}))}
function resolveImage(option){return option?.src||window.WillenaAssessmentAssets?.resolve?.(option?.assetKey)||''}
function optionHtml(option){const src=resolveImage(option);return `<div class="answer-choice">${src?`<img src="${esc(src)}" alt="${esc(option.alt||option.label||option.value)}">`:''}<span>${esc(option.label||option.value)}</span></div>`}
function speak(q){const t=text(q?.stimulus?.text||q?.metadata?.transcript);if(!t||!window.speechSynthesis)return;window.speechSynthesis.cancel();const u=new SpeechSynthesisUtterance(t);u.lang='en-US';u.rate=Number(q?.metadata?.rate)||0.9;window.speechSynthesis.speak(u)}
function renderQuestion(q){const host=$('#questionPreview');if(!q){host.innerHTML='<div class="empty">No question selected.</div>';return}const view=window.WillenaAssessmentRendererContract.questionView(q);let body='';if(view.context)body+=`<div class="question-context">${esc(view.context)}</div>`;if(view.renderKind==='sentence_unscramble'){body+=`<div class="question-prompt">${esc(view.prompt)}</div><div class="token-bank">${view.tokens.map(t=>`<span>${esc(t)}</span>`).join('')}</div>`}else{if(view.type==='listening'||view.renderKind==='listening_choice')body+=`<button class="listen-now" id="listenNow" type="button">▶ Play audio</button>`;body+=`<div class="question-prompt">${esc(view.prompt)}</div><div class="answer-grid ${isVisual(q)?'visual-grid':''}">${view.options.map(optionHtml).join('')}</div>`}const answer=Array.isArray(q.answerValue||q.a)?(q.answerValue||q.a).join(' '):(q.answerValue??q.a??'');host.innerHTML=`<article class="question-card"><div class="question-tags"><span>Internal ${esc(q.level)}</span><span>${esc(label(q.skill||typeName(q)))}</span><span>${esc(typeName(q))}</span></div>${body}${showAnswer?`<div class="answer-reveal"><b>Answer:</b> ${esc(answer)}</div>`:''}</article>`;$('#listenNow')?.addEventListener('click',()=>speak(q))}
function updateCurrent(q){if(!q)return renderQuestion(null);currentId=sourceKey(q);const i=filtered.findIndex(x=>sourceKey(x)===currentId);$('#currentTitle').textContent=`${i+1} / ${filtered.length} · ${currentId}`;$('#currentSub').textContent=`Internal ${q.level} · ${label(q.skill||typeName(q))}${isVisual(q)?' · image choices':''}`;$('#prevBtn').disabled=i<=0;$('#nextBtn').disabled=i<0||i>=filtered.length-1;renderQuestion(q);$$('.question-row').forEach(r=>r.classList.toggle('active',r.dataset.id===currentId));$('.question-row.active')?.scrollIntoView({block:'nearest'});const u=new URL(location.href);u.searchParams.set('question',currentId);history.replaceState(null,'',u)}
function selectQuestion(id){const q=filtered.find(x=>sourceKey(x)===id)||bank.find(x=>sourceKey(x)===id);if(q){showAnswer=false;$('#answerBtn').textContent='Show answer';updateCurrent(q)}}
function renderList(){const host=$('#questionList');$('#count').textContent=`${filtered.length} of ${bank.length} questions`;if(!filtered.length){host.innerHTML='<div class="empty">No questions match these filters.</div>';currentId='';renderQuestion(null);return}if(!filtered.some(q=>sourceKey(q)===currentId))currentId=sourceKey(filtered[0]);host.innerHTML=filtered.map((q,i)=>`<button class="question-row ${sourceKey(q)===currentId?'active':''}" type="button" data-id="${esc(sourceKey(q))}"><span class="question-index">${i+1}</span><span class="question-copy"><strong>${esc(sourceKey(q))}</strong><p>${esc(q.prompt||q.q||'Untitled question')}</p><span class="row-badges"><span>L${esc(q.level)}</span><span>${esc(label(q.skill||typeName(q)))}</span>${isVisual(q)?'<span class="visual">IMAGE</span>':''}</span></span></button>`).join('');$$('.question-row',host).forEach(b=>b.onclick=()=>selectQuestion(b.dataset.id));updateCurrent(filtered.find(q=>sourceKey(q)===currentId)||filtered[0])}
function applyFilters(){const level=$('#levelFilter').value,skill=$('#skillFilter').value,type=$('#typeFilter').value,visual=$('#visualFilter').value,query=text($('#searchInput').value).toLowerCase();filtered=bank.filter(q=>(level==='all'||String(q.level)===level)&&(skill==='all'||text(q.skill)===skill)&&(type==='all'||typeName(q)===type)&&(visual==='all'||(visual==='visual')===isVisual(q))&&(!query||qSearch(q).includes(query)));renderList()}
function step(d){const i=filtered.findIndex(q=>sourceKey(q)===currentId),q=filtered[i+d];if(q)selectQuestion(sourceKey(q))}
function bind(){['levelFilter','skillFilter','typeFilter','visualFilter'].forEach(id=>$('#'+id).onchange=applyFilters);$('#searchInput').oninput=applyFilters;$('#resetFilters').onclick=()=>{['levelFilter','skillFilter','typeFilter','visualFilter'].forEach(id=>$('#'+id).value='all');$('#searchInput').value='';applyFilters()};$('#prevBtn').onclick=()=>step(-1);$('#nextBtn').onclick=()=>step(1);$('#answerBtn').onclick=()=>{showAnswer=!showAnswer;$('#answerBtn').textContent=showAnswer?'Hide answer':'Show answer';const q=filtered.find(x=>sourceKey(x)===currentId)||bank.find(x=>sourceKey(x)===currentId);renderQuestion(q)};document.addEventListener('keydown',e=>{const tag=e.target?.tagName?.toLowerCase();if(['input','select','textarea'].includes(tag))return;if(e.key==='ArrowLeft'){e.preventDefault();step(-1)}if(e.key==='ArrowRight'){e.preventDefault();step(1)}})}
async function boot(){if(!(await requireTeacher()))return;bind();try{bank=sortBank(await window.loadQuestionBank());setupFilters();const wanted=text(new URLSearchParams(location.search).get('question'));currentId=bank.some(q=>sourceKey(q)===wanted)?wanted:sourceKey(bank[0]);applyFilters()}catch(e){$('#count').textContent='Could not load';$('#questionList').innerHTML='<div class="empty">'+esc(e.message||'Could not load bank')+'</div>';$('#questionPreview').innerHTML='<div class="empty">Bank unavailable</div>'}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
