(function(){
'use strict';
var rendered=false;
function publicLevelFromInternal(value){var n=Math.round(Number(value)||0);if(n<1||n>12)return null;return n<=2?n:n-2}
async function loadAssignment(){try{var response=await WillenaAPI.fetch('/.netlify/functions/student_study_current?_='+Date.now(),{credentials:'include',cache:'no-store'});var data=await response.json().catch(function(){return{}});return response.ok&&data.success!==false?data.assignment||null:null}catch(_){return null}}
function addStyles(){var style=document.createElement('style');style.textContent='.reward-screen{min-height:68vh;display:grid;place-items:center;padding:24px;position:relative;overflow:hidden}.reward-card{position:relative;z-index:2;width:min(680px,100%);background:#fff;border:1px solid #dbe8ee;border-radius:30px;padding:clamp(30px,7vw,58px);text-align:center;box-shadow:0 22px 65px rgba(38,66,88,.13)}.reward-kicker{font-size:13px;font-weight:800;letter-spacing:.14em;text-transform:uppercase;color:#71809a}.reward-title{margin:8px 0 12px;color:#17243f;font-size:clamp(30px,7vw,46px)}.reward-points{display:flex;justify-content:center;align-items:baseline;gap:10px;margin:10px 0}.reward-number{font-size:clamp(58px,15vw,96px);line-height:1;font-weight:800;color:#20b9c5;font-variant-numeric:tabular-nums}.reward-label{font-size:clamp(18px,4vw,25px);font-weight:800;color:#40516a}.reward-note{margin:0 auto 24px;max-width:520px;color:#71809a;line-height:1.65;font-weight:600}.reward-target{display:inline-flex;gap:8px;align-items:center;margin:0 auto 22px;padding:10px 14px;border-radius:999px;background:#eef9fa;color:#1c6d74;font-weight:800}.reward-home{display:inline-flex;align-items:center;justify-content:center;min-height:56px;padding:0 24px;border-radius:17px;background:#17243f;color:#fff;text-decoration:none;font-weight:800}.particle-layer{position:absolute;inset:0;pointer-events:none;z-index:1}.spark{position:absolute;width:6px;height:14px;border-radius:5px;background:currentColor;opacity:0;transform-origin:50% 80px;animation:spark-pop 900ms ease-out forwards}.burst-a{color:#20b9c5}.burst-b{color:#f5b942}.burst-c{color:#6c7bd9}@keyframes spark-pop{0%{opacity:0;transform:translate(-50%,-50%) rotate(var(--a)) translateY(0) scale(.6)}18%{opacity:1}100%{opacity:0;transform:translate(-50%,-50%) rotate(var(--a)) translateY(-82px) scale(.9)}}@media(prefers-reduced-motion:reduce){.spark{display:none}}';document.head.appendChild(style)}
function burst(layer,x,y,klass){for(var i=0;i<12;i++){var s=document.createElement('span');s.className='spark '+klass;s.style.left=x+'%';s.style.top=y+'%';s.style.setProperty('--a',(i*30)+'deg');s.style.animationDelay=(i%3)*35+'ms';layer.appendChild(s);setTimeout(function(el){el.remove()},1200,s)}}
function countUp(el,target){if(matchMedia('(prefers-reduced-motion: reduce)').matches){el.textContent=target;return}var start=performance.now(),duration=1050;function tick(now){var p=Math.min(1,(now-start)/duration);var eased=1-Math.pow(1-p,3);el.textContent=Math.round(target*eased);if(p<1)requestAnimationFrame(tick)}requestAnimationFrame(tick)}
async function render(event){if(rendered)return;rendered=true;var detail=event&&event.detail||{},result=detail.result||{},attempt=result.attempt||{};var q=Number(attempt.total_questions)||Number(detail.answered_count)||0;if([20,30,40,50].indexOf(q)<0)return;var internal=Number(attempt.recommended_level)||Number(window.WillenaInternalResultLevel)||Number(sessionStorage.getItem('willena_internal_result_level'))||null;var publicLevel=publicLevelFromInternal(internal),assignment=await loadAssignment();var target=assignment&&Number(assignment.catalog_level)>0?Number(assignment.catalog_level):null;var hit=Boolean(target&&publicLevel&&publicLevel>=target),points=hit?q*2:Math.round(q/2);var root=document.getElementById('app');if(!root)return;addStyles();var targetLine=target?'<div class="reward-target">Target level '+target+(hit?' reached':'')+'</div>':'';var note=hit?'You hit or exceeded your class target. Full completion reward earned.':'Test complete. Keep working toward your class target for the full reward next time.';root.innerHTML='<section class="reward-screen"><div class="particle-layer" aria-hidden="true"></div><div class="reward-card"><div class="reward-kicker">Willena Points</div><h1 class="reward-title">Test complete</h1><div class="reward-points"><strong class="reward-number">0</strong><span class="reward-label">points</span></div>'+targetLine+'<p class="reward-note">'+note+'</p><a class="reward-home" href="/students/dashboard.html">Return to student dashboard</a></div></section>';var num=root.querySelector('.reward-number'),layer=root.querySelector('.particle-layer');countUp(num,points);burst(layer,18,27,'burst-a');setTimeout(function(){burst(layer,82,23,'burst-b')},180);setTimeout(function(){burst(layer,52,18,'burst-c')},360)}
window.addEventListener('willena:recording-finished',function(event){setTimeout(function(){render(event)},40)});
})();
