(()=>{
  const dict={
    ko:{
      appTitle:'윌레나 관리자',studentOperations:'학생 관리',administrator:'관리자',students:'학생',classes:'반 관리',levelTests:'레벨 테스트',home:'홈',
      studentsTitle:'학생 관리',studentsSub:'학생 정보와 반 배정을 관리합니다.',classesTitle:'반 관리',classesSub:'15개 반의 현재 학생 명단입니다.',levelTestsTitle:'레벨 테스트',levelTestsSub:'내부, 온라인 및 대면 레벨 테스트 기록입니다.',homeTitle:'홈',homeSub:'빠른 현황과 일정 기능은 추후 추가됩니다.',
      optimisticNotice:'변경 내용은 화면에 즉시 반영되고 백그라운드에서 저장됩니다. 문제가 생긴 경우에만 알려드립니다.',classNotice:'학생 이동은 즉시 반영되며 백그라운드에서 저장됩니다.',homeEmpty:'홈 화면은 추후 구성할 예정입니다.',
      searchStudents:'학생 검색',refresh:'새로고침',addStudent:'학생 추가',allClasses:'전체 반',noClass:'미배정',allGrades:'전체 학년',noGrade:'학년 미입력',shown:'명 표시',studentCount:'명',noClassCount:'명 미배정',loadingStudents:'학생 정보를 불러오는 중…',checkingAccess:'관리자 권한 확인 중…',noStudents:'검색 결과가 없습니다.',
      approved:'승인됨',approvalPending:'승인 대기',saving:'저장 중',edit:'수정',move:'이동',assign:'배정',remove:'제외',viewRoster:'학생 명단 보기',
      editStudent:'학생 정보 수정',englishName:'영어 이름',koreanName:'한국 이름',username:'아이디',password:'임시 비밀번호',grade:'학년',school:'학교',phone:'전화번호',studentClass:'반',cancel:'취소',saveChanges:'저장',createStudent:'학생 계정 만들기',
      moveStudent:'반 이동',currentClass:'현재 반',moveTo:'이동할 반',moveStudentButton:'반 이동',removeFromClass:'반에서 제외',removeExplanation:'학생 계정과 학습 기록은 유지되며 현재 반 배정만 해제됩니다.',removeButton:'반에서 제외',
      chooseDifferent:'현재 반과 다른 반을 선택해 주세요.',requiredName:'영어 이름 또는 한국 이름을 입력해 주세요.',requiredUsername:'아이디를 입력해 주세요.',usernameFormat:'아이디는 영문 소문자, 숫자, 점, 하이픈, 밑줄을 사용해 3자 이상 입력해 주세요.',passwordLength:'비밀번호는 6자 이상이어야 합니다.',duplicateUsername:'이미 사용 중인 아이디입니다.',
      waitChanges:'현재 변경 사항이 저장될 때까지 잠시 기다려 주세요.',saveFailed:'학생 정보를 저장하지 못했습니다',moveFailed:'학생을 이동하지 못했습니다',removeFailed:'학생을 반에서 제외하지 못했습니다',createFailed:'학생 계정을 만들지 못했습니다',undoFailed:'실행 취소에 실패했습니다',removedFrom:'{name} 학생을 {class} 반에서 제외했습니다',undo:'실행 취소',
      profile:'학생 정보',account:'계정 정보',learningActivity:'학습 활동',actions:'관리',activityEmpty:'레벨 테스트, 숙제 활동, 게임 진도는 아직 이 화면에 연결되지 않았습니다. 다음 데이터 단계에서 추가할 예정입니다.',status:'상태',role:'권한',accountId:'계정 ID',editProfile:'정보 수정',moveClass:'반 이동',assignClass:'반 배정',closeDetails:'학생 정보 닫기',openInfo:'학생 정보 열기',student:'학생',
      newStudentHint:'학생은 화면에 즉시 추가되고 계정은 백그라운드에서 생성됩니다.',accountCreated:'{name} 학생 계정을 만들었습니다.'
    },
    en:{
      appTitle:'Willena Admin',studentOperations:'Student operations',administrator:'Administrator',students:'Students',classes:'Classes',levelTests:'Level Tests',home:'Home',
      studentsTitle:'Students',studentsSub:'Live student profiles and class management.',classesTitle:'Classes',classesSub:'15 canonical classes with live rosters.',levelTestsTitle:'Level Tests',levelTestsSub:'Recorded internal, online and face-to-face placement tests.',homeTitle:'Home',homeSub:'Quick updates will come later.',
      optimisticNotice:'Changes appear immediately and save quietly in the background. You will only be notified if something fails.',classNotice:'Class counts update immediately while changes save in the background.',homeEmpty:'Home updates will be designed later.',
      searchStudents:'Search students',refresh:'Refresh',addStudent:'Add student',allClasses:'All classes',noClass:'No class',allGrades:'All grades',noGrade:'No grade',shown:'shown',studentCount:'students',noClassCount:'no class',loadingStudents:'Loading students…',checkingAccess:'Checking admin access…',noStudents:'No students found.',
      approved:'Approved',approvalPending:'Approval pending',saving:'Saving',edit:'Edit',move:'Move',assign:'Assign',remove:'Remove',viewRoster:'View roster',
      editStudent:'Edit student',englishName:'English name',koreanName:'Korean name',username:'Username',password:'Temporary password',grade:'Grade',school:'School',phone:'Phone',studentClass:'Class',cancel:'Cancel',saveChanges:'Save changes',createStudent:'Create student account',
      moveStudent:'Move student',currentClass:'Current class',moveTo:'Move to',moveStudentButton:'Move student',removeFromClass:'Remove from class',removeExplanation:'The account and learning records remain. Only the current class is cleared.',removeButton:'Remove from class',
      chooseDifferent:'Choose a different class.',requiredName:'Enter an English or Korean name.',requiredUsername:'Enter a username.',usernameFormat:'Use 3 or more lowercase letters, numbers, dots, dashes or underscores.',passwordLength:'Password must be at least 6 characters.',duplicateUsername:'That username is already in use.',
      waitChanges:'Please wait for current changes to finish.',saveFailed:'Could not save student changes',moveFailed:'Could not move student',removeFailed:'Could not remove student',createFailed:'Could not create student account',undoFailed:'Could not undo',removedFrom:'{name} removed from {class}',undo:'Undo',
      profile:'Student profile',account:'Account',learningActivity:'Learning activity',actions:'Actions',activityEmpty:'Level-test results, homework activity and game progress are not connected to this view yet. This section is reserved for the next data phase.',status:'Status',role:'Role',accountId:'Account ID',editProfile:'Edit profile',moveClass:'Move class',assignClass:'Assign class',closeDetails:'Close student details',openInfo:'Open student information',student:'Student',
      newStudentHint:'The student appears immediately while the account is created in the background.',accountCreated:'Created the account for {name}.'
    }
  };

  let language=localStorage.getItem('willenaAdminLanguage');
  if(language!=='en'&&language!=='ko')language='ko';
  const t=(key,vars={})=>{let text=dict[language]?.[key]||dict.en[key]||key;for(const [k,v] of Object.entries(vars))text=text.replaceAll(`{${k}}`,String(v));return text};
  window.AdminI18n={t,get language(){return language},setLanguage};

  const style=document.createElement('style');
  style.textContent=`
    .student{cursor:pointer}.student:focus{outline:3px solid #86d4d8;outline-offset:2px}.student.temp{border-style:dashed}.student.temp .ava{animation:pulse 1.2s ease-in-out infinite}@keyframes pulse{50%{opacity:.45}}
    .add-modal-grid{display:grid;grid-template-columns:1fr 1fr;gap:12px}.add-modal-grid .full{grid-column:1/-1}.form-hint{font-size:.78rem;color:var(--mut);background:#f2f8f8;border-radius:10px;padding:10px}.drawer-backdrop{position:fixed;inset:0;background:#15202b66;z-index:80;opacity:0;pointer-events:none;transition:.2s}.drawer-backdrop.show{opacity:1;pointer-events:auto}.student-drawer{position:fixed;right:0;top:0;bottom:0;width:min(500px,94vw);z-index:81;background:#fff;box-shadow:-20px 0 60px #0002;transform:translateX(105%);transition:.24s ease;overflow:auto}.student-drawer.show{transform:none}.drawer-head{display:flex;gap:13px;align-items:center;padding:22px;border-bottom:1px solid var(--line);position:sticky;top:0;background:#fff;z-index:2}.drawer-avatar{width:55px;height:55px;border-radius:17px;background:var(--soft);color:var(--teal);display:grid;place-items:center;font-size:1.25rem;font-weight:800}.drawer-title{flex:1;min-width:0}.drawer-title h2{margin:0}.drawer-title p{margin:3px 0 0;color:var(--mut);font-size:.82rem}.drawer-close{border:0;background:#f1f3f6;width:36px;height:36px;border-radius:50%;font-size:1.3rem}.drawer-body{padding:20px;display:grid;gap:18px}.drawer-section{border:1px solid var(--line);border-radius:16px;padding:16px}.drawer-section h3{margin:0 0 12px}.detail-grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.detail{background:#f7f9fb;border-radius:11px;padding:10px}.detail.full{grid-column:1/-1}.detail label{display:block;font-size:.7rem;color:var(--mut);font-weight:700;margin-bottom:3px}.drawer-id{font-family:monospace;overflow-wrap:anywhere;font-size:.76rem}.status-good{color:#16754c;font-weight:800}.status-warn{color:#9b6414;font-weight:800}.drawer-empty{color:var(--mut);font-size:.82rem;line-height:1.6}.drawer-actions{display:flex;gap:8px;flex-wrap:wrap}.drawer-actions button{border:1px solid var(--line);background:#fff;border-radius:10px;padding:9px 11px;font-weight:700}.drawer-actions .danger{color:var(--red)}
    @media(max-width:720px){.add-modal-grid{grid-template-columns:1fr}.add-modal-grid .full{grid-column:auto}.student-drawer{top:auto;left:0;width:100%;height:min(82vh,720px);border-radius:22px 22px 0 0;transform:translateY(105%)}.student-drawer.show{transform:none}.detail-grid{grid-template-columns:1fr}}
  `;
  document.head.appendChild(style);

  class OptimisticManager{
    constructor(){this.revisions=new Map();this.pending=new Map()}
    async run({key,apply,request,rollback,commit,onError}){
      const revision=(this.revisions.get(key)||0)+1;this.revisions.set(key,revision);this.pending.set(key,revision);apply();
      try{const result=await request();if(this.revisions.get(key)===revision){commit?.(result);this.pending.delete(key)}return result}
      catch(error){if(this.revisions.get(key)===revision){rollback();this.pending.delete(key);onError?.(error)}throw error}
    }
    isPending(key){return this.pending.has(key)}
  }
  const optimistic=new OptimisticManager();
  window.AdminOptimistic=optimistic;

  function setLanguage(next){if(next!=='en'&&next!=='ko')return;language=next;localStorage.setItem('willenaAdminLanguage',next);applyLanguage()}
  function setText(selector,key){const el=document.querySelector(selector);if(el)el.textContent=t(key)}
  function applyLanguage(){
    document.documentElement.lang=language;document.title=t('appTitle');
    const brand=document.querySelector('.brand div');if(brand){brand.querySelector('b').textContent=t('appTitle');brand.querySelector('small').textContent=t('studentOperations')}
    document.querySelectorAll('[data-page="students"]').forEach(el=>el.textContent=`◎ ${t('students')}`);document.querySelectorAll('[data-page="classes"]').forEach(el=>el.textContent=`▦ ${t('classes')}`);document.querySelectorAll('[data-page="levelTests"]').forEach(el=>el.textContent=`◫ ${t('levelTests')}`);document.querySelectorAll('[data-page="home"]').forEach(el=>el.textContent=`⌂ ${t('home')}`);
    const who=document.querySelector('.who small');if(who)who.textContent=t('administrator');
    const notices=document.querySelectorAll('.notice');if(notices[0])notices[0].textContent=t('optimisticNotice');if(notices[1])notices[1].textContent=t('classNotice');
    setText('#home .empty','homeEmpty');const search=document.getElementById('searchBox');if(search)search.placeholder=t('searchStudents');setText('#refreshBtn','refresh');setText('#addStudentBtn','addStudent');
    const summary=document.querySelectorAll('.summary span');if(summary[0])summary[0].lastChild.textContent=` ${t('shown')}`;if(summary[1])summary[1].lastChild.textContent=` ${t('studentCount')}`;if(summary[2])summary[2].lastChild.textContent=` ${t('noClassCount')}`;
    setText('#editModal .modal-head h3','editStudent');const editLabels=document.querySelectorAll('#editModal label');['englishName','koreanName','username','grade','school','phone'].forEach((k,i)=>{if(editLabels[i])editLabels[i].textContent=t(k)});const editBtns=document.querySelectorAll('#editModal .modal-foot button');if(editBtns[0])editBtns[0].textContent=t('cancel');if(editBtns[1])editBtns[1].textContent=t('saveChanges');
    setText('#moveModal .modal-head h3','moveStudent');const moveLabels=document.querySelectorAll('#moveModal label');if(moveLabels[0])moveLabels[0].textContent=t('currentClass');if(moveLabels[1])moveLabels[1].textContent=t('moveTo');const moveBtns=document.querySelectorAll('#moveModal .modal-foot button');if(moveBtns[0])moveBtns[0].textContent=t('cancel');if(moveBtns[1])moveBtns[1].textContent=t('moveStudentButton');
    setText('#removeModal .modal-head h3','removeFromClass');setText('#removeModal .mut','removeExplanation');const removeBtns=document.querySelectorAll('#removeModal .modal-foot button');if(removeBtns[0])removeBtns[0].textContent=t('cancel');if(removeBtns[1])removeBtns[1].textContent=t('removeButton');
    document.querySelectorAll('.lang button').forEach((btn,i)=>{const code=i===0?'en':'ko';btn.dataset.lang=code;btn.classList.toggle('active',code===language);btn.onclick=()=>setLanguage(code)});
    buildFilters();apply();renderClasses();setPage(currentPage||'students');renderAddModal();if(openStudentId)renderDrawer();
    document.dispatchEvent(new CustomEvent('willena-language-change',{detail:{language}}));
  }

  window.buildFilters=function(){
    const classFilter=document.getElementById('classFilter'),gradeFilter=document.getElementById('gradeFilter'),moveTarget=document.getElementById('moveTarget');const oldClass=classFilter.value,oldGrade=gradeFilter.value;
    classFilter.innerHTML=`<option value="">${t('allClasses')}</option><option value="__none__">${t('noClass')}</option>`+canonical.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');
    const grades=[...new Set(students.map(s=>s.grade).filter(Boolean))].sort((a,b)=>String(a).localeCompare(String(b),undefined,{numeric:true}));gradeFilter.innerHTML=`<option value="">${t('allGrades')}</option>`+grades.map(g=>`<option value="${esc(g)}">${esc(g)}</option>`).join('');moveTarget.innerHTML=canonical.map(c=>`<option value="${esc(c)}">${esc(c)}</option>`).join('');
    if([...classFilter.options].some(o=>o.value===oldClass))classFilter.value=oldClass;if([...gradeFilter.options].some(o=>o.value===oldGrade))gradeFilter.value=oldGrade;
  };
  window.renderStudents=function(){
    const list=document.getElementById('studentList');if(!filtered.length){list.innerHTML=`<div class="card empty">${t('noStudents')}</div>`;return}
    list.innerHTML=filtered.map(s=>{const n=nameOf(s),temp=String(s.id).startsWith('temp-'),pendingState=temp||optimistic.isPending(`student:${s.id}`);return`<div class="card student${temp?' temp':''}${pendingState?' pending':''}" data-row-id="${esc(s.id)}"><div class="person"><div class="ava">${esc((n[0]||'S').toUpperCase())}</div><div><b>${esc(n)}</b><div class="mut">${esc(s.korean_name||'')} ${s.username?'· '+esc(s.username):''}${temp?' · '+t('saving'):''}</div></div></div><div class="mobile-hide"><span class="pill">${esc(s.class||t('noClass'))}</span><div class="mut">${esc(s.grade||t('noGrade'))}</div></div><div class="optional"><b>${esc(s.school||'')}</b><div class="mut">${s.approved!==false?t('approved'):t('approvalPending')}</div></div><div class="actions-inline">${temp?'':`<button class="link" data-edit="${esc(s.id)}">${t('edit')}</button><button class="link" data-move="${esc(s.id)}">${s.class?t('move'):t('assign')}</button>${s.class?`<button class="link danger" data-remove="${esc(s.id)}">${t('remove')}</button>`:''}`}</div></div>`}).join('');
    document.querySelectorAll('[data-edit]').forEach(b=>b.onclick=e=>{e.stopPropagation();openEdit(b.dataset.edit)});document.querySelectorAll('[data-move]').forEach(b=>b.onclick=e=>{e.stopPropagation();openMove(b.dataset.move)});document.querySelectorAll('[data-remove]').forEach(b=>b.onclick=e=>{e.stopPropagation();openRemove(b.dataset.remove)});
  };
  window.renderClasses=function(){const counts=Object.fromEntries(canonical.map(c=>[c,0]));students.forEach(s=>{if(counts[s.class]!==undefined)counts[s.class]++});document.getElementById('classGrid').innerHTML=canonical.map(c=>`<div class="card class-card"><h3>${c}</h3><div class="count">${counts[c]}</div><div class="mut">${t('studentCount')}</div><button data-view-class="${c}">${t('viewRoster')}</button></div>`).join('');document.querySelectorAll('[data-view-class]').forEach(b=>b.onclick=()=>{document.getElementById('classFilter').value=b.dataset.viewClass;apply();setPage('students')})};
  window.setPage=function(p){currentPage=p;document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(p).classList.add('active');document.querySelectorAll('[data-page]').forEach(b=>b.classList.toggle('active',b.dataset.page===p));const m={students:[t('studentsTitle'),t('studentsSub')],classes:[t('classesTitle'),t('classesSub')],levelTests:[t('levelTestsTitle'),t('levelTestsSub')],home:[t('homeTitle'),t('homeSub')]}[p];document.getElementById('pageTitle').textContent=m[0];document.getElementById('pageSub').textContent=m[1]};

  const toolbar=document.querySelector('#students .toolbar');const addButton=document.createElement('button');addButton.className='btn primary';addButton.id='addStudentBtn';toolbar.appendChild(addButton);
  const addModal=document.createElement('div');addModal.className='modal-bg';addModal.id='addStudentModal';document.body.appendChild(addModal);
  function renderAddModal(){
    const values={name:document.getElementById('addName')?.value||'',korean_name:document.getElementById('addKorean')?.value||'',username:document.getElementById('addUsername')?.value||'',password:document.getElementById('addPassword')?.value||'',className:document.getElementById('addClass')?.value||'',grade:document.getElementById('addGrade')?.value||'',school:document.getElementById('addSchool')?.value||'',phone:document.getElementById('addPhone')?.value||''};
    addModal.innerHTML=`<div class="modal"><div class="modal-head"><h3>${t('addStudent')}</h3><button class="close" id="closeAdd">×</button></div><div class="modal-body"><div class="add-modal-grid"><div><label>${t('englishName')}</label><input id="addName" value="${esc(values.name)}"></div><div><label>${t('koreanName')}</label><input id="addKorean" value="${esc(values.korean_name)}"></div><div><label>${t('username')}</label><input id="addUsername" autocomplete="off" value="${esc(values.username)}"></div><div><label>${t('password')}</label><input id="addPassword" type="text" autocomplete="new-password" value="${esc(values.password)}"></div><div><label>${t('studentClass')}</label><select id="addClass"><option value="">${t('noClass')}</option>${canonical.map(c=>`<option value="${esc(c)}"${values.className===c?' selected':''}>${esc(c)}</option>`).join('')}</select></div><div><label>${t('grade')}</label><input id="addGrade" value="${esc(values.grade)}"></div><div><label>${t('school')}</label><input id="addSchool" value="${esc(values.school)}"></div><div><label>${t('phone')}</label><input id="addPhone" value="${esc(values.phone)}"></div><div class="form-hint full">${t('newStudentHint')}</div><div class="msg full" id="addMsg"></div></div></div><div class="modal-foot"><button class="btn" id="cancelAdd">${t('cancel')}</button><button class="btn primary" id="confirmAdd">${t('createStudent')}</button></div></div>`;
    document.getElementById('closeAdd').onclick=closeAdd;document.getElementById('cancelAdd').onclick=closeAdd;document.getElementById('confirmAdd').onclick=createStudent;
  }
  function openAdd(){renderAddModal();addModal.classList.add('show');setTimeout(()=>document.getElementById('addName')?.focus(),20)}function closeAdd(){addModal.classList.remove('show')}addButton.onclick=openAdd;addModal.onclick=e=>{if(e.target===addModal)closeAdd()};

  async function createStudent(){
    const body={name:document.getElementById('addName').value.trim(),korean_name:document.getElementById('addKorean').value.trim(),username:document.getElementById('addUsername').value.trim().toLowerCase(),password:document.getElementById('addPassword').value,class:document.getElementById('addClass').value,grade:document.getElementById('addGrade').value.trim()||null,school:document.getElementById('addSchool').value.trim()||null,phone:document.getElementById('addPhone').value.trim()||null,approved:true};
    const msg=document.getElementById('addMsg');if(!body.name&&!body.korean_name){msg.textContent=t('requiredName');return}if(!body.username){msg.textContent=t('requiredUsername');return}if(!/^[a-z0-9._-]{3,40}$/.test(body.username)){msg.textContent=t('usernameFormat');return}if(body.password.length<6){msg.textContent=t('passwordLength');return}if(students.some(s=>String(s.username||'').toLowerCase()===body.username)){msg.textContent=t('duplicateUsername');return}
    const tempId=`temp-${Date.now()}-${Math.random().toString(36).slice(2)}`;const temp={id:tempId,email:`${body.username}@stu.willena`,username:body.username,name:body.name||body.username,korean_name:body.korean_name,role:'student',approved:true,class:body.class||'',grade:body.grade,school:body.school,phone:body.phone};closeAdd();
    try{await optimistic.run({key:`create:${body.username}`,apply:()=>{students.unshift(temp);buildFilters();apply();renderClasses();refreshCounts()},request:()=>api(`${API_ADMIN}?action=create_student`,{method:'POST',body:JSON.stringify(body)}),rollback:()=>{students=students.filter(s=>s.id!==tempId);buildFilters();apply();renderClasses();refreshCounts()},commit:result=>{const index=students.findIndex(s=>s.id===tempId);if(index>=0)students[index]={...result.student,class:result.student.class||''};buildFilters();apply();renderClasses();refreshCounts()},onError:error=>showToast(`${t('createFailed')}: ${error.message}`,{error:true,duration:6500})})}
    catch{}
  }

  document.getElementById('saveEdit').onclick=()=>{if(!selected)return;const id=selected.id,before=snapshot(selected),patch={name:document.getElementById('editName').value.trim(),korean_name:document.getElementById('editKorean').value.trim(),username:document.getElementById('editUsername').value.trim(),grade:document.getElementById('editGrade').value.trim()||null,school:document.getElementById('editSchool').value.trim()||null,phone:document.getElementById('editPhone').value.trim()||null};document.getElementById('editModal').classList.remove('show');optimistic.run({key:`student:${id}`,apply:()=>updateLocal(id,patch),request:()=>api(`${API_ADMIN}?action=update_student`,{method:'POST',body:JSON.stringify({user_id:id,...patch})}),rollback:()=>updateLocal(id,before),onError:error=>showToast(`${t('saveFailed')}: ${error.message}`,{error:true,duration:6000})}).catch(()=>{})};
  document.getElementById('confirmMove').onclick=()=>{if(!selected)return;const id=selected.id,target=document.getElementById('moveTarget').value,oldClass=selected.class;if(!target||target===oldClass){document.getElementById('moveMsg').textContent=t('chooseDifferent');return}document.getElementById('moveModal').classList.remove('show');optimistic.run({key:`student:${id}`,apply:()=>updateLocal(id,{class:target}),request:()=>api(`${API_ADMIN}?action=update_student`,{method:'POST',body:JSON.stringify({user_id:id,class:target})}),rollback:()=>updateLocal(id,{class:oldClass}),onError:error=>showToast(`${t('moveFailed')}: ${error.message}`,{error:true,duration:6000})}).catch(()=>{})};
  document.getElementById('confirmRemove').onclick=async()=>{if(!selected||!selected.class)return;const id=selected.id,oldClass=selected.class,student=snapshot(selected),row=document.querySelector(`[data-row-id="${CSS.escape(String(id))}"]`);document.getElementById('removeModal').classList.remove('show');if(row){row.classList.add('removing');await new Promise(r=>setTimeout(r,150))}optimistic.run({key:`student:${id}`,apply:()=>updateLocal(id,{class:''}),request:()=>api(`${API_ADMIN}?action=update_student`,{method:'POST',body:JSON.stringify({user_id:id,class:''})}),rollback:()=>updateLocal(id,{class:oldClass}),onError:error=>showToast(`${t('removeFailed')}: ${error.message}`,{error:true,duration:6000})}).then(()=>showToast(t('removedFrom',{name:nameOf(student),class:oldClass}),{action:t('undo'),onAction:()=>optimistic.run({key:`student:${id}`,apply:()=>updateLocal(id,{class:oldClass}),request:()=>api(`${API_ADMIN}?action=update_student`,{method:'POST',body:JSON.stringify({user_id:id,class:oldClass})}),rollback:()=>updateLocal(id,{class:''}),onError:error=>showToast(`${t('undoFailed')}: ${error.message}`,{error:true,duration:6000})}).catch(()=>{})})).catch(()=>{})};

  const studentList=document.getElementById('studentList'),backdrop=document.createElement('div'),drawer=document.createElement('aside');backdrop.className='drawer-backdrop';drawer.className='student-drawer';drawer.setAttribute('aria-hidden','true');document.body.append(backdrop,drawer);let openStudentId=null;
  const safe=v=>String(v??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));const value=v=>String(v??'').trim()||'—';const field=(label,v,extra='')=>`<div class="detail ${extra}"><label>${safe(label)}</label><div>${safe(value(v))}</div></div>`;
  function renderDrawer(){if(!openStudentId)return;const s=findStudent(openStudentId);if(!s||String(s.id).startsWith('temp-')){closeDrawer();return}const display=nameOf(s),approved=s.approved!==false;drawer.innerHTML=`<div class="drawer-head"><div class="drawer-avatar">${safe((display[0]||'S').toUpperCase())}</div><div class="drawer-title"><h2>${safe(display)}</h2><p>${safe([s.korean_name,s.username].filter(Boolean).join(' · '))}</p></div><button class="drawer-close" id="drawerClose" aria-label="${safe(t('closeDetails'))}">×</button></div><div class="drawer-body"><section class="drawer-section"><h3>${t('profile')}</h3><div class="detail-grid">${field(t('englishName'),s.name)}${field(t('koreanName'),s.korean_name)}${field(t('currentClass'),s.class||t('noClass'))}${field(t('grade'),s.grade)}${field(t('school'),s.school,'full')}${field(t('phone'),s.phone,'full')}</div></section><section class="drawer-section"><h3>${t('account')}</h3><div class="detail-grid">${field(t('username'),s.username)}<div class="detail"><label>${t('status')}</label><div class="${approved?'status-good':'status-warn'}">${approved?t('approved'):t('approvalPending')}</div></div>${field(t('role'),s.role||'student')}<div class="detail full"><label>${t('accountId')}</label><div class="drawer-id">${safe(value(s.id))}</div></div></div></section><section class="drawer-section"><h3>${t('learningActivity')}</h3><div class="drawer-empty">${t('activityEmpty')}</div></section><section class="drawer-section"><h3>${t('actions')}</h3><div class="drawer-actions"><button id="drawerEdit">${t('editProfile')}</button><button id="drawerMove">${s.class?t('moveClass'):t('assignClass')}</button>${s.class?`<button class="danger" id="drawerRemove">${t('removeFromClass')}</button>`:''}</div></section></div>`;document.getElementById('drawerClose').onclick=closeDrawer;document.getElementById('drawerEdit').onclick=()=>{const id=openStudentId;closeDrawer();openEdit(id)};document.getElementById('drawerMove').onclick=()=>{const id=openStudentId;closeDrawer();openMove(id)};const rem=document.getElementById('drawerRemove');if(rem)rem.onclick=()=>{const id=openStudentId;closeDrawer();openRemove(id)}}
  function openDrawer(id){if(!findStudent(id)||String(id).startsWith('temp-'))return;openStudentId=id;renderDrawer();backdrop.classList.add('show');drawer.classList.add('show');drawer.setAttribute('aria-hidden','false');document.body.style.overflow='hidden'}function closeDrawer(){backdrop.classList.remove('show');drawer.classList.remove('show');drawer.setAttribute('aria-hidden','true');document.body.style.overflow='';openStudentId=null}
  studentList.addEventListener('click',e=>{if(e.target.closest('button,a,input,select'))return;const row=e.target.closest('[data-row-id]');if(row)openDrawer(row.dataset.rowId)});studentList.addEventListener('keydown',e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('button')){const row=e.target.closest('[data-row-id]');if(row){e.preventDefault();openDrawer(row.dataset.rowId)}}});new MutationObserver(()=>{document.querySelectorAll('.student[data-row-id]').forEach(row=>{row.tabIndex=0;row.setAttribute('role','button');row.setAttribute('aria-label',t('openInfo'))});if(openStudentId)renderDrawer()}).observe(studentList,{childList:true,subtree:true});backdrop.onclick=closeDrawer;document.addEventListener('keydown',e=>{if(e.key==='Escape'){if(openStudentId)closeDrawer();else if(addModal.classList.contains('show'))closeAdd()}});

  renderAddModal();applyLanguage();
})();
