// free-mode.js
// Free mode for MINT AI modal (default, open prompt)

export default {
  id: 'free',
  name: 'Free',
  description: 'General AI prompt mode. Enter any request.',
  placeholder: 'e.g. Generate 5 grammar questions about the past tense.',
  async generate(prompt) {
    if (window.generateQuestionsWithAI) {
      return await window.generateQuestionsWithAI(prompt);
    } else {
      return 'Q1. Example question generated by AI.\nQ2. Another question.\nQ3. ...';
    }
  }
};
