// grammar-mode.js
// Grammar worksheet mode for MINT AI modal

export default {
  id: 'grammar',
  name: 'Grammar',
  description: 'Generate grammar worksheet questions or exercises.',
  placeholder: 'e.g. Create 5 questions about superlatives.',
  async generate(prompt) {
    // Use a system prompt for grammar worksheet generation
    const systemPrompt = 'You are a helpful ESL worksheet generator. When given a grammar point or examples, create a set of grammar questions or exercises for students. Respond in worksheet-ready format.';
    if (window.generateQuestionsWithAI) {
      return await window.generateQuestionsWithAI(prompt, systemPrompt);
    } else {
      return 'Q1. Grammar question generated by AI.\nQ2. Another grammar question.\nQ3. ...';
    }
  }
};
