(function(global){
'use strict';
var TARGET=20;
var CACHE_PREFIX='willena-study-v2-home:v1:';
var SESSION_PREFIX='willena-study-v2-daily:v1:';
var panel=document.getElementById('v2PracticePanel');
var root=document.getElementById('v2ActivityRoot');
var countEl=document.getElementById('practicePerf');
var titleEl=document.getElementById('v2PracticeTitle');
var skillEl=document.getElementById('v2PracticeSkill');
var card=document.getElementById('dailyWorkoutCard');
var engine=null,pools=[],poolById={},plan=[],session=null,current=null,answerLocked=false,loading=false;

function text(v){return String(v==null?'':v).trim();}
function arr(v){return Array.isArray(v)?v:[];}
function uid(){try{return text(localStorage.getItem('user_id')||sessionStorage.getItem('user_id')||localStorage.getItem('userId')||sessionStorage.getItem('userId'));}catch(_){return'';}}
function dateKey(){var d=new Date();return d.getFullYear()+'-'+String(d.getMonth()+1).padStart(2,'0')+'-'+String(d.getDate()).padStart(2,'0');}
function cacheKey(){return CACHE_PREFIX+uid();}
function sessionKey(){return SESSION_PREFIX+uid()+':'+dateKey();}
function langKo(){var b=document.getElementById('languageBtn');return !b||text(b.textContent)==='English';}
function shuffle(a){return(a||[]).slice().sort(function(){return Math.random()-.5;});}
function home(){try{var o=JSON.parse(localStorage.getItem(cacheKey())||'null');return o&&Array.isArray(o.books)?o:null;}catch(_){return null;}}
function readSession(){try{var o=JSON.parse(localStorage.getItem(sessionKey())||'null');return o&&o.date===dateKey()?o:null;}catch(_){return null;}}
function saveSession(){try{if(session)localStorage.setItem(sessionKey(),JSON.stringify(session));}catch(_){}}
function api(url){return (global.WillenaAPI?WillenaAPI.fetch:fetch)(url,{credentials:'include',cache:'no-store'}).then(function(r){return r.json().then(function(d){if(!r.ok||d&&d.success===false)throw new Error(d.error||'Request failed');return d;});});}
function adaptive(){return api('/.netlify/functions/progress_summary?section=adaptive_state&_='+Date.now()).catch(function(){return{items:[]};});}
function context(book){var u=book&&book.currentUnit;return{bookId:book.book_id,bookTitle:book.book_title,unitId:u&&u.id,unitNumber:Number(u&&u.unit_number)};}
async function loadBookPool(book){if(!book||!book.currentUnit||!global.WillenaStudyQuestionBank)return[];var c=context(book),rows=await global.WillenaStudyQuestionBank.loadUnit(null,c).catch(function(){return[];});return arr(rows).filter(function(a){return a&&a.id&&['vocabulary','spelling','grammar','sentence_building','conversation','listening','reading'].indexOf(a.skill)>=0;}).map(function(a){a.metadata=Object.assign({},a.metadata||{},{book_id:book.book_id,unit_id:book.currentUnit.id,daily_book_title:book.book_title,daily_unit_number:Number(book.currentUnit.unit_number)});return a;});}
function masteryKey(a){var m=a&&a.metadata||{},skill=text(a&&a.skill);if(m.mastery_content_id)return text(m.mastery_content_type||a.sourceType||'activity')+'|'+text(m.mastery_content_id)+'|'+skill;if(skill==='grammar'&&m.pattern_id)return'pattern|'+text(m.pattern_id)+'|grammar';return text(a&&a.sourceType||'activity')+'|'+text(a&&a.sourceId||a&&a.id)+'|'+skill;}
function quotas(n){var out=[],base=Math.floor(TARGET/n),rem=TARGET%n;for(var i=0;i<n;i++)out.push(base+(i<rem?1:0));return out;}
function chooseForBook(rows,state,target,book){if(global.WillenaAdaptiveStudy&&global.WillenaAdaptiveStudy.chooseSession){return global.WillenaAdaptiveStudy.chooseSession(rows,state,{target:target,currentBookId:book.book_id,currentUnitId:book.currentUnit.id});}return shuffle(rows).slice(0,target);}
function interleave(groups){var out=[],work=groups.map(function(g){return g.slice();}),progress=true;while(out.length<TARGET&&progress){progress=false;for(var i=0;i<work.length&&out.length<TARGET;i++){if(work[i].length){out.push(work[i].shift());progress=true;}}}return out;}
function hydratePlan(ids){var seen={};return arr(ids).map(function(id){var a=poolById[id];if(!a||seen[id])return null;seen[id]=true;return a;}).filter(Boolean);}
function fillPlan(existing){var used={};existing.forEach(function(a){used[a.id]=true;});var extras=shuffle(pools.filter(function(a){return !used[a.id];}));while(existing.length<TARGET&&extras.length)existing.push(extras.shift());return existing.slice(0,TARGET);}
async function prepare(){var h=home();if(!h||!h.books.length)throw new Error('Assigned books are still loading.');var books=h.books.filter(function(b){return b&&b.book_id&&b.currentUnit&&b.currentUnit.id;}).slice(0,3);if(!books.length)throw new Error('No study books are ready.');var both=await Promise.all([Promise.all(books.map(loadBookPool)),adaptive()]),groups=both[0],state=both[1];pools=[].concat.apply([],groups);poolById={};pools.forEach(function(a){poolById[a.id]=a;});var usable=[],usableBooks=[];groups.forEach(function(g,i){if(g.length){usable.push(g);usableBooks.push(books[i]);}});if(!usable.length)throw new Error('No Daily Study questions are available yet.');var saved=readSession();if(saved&&Array.isArray(saved.planIds)){plan=fillPlan(hydratePlan(saved.planIds));session=saved;session.planIds=plan.map(function(a){return a.id;});session.index=Math.min(Number(session.index)||0,plan.length);session.attempts=session.attempts||{};saveSession();return;}
 var qs=quotas(usable.length),chosenGroups=[];usable.forEach(function(g,i){chosenGroups.push(chooseForBook(g,state,qs[i],usableBooks[i]));});plan=interleave(chosenGroups);plan=fillPlan(plan);session={version:1,date:dateKey(),target:TARGET,index:0,planIds:plan.map(function(a){return a.id;}),attempts:{},completedIds:[],startedAt:Date.now(),finishedAt:null};saveSession();}
function paint(){var s=readSession(),done=s?Math.min(TARGET,Number(s.index)||0):0,pct=Math.round(done/TARGET*100),ring=document.querySelector('#dailyWorkoutCard .progress-ring'),num=document.getElementById('smartDailyPct'),copy=document.getElementById('smartProgressCopy'),title=document.getElementById('smartProgressTitle');if(ring)ring.style.setProperty('--progress',pct);if(num)num.textContent=done>=TARGET?'✓':done+'/'+TARGET;if(title)title.textContent=langKo()?'오늘의 학습':'Daily Workout';if(copy)copy.textContent=done>=TARGET?(langKo()?'오늘 목표 완료 ✓':'Goal complete ✓'):(langKo()?'오늘의 맞춤 학습 · '+done+'/'+TARGET:'Adaptive daily study · '+done+'/'+TARGET);}
function sourceBadge(a){if(!root)return;var c=root.querySelector('.activity-card');if(!c)return;var old=c.querySelector('.activity-source-badge');if(old)old.remove();var b=document.createElement('div');b.className='activity-source-badge';var m=a.metadata||{};b.textContent=(m.daily_book_title||'Study')+' · Unit '+(m.daily_unit_number||'');c.insertBefore(b,c.firstChild);}
function setHeader(){if(skillEl)skillEl.textContent=langKo()?'오늘의 학습':'DAILY STUDY';if(titleEl)titleEl.textContent=langKo()?'맞춤 Daily Study':'Adaptive Daily Study';if(countEl)countEl.textContent=Math.min(TARGET,session.index+1)+' / '+TARGET;}
function show(){if(!session||session.index>=plan.length){finish();return;}current=plan[session.index];if(!current){finish();return;}answerLocked=false;document.body.classList.add('study-v2-practice-mode','study-v2-daily-mode');if(panel)panel.hidden=false;setHeader();if(!engine)engine=new global.WillenaActivityEngine(root,{onAnswer:function(){}});engine.setActivity(current);sourceBadge(current);if(panel)panel.scrollTop=0;}
function replaceCheck(label,handler){var check=root&&root.querySelector('.activity-check');if(!check)return;var b=check.cloneNode(true);b.disabled=false;b.textContent=label;check.replaceWith(b);b.addEventListener('click',handler,{once:true});}
function attemptCount(){return Number(session.attempts[current.id]||0);}
function setAttempt(n){session.attempts[current.id]=n;saveSession();}
function alternateFor(a){var key=masteryKey(a),future={};for(var i=session.index+1;i<plan.length;i++)future[plan[i].id]=true;var used={};for(var j=0;j<=session.index;j++)used[plan[j].id]=true;var candidates=pools.filter(function(x){return x.id!==a.id&&!used[x.id]&&!future[x.id]&&masteryKey(x)===key;});return shuffle(candidates)[0]||null;}
function scheduleRetest(a){var alt=alternateFor(a);if(!alt||session.index+2>=plan.length)return false;var replaceAt=Math.min(plan.length-1,session.index+4);plan[replaceAt]=alt;session.planIds=plan.map(function(x){return x.id;});saveSession();return true;}
function settle(wasWrong){if(wasWrong)scheduleRetest(current);if(session.completedIds.indexOf(current.id)<0)session.completedIds.push(current.id);session.index++;session.attempts[current.id]=0;if(session.index>=TARGET||session.index>=plan.length){session.finishedAt=Date.now();saveSession();paint();finish();return;}saveSession();paint();show();}
function onAnswer(e){if(!document.body.classList.contains('study-v2-daily-mode')||!current||answerLocked)return;var d=e.detail||{},a=d.activity||{},r=d.result||{};if(a.id!==current.id)return;answerLocked=true;var attempts=attemptCount()+1;setAttempt(attempts);if(r.correct){replaceCheck(session.index+1>=TARGET?(langKo()?'완료':'Done'):(langKo()?'다음':'Next'),function(){settle(attempts>1);});return;}if(attempts===1){replaceCheck(langKo()?'다시 해보기':'Try again',function(){answerLocked=false;engine.setActivity(current);sourceBadge(current);setHeader();});return;}replaceCheck(session.index+1>=TARGET?(langKo()?'완료':'Done'):(langKo()?'다음':'Next'),function(){settle(true);});}
function finish(){document.body.classList.add('study-v2-practice-mode','study-v2-daily-mode');if(panel)panel.hidden=false;if(countEl)countEl.textContent=langKo()?'완료':'Done';if(skillEl)skillEl.textContent=langKo()?'오늘의 학습':'DAILY STUDY';if(titleEl)titleEl.textContent=langKo()?'오늘 목표 완료':'Daily goal complete';if(root)root.innerHTML='<div class="smart-finish"><div class="smart-confetti">✓</div><h2>'+(langKo()?'잘했어요!':'Great work!')+'</h2><p>'+(langKo()?'오늘의 20문항을 모두 끝냈어요.':'You finished today’s 20 activities.')+'</p><button id="v2DailyHome" class="primary-button smart-home-button" type="button">'+(langKo()?'돌아가기':'Back to Study')+'</button></div>';var homeBtn=document.getElementById('v2DailyHome');if(homeBtn)homeBtn.addEventListener('click',close);paint();}
function close(){document.body.classList.remove('study-v2-practice-mode','study-v2-daily-mode');if(panel)panel.hidden=true;if(root)root.innerHTML='';current=null;engine=null;paint();window.scrollTo({top:0,behavior:'auto'});}
async function open(){if(loading)return;loading=true;try{await prepare();if(session.index>=TARGET){finish();}else show();}catch(e){console.warn('[StudyV2 Daily]',e);if(countEl)countEl.textContent=langKo()?'잠시 후 다시 시도하세요.':'Please try again shortly.';}finally{loading=false;}}
function bind(){if(card){card.addEventListener('click',open);card.addEventListener('keydown',function(e){if(e.key==='Enter'||e.key===' '){e.preventDefault();open();}});}document.addEventListener('click',function(e){var closeBtn=e.target&&e.target.closest&&e.target.closest('#v2PracticeClose');if(closeBtn&&document.body.classList.contains('study-v2-daily-mode')){e.preventDefault();e.stopImmediatePropagation();close();}},true);global.addEventListener('willena:activity-answer',onAnswer);global.addEventListener('willena:study-progress-updated',function(){setTimeout(paint,40);});[0,400,1200,2800].forEach(function(ms){setTimeout(paint,ms);});}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bind,{once:true});else bind();
global.WillenaStudyV2Daily={open:open,close:close,paint:paint,getSession:readSession};
})(window);
