(function(){
'use strict';
var CONTENT_URL='https://gxwfsqxyuufqtitspfqg.supabase.co';
var CONTENT_KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
var OP_URL='https://fiieuiktlsivwfgyivai.supabase.co';
var OP_KEY='sb_publishable_e-K50PquV9gHdfmefG6tmg_o-vVSl0e';
var CACHE_PREFIX='willena-study-v2-home:v1:';
var ACTIVE_BOOK_KEY='willena-study-v2-active-book';
var lang='ko';
var state={student:null,classInfo:null,books:[],activeIndex:0,adaptive:null,ready:false};
var SKILLS=['vocabulary','spelling','grammar','sentence_building','conversation','listening'];
var KO={vocabulary:'어휘',spelling:'철자',grammar:'문법',sentence_building:'문장 만들기',conversation:'회화',listening:'듣기'};
var EN={vocabulary:'Vocabulary',spelling:'Spelling',grammar:'Grammar',sentence_building:'Sentence Builder',conversation:'Conversation',listening:'Listening'};
function txt(v){return String(v==null?'':v).trim();}
function uid(){try{return txt(localStorage.getItem('user_id')||sessionStorage.getItem('user_id')||localStorage.getItem('userId')||sessionStorage.getItem('userId'));}catch(_){return'';}}
function cacheKey(){return CACHE_PREFIX+uid();}
function saveCache(){try{if(!uid()||!state.books.length)return;localStorage.setItem(cacheKey(),JSON.stringify({t:Date.now(),books:state.books,activeBookId:activeBook()&&activeBook().book_id}));}catch(_){}}
function readCache(){try{var raw=localStorage.getItem(cacheKey());if(!raw)return null;var o=JSON.parse(raw);if(!o||!o.t||Date.now()-o.t>7*24*60*60*1000||!Array.isArray(o.books))return null;return o;}catch(_){return null;}}
function activeBook(){return state.books[state.activeIndex]||null;}
function setActiveFromId(id){var i=state.books.findIndex(function(b){return String(b.book_id)===String(id);});state.activeIndex=i>=0?i:0;}
async function api(url,opts){var r=await (window.WillenaAPI?WillenaAPI.fetch:fetch)(url,Object.assign({credentials:'include',cache:'no-store'},opts||{}));var d=await r.json().catch(function(){return{}});if(!r.ok||d&&d.success===false)throw new Error(d.error||('Request failed ('+r.status+').'));return d;}
async function profile(){return api('/.netlify/functions/progress_summary?section=my_progress&_='+Date.now());}
async function assignments(className){var r=await fetch(OP_URL+'/rest/v1/rpc/get_study_assignment_for_class',{method:'POST',headers:{apikey:OP_KEY,Authorization:'Bearer '+OP_KEY,'Content-Type':'application/json'},body:JSON.stringify({p_class_name:className}),cache:'no-store'});var d=await r.json().catch(function(){return{}});if(!r.ok||!d.success)throw new Error(d.error||'Could not load assigned books.');return d;}
async function content(path){var r=await fetch(CONTENT_URL+'/rest/v1/'+path,{headers:{apikey:CONTENT_KEY,Authorization:'Bearer '+CONTENT_KEY},cache:'no-store'});if(!r.ok)throw new Error('Content DB '+r.status);return r.json();}
async function getProgress(bookId,unitId){var q='/.netlify/functions/progress_summary?section=study_progress&_='+Date.now()+'&book_id='+encodeURIComponent(bookId)+'&unit_id='+encodeURIComponent(unitId);return api(q);}
async function getAdaptive(){return api('/.netlify/functions/progress_summary?section=adaptive_state&_='+Date.now());}
function resolveUnit(rows,a){if(!rows.length)return null;var saved='';try{saved=localStorage.getItem('willena-study-v2-unit:'+a.book_id)||'';}catch(_){}var hint=saved||a.current_unit||a.starting_unit||'';var n=(String(hint).match(/\d+/)||[])[0];return rows.find(function(u){return String(u.id)===String(hint)||String(u.unit_number)===String(n);})||rows[0];}
function masteryMap(progress){var rows=Array.isArray(progress&&progress.skill_summary)?progress.skill_summary:(Array.isArray(progress&&progress.unit_skills)?progress.unit_skills:[]),m={};rows.forEach(function(r){m[r.skill]=Math.max(0,Math.min(100,Math.round(Number(r.mastery_score)||0)));});return m;}
function dailyPct(progress){var m=masteryMap(progress),vals=SKILLS.map(function(k){return Number(m[k]);}).filter(function(v){return isFinite(v);});if(!vals.length)return 0;return Math.round(vals.reduce(function(a,b){return a+b;},0)/vals.length);}
function recoverable(x){return x&&Number(x.lapses||0)>0&&Number(x.mastery_score||0)<80;}
function recommendations(book){var adaptive=state.adaptive&&state.adaptive.items||[],unit=book.currentUnit,out=[],groups={};adaptive.forEach(function(x){if(String(x.book_id)!==String(book.book_id)||String(x.unit_id)!==String(unit.id)||!recoverable(x))return;(groups[x.skill]||(groups[x.skill]=[])).push(x);});Object.keys(groups).sort(function(a,b){return groups[b].length-groups[a].length;}).slice(0,2).forEach(function(skill){out.push({type:'mistakes',skill:skill,count:groups[skill].length});});var due=adaptive.filter(function(x){return String(x.book_id)===String(book.book_id)&&String(x.unit_id)===String(unit.id)&&x.due&&Number(x.lapses||0)===0;});if(out.length<3&&due.length)out.push({type:'due',count:due.length});var vm=masteryMap(book.progress).vocabulary||0,next=book.units.find(function(u){return Number(u.unit_number)===Number(unit.unit_number)+1;});if(out.length<3&&vm>=80&&next)out.push({type:'preview',unit:Number(next.unit_number)});if(!out.length)out.push({type:'fresh'});return out.slice(0,3);}
async function loadBook(a){var units=await content('content_units?select=id,unit_number,title,metadata&book_id=eq.'+encodeURIComponent(a.book_id)+'&status=in.(review,published)&order=unit_number.asc');var current=resolveUnit(units,a);var progress=current?await getProgress(a.book_id,current.id):{};return Object.assign({},a,{units:units,currentUnit:current,progress:progress});}
function renderTabs(){var tabs=document.getElementById('bookTabs'),pips=document.getElementById('bookPips');if(!tabs||!pips)return;var multi=state.books.length>1;tabs.hidden=!multi;pips.hidden=!multi;if(!multi){tabs.innerHTML='';pips.innerHTML='';return;}tabs.innerHTML=state.books.map(function(b,i){return '<button class="study-v2-book-tab'+(i===state.activeIndex?' is-active':'')+'" type="button" data-book-index="'+i+'">'+escapeHtml(b.book_title)+'</button>';}).join('');pips.innerHTML=state.books.map(function(b,i){return '<button class="study-v2-book-pip'+(i===state.activeIndex?' is-active':'')+'" type="button" data-book-index="'+i+'" aria-label="'+escapeHtml(b.book_title)+'"></button>';}).join('');tabs.querySelectorAll('[data-book-index]').forEach(bindBookButton);pips.querySelectorAll('[data-book-index]').forEach(bindBookButton);}
function bindBookButton(b){b.addEventListener('click',function(){switchBook(Number(b.dataset.bookIndex));});}
function escapeHtml(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c];});}
function renderUnits(book){var strip=document.getElementById('unitStrip'),cur=document.getElementById('currentUnitLabel');if(!strip||!cur)return;cur.textContent=(lang==='ko'?'현재 · Unit ':'Current · Unit ')+(book.currentUnit?book.currentUnit.unit_number:'—');strip.innerHTML=book.units.map(function(u){return '<button class="study-v2-unit'+(book.currentUnit&&String(book.currentUnit.id)===String(u.id)?' is-current':'')+'" type="button" data-unit-id="'+escapeHtml(u.id)+'">Unit '+escapeHtml(u.unit_number)+'</button>';}).join('');strip.querySelectorAll('[data-unit-id]').forEach(function(b){b.addEventListener('click',function(){selectUnit(b.dataset.unitId);});});}
function renderMastery(book){var map=masteryMap(book.progress);document.querySelectorAll('#headerSkillMastery [data-skill]').forEach(function(card){var skill=card.dataset.skill,v=map[skill]||0,p=card.querySelector('.header-skill-master-pct'),f=card.querySelector('.header-skill-master-fill'),label=card.querySelector('strong');card.classList.remove('is-loading');if(label)label.textContent=(lang==='ko'?KO:EN)[skill];if(p)p.textContent=v+'%';if(f)f.style.width=v+'%';card.classList.toggle('is-complete',v>=80);});var h=document.querySelector('#headerSkillMastery .header-skill-mastery-head strong'),s=document.querySelector('#headerSkillMastery .header-skill-mastery-head span');if(h)h.textContent=lang==='ko'?'단원 숙련도':'Unit mastery';if(s)s.textContent=lang==='ko'?'영역을 눌러 연습하세요':'Tap a skill to practice';}
function renderDaily(book){var pct=dailyPct(book.progress),ring=document.querySelector('#dailyWorkoutCard .progress-ring'),num=document.getElementById('smartDailyPct'),title=document.getElementById('smartProgressTitle'),copy=document.getElementById('smartProgressCopy');if(num)num.textContent=pct+'%';if(ring)ring.style.setProperty('--progress',pct);if(title)title.textContent=lang==='ko'?'오늘의 학습':'Daily Workout';if(copy)copy.textContent=lang==='ko'?'오늘 목표 12문항 · 맞춤 복습':'12 questions · adaptive review';}
function recText(r){if(lang==='en'){if(r.type==='mistakes')return['One more try','Practice '+(EN[r.skill]||r.skill)+' again',r.count+' item'+(r.count===1?'':'s')+' will benefit from another go.','Practice again →'];if(r.type==='due')return['Review time','A quick review will help',r.count+' learned item'+(r.count===1?' is':'s are')+' ready to review.','Start review →'];if(r.type==='preview')return['New words','Take a peek at Unit '+r.unit,'You are doing well here, so you can look ahead a little.','Preview →'];return['Today’s review','Keep it fresh','A short review now will help this unit stick.','Start review →'];}if(r.type==='mistakes')return['한 번 더',(KO[r.skill]||r.skill)+' 다시 도전하기',r.count+'개 내용을 한 번 더 풀어 보면 훨씬 익숙해질 거예요.','다시 해보기 →'];if(r.type==='due')return['오늘의 복습','지금 복습하면 딱 좋아요',r.count+'개 내용이 지금 다시 보면 좋은 타이밍이에요.','복습 시작 →'];if(r.type==='preview')return['새로운 단어','Unit '+r.unit+' 단어 살짝 보기','지금 잘하고 있어요. 다음 단원에서 만날 단어를 먼저 구경해 볼까요?','미리 보기 →'];return['오늘의 복습','오늘 배운 것 다시 보기','오늘 배운 내용을 짧게 다시 보면 기억에 더 오래 남아요.','복습 시작 →'];}
function renderAi(book){var head=document.getElementById('aiHeading'),grid=document.getElementById('aiGrid');if(head)head.textContent=lang==='ko'?'AI 추천':'AI Recommends';if(!grid)return;grid.innerHTML=recommendations(book).map(function(r){var t=recText(r);return '<button class="study-coach-card" type="button"><span class="coach-kicker">'+escapeHtml(t[0])+'</span><strong>'+escapeHtml(t[1])+'</strong><small>'+escapeHtml(t[2])+'</small><span class="coach-action">'+escapeHtml(t[3])+'</span></button>';}).join('');}
function renderBook(){var b=activeBook();if(!b||!b.currentUnit)return;document.getElementById('bookTitle').textContent=b.book_title;document.getElementById('unitTitle').textContent='Unit '+b.currentUnit.unit_number+' · '+(b.currentUnit.title||'');renderTabs();renderUnits(b);renderMastery(b);renderDaily(b);renderAi(b);try{localStorage.setItem(ACTIVE_BOOK_KEY,b.book_id);}catch(_){}saveCache();}
function switchBook(next){if(!state.ready||state.books.length<=1||next===state.activeIndex||next<0||next>=state.books.length)return;var wrap=document.getElementById('bookSwipe'),dir=next>state.activeIndex?1:-1;if(!wrap){state.activeIndex=next;renderBook();return;}wrap.classList.add(dir>0?'is-left':'is-right');setTimeout(function(){state.activeIndex=next;renderBook();wrap.style.transition='none';wrap.classList.remove('is-left','is-right');wrap.style.transform=dir>0?'translateX(24px)':'translateX(-24px)';wrap.style.opacity='0';requestAnimationFrame(function(){requestAnimationFrame(function(){wrap.style.transition='';wrap.style.transform='';wrap.style.opacity='';});});},160);}
async function selectUnit(id){var b=activeBook(),u=b&&b.units.find(function(x){return String(x.id)===String(id);});if(!b||!u||String(u.id)===String(b.currentUnit&&b.currentUnit.id))return;b.currentUnit=u;try{localStorage.setItem('willena-study-v2-unit:'+b.book_id,u.id);}catch(_){}document.querySelectorAll('#headerSkillMastery [data-skill]').forEach(function(c){c.classList.add('is-loading');});renderUnits(b);document.getElementById('unitTitle').textContent='Unit '+u.unit_number+' · '+(u.title||'');try{b.progress=await getProgress(b.book_id,u.id);}catch(_){b.progress={};}renderMastery(b);renderDaily(b);renderAi(b);saveCache();}
function bindSwipe(){var w=document.getElementById('bookSwipe');if(!w)return;var sx=0,sy=0;w.addEventListener('touchstart',function(e){if(state.books.length<=1||!e.touches[0])return;sx=e.touches[0].clientX;sy=e.touches[0].clientY;},{passive:true});w.addEventListener('touchend',function(e){if(state.books.length<=1||!e.changedTouches[0])return;var dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)<45||Math.abs(dx)<Math.abs(dy))return;var next=dx<0?state.activeIndex+1:state.activeIndex-1;if(next<0)next=state.books.length-1;if(next>=state.books.length)next=0;switchBook(next);},{passive:true});}
function bindUi(){var l=document.getElementById('languageBtn');if(l)l.addEventListener('click',function(){lang=lang==='ko'?'en':'ko';l.textContent=lang==='ko'?'English':'한국어';renderBook();});var ai=document.getElementById('practiceHeroBtn');if(ai)ai.addEventListener('click',function(){var s=document.getElementById('aiRecommendations');if(s)s.scrollIntoView({behavior:'smooth',block:'start'});});bindSwipe();}
function hydrateCache(){var c=readCache();if(!c||!c.books.length)return false;state.books=c.books;setActiveFromId(c.activeBookId);state.ready=true;renderBook();return true;}
async function init(){hydrateCache();try{var me=await profile();var className=txt(me.class);if(!className)throw new Error('No active class is assigned.');state.student={id:me.user_id||null,name:me.name||null};var a=await assignments(className);state.classInfo=a.class;var list=Array.isArray(a.assignments)&&a.assignments.length?a.assignments:(a.assignment?[a.assignment]:[]);if(!list.length)throw new Error('No active book is assigned.');var adaptivePromise=getAdaptive().catch(function(){return{items:[]};});var booksPromise=Promise.all(list.slice(0,3).map(loadBook));var both=await Promise.all([booksPromise,adaptivePromise]);state.books=both[0];state.adaptive=both[1];var wanted='';try{wanted=localStorage.getItem(ACTIVE_BOOK_KEY)||'';}catch(_){}setActiveFromId(wanted||a.assignment&&a.assignment.book_id);state.ready=true;renderBook();saveCache();}catch(e){console.error('[StudyV2]',e);var title=document.getElementById('bookTitle'),unit=document.getElementById('unitTitle');if(!state.books.length&&title)title.textContent='Could not load study content';if(!state.books.length&&unit)unit.textContent=e.message||'Please try again.';}}
bindUi();init();
})();
