(function(){
'use strict';
var CONTENT_URL='https://gxwfsqxyuufqtitspfqg.supabase.co';
var CONTENT_KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
var OP_URL='https://fiieuiktlsivwfgyivai.supabase.co';
var OP_KEY='sb_publishable_e-K50PquV9gHdfmefG6tmg_o-vVSl0e';
var CACHE_PREFIX='willena-study-v2-home:v1:';
var ACTIVE_BOOK_KEY='willena-study-v2-active-book';
var ALL_SKILLS=['vocabulary','spelling','grammar','sentence_building','conversation','listening','reading','speaking','writing'];
var RUNNABLE_SKILLS=['vocabulary','spelling','grammar','sentence_building','conversation','listening','reading'];
var KO={vocabulary:'어휘',spelling:'철자',grammar:'문법',sentence_building:'문장 만들기',conversation:'회화',listening:'듣기',reading:'읽기',speaking:'말하기',writing:'쓰기'};
var EN={vocabulary:'Vocabulary',spelling:'Spelling',grammar:'Grammar',sentence_building:'Sentence Builder',conversation:'Conversation',listening:'Listening',reading:'Reading',speaking:'Speaking',writing:'Writing'};
var lang='ko';
var state={student:null,classInfo:null,books:[],activeIndex:0,adaptive:null,ready:false};
var practice={engine:null,book:null,unit:null,skill:null,items:[],index:0,answered:false};
function txt(v){return String(v==null?'':v).trim();}
function arr(v){return Array.isArray(v)?v:[];}
function uid(){try{return txt(localStorage.getItem('user_id')||sessionStorage.getItem('user_id')||localStorage.getItem('userId')||sessionStorage.getItem('userId'));}catch(_){return'';}}
function cacheKey(){return CACHE_PREFIX+uid();}
function cacheSafeBook(b){var copy={};Object.keys(b||{}).forEach(function(k){if(k!=='practiceBank')copy[k]=b[k];});return copy;}
function saveCache(){try{if(!uid()||!state.books.length)return;localStorage.setItem(cacheKey(),JSON.stringify({t:Date.now(),books:state.books.map(cacheSafeBook),activeBookId:activeBook()&&activeBook().book_id}));}catch(_){}}
function readCache(){try{var raw=localStorage.getItem(cacheKey());if(!raw)return null;var o=JSON.parse(raw);if(!o||!o.t||Date.now()-o.t>7*24*60*60*1000||!Array.isArray(o.books))return null;return o;}catch(_){return null;}}
function activeBook(){return state.books[state.activeIndex]||null;}
function setActiveFromId(id){var i=state.books.findIndex(function(b){return String(b.book_id)===String(id);});state.activeIndex=i>=0?i:0;}
function escapeHtml(v){return String(v==null?'':v).replace(/[&<>"']/g,function(c){return{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c];});}
function shuffle(items){return items.slice().sort(function(){return Math.random()-.5;});}
function unique(items){var out=[];items.forEach(function(x){var v=txt(x);if(v&&out.indexOf(v)<0)out.push(v);});return out;}
async function api(url,opts){var r=await (window.WillenaAPI?WillenaAPI.fetch:fetch)(url,Object.assign({credentials:'include',cache:'no-store'},opts||{}));var d=await r.json().catch(function(){return{}});if(!r.ok||d&&d.success===false)throw new Error(d.error||('Request failed ('+r.status+').'));return d;}
async function profile(){return api('/.netlify/functions/progress_summary?section=my_progress&_='+Date.now());}
async function assignments(className){var r=await fetch(OP_URL+'/rest/v1/rpc/get_study_assignment_for_class',{method:'POST',headers:{apikey:OP_KEY,Authorization:'Bearer '+OP_KEY,'Content-Type':'application/json'},body:JSON.stringify({p_class_name:className}),cache:'no-store'});var d=await r.json().catch(function(){return{}});if(!r.ok||!d.success)throw new Error(d.error||'Could not load assigned books.');return d;}
async function content(path){var r=await fetch(CONTENT_URL+'/rest/v1/'+path,{headers:{apikey:CONTENT_KEY,Authorization:'Bearer '+CONTENT_KEY},cache:'no-store'});if(!r.ok)throw new Error('Content DB '+r.status);return r.json();}
async function getProgress(bookId,unitId){var q='/.netlify/functions/progress_summary?section=study_progress&_='+Date.now()+'&book_id='+encodeURIComponent(bookId)+'&unit_id='+encodeURIComponent(unitId);return api(q);}
async function getAdaptive(){return api('/.netlify/functions/progress_summary?section=adaptive_state&_='+Date.now());}
function resolveUnit(rows,a){if(!rows.length)return null;var saved='';try{saved=localStorage.getItem('willena-study-v2-unit:'+a.book_id)||'';}catch(_){}var hint=saved||a.current_unit||a.starting_unit||'';var n=(String(hint).match(/\d+/)||[])[0];return rows.find(function(u){return String(u.id)===String(hint)||String(u.unit_number)===String(n);})||rows[0];}
function masteryMap(progress){var rows=Array.isArray(progress&&progress.skill_summary)?progress.skill_summary:(Array.isArray(progress&&progress.unit_skills)?progress.unit_skills:[]),m={};rows.forEach(function(r){m[r.skill]=Math.max(0,Math.min(100,Math.round(Number(r.mastery_score)||0)));});return m;}
function declaredSkills(book){var meta=book&&book.currentUnit&&book.currentUnit.metadata||{},cfg=meta.study_practice||{},modes=Array.isArray(cfg.modes)?cfg.modes:[];return modes.filter(function(k){return RUNNABLE_SKILLS.indexOf(k)>=0;});}
function availableSkills(book){if(book&&Array.isArray(book.availableSkills)&&book.availableSkills.length)return book.availableSkills.slice();var declared=declaredSkills(book);if(declared.length)return declared;var map=masteryMap(book&&book.progress),fromProgress=RUNNABLE_SKILLS.filter(function(k){return Object.prototype.hasOwnProperty.call(map,k);});if(fromProgress.length)return fromProgress;return RUNNABLE_SKILLS.slice();}
function dailyPct(book){var m=masteryMap(book&&book.progress),skills=availableSkills(book),vals=skills.map(function(k){return Number(m[k]);}).filter(function(v){return isFinite(v);});if(!vals.length)return 0;return Math.round(vals.reduce(function(a,b){return a+b;},0)/vals.length);}
function recoverable(x){return x&&Number(x.lapses||0)>0&&Number(x.mastery_score||0)<80;}
function recommendations(book){var adaptive=state.adaptive&&state.adaptive.items||[],unit=book.currentUnit,out=[],groups={};adaptive.forEach(function(x){if(String(x.book_id)!==String(book.book_id)||String(x.unit_id)!==String(unit.id)||!recoverable(x))return;(groups[x.skill]||(groups[x.skill]=[])).push(x);});Object.keys(groups).sort(function(a,b){return groups[b].length-groups[a].length;}).slice(0,2).forEach(function(skill){out.push({type:'mistakes',skill:skill,count:groups[skill].length});});var due=adaptive.filter(function(x){return String(x.book_id)===String(book.book_id)&&String(x.unit_id)===String(unit.id)&&x.due&&Number(x.lapses||0)===0;});if(out.length<3&&due.length)out.push({type:'due',count:due.length});var vm=masteryMap(book.progress).vocabulary||0,next=book.units.find(function(u){return Number(u.unit_number)===Number(unit.unit_number)+1;});if(out.length<3&&vm>=80&&next)out.push({type:'preview',unit:Number(next.unit_number)});if(!out.length)out.push({type:'fresh'});return out.slice(0,3);}
function groupBank(rows){var by={};arr(rows).forEach(function(a){if(!a||!a.skill)return;(by[a.skill]||(by[a.skill]=[])).push(a);});return by;}
async function loadSourceVocabulary(unitId){var occ=await content('source_content_occurrences?select=id,lexical_entry_id,source_text&unit_id=eq.'+encodeURIComponent(unitId)+'&occurrence_type=eq.lexical_entry&status=in.(review,published)');var ids=unique(occ.map(function(o){return o.lexical_entry_id;}));if(!ids.length)return[];var rows=await content('lexical_entries?select=id,canonical_text,translation_ko,emoji&id=in.'+encodeURIComponent('('+ids.join(',')+')')+'&status=in.(review,published)');var by={};rows.forEach(function(r){by[r.id]=r;});return occ.map(function(o){var e=by[o.lexical_entry_id];if(!e)return null;return{id:e.id,occurrenceId:o.id,word:txt(e.canonical_text||o.source_text),ko:txt(e.translation_ko),emoji:e.emoji||null};}).filter(function(x){return x&&x.word&&x.ko;});}
function sourceVocabularyActivities(book,unit,items){var out=[],koPool=unique(items.map(function(x){return x.ko;})),enPool=unique(items.map(function(x){return x.word;}));items.forEach(function(item){var koChoices=shuffle(unique([item.ko].concat(shuffle(koPool.filter(function(x){return x!==item.ko;})).slice(0,3))));if(koChoices.length>=2)out.push({id:'v2-vocab-en-ko-'+item.occurrenceId,sourceType:'lexical_entry',sourceId:item.id,skill:'vocabulary',usage:['practice'],stimulus:{type:'text',prompt:(item.emoji?item.emoji+'  ':'')+item.word,context:'한국어 뜻을 고르세요.'},response:{type:'multiple_choice',choices:koChoices},answer:item.ko,metadata:{book_id:book.book_id,unit_id:unit.id,occurrence_id:item.occurrenceId,pool_source:'source_content',source_label:'Book vocabulary'}});var enChoices=shuffle(unique([item.word].concat(shuffle(enPool.filter(function(x){return x!==item.word;})).slice(0,3))));if(enChoices.length>=2)out.push({id:'v2-vocab-ko-en-'+item.occurrenceId,sourceType:'lexical_entry',sourceId:item.id,skill:'vocabulary',usage:['practice'],stimulus:{type:'text',prompt:item.ko,context:'알맞은 영어 표현을 고르세요.'},response:{type:'multiple_choice',choices:enChoices},answer:item.word,metadata:{book_id:book.book_id,unit_id:unit.id,occurrence_id:item.occurrenceId,pool_source:'source_content',source_label:'Book vocabulary'}});var letters=item.word.toLowerCase().replace(/[^a-z]/g,'').split('');if(letters.length>=2)out.push({id:'v2-spelling-'+item.occurrenceId,sourceType:'lexical_entry',sourceId:item.id,skill:'spelling',usage:['practice'],stimulus:{type:'text',prompt:item.ko,context:'글자를 눌러 영어 단어를 만드세요.'},response:{type:'letter_order',tokens:letters,wordLengths:[letters.length]},answer:item.word.toLowerCase().replace(/[^a-z]/g,''),metadata:{book_id:book.book_id,unit_id:unit.id,occurrence_id:item.occurrenceId,pool_source:'source_content',source_label:'Book vocabulary'}});});return out;}
async function loadPracticeBank(book,unit){if(!unit)return{unitId:null,bySkill:{},availableSkills:[]};var authoredPromise=(window.WillenaStudyQuestionBank?WillenaStudyQuestionBank.loadUnit(null,{bookId:book.book_id,unitId:unit.id,bookTitle:book.book_title,unitNumber:Number(unit.unit_number)}):Promise.resolve([])).catch(function(e){console.warn('[StudyV2] authored bank',e);return[];});var vocabPromise=loadSourceVocabulary(unit.id).catch(function(e){console.warn('[StudyV2] source vocabulary',e);return[];});var both=await Promise.all([authoredPromise,vocabPromise]),by=groupBank(both[0]),generated=sourceVocabularyActivities(book,unit,both[1]);generated.forEach(function(a){(by[a.skill]||(by[a.skill]=[])).push(a);});var skills=ALL_SKILLS.filter(function(k){return by[k]&&by[k].length;});return{unitId:unit.id,bySkill:by,availableSkills:skills};}
async function loadBook(a){var units=await content('content_units?select=id,unit_number,title,metadata&book_id=eq.'+encodeURIComponent(a.book_id)+'&status=in.(review,published)&order=unit_number.asc');var current=resolveUnit(units,a),base=Object.assign({},a,{units:units,currentUnit:current,progress:{},practiceBank:null,availableSkills:[]});if(!current)return base;var both=await Promise.all([getProgress(a.book_id,current.id).catch(function(){return{};}),loadPracticeBank(base,current)]);base.progress=both[0];base.practiceBank=both[1];base.availableSkills=both[1].availableSkills;return base;}
function renderTabs(){var tabs=document.getElementById('bookTabs'),pips=document.getElementById('bookPips');if(!tabs||!pips)return;var multi=state.books.length>1;tabs.hidden=!multi;pips.hidden=!multi;if(!multi){tabs.innerHTML='';pips.innerHTML='';return;}tabs.innerHTML=state.books.map(function(b,i){return '<button class="study-v2-book-tab'+(i===state.activeIndex?' is-active':'')+'" type="button" data-book-index="'+i+'">'+escapeHtml(b.book_title)+'</button>';}).join('');pips.innerHTML=state.books.map(function(b,i){return '<button class="study-v2-book-pip'+(i===state.activeIndex?' is-active':'')+'" type="button" data-book-index="'+i+'" aria-label="'+escapeHtml(b.book_title)+'"></button>';}).join('');tabs.querySelectorAll('[data-book-index]').forEach(bindBookButton);pips.querySelectorAll('[data-book-index]').forEach(bindBookButton);}
function bindBookButton(b){b.addEventListener('click',function(){switchBook(Number(b.dataset.bookIndex));});}
function renderUnits(book){var strip=document.getElementById('unitStrip'),cur=document.getElementById('currentUnitLabel');if(!strip||!cur)return;cur.textContent=(lang==='ko'?'현재 · Unit ':'Current · Unit ')+(book.currentUnit?book.currentUnit.unit_number:'—');strip.innerHTML=book.units.map(function(u){return '<button class="study-v2-unit'+(book.currentUnit&&String(book.currentUnit.id)===String(u.id)?' is-current':'')+'" type="button" data-unit-id="'+escapeHtml(u.id)+'">Unit '+escapeHtml(u.unit_number)+'</button>';}).join('');strip.querySelectorAll('[data-unit-id]').forEach(function(b){b.addEventListener('click',function(){selectUnit(b.dataset.unitId);});});}
function masteryCard(skill,value){var label=(lang==='ko'?KO:EN)[skill]||skill;return '<button class="header-skill-master" type="button" data-skill="'+escapeHtml(skill)+'"><div class="header-skill-master-top"><strong>'+escapeHtml(label)+'</strong><span class="header-skill-master-pct">'+value+'%</span></div><div class="header-skill-master-track"><i class="header-skill-master-fill" style="width:'+value+'%"></i></div></button>';}
function renderMastery(book){var grid=document.getElementById('masteryGrid'),map=masteryMap(book.progress),skills=availableSkills(book);if(grid){grid.innerHTML=skills.map(function(skill){return masteryCard(skill,map[skill]||0);}).join('');grid.querySelectorAll('[data-skill]').forEach(function(card){var skill=card.dataset.skill;if(RUNNABLE_SKILLS.indexOf(skill)>=0)card.addEventListener('click',function(){openPractice(skill);});});}var h=document.querySelector('#headerSkillMastery .header-skill-mastery-head strong'),s=document.querySelector('#headerSkillMastery .header-skill-mastery-head span');if(h)h.textContent=lang==='ko'?'단원 숙련도':'Unit mastery';if(s)s.textContent=lang==='ko'?'영역을 눌러 연습하세요':'Tap a skill to practice';}
function renderDaily(book){var pct=dailyPct(book),ring=document.querySelector('#dailyWorkoutCard .progress-ring'),num=document.getElementById('smartDailyPct'),title=document.getElementById('smartProgressTitle'),copy=document.getElementById('smartProgressCopy');if(num)num.textContent=pct+'%';if(ring)ring.style.setProperty('--progress',pct);if(title)title.textContent=lang==='ko'?'오늘의 학습':'Daily Workout';if(copy)copy.textContent=lang==='ko'?'오늘 목표 20문항 · 맞춤 복습':'20 questions · adaptive review';}
function recText(r){if(lang==='en'){if(r.type==='mistakes')return['One more try','Practice '+(EN[r.skill]||r.skill)+' again',r.count+' item'+(r.count===1?'':'s')+' will benefit from another go.','Practice again →'];if(r.type==='due')return['Review time','A quick review will help',r.count+' learned item'+(r.count===1?' is':'s are')+' ready to review.','Start review →'];if(r.type==='preview')return['New words','Take a peek at Unit '+r.unit,'You are doing well here, so you can look ahead a little.','Preview →'];return['Today’s review','Keep it fresh','A short review now will help this unit stick.','Start review →'];}if(r.type==='mistakes')return['한 번 더',(KO[r.skill]||r.skill)+' 다시 도전하기',r.count+'개 내용을 한 번 더 풀어 보면 훨씬 익숙해질 거예요.','다시 해보기 →'];if(r.type==='due')return['오늘의 복습','지금 복습하면 딱 좋아요',r.count+'개 내용이 지금 다시 보면 좋은 타이밍이에요.','복습 시작 →'];if(r.type==='preview')return['새로운 단어','Unit '+r.unit+' 단어 살짝 보기','지금 잘하고 있어요. 다음 단원에서 만날 단어를 먼저 구경해 볼까요?','미리 보기 →'];return['오늘의 복습','오늘 배운 것 다시 보기','오늘 배운 내용을 짧게 다시 보면 기억에 더 오래 남아요.','복습 시작 →'];}
function renderAi(book){var head=document.getElementById('aiHeading'),grid=document.getElementById('aiGrid');if(head)head.textContent=lang==='ko'?'AI 추천':'AI Recommends';if(!grid)return;grid.innerHTML=recommendations(book).map(function(r){var t=recText(r);return '<button class="study-coach-card" type="button"><span class="coach-kicker">'+escapeHtml(t[0])+'</span><strong>'+escapeHtml(t[1])+'</strong><small>'+escapeHtml(t[2])+'</small><span class="coach-action">'+escapeHtml(t[3])+'</span></button>';}).join('');}
function renderBook(){var b=activeBook();if(!b||!b.currentUnit)return;document.getElementById('bookTitle').textContent=b.book_title;document.getElementById('unitTitle').textContent='Unit '+b.currentUnit.unit_number+' · '+(b.currentUnit.title||'');renderTabs();renderUnits(b);renderMastery(b);renderDaily(b);renderAi(b);try{localStorage.setItem(ACTIVE_BOOK_KEY,b.book_id);}catch(_){}saveCache();}
function switchBook(next){if(!state.ready||state.books.length<=1||next===state.activeIndex||next<0||next>=state.books.length)return;var wrap=document.getElementById('bookSwipe'),dir=next>state.activeIndex?1:-1;if(!wrap){state.activeIndex=next;renderBook();return;}wrap.classList.add(dir>0?'is-left':'is-right');setTimeout(function(){state.activeIndex=next;renderBook();wrap.style.transition='none';wrap.classList.remove('is-left','is-right');wrap.style.transform=dir>0?'translateX(24px)':'translateX(-24px)';wrap.style.opacity='0';requestAnimationFrame(function(){requestAnimationFrame(function(){wrap.style.transition='';wrap.style.transform='';wrap.style.opacity='';});});},160);}
async function selectUnit(id){var b=activeBook(),u=b&&b.units.find(function(x){return String(x.id)===String(id);});if(!b||!u||String(u.id)===String(b.currentUnit&&b.currentUnit.id))return;b.currentUnit=u;b.availableSkills=[];b.practiceBank=null;try{localStorage.setItem('willena-study-v2-unit:'+b.book_id,u.id);}catch(_){}renderUnits(b);document.getElementById('unitTitle').textContent='Unit '+u.unit_number+' · '+(u.title||'');renderMastery(b);try{var both=await Promise.all([getProgress(b.book_id,u.id).catch(function(){return{};}),loadPracticeBank(b,u)]);if(String(b.currentUnit.id)!==String(u.id))return;b.progress=both[0];b.practiceBank=both[1];b.availableSkills=both[1].availableSkills;renderMastery(b);renderDaily(b);renderAi(b);saveCache();}catch(e){console.warn('[StudyV2] unit preload',e);}}
function practiceItems(book,skill){var bank=book&&book.practiceBank;if(!bank||String(bank.unitId)!==String(book.currentUnit&&book.currentUnit.id))return[];return arr(bank.bySkill&&bank.bySkill[skill]);}
function ensureEngine(){if(practice.engine)return practice.engine;var root=document.getElementById('v2ActivityRoot');if(!root||!window.WillenaActivityEngine)throw new Error('Practice engine is not ready.');practice.engine=new WillenaActivityEngine(root,{onAnswer:function(){practice.answered=true;var next=document.getElementById('v2PracticeNext');if(next)next.disabled=false;}});return practice.engine;}
function showPracticeItem(){var item=practice.items[practice.index];if(!item)return closePractice();practice.answered=false;var next=document.getElementById('v2PracticeNext');if(next){next.disabled=true;next.textContent=lang==='ko'?'다음':'Next';}ensureEngine().setActivity(item);}
function openPractice(skill){var b=activeBook(),items=practiceItems(b,skill);if(!b||!b.currentUnit||!items.length)return;var t0=(performance&&performance.now)?performance.now():Date.now();practice.book=b;practice.unit=b.currentUnit;practice.skill=skill;practice.items=shuffle(items).slice(0,10);practice.index=0;var label=(lang==='ko'?KO:EN)[skill]||skill,title=document.getElementById('v2PracticeTitle'),eyebrow=document.getElementById('v2PracticeSkill'),perf=document.getElementById('practicePerf');if(title)title.textContent=b.book_title+' · Unit '+b.currentUnit.unit_number;if(eyebrow)eyebrow.textContent=label;if(perf)perf.textContent='';document.body.classList.add('study-v2-practice-mode');var panel=document.getElementById('v2PracticePanel');if(panel)panel.hidden=false;showPracticeItem();requestAnimationFrame(function(){var ms=Math.round(((performance&&performance.now)?performance.now():Date.now())-t0);if(perf)perf.textContent=(lang==='ko'?'준비 ':'Ready ')+ms+'ms';});window.scrollTo({top:0,behavior:'auto'});}
function nextPractice(){if(!practice.answered)return;practice.index++;if(practice.index>=practice.items.length)return closePractice();showPracticeItem();}
function closePractice(){document.body.classList.remove('study-v2-practice-mode');var panel=document.getElementById('v2PracticePanel');if(panel)panel.hidden=true;var root=document.getElementById('v2ActivityRoot');if(root)root.innerHTML='';practice.book=null;practice.unit=null;practice.skill=null;practice.items=[];practice.index=0;practice.answered=false;renderBook();window.scrollTo({top:0,behavior:'auto'});}
function bindSwipe(){var w=document.getElementById('bookSwipe');if(!w)return;var sx=0,sy=0;w.addEventListener('touchstart',function(e){if(state.books.length<=1||!e.touches[0])return;sx=e.touches[0].clientX;sy=e.touches[0].clientY;},{passive:true});w.addEventListener('touchend',function(e){if(state.books.length<=1||!e.changedTouches[0])return;var dx=e.changedTouches[0].clientX-sx,dy=e.changedTouches[0].clientY-sy;if(Math.abs(dx)<45||Math.abs(dx)<Math.abs(dy))return;var next=dx<0?state.activeIndex+1:state.activeIndex-1;if(next<0)next=state.books.length-1;if(next>=state.books.length)next=0;switchBook(next);},{passive:true});}
function bindUi(){var l=document.getElementById('languageBtn');if(l)l.addEventListener('click',function(){lang=lang==='ko'?'en':'ko';l.textContent=lang==='ko'?'English':'한국어';renderBook();});var ai=document.getElementById('practiceHeroBtn');if(ai)ai.addEventListener('click',function(){var s=document.getElementById('aiRecommendations');if(s)s.scrollIntoView({behavior:'smooth',block:'start'});});var close=document.getElementById('v2PracticeClose'),next=document.getElementById('v2PracticeNext');if(close)close.addEventListener('click',closePractice);if(next)next.addEventListener('click',nextPractice);bindSwipe();window.addEventListener('willena:study-progress-updated',function(e){var d=e&&e.detail;if(!practice.book||!practice.unit||!d)return;practice.book.progress=d;if(activeBook()===practice.book&&String(activeBook().currentUnit.id)===String(practice.unit.id)){renderMastery(practice.book);renderDaily(practice.book);renderAi(practice.book);}saveCache();});}
function hydrateCache(){var c=readCache();if(!c||!c.books.length)return false;state.books=c.books;setActiveFromId(c.activeBookId);state.ready=true;renderBook();return true;}
async function init(){hydrateCache();try{var me=await profile();var className=txt(me.class);if(!className)throw new Error('No active class is assigned.');state.student={id:me.user_id||null,name:me.name||null};var a=await assignments(className);state.classInfo=a.class;var list=Array.isArray(a.assignments)&&a.assignments.length?a.assignments:(a.assignment?[a.assignment]:[]);if(!list.length)throw new Error('No active book is assigned.');var adaptivePromise=getAdaptive().catch(function(){return{items:[]};});var booksPromise=Promise.all(list.slice(0,3).map(loadBook));var both=await Promise.all([booksPromise,adaptivePromise]);state.books=both[0];state.adaptive=both[1];var wanted='';try{wanted=localStorage.getItem(ACTIVE_BOOK_KEY)||'';}catch(_){}setActiveFromId(wanted||a.assignment&&a.assignment.book_id);state.ready=true;renderBook();saveCache();}catch(e){console.error('[StudyV2]',e);var title=document.getElementById('bookTitle'),unit=document.getElementById('unitTitle');if(!state.books.length&&title)title.textContent='Could not load study content';if(!state.books.length&&unit)unit.textContent=e.message||'Please try again.';}}
async function boot(){var allowed=true;try{if(window.WillenaStudyV2AuthReady)allowed=await window.WillenaStudyV2AuthReady;}catch(_){allowed=false;}if(!allowed)return;bindUi();init();}
boot();
})();