(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const choices=['🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🦄','🐔','🐧','🐦','🐤','🦆','🦅','🦉','🦇','🐺','🦝','🦨','🦡','🐗','🦙','🐴','🦓','🦌','🦬','🐑','🐐','🐪','🐫','🦒','🐘','🦏','🦛','🦔','🐇','🐿️','🦎','🐍','🐢','🐊','🦖','🦕','🐬','🐳','🐋','🦈','🐟','🐠','🐡','🦐','🦑','🦀','🐙','🦞','🦋','🐌','🐛','🐜','🐝','🐞'];
let currentAvatar='🙂',selectedAvatar='🙂';
async function jsonFetch(url,opts={}){const r=await WillenaAPI.fetch(url,{cache:'no-store',...opts});const d=await r.json().catch(()=>({}));return{r,d}}
async function getSession(){let x=await jsonFetch(`/.netlify/functions/supabase_auth?action=whoami&_=${Date.now()}`);if(x.r.ok&&x.d.success)return x.d;try{const ref=await jsonFetch(`/.netlify/functions/supabase_auth?action=refresh&_=${Date.now()}`);if(ref.r.ok&&ref.d.success){x=await jsonFetch(`/.netlify/functions/supabase_auth?action=whoami&_=${Date.now()}`);if(x.r.ok&&x.d.success)return x.d}}catch{}return null}
function text(id,value){const el=document.getElementById(id);if(!el)return;el.textContent=value??'—';el.classList.remove('skeleton')}
function calcSuper(stars,points,explicit){const e=Number(explicit);if(Number.isFinite(e))return Math.max(0,Math.round(e));return Math.max(0,Math.round(((Number(stars)||0)*(Number(points)||0))/1000))}
function applyProfile(profile={},overview={}){const name=profile.name||profile.username||'Student',cls=profile.class||'Willena English',avatar=profile.avatar||'🙂';currentAvatar=selectedAvatar=avatar;text('headerName',name);text('headerClass',cls);text('profileName',name);text('profileClassSummary',cls);text('pfNameEn',profile.name||profile.username||'—');text('pfNameKo',profile.korean_name||'—');text('pfClass',profile.class||'—');text('pfEmail',profile.email||'—');const av=$('#profileAvatar');if(av){av.textContent=avatar;av.classList.remove('skeleton')}const hav=$('.avatar');if(hav)hav.textContent=avatar;const stars=Number(overview.stars),pts=Number(overview.points),superPts=calcSuper(stars,pts,overview.super_score);text('headerStars',Number.isFinite(stars)?`⭐ ${stars.toLocaleString()}`:'⭐ —');text('headerPoints',Number.isFinite(pts)?`+ ${pts.toLocaleString()}`:'+ —');text('rewardStars',Number.isFinite(stars)?stars.toLocaleString():'—');text('rewardPoints',Number.isFinite(pts)?pts.toLocaleString():'—');text('rewardSuper',superPts.toLocaleString())}
function status(message,tone=''){const el=$('#profileStatus');if(!el)return;el.textContent=message||'';el.className='status'+(tone?' '+tone:'')}
function openAvatar(){const modal=$('#avatarModal');if(!modal)return;selectedAvatar=currentAvatar;$$('.emoji-btn',modal).forEach(b=>b.classList.toggle('selected',b.dataset.e===selectedAvatar));modal.classList.add('open');modal.setAttribute('aria-hidden','false')}
function closeAvatar(){const modal=$('#avatarModal');if(!modal)return;modal.classList.remove('open');modal.setAttribute('aria-hidden','true')}
function buildEmojiGrid(){const grid=$('#emojiGrid');if(!grid||grid.dataset.ready)return;grid.innerHTML=choices.map(e=>`<button type="button" class="emoji-btn" data-e="${e}" aria-label="Choose ${e}">${e}</button>`).join('');grid.dataset.ready='1';grid.addEventListener('click',e=>{const b=e.target.closest('.emoji-btn');if(!b)return;selectedAvatar=b.dataset.e;$$('.emoji-btn',grid).forEach(x=>x.classList.toggle('selected',x===b))})}
async function saveAvatar(){const btn=$('#avatarSave');if(btn)btn.disabled=true;status('Saving…');try{const {r,d}=await jsonFetch('/.netlify/functions/supabase_auth?action=update_profile_avatar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({avatar:selectedAvatar})});if(!r.ok||!d.success)throw new Error(d.error||'Save failed');currentAvatar=selectedAvatar;$('#profileAvatar').textContent=currentAvatar;$('.avatar').textContent=currentAvatar;closeAvatar();status('Avatar saved.','success')}catch(e){status(e.message||'Could not save avatar.','error')}finally{if(btn)btn.disabled=false}}
function wire(){buildEmojiGrid();$('#profileAvatar')?.addEventListener('click',openAvatar);$('#changeAvatar')?.addEventListener('click',openAvatar);$('.avatar')?.addEventListener('click',openAvatar);$('#avatarClose')?.addEventListener('click',closeAvatar);$('#avatarCancel')?.addEventListener('click',closeAvatar);$('#avatarSave')?.addEventListener('click',saveAvatar);$('#avatarModal')?.addEventListener('click',e=>{if(e.target.id==='avatarModal')closeAvatar()});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeAvatar()});$('#backDashboard')?.addEventListener('click',()=>location.href='/students/dashboard');}
async function boot(){wire();if(!window.WillenaAPI){location.replace('/students/signin.html?next='+encodeURIComponent(location.pathname));return}const who=await getSession();if(!who){location.replace('/students/signin.html?next='+encodeURIComponent(location.pathname));return}try{const [{r:pr,d:profile},{r:or,d:overview}]=await Promise.all([jsonFetch(`/.netlify/functions/supabase_auth?action=get_profile&_=${Date.now()}`),jsonFetch(`/.netlify/functions/progress_summary?section=overview&_=${Date.now()}`)]);if(!pr.ok||profile.success===false)throw new Error(profile.error||'Could not load profile');applyProfile(profile,or.ok?overview:{});status('')}catch(e){status(e.message||'Could not load profile.','error')}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();