

// Past participles quiz questions
export const participlesQuestions = [
  { base: "eat", answer: "eaten", options: ["eaten", "eats", "eating", "ate"] },
  { base: "go", answer: "gone", options: ["gone", "goes", "going", "went"] },
  { base: "see", answer: "seen", options: ["seen", "sees", "seeing", "saw"] },
  { base: "write", answer: "written", options: ["written", "writes", "writing", "wrote"] },
  { base: "take", answer: "taken", options: ["taken", "takes", "taking", "took"] },
  { base: "give", answer: "given", options: ["given", "gives", "giving", "gave"] },
  { base: "come", answer: "come", options: ["come", "comes", "coming", "came"] },
  { base: "run", answer: "run", options: ["run", "runs", "running", "ran"] },
  { base: "drink", answer: "drunk", options: ["drunk", "drinks", "drinking", "drank"] },
  { base: "sing", answer: "sung", options: ["sung", "sings", "singing", "sang"] },
  { base: "swim", answer: "swum", options: ["swum", "swims", "swimming", "swam"] },
  { base: "begin", answer: "begun", options: ["begun", "begins", "beginning", "began"] },
  { base: "break", answer: "broken", options: ["broken", "breaks", "breaking", "broke"] },
  { base: "choose", answer: "chosen", options: ["chosen", "chooses", "choosing", "chose"] },
  { base: "drive", answer: "driven", options: ["driven", "drives", "driving", "drove"] },
  { base: "fall", answer: "fallen", options: ["fallen", "falls", "falling", "fell"] },
  { base: "forget", answer: "forgotten", options: ["forgotten", "forgets", "forgetting", "forgot"] },
  { base: "freeze", answer: "frozen", options: ["frozen", "freezes", "freezing", "froze"] },
  { base: "grow", answer: "grown", options: ["grown", "grows", "growing", "grew"] },
  { base: "know", answer: "known", options: ["known", "knows", "knowing", "knew"] },
  { base: "ride", answer: "ridden", options: ["ridden", "rides", "riding", "rode"] },
  { base: "rise", answer: "risen", options: ["risen", "rises", "rising", "rose"] },
  { base: "speak", answer: "spoken", options: ["spoken", "speaks", "speaking", "spoke"] },
  { base: "steal", answer: "stolen", options: ["stolen", "steals", "stealing", "stole"] },
  { base: "throw", answer: "thrown", options: ["thrown", "throws", "throwing", "threw"] },
  { base: "wake", answer: "woken", options: ["woken", "wakes", "waking", "woke"] },
  { base: "wear", answer: "worn", options: ["worn", "wears", "wearing", "wore"] },
  { base: "fly", answer: "flown", options: ["flown", "flies", "flying", "flew"] },
  { base: "hide", answer: "hidden", options: ["hidden", "hides", "hiding", "hid"] },
  { base: "hold", answer: "held", options: ["held", "holds", "holding", "helded"] },
  { base: "leave", answer: "left", options: ["left", "leaves", "leaving", "leaved"] },
  { base: "lose", answer: "lost", options: ["lost", "loses", "losing", "lose"] },
  { base: "make", answer: "made", options: ["made", "makes", "making", "maked"] },
  { base: "meet", answer: "met", options: ["met", "meets", "meeting", "meet"] },
  { base: "pay", answer: "paid", options: ["paid", "pays", "paying", "pay"] },
  { base: "read", answer: "read", options: ["read", "reads", "reading", "red"] },
  { base: "sell", answer: "sold", options: ["sold", "sells", "selling", "selled"] },
  { base: "send", answer: "sent", options: ["sent", "sends", "sending", "sended"] }
];
