name = "daily-study-state"
main = "src/index.js"
compatibility_date = "2025-12-08"
workers_dev = true

[[routes]]
pattern = "api.willenaenglish.com/api/daily-study-state*"
zone_name = "willenaenglish.com"
