(function(){
'use strict';
const CONTENT='https://gxwfsqxyuufqtitspfqg.supabase.co';
const KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const HEAD={apikey:KEY,Authorization:`Bearer ${KEY}`};
let selection=null;
function addScript(src,dataKey){if(document.querySelector(`script[${dataKey}]`))return;const s=document.createElement('script');s.src=src;s.setAttribute(dataKey,'1');document.head.appendChild(s)}
if(!document.querySelector('script[data-testprep-student-header]')){const s=document.createElement('script');s.type='module';s.src='/students/components/student-header.js?v=20260826-testprep8';s.dataset.testprepStudentHeader='1';document.head.appendChild(s)}
addScript('./tracking-phase1.js?v=20260827-phase10','data-testprep-phase1-tracking');
addScript('./vocab-practice.js?v=20260827-vocab9','data-testprep-vocab-practice');
addScript('./vocab-test-practice.js?v=20260827-vocabtest3','data-testprep-vocab-test-practice');
addScript('./sentence-practice.js?v=20260827-sentence8','data-testprep-sentence-practice');
if(!document.querySelector('student-header[data-testprep-header]')){const header=document.createElement('student-header');header.setAttribute('data-testprep-header','1');header.setAttribute('title','Test Prep');header.setAttribute('show-id','false');header.setAttribute('show-home','false');header.setAttribute('show-points','true');header.setAttribute('show-logout','true');document.body.insertBefore(header,document.body.firstChild)}
const app=document.querySelector('.app'),home=document.createElement('div'),quiz=document.createElement('div');
home.id='assignmentHome';quiz.id='assignedQuizPane';quiz.style.display='none';
if(app){const engine=document.getElementById('engineShell');app.append(home,quiz);if(engine)quiz.appendChild(engine)}
const style=document.createElement('style');style.textContent=`html,body,button,input,textarea,select{font-family:'Poppins','Noto Sans KR',sans-serif!important}body{background:linear-gradient(180deg,#f4f8fa 0,#f7f9fb 230px,#f6f7fb 100%)!important;color:#203039!important}.app{max-width:920px!important;padding:24px 18px 54px!important}#assignmentHome{padding:2px 0 24px}.tp-shell-loading{padding:42px 20px;text-align:center;color:#73828a;font-size:12px;font-weight:700}.quiz-top-back{display:flex;align-items:center;gap:10px;margin:0 0 14px}.back-assign{border:2px solid #67d4da;background:#fff;color:#ee5f91;border-radius:13px;padding:10px 13px;font-size:11px;font-weight:800;cursor:pointer}.quiz-context{font-size:11px;color:#73828a;font-weight:700}.engine-progress{margin-top:0!important}#trackingDebug{position:fixed;right:12px;bottom:12px;z-index:99999;width:min(420px,calc(100vw - 24px));max-height:44vh;overflow:auto;background:#172127;color:#e9f5f6;border:1px solid #67d4da;border-radius:14px;padding:12px 14px;font:12px/1.45 ui-monospace,monospace}#trackingDebug strong{display:block;color:#67d4da;margin-bottom:6px}#trackingDebug pre{white-space:pre-wrap;word-break:break-word;margin:0}.tp-wrong-page-head h1{font-size:32px!important;line-height:1.2!important}.tp-wrong-page-head p{font-size:14px!important;line-height:1.55!important}.tp-review-start{font-size:15px!important;padding:16px 18px!important}.tp-review-group b{font-size:16px!important;line-height:1.35!important}.tp-review-group small{font-size:12px!important;line-height:1.45!important}.tp-review-btn{font-size:12px!important;padding:10px 13px!important}.tp-review-empty{font-size:14px!important}@media(max-width:650px){.app{padding:16px 11px 38px!important}.quiz-top-back{align-items:flex-start;flex-direction:column}.quiz-context{padding-left:2px}}`;document.head.appendChild(style);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
const practiceLabel=k=>({vocabulary:'단어 학습',vocab_test:'어휘 시험',sentences:'본문외우기',communication:'Communication',grammar:'Grammar',reading:'Reading'}[k]||k);
function installDebugPanel(){const qs=new URLSearchParams(location.search);if(qs.get('debug')!=='tracking'||document.getElementById('trackingDebug'))return;const panel=document.createElement('div');panel.id='trackingDebug';panel.innerHTML='<strong>Tracking debug</strong><pre>Answer a question to see the saved event.</pre>';document.body.appendChild(panel);const show=(type,detail)=>{const pre=panel.querySelector('pre');if(pre)pre.textContent=JSON.stringify({type,...detail},null,2)};window.addEventListener('testprep:tracking',e=>show('tracking',e.detail));window.addEventListener('testprep:vocab-attempt',e=>show('vocab-attempt',e.detail));window.addEventListener('testprep:sentence-attempt',e=>show('sentence-attempt',e.detail))}
function restorePractice(){window.WillenaVocabPractice?.restore?.();window.WillenaVocabTestPractice?.restore?.();window.WillenaSentencePractice?.restore?.()}
function activePracticeState(){return history.state?.tp==='practice'&&quiz.style.display!=='none'}
function showHomeSurface(){if(activePracticeState())return false;quiz.style.display='none';home.style.display='block';return true}
function renderHome(){if(activePracticeState())return false;restorePractice();selection=null;showHomeSurface();home.innerHTML='<div class="tp-shell-loading">시험 대비를 불러오는 중...</div>';return true}
async function contentGet(path){const r=await fetch(CONTENT+path,{headers:HEAD,cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
async function resolveIds(plan,lesson){const books=await contentGet(`/rest/v1/content_books?select=id,title&title=eq.${encodeURIComponent(plan.book_label)}&limit=1`);if(!books[0])throw new Error('교재를 콘텐츠 DB에서 찾지 못했습니다.');const units=await contentGet(`/rest/v1/content_units?select=id,title&book_id=eq.${books[0].id}&title=eq.${encodeURIComponent(lesson)}&limit=1`);if(!units[0])throw new Error('Lesson을 콘텐츠 DB에서 찾지 못했습니다.');return{bookId:books[0].id,unitId:units[0].id}}
async function waitFor(name){for(let i=0;i<80;i++){if(window[name])return window[name];await new Promise(r=>setTimeout(r,50))}throw new Error('Practice module did not load.')}
function showBack(plan){let back=document.getElementById('assignedBackRow');if(!back){back=document.createElement('div');back.id='assignedBackRow';back.className='quiz-top-back';quiz.insertBefore(back,quiz.firstChild)}back.innerHTML=`<button class="back-assign">${selection?.reviewMode?'← 오답 복습':`← ${esc(selection?.lesson||'Lesson')}`}</button><span class="quiz-context">${esc(plan.book_label)} · ${esc(selection.lesson)} · ${esc(practiceLabel(selection.section))}</span>`;return back}
function leavePractice(){const old=selection;restorePractice();quiz.style.display='none';home.style.display='block';if(old?.reviewMode&&window.WillenaTestPrepUX?.showWrongCenter){window.WillenaTestPrepUX.showWrongCenter();return}if(old?.plan&&old?.lesson&&window.WillenaTestPrepUX?.renderLesson){window.WillenaTestPrepUX.renderLesson(old.plan.id,old.lesson,old.section);return}window.WillenaTestPrepUX?.renderHome?.()}
async function start(btn){const state=window.WillenaTestPrepAuth.state,plan=state.plans.find(p=>String(p.id)===String(btn.dataset.plan));if(!plan)return;btn.classList.add('loading');try{const ids=await resolveIds(plan,btn.dataset.lesson),opts=btn.__reviewOptions||{};selection={plan,lesson:btn.dataset.lesson,section:String(btn.dataset.section||'communication').toLowerCase(),...ids,reviewMode:!!opts.reviewMode,reviewIds:Array.isArray(opts.reviewIds)?opts.reviewIds.map(String):[]};home.style.display='none';quiz.style.display='block';window.WillenaTestPrepAuth.setActivePlan(plan,selection.lesson);const back=showBack(plan);if(selection.section==='vocabulary'){window.WillenaVocabTestPractice?.restore?.();window.WillenaSentencePractice?.restore?.();back.querySelector('button').onclick=leavePractice;const mod=await waitFor('WillenaVocabPractice');await mod.start({quiz,unitId:selection.unitId,lesson:selection.lesson,bookLabel:plan.book_label,onlyIds:selection.reviewIds,reviewMode:selection.reviewMode});return}if(selection.section==='vocab_test'){window.WillenaVocabPractice?.restore?.();window.WillenaSentencePractice?.restore?.();back.querySelector('button').onclick=leavePractice;const mod=await waitFor('WillenaVocabTestPractice');await mod.start({quiz,unitId:selection.unitId,lesson:selection.lesson,bookLabel:plan.book_label,onlyIds:selection.reviewIds,reviewMode:selection.reviewMode});return}if(selection.section==='sentences'){window.WillenaVocabPractice?.restore?.();window.WillenaVocabTestPractice?.restore?.();back.querySelector('button').onclick=leavePractice;const mod=await waitFor('WillenaSentencePractice');await mod.start({quiz,unitId:selection.unitId,lesson:selection.lesson,bookLabel:plan.book_label,onlyIds:selection.reviewIds,reviewMode:selection.reviewMode});return}restorePractice();window.WillenaTestPrepAuth.beginStudyActivity?.();back.querySelector('button').onclick=async()=>{try{await window.WillenaTestPrepAuth.completeSession(0,0,[])}catch(_){}leavePractice()};const engine=window.WillenaTestPrepQuestionEngine;if(!engine?.loadSection)throw new Error('Question engine did not load.');await engine.loadSection(selection.section)}catch(e){console.error('[test-prep] activity start failed',e);alert(e.message||'시험 범위를 불러오지 못했습니다.');quiz.style.display='none';home.style.display='block';if(selection?.reviewMode&&window.WillenaTestPrepUX?.showWrongCenter)window.WillenaTestPrepUX.showWrongCenter();else if(window.WillenaTestPrepUX?.renderHome)window.WillenaTestPrepUX.renderHome()}finally{btn.classList.remove('loading')}}
async function startSelection(planId,lesson,section,opts={}){const b=document.createElement('button');b.dataset.plan=String(planId);b.dataset.lesson=String(lesson);b.dataset.section=String(section);b.__reviewOptions=opts;return start(b)}
function questionQuery(){if(!selection)return'';let q=`&book_id=eq.${encodeURIComponent(selection.bookId)}&unit_id=eq.${encodeURIComponent(selection.unitId)}`;if(selection.reviewIds?.length&&!['vocabulary','vocab_test','sentences'].includes(selection.section))q+=`&id=in.${encodeURIComponent('('+selection.reviewIds.join(',')+')')}`;return q}
function init(){installDebugPanel();renderHome()}
window.addEventListener('testprep:review-group-complete',()=>{restorePractice()});
window.WillenaAssignedTestPrep={init,renderHome,startSelection,questionQuery,showHomeSurface,get selection(){return selection}};
})();