(function(){
'use strict';
const DB='https://fiieuiktlsivwfgyivai.supabase.co';
const API_KEY='sb_publishable_e-K50PquV9gHdfmefG6tmg_o-vVSl0e';
const REASONS=['정답이 이상함','문제가 애매함','영어가 이상함','한국어가 이상함','문장이 이상하게 잘림','시험 범위와 안 맞음','반복 문제','화면/표시 문제','기타'];
let pending=null,reason='',sending=false;
const esc=s=>String(s??'').replace(/[&<>\"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot',"'":'&#39;'}[c]));
function hash(s){let h=2166136261;for(let i=0;i<s.length;i++)h=Math.imul(h^s.charCodeAt(i),16777619);return (h>>>0).toString(16).padStart(8,'0')}
function text(sel,root=document){return root.querySelector(sel)?.textContent?.trim()||''}
function texts(sel,root=document){return [...root.querySelectorAll(sel)].map(x=>x.textContent.trim()).filter(Boolean)}
function toast(msg){const t=document.getElementById('toast');if(t){t.textContent=msg;t.classList.add('show');setTimeout(()=>t.classList.remove('show'),1800)}else console.log(msg)}
function ensureUi(){if(document.getElementById('tpPracticeFlagStyles'))return;const st=document.createElement('style');st.id='tpPracticeFlagStyles';st.textContent=`.tp-practice-flag{width:34px;height:34px;flex:0 0 34px;border:2px solid #67d4da;background:#fff;color:#ee5f91;border-radius:50%;display:grid;place-items:center;padding:0;font-size:15px;line-height:1;cursor:pointer}.tp-practice-head-right{display:flex;align-items:center;gap:9px}.tp-pflag-overlay{position:fixed;inset:0;background:rgba(20,22,29,.38);display:none;align-items:flex-end;justify-content:center;padding:12px;z-index:100010}.tp-pflag-overlay.open{display:flex}.tp-pflag-modal,.tp-pflag-modal *{font-family:'Poppins','Noto Sans KR',sans-serif!important}.tp-pflag-modal{width:min(560px,100%);background:#fff;border:2px solid #67d4da;border-radius:22px;padding:18px}.tp-pflag-modal h3{margin:0 0 5px;font-size:17px}.tp-pflag-modal p{margin:0 0 13px;color:#78878e;font-size:11px}.tp-pflag-reasons{display:flex;flex-wrap:wrap;gap:8px}.tp-pflag-reason{border:1.5px solid #67d4da;background:#fff;color:#ee5f91;border-radius:999px;padding:9px 11px;font-size:11px;font-weight:700;cursor:pointer}.tp-pflag-reason.on{background:#fff6fa}.tp-pflag-note{width:100%;min-height:72px;margin-top:12px;border:1.5px solid #67d4da;border-radius:12px;padding:11px;resize:vertical}.tp-pflag-actions{display:flex;gap:8px;margin-top:12px;flex-wrap:wrap}.tp-pflag-actions button{flex:1 1 120px;border:2px solid #67d4da;background:#fff;color:#ee5f91;border-radius:13px;padding:11px 13px;font-weight:800;cursor:pointer}.tp-pflag-actions button:disabled{opacity:.45;cursor:wait}.tp-pflag-replace{background:#19777e!important;border-color:#19777e!important;color:#fff!important}`;document.head.appendChild(st);
const o=document.createElement('div');o.id='tpPracticeFlagOverlay';o.className='tp-pflag-overlay';o.innerHTML=`<div class="tp-pflag-modal"><h3>이 항목에 문제가 있나요? 🚩</h3><p id="tpPflagHelp">이유를 골라 주세요. 현재 화면 정보도 같이 저장됩니다.</p><div class="tp-pflag-reasons" id="tpPflagReasons"></div><textarea class="tp-pflag-note" id="tpPflagNote" placeholder="추가 메모 (선택)"></textarea><div class="tp-pflag-actions"><button id="tpPflagCancel">취소</button><button id="tpPflagSend">신고만</button><button class="tp-pflag-replace" id="tpPflagReplace" style="display:none">신고 + 교체</button></div></div>`;document.body.appendChild(o);o.onclick=e=>{if(e.target===o)close()};document.getElementById('tpPflagCancel').onclick=close;document.getElementById('tpPflagSend').onclick=()=>send(false);document.getElementById('tpPflagReplace').onclick=()=>send(true)}
function setBusy(on){sending=on;['tpPflagCancel','tpPflagSend','tpPflagReplace'].forEach(id=>{const b=document.getElementById(id);if(b)b.disabled=on})}
function close(){if(sending)return;document.getElementById('tpPracticeFlagOverlay')?.classList.remove('open');pending=null;reason=''}
function open(data){ensureUi();pending=data;reason='기타';sending=false;const r=document.getElementById('tpPflagReasons'),n=document.getElementById('tpPflagNote'),replace=document.getElementById('tpPflagReplace'),help=document.getElementById('tpPflagHelp');n.value='';r.innerHTML=REASONS.map(x=>`<button class="tp-pflag-reason ${x==='기타'?'on':''}">${esc(x)}</button>`).join('');r.querySelectorAll('.tp-pflag-reason').forEach(b=>b.onclick=()=>{reason=b.textContent;r.querySelectorAll('.tp-pflag-reason').forEach(x=>x.classList.toggle('on',x===b))});const canReplace=!!data?.allowReplace&&Number(data?.replaceRemaining)>0;if(replace){replace.style.display=canReplace?'':'none';replace.textContent=canReplace?`신고 + 교체 (${Number(data.replaceRemaining)}회 남음)`:'신고 + 교체'}if(help)help.textContent=canReplace?'이유를 고른 뒤 신고만 하거나, 문제를 다른 문제로 교체할 수 있어요.':'이유를 골라 주세요. 현재 화면 정보도 같이 저장됩니다.';setBusy(false);document.getElementById('tpPracticeFlagOverlay').classList.add('open');setTimeout(()=>n.focus(),0)}
function capture(root,type){const sel=window.WillenaAssignedTestPrep?.selection||{},snapshot={page:location.pathname,lesson:sel.lesson||null,practice_type:sel.section||null,review_mode:!!sel.reviewMode};if(type==='vocab_practice'){snapshot.title=text('.vp-title',root);snapshot.count=text('.vp-count:last-child',root);snapshot.prompt=text('.vp-prompt',root);snapshot.part_of_speech=text('.vp-sub',root);snapshot.mode=text('.vp-mode.active',root)||'cards';snapshot.choices=texts('.vp-choice',root);snapshot.revealed_answer=text('.vp-flash-answer.show',root)||null;snapshot.typed_answer=root.querySelector('.vp-spell')?.value||null}else if(type==='vocab_test'){snapshot.title=text('.vt-title',root);snapshot.count=text('.vt-count',root);snapshot.definition=text('.vt-def',root);snapshot.choices=texts('.vt-choice',root)}else if(type==='sentence_unscramble'){snapshot.title=text('.sp-title',root);snapshot.count=text('.sp-count',root);snapshot.passage=text('.sp-meta',root);snapshot.speaker=text('.sp-speaker',root)||null;snapshot.korean=text('.sp-ko',root)||null;snapshot.answer_bank=texts('.sp-bank .sp-word',root);snapshot.current_answer=texts('.sp-answer .sp-word',root)}const raw=JSON.stringify(snapshot);return{source_type:type,source_id:`${type}:${hash(raw)}`,snapshot}}
function installOne(root,type){const head=root.querySelector(type==='vocab_practice'?'.vp-head':type==='vocab_test'?'.vt-head':'.sp-head');if(!head||head.querySelector('.tp-practice-flag'))return;const existing=head.lastElementChild,wrap=document.createElement('div');wrap.className='tp-practice-head-right';if(existing)wrap.appendChild(existing);const b=document.createElement('button');b.type='button';b.className='tp-practice-flag';b.title='문제 신고';b.setAttribute('aria-label','문제 신고');b.textContent='⚑';b.onclick=e=>{e.preventDefault();e.stopPropagation();open(capture(root,type))};wrap.appendChild(b);head.appendChild(wrap)}
function installButtons(){document.querySelectorAll('.vp-wrap').forEach(x=>installOne(x,'vocab_practice'));document.querySelectorAll('.vt-wrap').forEach(x=>installOne(x,'vocab_test'));document.querySelectorAll('.sp-wrap').forEach(x=>installOne(x,'sentence_unscramble'))}
async function post(payload,token){return fetch(`${DB}/rest/v1/test_prep_practice_flags`,{method:'POST',headers:{apikey:API_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json',Prefer:'return=minimal'},body:JSON.stringify(payload)})}
async function send(wantsReplace=false){if(!pending||sending)return;if(!reason){toast('이유를 하나 골라 주세요');return}const current=pending,auth=window.WillenaTestPrepAuth,state=auth?.state,sel=window.WillenaAssignedTestPrep?.selection||{};if(!state?.user?.id){toast('로그인이 필요합니다');return}setBusy(true);let replacement=null;try{if(wantsReplace){if(!current.allowReplace||typeof current.onReplaceRequest!=='function')throw new Error('이 문제는 교체할 수 없습니다.');replacement=await current.onReplaceRequest();if(!replacement?.question)throw new Error('교체할 다른 문제를 찾지 못했습니다.')}const snapshot={...(current.snapshot||{})};if(replacement){snapshot.replacement_requested=true;snapshot.replacement_question_id=replacement.question.id||null;snapshot.replacement_question_type=replacement.question.question_type||null;snapshot.replacement_source_label=replacement.question.student_source_label||null}const payload={student_id:state.user.id,plan_id:sel.plan?.id||state.plan?.id||current.snapshot?.plan_id||null,unit_key:sel.lesson||state.lesson||current.snapshot?.lesson||null,practice_type:String(sel.section||current.snapshot?.practice_type||'unknown'),source_type:current.source_type,source_id:current.source_id,reason,note:document.getElementById('tpPflagNote').value.trim()||null,snapshot,status:'open'};let token=window.WillenaAPI?.getLocalAccessToken?.()||localStorage.getItem('sb_access_token')||'';if(!token){await auth?.ready;token=window.WillenaAPI?.getLocalAccessToken?.()||localStorage.getItem('sb_access_token')||''}let r=await post(payload,token);if(r.status===401&&auth?.edge){try{await auth.edge('me')}catch(_){}token=window.WillenaAPI?.getLocalAccessToken?.()||localStorage.getItem('sb_access_token')||'';r=await post(payload,token)}if(!r.ok)throw new Error(await r.text());sending=false;document.getElementById('tpPracticeFlagOverlay')?.classList.remove('open');pending=null;reason='';toast(replacement?'신고하고 문제를 교체했어요.':'신고했습니다. 고마워요!');await current.onSent?.({replace:!!replacement,replacement})}catch(e){console.error('[REV46j flag]',e);sending=false;setBusy(false);toast(e?.message||'신고 저장에 실패했습니다')}}
function boot(){ensureUi();installButtons();new MutationObserver(installButtons).observe(document.body,{childList:true,subtree:true})}
window.WillenaPracticeFlagger={open,capture};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
console.log('[REV46j] Flagger replacement-aware');
})();