(function(){
'use strict';
const U='https://gxwfsqxyuufqtitspfqg.supabase.co';
const K=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const H={apikey:K,Authorization:`Bearer ${K}`};
const REGULAR=['communication','grammar','reading'];
const BLUEPRINT={vocab_test:5,communication:5,grammar:7,reading:8};
const LABEL={vocab_test:'어휘',communication:'Communication',grammar:'Grammar',reading:'Reading',constructed_response:'서술형'};
let patched=false,questions=[],index=0,score=0,selected=new Set(),checked=false,wrongIds=[],pending=[],finishing=false,startedAt=0;
const card=()=>document.getElementById('card'),bar=()=>document.getElementById('bar');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>{let s=String(v??'').replace(/\r\n?/g,'\n');for(let i=0;i<4;i++)s=s.replace(/\\+n/g,'\n');return s};
const answerNorm=v=>String(v??'').normalize('NFKC').toLowerCase().replace(/[’‘]/g,"'").replace(/[.!?,;:]+$/g,'').replace(/\s+/g,' ').trim();
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
function text(v){return norm(v).split('\n').map(x=>`<span class="line">${esc(x)}</span>`).join('')}
function block(title,v){if(v==null||v==='')return'';return `<div class="context">${title?`<div class="context-title">${esc(title)}</div>`:''}${text(v)}</div>`}
function arr(title,a){if(!Array.isArray(a)||!a.length)return'';return `<div class="context">${title?`<div class="context-title">${esc(title)}</div>`:''}<div class="items">${a.map(x=>`<div class="item">${Array.isArray(x)?x.map(y=>text(y)).join('<hr>'):text(x)}</div>`).join('')}</div></div>`}
function obj(title,o,cls='segment'){if(!o||typeof o!=='object'||Array.isArray(o))return'';return `<div class="context"><div class="context-title">${esc(title)}</div><div class="${cls==='claim'?'claims':'segments'}">${Object.entries(o).map(([k,v])=>`<div class="${cls}"><b>${esc(k)}</b> ${text(v)}</div>`).join('')}</div></div>`}
function contextHtml(q){const c=q.context||{};let o='';if(c.passage)o+=block('',c.passage);if(c.passage_start)o+=block('',c.passage_start)+obj('A–D',c.segments)+block('',c.passage_end);if(c.source_passage)o+=block('원문',c.source_passage);if(c.rewritten)o+=block('바꿔 쓴 글',c.rewritten);if(c.dialogue)o+=block('대화',c.dialogue);if(c.dialogue_start)o+=block('',c.dialogue_start)+obj('A–D',c.segments)+block('',c.dialogue_end);if(c.dialogue_a)o+=block('대화 A',c.dialogue_a);if(c.dialogue_b)o+=block('대화 B',c.dialogue_b);if(c.dialogue1)o+=block('대화 1',c.dialogue1);if(c.dialogue2)o+=block('대화 2',c.dialogue2);if(c.given_sentence)o+=block('<보기>',c.given_sentence);if(c.bank)o+=Array.isArray(c.bank)?arr('<보기>',c.bank):typeof c.bank==='object'?obj('<보기>',c.bank):block('<보기>',c.bank);o+=arr('',c.items);o+=arr('',c.pairs);o+=arr('문제 단서',c.clues);o+=arr('',c.statements);o+=obj('설명',c.claims,'claim');if(c.table)o+=obj('표',c.table);if(c.definition)o+=block('정의',c.definition);if(c.korean)o+=block('우리말',c.korean);if(c.pattern)o+=block('형식',c.pattern);if(c.target)o+=block('대상',c.target);if(c.A)o+=block('(A)',c.A);if(c.B)o+=block('(B)',c.B);if(c.proposed_pairs)o+=arr('',c.proposed_pairs);return o}
function scopeRow(sel){return sel?.plan?.group?.scope?.lessons?.find(x=>String(x.lesson)===String(sel.lesson))||null}
function scopeRaw(sel){const row=scopeRow(sel),raw=Array.isArray(row?.sections)?row.sections:(sel?.plan?.practice_types||[]);return [...new Set(raw.map(x=>String(x).toLowerCase()))]}
function scopeSections(sel){const allowed=scopeRaw(sel).filter(x=>REGULAR.includes(x));return allowed.length?allowed:REGULAR}
function vocabAllowed(sel){const raw=scopeRaw(sel);return raw.includes('vocabulary')||raw.includes('vocab_test')}
function seosulCount(sel){const raw=scopeRaw(sel);if(!raw.includes('constructed_response'))return 0;return Math.max(0,Math.min(10,Number(sel?.plan?.group?.scope?.constructed_response_count)||0))}
async function fetchSection(sel,section){const fields='id,section,source_question_number,question_type,prompt_text,context,choices,correct_answer,targets,answer_mode,student_source_label,content_status,metadata';const q=new URLSearchParams({select:fields,student_usable:'eq.true',book_id:`eq.${sel.bookId}`,unit_id:`eq.${sel.unitId}`,section:`eq.${section}`});const r=await fetch(`${U}/rest/v1/test_prep_questions?${q}`,{headers:H,cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
function typeBalanced(rows,count,used=new Set()){const pool=rows.filter(q=>!used.has(String(q.id))),groups=new Map();for(const q of shuffle(pool)){const t=String(q.question_type||q.type||'other');if(!groups.has(t))groups.set(t,[]);groups.get(t).push(q)}const keys=shuffle([...groups.keys()]),out=[];let moved=true;while(out.length<count&&moved){moved=false;for(const k of keys){const g=groups.get(k);if(g?.length&&out.length<count){const q=g.shift();used.add(String(q.id));out.push(q);moved=true}}}return out}
async function vocabPool(sel){if(!vocabAllowed(sel))return[];for(let i=0;i<80;i++){const m=window.WillenaVocabTestPractice;if(m?.buildMockPool)return m.buildMockPool(sel.unitId,sel.lesson);await new Promise(r=>setTimeout(r,50))}return[]}
async function seosulPool(sel,count){if(!count)return[];for(let i=0;i<100;i++){const m=window.WillenaSeosulEngine;if(m?.loadBank){const d=await m.loadBank(sel.unitId);return shuffle((d.bank||[]).filter(q=>!q.selfCheck)).slice(0,count).map(q=>({...q,__seosul:true,section:'constructed_response',question_type:q.type,prompt_text:q.instruction,correct_answer:q.answer,student_source_label:'Willena Generated'}))}await new Promise(r=>setTimeout(r,50))}return[]}
function targetsForMock(sel,reserved){const t={...BLUEPRINT};if(!vocabAllowed(sel))t.vocab_test=0;for(const section of REGULAR)if(!scopeSections(sel).includes(section))t[section]=0;let remove=reserved;for(const k of ['reading','grammar','communication','vocab_test']){while(remove>0&&t[k]>0){t[k]--;remove--}}return t}
async function buildMock(sel){
 const requested=seosulCount(sel),sections=scopeSections(sel),targets=targetsForMock(sel,requested),regularPools=await Promise.all(sections.map(async section=>({section,rows:await fetchSection(sel,section)}))),vocab=await vocabPool(sel),written=await seosulPool(sel,requested),used=new Set(),picked=[];
 if(vocab.length&&targets.vocab_test)picked.push(...typeBalanced(vocab,Math.min(targets.vocab_test,vocab.length),used));
 for(const section of REGULAR){const pool=regularPools.find(x=>x.section===section);if(!pool?.rows?.length||!targets[section])continue;picked.push(...typeBalanced(pool.rows,targets[section],used))}
 const mcTarget=25-written.length;if(picked.length<mcTarget){const leftovers=[...vocab,...regularPools.flatMap(x=>x.rows)];picked.push(...typeBalanced(leftovers,mcTarget-picked.length,used))}
 const mc=picked.slice(0,mcTarget),vocabFirst=mc.filter(q=>q.section==='vocab_test'),rest=mc.filter(q=>q.section!=='vocab_test');
 return[...shuffle(vocabFirst),...shuffle(rest),...shuffle(written)]
}
function injectCard(){const subway=document.querySelector('#assignmentHome .tp-subway');if(!subway||document.querySelector('.tp-mock-card'))return;const hs=history.state||{},planId=hs.planId,lesson=hs.lesson;if(!planId||!lesson)return;const plan=window.WillenaTestPrepAuth?.state?.plans?.find(p=>String(p.id)===String(planId)),row=plan?.group?.scope?.lessons?.find(x=>String(x.lesson)===String(lesson)),n=row&&Array.isArray(row.sections)&&row.sections.includes('constructed_response')?Math.max(0,Math.min(10,Number(plan?.group?.scope?.constructed_response_count)||0)):0;const b=document.createElement('button');b.type='button';b.className='tp-mock-card';b.innerHTML=`<span class="tp-mock-icon">25</span><span class="tp-mock-copy"><b>모의고사</b><small>25문제${n?` · 서술형 ${n}문제`:''} · 이 Lesson 시험 범위</small></span><span class="tp-mock-go">START →</span>`;b.onclick=async()=>{history.pushState({tp:'practice',planId:String(planId),lesson:String(lesson),skill:'mock',returnTo:'lesson'},'',location.href);await window.WillenaAssignedTestPrep?.startSelection?.(planId,lesson,'mock')};subway.insertAdjacentElement('afterend',b)}
function writtenHtml(q){const bank=q.bank?.length?q.bank:(q.chips?.length?q.chips:[]);return `<div class="seosul-kind">${esc(q.kind||'서술형')}</div><p class="seosul-instruction">${esc(q.instruction||q.prompt_text||'답을 쓰세요.')}</p><div class="seosul-source">${esc(q.source||'')}</div>${bank.length?`<div class="seosul-bank">${bank.map(w=>`<span class="seosul-word">${esc(w)}</span>`).join('')}</div>`:''}<textarea class="seosul-answer" id="mockWrittenAnswer" spellcheck="false" placeholder="답을 입력하세요"></textarea><div class="feedback" id="mockFeedback"></div><div class="seosul-model" id="mockWrittenModel"><b>정답</b>${esc(q.answer||q.correct_answer||'')}</div><div class="actions"><button class="primary" id="mockCheck" disabled>정답 확인</button></div>`}
function render(){const c=card(),b=bar();if(!c||!b)return;if(index>=questions.length){finish();return}const q=questions[index];selected=new Set();checked=false;startedAt=Date.now();b.style.width=`${index/questions.length*100}%`;if(q.__seosul){c.innerHTML=`<div class="card-head"><div><div class="mock-kicker">모의고사 · 서술형 · ${esc(q.kind||q.question_type||'')}</div><div class="qnum">${index+1} / ${questions.length}</div></div></div><div class="body">${writtenHtml(q)}</div>`;const input=document.getElementById('mockWrittenAnswer'),btn=document.getElementById('mockCheck');input.oninput=()=>btn.disabled=!input.value.trim();input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!btn.disabled){e.preventDefault();btn.click()}};btn.onclick=()=>checkWritten(q,input.value);setTimeout(()=>input.focus(),30);return}c.innerHTML=`<div class="card-head"><div><div class="mock-kicker">모의고사 · ${esc(LABEL[q.section]||q.section)} · ${esc(q.question_type||'')}</div><div class="qnum">${index+1} / ${questions.length}</div></div><button class="mock-flag" id="mockFlag" aria-label="문제 신고">⚑</button></div><div class="body"><div class="prompt">${esc(q.prompt_text||'')}</div>${contextHtml(q)}<div class="choices">${(q.choices||[]).map((x,i)=>`<button class="choice" data-i="${i+1}"><span class="n">${['①','②','③','④','⑤','⑥'][i]||i+1}</span><span class="t">${text(typeof x==='string'?x:(x.text||JSON.stringify(x)))}</span></button>`).join('')}</div><div class="feedback" id="mockFeedback"></div><div class="explanation" id="mockExplanation"></div><div class="actions"><button class="primary" id="mockCheck" disabled>정답 확인</button></div></div>`;c.querySelectorAll('.choice').forEach(x=>x.onclick=()=>choose(x,q));document.getElementById('mockCheck').onclick=()=>check(q);document.getElementById('mockFlag').onclick=()=>flag(q)}
function choose(b,q){if(checked)return;const n=b.dataset.i;if(q.answer_mode==='multi_select'){selected.has(n)?selected.delete(n):selected.add(n);b.classList.toggle('selected')}else{selected=new Set([n]);card().querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}document.getElementById('mockCheck').disabled=!selected.size}
function same(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}
function check(q){if(checked){index++;render();return}checked=true;const ans=(q.correct_answer||[]).map(String),mine=[...selected].map(String),ok=same(mine,ans);if(ok)score++;else wrongIds.push(q.id);const p=window.WillenaTestPrepAuth?.recordAttempt?.({practice_type:q.section,question_id:q.id,selected_answer:mine,correct_answer:ans,is_correct:ok,source_question_number:q.source_question_number,question_type:q.question_type,source_label:q.student_source_label,targets:Array.isArray(q.targets)?q.targets:[],metadata:{...(q.metadata||{}),mock_test:true,mock_size:25,underlying_section:q.section}});pending.push(Promise.resolve(p).catch(()=>null));card().querySelectorAll('.choice').forEach(b=>{const n=b.dataset.i;if(ans.includes(n))b.classList.add('correct');else if(selected.has(n))b.classList.add('wrong')});const f=document.getElementById('mockFeedback');f.className='feedback '+(ok?'ok':'bad');f.textContent=ok?'정답입니다!':'정답: '+ans.join(', ')+'번';if(!ok&&q.metadata?.source_explanation_ko){const e=document.getElementById('mockExplanation');e.innerHTML=`<strong>해설</strong>${text(q.metadata.source_explanation_ko)}`;e.classList.add('show')}const btn=document.getElementById('mockCheck');btn.disabled=false;btn.textContent=index===questions.length-1?'결과 보기':'다음 문제'}
function checkWritten(q,mine){if(checked){index++;render();return}checked=true;const ans=String(q.answer||q.correct_answer||''),ok=answerNorm(mine)===answerNorm(ans);if(ok)score++;else wrongIds.push(q.id);const p=window.WillenaTestPrepAuth?.recordAttempt?.({practice_type:'constructed_response',question_id:q.id,selected_answer:mine,correct_answer:ans,is_correct:ok,question_type:q.type||q.question_type,source_label:'Willena Generated',targets:Array.isArray(q.targets)?q.targets:[],response_time_ms:Date.now()-startedAt,metadata:{mock_test:true,mock_size:25,generated:true,origin_id:q.origin,engine:'seosul_v1'}});pending.push(Promise.resolve(p).catch(()=>null));const f=document.getElementById('mockFeedback');f.className='feedback '+(ok?'ok':'bad');f.textContent=ok?'정답입니다!':'정답을 확인해 보세요.';document.getElementById('mockWrittenModel')?.classList.add('show');const btn=document.getElementById('mockCheck');btn.disabled=false;btn.textContent=index===questions.length-1?'결과 보기':'다음 문제';btn.onclick=()=>{index++;render()}}
async function finish(){if(finishing)return;finishing=true;const c=card(),b=bar();if(!c||!b)return;await Promise.allSettled(pending);try{await window.WillenaTestPrepAuth?.completeSession?.(0,0,wrongIds)}catch(_){}b.style.width='100%';const total=questions.length,p=total?Math.round(score/total*100):0,wrong=[...new Set(wrongIds)],hasWrong=wrong.length>0;c.innerHTML=`<div class="result"><div class="score">${score}/${total}</div><div class="mock-percent">${p}%</div><h2>모의고사 완료</h2><p>오답 ${wrong.length}개</p><div class="mock-result-actions">${hasWrong?'<button class="mock-btn" id="mockWrong">오답하기</button>':''}<button class="mock-btn" id="mockDone">완료</button></div></div>`;document.getElementById('mockDone').onclick=()=>document.querySelector('#assignedBackRow .back-assign')?.click();if(hasWrong)document.getElementById('mockWrong').onclick=()=>{const set=new Set(wrong);questions=questions.filter(q=>set.has(q.id));index=0;score=0;wrongIds=[];pending=[];finishing=false;render()}}
function flag(q){window.WillenaPracticeFlagger?.open?.({source_type:'mock_question',source_id:String(q.id),snapshot:{page:location.pathname,lesson:window.WillenaAssignedTestPrep?.selection?.lesson||null,practice_type:'mock',section:q.section,question_id:q.id,question_type:q.question_type,prompt:q.prompt_text,choices:q.choices,correct_answer:q.correct_answer,source_question_number:q.source_question_number}})}
async function startMock(){const sel=window.WillenaAssignedTestPrep?.selection,c=card(),b=bar();if(!sel||!c||!b)return;c.innerHTML='<div class="loading">모의고사 25문제를 준비하는 중...</div>';b.style.width='0';const context=document.querySelector('.quiz-context');if(context)context.textContent=`${sel.plan?.book_label||''} · ${sel.lesson} · 모의고사`;try{questions=await buildMock(sel);if(!questions.length)throw new Error('모의고사 문제를 찾지 못했습니다.');index=0;score=0;wrongIds=[];pending=[];finishing=false;render()}catch(e){c.innerHTML=`<div class="empty">모의고사를 만들지 못했습니다.<br><small>${esc(e.message)}</small></div>`}}
function patchEngine(){if(patched)return true;const engine=window.WillenaTestPrepQuestionEngine;if(!engine?.loadSection)return false;const original=engine.loadSection.bind(engine);engine.loadSection=function(name){if(String(name).toLowerCase()==='mock')return startMock();return original(name)};patched=true;return true}
function boot(){let tries=0;const timer=setInterval(()=>{patchEngine();injectCard();if(++tries>200)clearInterval(timer)},50);new MutationObserver(injectCard).observe(document.body,{childList:true,subtree:true})}
window.WillenaMockTest={start:startMock,injectCard,buildMock};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();