(function(){
'use strict';
const U='https://gxwfsqxyuufqtitspfqg.supabase.co';
const K=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const H={apikey:K,Authorization:`Bearer ${K}`};
const REGULAR=['communication','grammar','reading'];
const LABEL={communication:'Communication',grammar:'Grammar',reading:'Reading'};
let patched=false,questions=[],index=0,score=0,selected=new Set(),checked=false,wrongIds=[],pending=[],finishing=false;
const card=()=>document.getElementById('card'),bar=()=>document.getElementById('bar');
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=v=>{let s=String(v??'').replace(/\r\n?/g,'\n');for(let i=0;i<4;i++)s=s.replace(/\\+n/g,'\n');return s};
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
function text(v){return norm(v).split('\n').map(x=>`<span class="line">${esc(x)}</span>`).join('')}
function block(title,v){if(v==null||v==='')return'';return `<div class="context">${title?`<div class="context-title">${esc(title)}</div>`:''}${text(v)}</div>`}
function arr(title,a){if(!Array.isArray(a)||!a.length)return'';return `<div class="context">${title?`<div class="context-title">${esc(title)}</div>`:''}<div class="items">${a.map(x=>`<div class="item">${Array.isArray(x)?x.map(y=>text(y)).join('<hr>'):text(x)}</div>`).join('')}</div></div>`}
function obj(title,o,cls='segment'){if(!o||typeof o!=='object'||Array.isArray(o))return'';return `<div class="context"><div class="context-title">${esc(title)}</div><div class="${cls==='claim'?'claims':'segments'}">${Object.entries(o).map(([k,v])=>`<div class="${cls}"><b>${esc(k)}</b> ${text(v)}</div>`).join('')}</div></div>`}
function contextHtml(q){const c=q.context||{};let o='';if(c.passage)o+=block('',c.passage);if(c.passage_start)o+=block('',c.passage_start)+obj('A–D',c.segments)+block('',c.passage_end);if(c.source_passage)o+=block('원문',c.source_passage);if(c.rewritten)o+=block('바꿔 쓴 글',c.rewritten);if(c.dialogue)o+=block('대화',c.dialogue);if(c.dialogue_start)o+=block('',c.dialogue_start)+obj('A–D',c.segments)+block('',c.dialogue_end);if(c.dialogue_a)o+=block('대화 A',c.dialogue_a);if(c.dialogue_b)o+=block('대화 B',c.dialogue_b);if(c.dialogue1)o+=block('대화 1',c.dialogue1);if(c.dialogue2)o+=block('대화 2',c.dialogue2);if(c.given_sentence)o+=block('<보기>',c.given_sentence);if(c.bank)o+=Array.isArray(c.bank)?arr('<보기>',c.bank):typeof c.bank==='object'?obj('<보기>',c.bank):block('<보기>',c.bank);o+=arr('',c.items);o+=arr('',c.pairs);o+=arr('문제 단서',c.clues);o+=arr('',c.statements);o+=obj('설명',c.claims,'claim');if(c.table)o+=obj('표',c.table);if(c.definition)o+=block('정의',c.definition);if(c.korean)o+=block('우리말',c.korean);if(c.pattern)o+=block('형식',c.pattern);if(c.target)o+=block('대상',c.target);if(c.A)o+=block('(A)',c.A);if(c.B)o+=block('(B)',c.B);if(c.proposed_pairs)o+=arr('',c.proposed_pairs);return o}
function scopeSections(sel){const lesson=sel?.plan?.group?.scope?.lessons?.find(x=>String(x.lesson)===String(sel.lesson)),raw=Array.isArray(lesson?.sections)?lesson.sections:(sel?.plan?.practice_types||[]),allowed=raw.map(x=>String(x).toLowerCase()).filter(x=>REGULAR.includes(x));return allowed.length?[...new Set(allowed)]:REGULAR}
async function fetchSection(sel,section){const fields='id,section,source_question_number,question_type,prompt_text,context,choices,correct_answer,targets,answer_mode,student_source_label,content_status,metadata';const q=new URLSearchParams({select:fields,student_usable:'eq.true',book_id:`eq.${sel.bookId}`,unit_id:`eq.${sel.unitId}`,section:`eq.${section}`});const r=await fetch(`${U}/rest/v1/test_prep_questions?${q}`,{headers:H,cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
function allocate(total,sections){const order=shuffle(sections),base=Math.floor(total/order.length),rem=total%order.length;return order.map((s,i)=>({section:s,count:base+(i<rem?1:0)}))}
async function buildMock(sel){const sections=scopeSections(sel),parts=allocate(25,sections),all=[];for(const p of parts){const rows=await fetchSection(sel,p.section);all.push(...shuffle(rows).slice(0,p.count))}if(all.length<25){const existing=new Set(all.map(x=>x.id));for(const s of sections){const rows=await fetchSection(sel,s);for(const q of shuffle(rows)){if(all.length>=25)break;if(!existing.has(q.id)){existing.add(q.id);all.push(q)}}}}const sectionOrder=shuffle(sections),rank=new Map(sectionOrder.map((s,i)=>[s,i]));return all.slice(0,25).sort((a,b)=>(rank.get(a.section)??9)-(rank.get(b.section)??9)||Math.random()-.5)}
function addStyles(){if(document.getElementById('tpMockStyle'))return;const s=document.createElement('style');s.id='tpMockStyle';s.textContent=`.tp-mock-card{width:100%;margin-top:16px;border:2px solid #67d4da;background:#fff;border-radius:20px;padding:17px 18px;display:grid;grid-template-columns:48px 1fr auto;gap:13px;align-items:center;text-align:left;color:#203039;cursor:pointer}.tp-mock-icon{width:48px;height:48px;border-radius:15px;border:2px solid #67d4da;color:#ee5f91;display:grid;place-items:center;font-size:18px;font-weight:900}.tp-mock-copy b{display:block;font-size:14px}.tp-mock-copy small{display:block;font-size:9px;color:#7c8b92;margin-top:3px}.tp-mock-go{color:#ee5f91;font-size:11px;font-weight:900}.mock-kicker{font-size:10px;color:#07888d;font-weight:800;margin-bottom:4px}.mock-result-actions{display:flex;gap:9px;margin-top:16px}.mock-btn{flex:1;border:2px solid #67d4da;background:#fff;color:#ee5f91;border-radius:14px;padding:13px 15px;font-weight:800;cursor:pointer}.mock-flag{width:34px;height:34px;border:2px solid #67d4da;background:#fff;color:#ee5f91;border-radius:50%;display:grid;place-items:center;font-size:15px;cursor:pointer}`;document.head.appendChild(s)}
function injectCard(){addStyles();const subway=document.querySelector('#assignmentHome .tp-subway');if(!subway||document.querySelector('.tp-mock-card'))return;const hs=history.state||{},planId=hs.planId,lesson=hs.lesson;if(!planId||!lesson)return;const b=document.createElement('button');b.type='button';b.className='tp-mock-card';b.innerHTML='<span class="tp-mock-icon">25</span><span class="tp-mock-copy"><b>모의고사</b><small>25문제 · 이 Lesson 시험 범위</small></span><span class="tp-mock-go">START →</span>';b.onclick=async()=>{history.pushState({tp:'practice',planId:String(planId),lesson:String(lesson),skill:'mock',returnTo:'lesson'},'',location.href);await window.WillenaAssignedTestPrep?.startSelection?.(planId,lesson,'mock')};subway.insertAdjacentElement('afterend',b)}
function render(){const c=card(),b=bar();if(!c||!b)return;if(index>=questions.length){finish();return}const q=questions[index];selected=new Set();checked=false;b.style.width=`${index/questions.length*100}%`;c.innerHTML=`<div class="card-head"><div><div class="mock-kicker">모의고사 · ${esc(LABEL[q.section]||q.section)}</div><div class="qnum">${index+1} / ${questions.length}</div></div><button class="mock-flag" id="mockFlag" aria-label="문제 신고">⚑</button></div><div class="body"><div class="prompt">${esc(q.prompt_text||'')}</div>${contextHtml(q)}<div class="choices">${(q.choices||[]).map((x,i)=>`<button class="choice" data-i="${i+1}"><span class="n">${['①','②','③','④','⑤','⑥'][i]||i+1}</span><span class="t">${text(typeof x==='string'?x:(x.text||JSON.stringify(x)))}</span></button>`).join('')}</div><div class="feedback" id="mockFeedback"></div><div class="explanation" id="mockExplanation"></div><div class="actions"><button class="primary" id="mockCheck" disabled>정답 확인</button></div></div>`;c.querySelectorAll('.choice').forEach(x=>x.onclick=()=>choose(x,q));document.getElementById('mockCheck').onclick=()=>check(q);document.getElementById('mockFlag').onclick=()=>flag(q)}
function choose(b,q){if(checked)return;const n=b.dataset.i;if(q.answer_mode==='multi_select'){selected.has(n)?selected.delete(n):selected.add(n);b.classList.toggle('selected')}else{selected=new Set([n]);card().querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}document.getElementById('mockCheck').disabled=!selected.size}
function same(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}
function check(q){if(checked){index++;render();return}checked=true;const ans=(q.correct_answer||[]).map(String),mine=[...selected].map(String),ok=same(mine,ans);if(ok)score++;else wrongIds.push(q.id);const p=window.WillenaTestPrepAuth?.recordAttempt?.({practice_type:q.section,question_id:q.id,selected_answer:mine,correct_answer:ans,is_correct:ok,source_question_number:q.source_question_number,question_type:q.question_type,source_label:q.student_source_label,targets:Array.isArray(q.targets)?q.targets:[],metadata:{mock_test:true,mock_size:25,underlying_section:q.section}});pending.push(Promise.resolve(p).catch(()=>null));card().querySelectorAll('.choice').forEach(b=>{const n=b.dataset.i;if(ans.includes(n))b.classList.add('correct');else if(selected.has(n))b.classList.add('wrong')});const f=document.getElementById('mockFeedback');f.className='feedback '+(ok?'ok':'bad');f.textContent=ok?'정답입니다!':'정답: '+ans.join(', ')+'번';if(!ok&&q.metadata?.source_explanation_ko){const e=document.getElementById('mockExplanation');e.innerHTML=`<strong>해설</strong>${text(q.metadata.source_explanation_ko)}`;e.classList.add('show')}const btn=document.getElementById('mockCheck');btn.disabled=false;btn.textContent=index===questions.length-1?'결과 보기':'다음 문제'}
async function finish(){if(finishing)return;finishing=true;const c=card(),b=bar();if(!c||!b)return;await Promise.allSettled(pending);try{await window.WillenaTestPrepAuth?.completeSession?.(0,0,wrongIds)}catch(_){}b.style.width='100%';const total=questions.length,p=total?Math.round(score/total*100):0,wrong=[...new Set(wrongIds)],hasWrong=wrong.length>0;c.innerHTML=`<div class="result"><div class="score">${score}/${total}</div><h2>모의고사 완료</h2><p>정답률 ${p}% · 오답 ${wrong.length}개</p><div class="mock-result-actions">${hasWrong?'<button class="mock-btn" id="mockWrong">오답하기</button>':''}<button class="mock-btn" id="mockDone">완료</button></div></div>`;document.getElementById('mockDone').onclick=()=>document.querySelector('#assignedBackRow .back-assign')?.click();if(hasWrong)document.getElementById('mockWrong').onclick=()=>{const set=new Set(wrong);questions=questions.filter(q=>set.has(q.id)).sort((a,b)=>String(a.section).localeCompare(String(b.section)));index=0;score=0;wrongIds=[];pending=[];finishing=false;render()}}
function flag(q){window.WillenaPracticeFlagger?.open?.({source_type:'mock_question',source_id:String(q.id),snapshot:{page:location.pathname,lesson:window.WillenaAssignedTestPrep?.selection?.lesson||null,practice_type:'mock',section:q.section,question_id:q.id,question_type:q.question_type,prompt:q.prompt_text,choices:q.choices,correct_answer:q.correct_answer,source_question_number:q.source_question_number}})}
async function startMock(){const sel=window.WillenaAssignedTestPrep?.selection,c=card(),b=bar();if(!sel||!c||!b)return;c.innerHTML='<div class="loading">모의고사 25문제를 준비하는 중...</div>';b.style.width='0';const context=document.querySelector('.quiz-context');if(context)context.textContent=`${sel.plan?.book_label||''} · ${sel.lesson} · 모의고사`;try{questions=await buildMock(sel);if(!questions.length)throw new Error('모의고사 문제를 찾지 못했습니다.');index=0;score=0;wrongIds=[];pending=[];finishing=false;render()}catch(e){c.innerHTML=`<div class="empty">모의고사를 만들지 못했습니다.<br><small>${esc(e.message)}</small></div>`}}
function patchEngine(){if(patched)return true;const engine=window.WillenaTestPrepQuestionEngine;if(!engine?.loadSection)return false;const original=engine.loadSection.bind(engine);engine.loadSection=function(name){if(String(name).toLowerCase()==='mock')return startMock();return original(name)};patched=true;return true}
function boot(){addStyles();let tries=0;const timer=setInterval(()=>{patchEngine();injectCard();if(++tries>200)clearInterval(timer)},50);new MutationObserver(injectCard).observe(document.body,{childList:true,subtree:true})}
window.WillenaMockTest={start:startMock,injectCard};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();
