const U='https://gxwfsqxyuufqtitspfqg.supabase.co',K=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join(''),H={apikey:K,Authorization:`Bearer ${K}`,'Content-Type':'application/json'};
const card=document.getElementById('card'),bar=document.getElementById('bar'),overlay=document.getElementById('overlay'),reasonsEl=document.getElementById('reasons'),flagNote=document.getElementById('flagNote');
let section='communication',bank=[],questions=[],index=0,selected=new Set(),checked=false,score=0,wrongIds=[],flagReason='';
const flagReasons=['정답이 이상함','문제가 애매함','영어가 이상함','시험 범위와 안 맞음','너무 쉬움','너무 어려움','반복 문제','화면/표시 문제','기타'];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
function norm(v){let s=String(v??'').replace(/\r\n?/g,'\n');for(let i=0;i<4;i++)s=s.replace(/\\+n/g,'\n');return s}
function markedLine(v,spans=[]){const src=String(v??'');if(!Array.isArray(spans))spans=[spans];const ss=[...new Set(spans.map(String).filter(Boolean))];if(!src||!ss.length)return esc(src);const hits=[];for(const x of ss){let from=0;while(from<src.length){const p=src.indexOf(x,from);if(p<0)break;hits.push([p,p+x.length]);from=p+x.length}}if(!hits.length)return esc(src);hits.sort((a,b)=>a[0]-b[0]||b[1]-a[1]);const merged=[];for(const h of hits){const last=merged[merged.length-1];if(!last||h[0]>=last[1])merged.push([...h]);else last[1]=Math.max(last[1],h[1])}let out='',p=0;for(const [a,b] of merged){out+=esc(src.slice(p,a))+`<span class="u">${esc(src.slice(a,b))}</span>`;p=b}return out+esc(src.slice(p))}
function text(v,spans=[]){return norm(v).split('\n').map(x=>`<span class="line">${markedLine(x,spans)}</span>`).join('')}
function spans(c){const a=[];if(c?.underlined)a.push(c.underlined);if(Array.isArray(c?.underlined_spans))a.push(...c.underlined_spans);return [...new Set(a.map(String).filter(Boolean))]}
function block(title,v,u=[]){if(v==null||v==='')return'';return `<div class="context">${title?`<div class="context-title">${esc(title)}</div>`:''}${text(v,u)}</div>`}
function arr(title,a,u=[]){if(!Array.isArray(a)||!a.length)return'';return `<div class="context">${title?`<div class="context-title">${esc(title)}</div>`:''}<div class="items">${a.map(x=>`<div class="item">${Array.isArray(x)?x.map(y=>text(y,u)).join('<hr>'):text(x,u)}</div>`).join('')}</div></div>`}
function obj(title,o,cls='segment',u=[]){if(!o||typeof o!=='object'||Array.isArray(o))return'';return `<div class="context"><div class="context-title">${esc(title)}</div><div class="${cls==='claim'?'claims':'segments'}">${Object.entries(o).map(([k,v])=>`<div class="${cls}"><b>${esc(k)}</b> ${text(v,u)}</div>`).join('')}</div></div>`}
function ctx(q){const c=q.context||{},u=spans(c);let o='';if(c.sentence)o+=block('',c.sentence,u);if(c.passage)o+=block('',c.passage,u);if(c.passage_start)o+=block('',c.passage_start,u)+obj('A–D',c.segments,'segment',u)+block('',c.passage_end,u);if(c.source_passage)o+=block('원문',c.source_passage,u);if(c.rewritten)o+=block('바꿔 쓴 글',c.rewritten,u);if(c.dialogue)o+=block('대화',c.dialogue,u);if(c.dialogue_start)o+=block('',c.dialogue_start,u)+obj('A–D',c.segments,'segment',u)+block('',c.dialogue_end,u);if(c.dialogue_a)o+=block('대화 A',c.dialogue_a,u);if(c.dialogue_b)o+=block('대화 B',c.dialogue_b,u);if(c.dialogue1)o+=block('대화 1',c.dialogue1,u);if(c.dialogue2)o+=block('대화 2',c.dialogue2,u);if(c.given_sentence)o+=block('<보기>',c.given_sentence,u);if(c.bank)o+=Array.isArray(c.bank)?arr('<보기>',c.bank,u):typeof c.bank==='object'?obj('<보기>',c.bank,'segment',u):block('<보기>',c.bank,u);o+=arr('',c.items,u);o+=arr('',c.pairs,u);o+=arr('문제 단서',c.clues,u);o+=arr('',c.statements,u);o+=obj('설명',c.claims,'claim',u);if(c.table)o+=obj('표',c.table,'segment',u);if(c.definition)o+=block('정의',c.definition,u);if(c.korean)o+=block('우리말',c.korean,u);if(c.pattern)o+=block('형식',c.pattern,u);if(c.target)o+=block('대상',c.target,u);if(c.source)o+=block('',c.source,u);if(c.source_sentence)o+=block('',c.source_sentence,u);if(c.source_phrase)o+=block('',c.source_phrase,u);if(c.phrase)o+=block('',c.phrase,u);if(c.example)o+=block('',c.example,u);if(c.incorrect)o+=block('',c.incorrect,u);if(c.original)o+=block('원문',c.original,u);if(c.comparison)o+=block('비교',c.comparison,u);if(c.word)o+=block('',c.word,u);if(c.A)o+=block('(A)',c.A,u);if(c.B)o+=block('(B)',c.B,u);if(c.a)o+=block('(A)',c.a,u);if(c.b)o+=block('(B)',c.b,u);if(c.proposed_pairs)o+=arr('',c.proposed_pairs,u);return o}
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
function toast(t){const x=document.getElementById('toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),1600)}
function isW(q){return q.content_status==='willena_published'}
function sourceLabel(q){return isW(q)?'응용 문제':'유형별 문제'}
function sourceNumber(q){return isW(q)?`W${q.metadata?.willena_question_number||q.source_question_number}`:`Q${q.source_question_number}`}
function renderableChoiceQuestion(q){return !!q&&Array.isArray(q.choices)&&q.choices.length>0&&['single_choice','single_select','multi_select'].includes(String(q.answer_mode||''))}
async function applyFilter(){const sel=window.WillenaAssignedTestPrep?.selection,session=window.WillenaTestPrepSession;if(sel?.reviewMode){questions=shuffle(bank)}else if(session?.smartSelect&&sel?.plan?.id){questions=await session.smartSelect(bank,{planId:sel.plan.id,lesson:sel.lesson,practice:section,typeBalance:true,typeFn:q=>q.question_type||'other'})}else{questions=shuffle(bank).slice(0,20)}index=0;score=0;wrongIds=[];selected=new Set();checked=false;render()}
function render(){if(!questions.length){card.innerHTML='<div class="empty">이 영역에 해당하는 문제가 없습니다.</div>';bar.style.width='0';return}if(index>=questions.length)return result();const q=questions[index];selected=new Set();checked=false;bar.style.width=`${index/questions.length*100}%`;const w=isW(q),u=spans(q.context||{});card.innerHTML=`<div class="card-head"><div class="qnum">${index+1} / ${questions.length}</div><div style="display:flex;align-items:center;gap:4px"><span class="source ${w?'w':''}">${sourceLabel(q)} · ${sourceNumber(q)}</span><button class="flag" id="flagBtn">🚩</button></div></div><div class="body"><div class="prompt">${esc(q.prompt_text||'')}</div>${ctx(q)}<div class="choices">${(q.choices||[]).map((x,i)=>`<button class="choice" data-i="${i+1}"><span class="n">${['①','②','③','④','⑤','⑥'][i]||i+1}</span><span class="t">${text(typeof x==='string'?x:(x.text||JSON.stringify(x)),u)}</span></button>`).join('')}</div><div class="feedback" id="feedback"></div><div class="explanation" id="explanation"></div><div class="actions"><button class="primary" id="check" disabled>정답 확인</button></div></div>`;card.querySelectorAll('.choice').forEach(b=>b.onclick=()=>choose(b,q));document.getElementById('check').onclick=()=>check(q);document.getElementById('flagBtn').onclick=openFlag}
function choose(b,q){if(checked)return;const n=b.dataset.i;if(q.answer_mode==='multi_select'){selected.has(n)?selected.delete(n):selected.add(n);b.classList.toggle('selected')}else{selected=new Set([n]);card.querySelectorAll('.choice').forEach(x=>x.classList.remove('selected'));b.classList.add('selected')}document.getElementById('check').disabled=!selected.size}
function same(a,b){return a.length===b.length&&a.every(x=>b.includes(x))}
function check(q){if(checked){index++;return render()}checked=true;const ans=(q.correct_answer||[]).map(String),mine=[...selected].map(String),ok=same(mine,ans);if(ok)score++;else wrongIds.push(q.id);window.WillenaTestPrepAuth?.recordAttempt({practice_type:section,question_id:q.id,selected_answer:mine,correct_answer:ans,is_correct:ok,source_question_number:q.source_question_number,question_type:q.question_type,source_label:q.student_source_label,targets:Array.isArray(q.targets)?q.targets:[]});card.querySelectorAll('.choice').forEach(b=>{const n=b.dataset.i;if(ans.includes(n))b.classList.add('correct');else if(selected.has(n))b.classList.add('wrong')});const f=document.getElementById('feedback');f.className='feedback '+(ok?'ok':'bad');f.textContent=ok?'정답입니다!':'정답: '+ans.join(', ')+'번';if(!ok&&q.metadata?.source_explanation_ko){const e=document.getElementById('explanation');e.innerHTML=`<strong>해설</strong>${text(q.metadata.source_explanation_ko)}`;e.classList.add('show')}const c=document.getElementById('check');c.disabled=false;c.textContent=index===questions.length-1?'결과 보기':'다음 문제'}
function result(){window.WillenaTestPrepAuth?.completeSession(score,questions.length,wrongIds);bar.style.width='100%';const p=questions.length?Math.round(score/questions.length*100):0;card.innerHTML=`<div class="result"><div class="score">${score}/${questions.length}</div><h2>${p>=80?'좋아요! 시험 준비가 잘 되고 있어요.':'틀린 문제를 한 번 더 보면 좋아요.'}</h2><p>정답률 ${p}% · 틀린 문제 ${wrongIds.length}개</p><div class="actions"><button class="secondary" id="again">새 문제 세트</button>${wrongIds.length?'<button class="primary" id="retry">오답하기</button>':''}</div></div>`;document.getElementById('again').onclick=()=>applyFilter();if(wrongIds.length)document.getElementById('retry').onclick=()=>{questions=shuffle(questions.filter(q=>wrongIds.includes(q.id)));index=0;score=0;wrongIds=[];render()}}
function openFlag(){flagReason='';flagNote.value='';reasonsEl.innerHTML=flagReasons.map(r=>`<button class="reason">${r}</button>`).join('');reasonsEl.querySelectorAll('.reason').forEach(b=>b.onclick=()=>{flagReason=b.textContent;reasonsEl.querySelectorAll('.reason').forEach(x=>x.classList.toggle('on',x===b))});overlay.classList.add('open')}
document.getElementById('cancelFlag').onclick=()=>overlay.classList.remove('open');
overlay.onclick=e=>{if(e.target===overlay)overlay.classList.remove('open')};
document.getElementById('sendFlag').onclick=async()=>{if(!flagReason)return toast('이유를 하나 골라 주세요');const q=questions[index],payload={question_id:q.id,reason:flagReason,note:flagNote.value.trim()||null,selected_answer:[...selected],correct_answer_snapshot:q.correct_answer||[],status:'open',metadata:{source_label:q.student_source_label,source_question_number:q.source_question_number,question_type:q.question_type,section,page:location.pathname}};try{const r=await fetch(`${U}/rest/v1/test_prep_question_flags`,{method:'POST',headers:{...H,Prefer:'return=minimal'},body:JSON.stringify(payload)});if(!r.ok)throw Error(await r.text());overlay.classList.remove('open');toast('신고했습니다. 고마워요!')}catch(e){console.error(e);toast('신고 저장에 실패했습니다')}};
async function load(){card.innerHTML='<div class="loading">문제를 불러오는 중...</div>';bar.style.width='0';const sel='id,source_question_number,source_page,question_type,prompt_text,context,choices,correct_answer,targets,answer_mode,context_type,difficulty,student_source_label,content_status,metadata';try{const aq=window.WillenaAssignedTestPrep?.questionQuery?.()||'';const r=await fetch(`${U}/rest/v1/test_prep_questions?select=${encodeURIComponent(sel)}&student_usable=eq.true&section=eq.${section}${aq}&order=source_question_number.asc`,{headers:H,cache:'no-store'});if(!r.ok)throw Error(await r.text());const rows=await r.json();bank=rows.filter(renderableChoiceQuestion);const skipped=rows.length-bank.length;if(skipped)console.info(`[test-prep] skipped ${skipped} non-choice/constructed-response ${section} questions; use the 서술형 flow for text answers`);await applyFilter()}catch(e){card.innerHTML=`<div class="empty">문제를 불러오지 못했습니다.<br><small>${esc(e.message)}</small></div>`}}
window.WillenaTestPrepQuestionEngine={loadSection(name){section=String(name||'communication').toLowerCase();return load()},reload:load,get section(){return section}};
