(function(){
'use strict';
const EDGE='https://fiieuiktlsivwfgyivai.supabase.co/functions/v1/test-prep-review';
const API_KEY='sb_publishable_e-K50PquV9gHdfmefG6tmg_o-vVSl0e';
const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot',"'":'&#39;'}[c]));
let queue=[],running=false,initialTotal=0;
function token(){return window.WillenaAPI?.getLocalAccessToken?.()||localStorage.getItem('sb_access_token')||''}
async function load(){const t=token();if(!t)throw new Error('로그인이 필요합니다.');const r=await fetch(EDGE,{headers:{Authorization:`Bearer ${t}`,apikey:API_KEY},cache:'no-store'});const d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.error||'오답을 불러오지 못했습니다.');const seen=new Set();return (d.reviews||[]).filter(x=>{const k=`${x.plan_id}::${x.question_id}`;if(seen.has(k))return false;seen.add(k);return true})}
function due(x){return x.due_now===true||!x.next_review_at||new Date(x.next_review_at).getTime()<=Date.now()}
function mins(x){if(!x?.next_review_at)return 0;return Math.max(1,Math.ceil((new Date(x.next_review_at).getTime()-Date.now())/60000))}
function card(reviews){const ready=reviews.filter(due).length,later=reviews.length-ready;return `<button class="tp-wrong-card ${reviews.length?'':'no-wrong'}" ${reviews.length?'':'disabled'}><span class="tp-wrong-icon">↺</span><span class="tp-wrong-copy"><b>${reviews.length?'오답 복습':'오답 없음'}</b><small>${ready?`지금 ${ready}개 복습할 수 있어요`:later?`${later}개가 나중에 다시 나와요`:'현재 남아 있는 오답이 없어요'}</small></span><span class="tp-wrong-count">${reviews.length}<small>개 남음</small></span></button>`}
async function refreshHomeCard(){const home=$('#assignmentHome');if(!home)return;try{const reviews=await load(),old=$('.tp-wrong-card',home);if(old){const wrap=document.createElement('div');wrap.innerHTML=card(reviews);old.replaceWith(wrap.firstElementChild);$('.tp-wrong-card:not(.no-wrong)',home)?.addEventListener('click',show)}}catch(e){console.warn('[REV47b] card refresh failed',e)}}
function progress(done,total){return `<div style="margin:18px 0 24px"><div style="display:flex;justify-content:space-between;font-weight:800"><span>오답 복습</span><span>${done} / ${total}</span></div><div style="height:10px;background:var(--tp-track);border-radius:99px;overflow:hidden;margin-top:9px"><i style="display:block;height:100%;width:${total?Math.round(done/total*100):100}%;background:var(--tp-accent);border-radius:99px"></i></div></div>`}
async function show(){const home=$('#assignmentHome');if(!home)return;home.style.display='block';home.innerHTML='<button class="tp-back">← 시험 대비</button><div class="tp-wrong-page-head"><h1>오답 복습</h1><p>틀린 문제를 하나씩 끝내요.</p></div><div class="tp-review-panel"><div class="tp-review-empty">불러오는 중...</div></div>';$('.tp-back',home).onclick=()=>window.WillenaTestPrepUX?.renderHome?.();try{const all=await load(),ready=all.filter(due),later=all.filter(x=>!due(x));initialTotal=all.length;const next=later.sort((a,b)=>new Date(a.next_review_at)-new Date(b.next_review_at))[0];$('.tp-review-panel',home).innerHTML=`${progress(0,all.length)}<div style="display:grid;grid-template-columns:repeat(3,1fr);gap:10px;margin-bottom:18px"><div class="tp-stat"><b>${ready.length}</b><span>지금 복습</span></div><div class="tp-stat"><b>${later.length}</b><span>나중에</span></div><div class="tp-stat"><b>${all.length}</b><span>남은 오답</span></div></div>${ready.length?`<button class="tp-review-start">${ready.length}개 복습 시작 →</button>`:all.length?`<div class="tp-review-empty">지금 풀 문제는 없어요.<br><small>다음 복습 ${mins(next)}분 후</small></div>`:`<div class="tp-review-empty"><b>오답 완료 ✓</b><br>남아 있는 오답이 없어요.</div>`}`;$('.tp-review-start',home)?.addEventListener('click',()=>start(ready))}catch(e){$('.tp-review-panel',home).innerHTML=`<div class="tp-review-empty">${esc(e.message)}</div>`}}
function group(items){const m=new Map();for(const r of items){const k=[r.plan_id,r.unit_key||'',String(r.practice_type||'reading').toLowerCase()].join('||');if(!m.has(k))m.set(k,{planId:r.plan_id,lesson:r.unit_key,skill:String(r.practice_type||'reading').toLowerCase(),ids:[]});m.get(k).ids.push(r.question_id)}return [...m.values()]}
function start(items){queue=group(items);running=true;next()}
function next(){if(!running)return;if(!queue.length){running=false;setTimeout(show,250);return}const g=queue.shift();window.WillenaAssignedTestPrep?.startSelection?.(g.planId,g.lesson,g.skill,{reviewMode:true,reviewIds:g.ids})}
window.addEventListener('testprep:review-group-complete',()=>{if(running)setTimeout(next,100)});
window.addEventListener('testprep:student-state-refresh',()=>setTimeout(refreshHomeCard,80));
function install(){const ux=window.WillenaTestPrepUX;if(!ux){setTimeout(install,50);return}ux.showWrongCenter=show;const old=ux.renderHome;if(!old.__rev47b){const wrapped=function(){const r=old.apply(this,arguments);setTimeout(refreshHomeCard,50);return r};wrapped.__rev47b=true;ux.renderHome=wrapped}refreshHomeCard()}
install();
window.WillenaReview47b={show,load};
})();