(function(){
'use strict';
const U='https://gxwfsqxyuufqtitspfqg.supabase.co';
const K=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const H={apikey:K,Authorization:`Bearer ${K}`};
const $=(s,r=document)=>r.querySelector(s);
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const shuffle=a=>{const b=[...a];for(let i=b.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[b[i],b[j]]=[b[j],b[i]]}return b};
let bank=[],questions=[],index=0,score=0,wrongIds=[],startedAt=0,checked=false,reviewMode=false,sessionGroups=null;

function styles(){if($('#seosulStyles'))return;const s=document.createElement('style');s.id='seosulStyles';s.textContent=`
.seosul-kind{display:inline-flex;align-items:center;padding:5px 9px;border-radius:999px;background:#eef9fa;color:#19777e;font-size:11px;font-weight:800;margin-bottom:12px}.seosul-instruction{font-size:13px;color:#68747d;margin:0 0 12px;line-height:1.55}.seosul-source{padding:16px 17px;border:1.5px solid #dde5e8;border-radius:15px;background:#f8fafb;font-size:16px;line-height:1.65;margin:0 0 14px;white-space:pre-wrap}.seosul-bank{display:flex;flex-wrap:wrap;gap:7px;margin:0 0 14px}.seosul-word{border:1.5px solid #cfdadd;background:#fff;border-radius:10px;padding:7px 10px;font-weight:700;font-size:13px;color:#47545d}.seosul-answer{width:100%;min-height:60px;box-sizing:border-box;border:2px solid #d9e2e5;border-radius:14px;padding:13px 14px;font:600 16px/1.45 inherit;resize:vertical;outline:none;background:#fff;color:#303941}.seosul-answer:focus{border-color:#58c3d2;box-shadow:0 0 0 3px rgba(88,195,210,.12)}.seosul-order{display:flex;flex-wrap:wrap;gap:8px;min-height:48px;padding:10px;border:1.5px dashed #cfdadd;border-radius:13px;margin-bottom:10px;background:#fbfcfc}.seosul-order .seosul-word{cursor:pointer}.seosul-order.answer{border-style:solid;background:#f4fbfc}.seosul-model{display:none;margin-top:12px;padding:13px 14px;border-radius:12px;background:#f4f7f8;font-size:14px;line-height:1.6}.seosul-model.show{display:block}.seosul-model b{display:block;color:#19777e;margin-bottom:4px}.seosul-head-actions{display:flex;align-items:center;gap:8px}.seosul-flag{border:1px solid #d7dde0;background:#fff;border-radius:999px;width:30px;height:30px;display:inline-grid;place-items:center;cursor:pointer;font-size:15px;color:#7b8790}.seosul-flag:hover{background:#f6f8f9}`;document.head.appendChild(s)}
async function get(path){const r=await fetch(U+path,{headers:H,cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
const inFilter=ids=>encodeURIComponent('('+ids.join(',')+')');
const clean=v=>String(v||'').replace(/\\\\n/g,'\n').replace(/\\n/g,'\n').replace(/\r/g,'').trim();
const stripSpeaker=v=>String(v||'').replace(/^[^:：]{1,28}[:：]\s*/,'').trim();
const tokenize=v=>String(v||'').replace(/[“”"!?.,;:()]/g,'').split(/\s+/).filter(Boolean);
const normalize=v=>String(v??'').normalize('NFKC').toLowerCase().replace(/[’‘]/g,"'").replace(/[“”"]/g,'').replace(/[.!?,;:]/g,'').replace(/\s+/g,' ').trim();
const stable=(type,id,n='')=>`seosul:${type}:${id}${n!==''?':'+n:''}`;
const wordCount=v=>tokenize(v).length;
function answerChoice(q){let ans=q.correct_answer;if(!Array.isArray(ans))ans=ans==null?[]:[ans];const n=Number(ans[0]);return Number.isInteger(n)&&n>0&&Array.isArray(q.choices)?q.choices[n-1]:null}
function englishSentence(v){const s=String(v||'').trim(),n=wordCount(s);return n>=3&&n<=20&&/[A-Za-z]/.test(s)&&s.includes(' ')&&!/[①②③④⑤]/.test(s)}
function pairKey(x){return normalize(x.en)+'|'+String(x.ko||'').trim()}
function dedupe(rows){const seen=new Set();return rows.filter(x=>{const k=pairKey(x);if(!x.en||!x.ko||seen.has(k))return false;seen.add(k);return true})}
function passagePairs(passages){const out=[];for(const p of passages){const en=clean(p.body).split('\n').map(x=>x.trim()).filter(Boolean),ko=Array.isArray(p.metadata?.sentence_translations_ko)?p.metadata.sentence_translations_ko:clean(p.translation_ko).split('\n').map(x=>x.trim()).filter(Boolean);if(en.length!==ko.length)continue;for(let i=0;i<en.length;i++){const a=stripSpeaker(en[i]),b=stripSpeaker(ko[i]);if(englishSentence(a)&&b)out.push({id:p.id,index:i,en:a,ko:b,origin:p.id,source:'passage',section:'reading',targets:[]})}}return out}
function authoredPairs(rows){const good=new Set(['sentence_order','translation_grammar','korean_to_english','translation_constrained']);return rows.filter(q=>good.has(String(q.question_type||''))&&q.context?.korean).map(q=>{const a=answerChoice(q);return englishSentence(a)?{id:q.id,index:'q',en:String(a).trim(),ko:String(q.context.korean).trim(),origin:q.id,source:'question',section:String(q.section||''),targets:Array.isArray(q.targets)?q.targets:[]}:null}).filter(Boolean)}
const STOP=new Set(['the','a','an','is','are','was','were','am','be','been','to','of','in','on','at','for','and','or','but','it','i','you','we','they','he','she','this','that','than','with','my','your','his','her','our','their']);
function keyWords(en,n=3){const all=tokenize(en).map(x=>x.replace(/[^A-Za-z'-]/g,'')).filter(Boolean),strong=[...new Set(all.filter(x=>x.length>=2&&!STOP.has(x.toLowerCase())))];return (strong.length>=n?strong:all).slice(0,n)}
function grammarTarget(x){const raw=(x.targets||[]).map(String).filter(Boolean);const useful=raw.find(t=>!/^(grammar|sentence|sentence_production|translation|reading|communication)$/i.test(t));return useful||null}
function wordBank(pairs){return pairs.map(x=>({id:stable('word_bank_sentence',x.id,x.index),type:'word_bank_sentence',kind:'단어 배열 영작',instruction:'보기의 단어를 모두 사용하여 우리말과 같은 문장을 쓰세요.',source:x.ko,bank:shuffle(tokenize(x.en)),answer:x.en,targets:['sentence_production'],origin:x.origin,constraints:{word_count:wordCount(x.en),required_words:tokenize(x.en)}}))}
function unscramble(pairs){return pairs.map(x=>({id:stable('sentence_unscramble',x.id,x.index),type:'sentence_unscramble',kind:'문장 순서 배열',instruction:'단어를 눌러 올바른 문장을 만드세요.',source:x.ko,chips:shuffle(tokenize(x.en)),answer:x.en,targets:['sentence_order'],origin:x.origin,constraints:{word_count:wordCount(x.en),required_words:tokenize(x.en)}}))}
function constrained(pairs){return pairs.map(x=>{const words=keyWords(x.en,2),n=wordCount(x.en),gt=grammarTarget(x);if(!words.length)return null;const condition=[`${n}단어`,`${words.join(', ')} 포함`,gt?`${gt} 사용`:null].filter(Boolean).join(' · ');return{id:stable('constrained_translation',x.id,x.index),type:'constrained_translation',kind:'조건 영작',instruction:`우리말과 같도록 영어로 쓰세요. (${condition})`,source:x.ko,bank:words,answer:x.en,targets:['sentence_production',...(gt?[gt]:[])],origin:x.origin,constraints:{word_count:n,required_words:words,target_grammar:gt}}}).filter(Boolean)}
function givenWordsGrammar(pairs){return pairs.filter(x=>x.section==='grammar').map(x=>{const words=keyWords(x.en,3),gt=grammarTarget(x);if(words.length<3)return null;return{id:stable('given_words_grammar',x.id,x.index),type:'given_words_grammar',kind:'주어진 단어로 영작',instruction:`주어진 세 단어를 모두 사용하여 올바른 문장을 쓰세요.${gt?` (${gt} 활용)`:''}`,source:words.join(' · '),bank:words,answer:x.en,targets:['grammar','sentence_production',...(gt?[gt]:[])],origin:x.origin,constraints:{required_words:words,target_grammar:gt,reference_only:true}}}).filter(Boolean)}
function blankCount(s){return (String(s||'').match(/_{2,}|\(A\)|\(B\)|\[\s*\]/g)||[]).length}
function dialogueAnchor(answer){const w=keyWords(answer,1);return w[0]||null}
function sourceDialogues(rows){const out=[];for(const d of rows){const lines=clean(d.metadata?.full_text).split('\n').map(x=>x.trim()).filter(Boolean);if(lines.length<2)continue;for(let i=0;i<lines.length;i++){const m=lines[i].match(/^([^:：]{1,28}[:：])\s*(.+)$/);if(!m?.[2]||wordCount(m[2])>12)continue;const anchor=dialogueAnchor(m[2]);const instruction=anchor?`대화의 빈칸에 들어갈 말을 쓰세요. (${anchor} 사용)`:'대화의 빈칸에 들어갈 말을 쓰세요.';out.push({id:stable('dialogue_completion',d.id,i),type:'dialogue_completion',kind:'대화 완성',instruction,source:lines.map((x,j)=>j===i?`${m[1]} ______`:x).join('\n'),bank:anchor?[anchor]:[],answer:m[2].trim(),targets:[d.language_function||'communication'],origin:d.id,constraints:{required_words:anchor?[anchor]:[],target_function:d.language_function||null}})}}return out}
function authoredDialogues(rows){const types=new Set(['dialogue_blank','contextual_reply_blank','translation_dialogue_blank','blank_question','location_blank']);return rows.filter(q=>types.has(String(q.question_type||''))&&q.context?.dialogue).map(q=>{const a=answerChoice(q),d=clean(q.context.dialogue);if(!a||!d||blankCount(d)!==1)return null;const anchor=dialogueAnchor(String(a));const gt=(Array.isArray(q.targets)?q.targets:[]).map(String).find(Boolean)||null;const instruction=[`대화의 빈칸에 들어갈 말을 쓰세요.`,anchor?`(${anchor} 사용${gt?` · ${gt}`:''})`:gt?`(${gt} 활용)`:'' ].join(' ').trim();return{id:stable('dialogue_completion',q.id,'q'),type:'dialogue_completion',kind:'대화 완성',instruction,source:d,bank:anchor?[anchor]:[],answer:String(a).trim(),targets:['communication',...(gt?[gt]:[])],origin:q.id,constraints:{required_words:anchor?[anchor]:[],target_function:gt}}}).filter(Boolean)}
function readingTranslation(pairs){return pairs.filter(x=>x.source==='passage').map(x=>({id:stable('reading_translation',x.id,x.index),type:'reading_translation',kind:'본문 해석',instruction:'다음 본문 문장을 우리말로 해석하세요.',source:x.en,answer:x.ko,selfCheck:true,targets:['reading_translation'],origin:x.origin}))}
function buildSession(g){if(!g)return[];const out=[],used=new Set();const take=(pool,n)=>{for(const q of shuffle(pool||[])){if(n<=0||out.length>=20)break;if(used.has(String(q.id)))continue;used.add(String(q.id));out.push(q);n--}};
 take(g.dialogue,9);
 take(g.constrained,5);
 take(g.givenWords,3);
 take(g.wordBank,1);
 take(g.unscramble,1);
 // English→Korean translation is held out until the AI verifier is wired in.
 take([...(g.dialogue||[]),...(g.constrained||[]),...(g.givenWords||[]),...(g.wordBank||[]),...(g.unscramble||[])],20-out.length);
 return shuffle(out).slice(0,20)}
async function loadBank(unitId){
 const occ=await get(`/rest/v1/source_content_occurrences?select=passage_id&unit_id=eq.${encodeURIComponent(unitId)}`),passageIds=[...new Set(occ.map(x=>x.passage_id).filter(Boolean))];
 const [passages,dialogs,rows]=await Promise.all([
  passageIds.length?get(`/rest/v1/passages?select=id,body,translation_ko,metadata&id=in.${inFilter(passageIds)}`):[],
  get(`/rest/v1/source_dialogues?select=id,language_function,metadata&unit_id=eq.${encodeURIComponent(unitId)}&status=neq.archived`),
  get(`/rest/v1/test_prep_questions?select=id,section,question_type,prompt_text,context,choices,correct_answer,targets,student_usable,replacement_needed&unit_id=eq.${encodeURIComponent(unitId)}&student_usable=eq.true`)
 ]);
 const usable=rows.filter(x=>x.replacement_needed!==true),pairs=dedupe([...passagePairs(passages),...authoredPairs(usable)]),wordBankGroup=wordBank(pairs),unscrambleGroup=unscramble(pairs),constrainedGroup=constrained(pairs),givenWordsGroup=givenWordsGrammar(pairs),dialogueGroup=[...sourceDialogues(dialogs),...authoredDialogues(usable)],readingGroup=readingTranslation(pairs);
 sessionGroups={wordBank:wordBankGroup,unscramble:unscrambleGroup,constrained:constrainedGroup,givenWords:givenWordsGroup,dialogue:dialogueGroup,reading:readingGroup};
 bank=[...wordBankGroup,...unscrambleGroup,...constrainedGroup,...givenWordsGroup,...dialogueGroup,...readingGroup];questions=buildSession(sessionGroups);
 return{bank,questions,counts:{word_bank_sentence:wordBankGroup.length,sentence_unscramble:unscrambleGroup.length,constrained_translation:constrainedGroup.length,given_words_grammar:givenWordsGroup.length,dialogue_completion:dialogueGroup.length,reading_translation:readingGroup.length}}
}
function cardEl(){return $('#card')}function barEl(){return $('#bar')}
function sourceHtml(q){return `<div class="seosul-kind">${esc(q.kind)}</div><p class="seosul-instruction">${esc(q.instruction)}</p><div class="seosul-source">${esc(q.source)}</div>${q.bank?.length?`<div class="seosul-bank">${q.bank.map(w=>`<span class="seosul-word">${esc(w)}</span>`).join('')}</div>`:''}`}
function inputHtml(q){return `${sourceHtml(q)}<textarea class="seosul-answer" id="seosulAnswer" autocomplete="off" spellcheck="false" placeholder="답을 입력하세요"></textarea><div class="feedback" id="feedback"></div><div class="seosul-model" id="seosulModel"><b>모범 답안</b>${esc(q.answer)}</div><div class="actions"><button class="primary" id="seosulCheck" disabled>정답 확인</button></div>`}
function orderHtml(q){return `${sourceHtml(q)}<div class="seosul-order answer" id="seosulBuilt"></div><div class="seosul-order" id="seosulPool">${q.chips.map((w,i)=>`<button type="button" class="seosul-word" data-chip="${i}">${esc(w)}</button>`).join('')}</div><div class="feedback" id="feedback"></div><div class="actions"><button class="primary" id="seosulCheck" disabled>정답 확인</button></div>`}
function flag(q){window.WillenaPracticeFlagger?.open?.({source_type:'generated_seosul',source_id:String(q.id),snapshot:{page:location.pathname,lesson:window.WillenaAssignedTestPrep?.selection?.lesson||null,practice_type:'constructed_response',question_id:q.id,question_type:q.type,kind:q.kind,instruction:q.instruction,source:q.source,answer:q.answer,constraints:q.constraints||null,origin_id:q.origin,engine:'seosul_v2',source_label:'W'}})}
function render(){const c=cardEl(),b=barEl();if(!c)return;if(!questions.length){c.innerHTML='<div class="empty">이 Lesson에서 만들 수 있는 서술형 문제가 아직 없습니다.</div>';if(b)b.style.width='0';return}if(index>=questions.length)return result();checked=false;startedAt=Date.now();if(b)b.style.width=`${index/questions.length*100}%`;const q=questions[index];c.innerHTML=`<div class="card-head"><div class="qnum">${index+1} / ${questions.length}</div><div class="seosul-head-actions"><span class="source w">W</span><button type="button" class="seosul-flag" id="seosulFlag" aria-label="문제 신고">⚑</button></div></div><div class="body">${q.type==='sentence_unscramble'?orderHtml(q):inputHtml(q)}</div>`;$('#seosulFlag')?.addEventListener('click',()=>flag(q));q.type==='sentence_unscramble'?wireOrder(q):wireInput(q)}
function wireInput(q){const input=$('#seosulAnswer'),btn=$('#seosulCheck');input.oninput=()=>btn.disabled=!input.value.trim();input.onkeydown=e=>{if(e.key==='Enter'&&!e.shiftKey&&!btn.disabled){e.preventDefault();btn.click()}};btn.onclick=()=>check(q,input.value);setTimeout(()=>input.focus(),30)}
function wireOrder(q){const built=$('#seosulBuilt'),pool=$('#seosulPool'),btn=$('#seosulCheck'),chosen=[];function draw(){built.innerHTML=chosen.map((x,i)=>`<button type="button" class="seosul-word" data-built="${i}">${esc(x.w)}</button>`).join('');pool.querySelectorAll('[data-chip]').forEach(b=>b.hidden=chosen.some(x=>x.i===Number(b.dataset.chip)));btn.disabled=!chosen.length;built.querySelectorAll('[data-built]').forEach(b=>b.onclick=()=>{chosen.splice(Number(b.dataset.built),1);draw()})}pool.querySelectorAll('[data-chip]').forEach(b=>b.onclick=()=>{chosen.push({i:Number(b.dataset.chip),w:b.textContent});draw()});btn.onclick=()=>check(q,chosen.map(x=>x.w).join(' '));draw()}
function constraintCheck(q,mine){const c=q.constraints||{},n=normalize(mine),missing=(c.required_words||[]).filter(w=>!n.includes(normalize(w)));if(c.word_count&&wordCount(mine)!==Number(c.word_count))return{ok:false,msg:`${c.word_count}단어로 써야 합니다.`};if(missing.length)return{ok:false,msg:`필수 단어/표현을 사용하세요: ${missing.join(', ')}`};return{ok:true,msg:''}}
async function save(q,mine,ok){try{await window.WillenaTestPrepAuth?.recordAttempt?.({practice_type:'constructed_response',question_id:q.id,selected_answer:mine,correct_answer:q.answer,is_correct:ok,question_type:q.type,targets:q.targets||[],response_time_ms:Date.now()-startedAt,metadata:{generated:true,origin_id:q.origin,engine:'seosul_v2',source_label:'W',constraints:q.constraints||null}})}catch(_){}}
function nextButton(ok,msg=''){const f=$('#feedback');if(f){f.className='feedback '+(ok?'ok':'bad');f.textContent=ok?'정답입니다!':(msg||'정답을 확인해 보세요.')}$('#seosulModel')?.classList.add('show');const btn=$('#seosulCheck');if(btn){btn.disabled=false;btn.textContent=index===questions.length-1?'결과 보기':'다음 문제';btn.onclick=()=>{index++;render()}}}
async function check(q,mine){if(checked)return;checked=true;const cc=constraintCheck(q,mine);const ok=cc.ok&&normalize(mine)===normalize(q.answer);ok?score++:wrongIds.push(q.id);save(q,mine,ok);nextButton(ok,cc.msg)}
function result(){const c=cardEl(),b=barEl();if(b)b.style.width='100%';window.WillenaTestPrepAuth?.completeSession?.(score,questions.length,wrongIds);const p=questions.length?Math.round(score/questions.length*100):0;if(reviewMode){c.innerHTML=`<div class="result"><div class="score">${score}/${questions.length}</div><h2>서술형 오답 복습 완료</h2><p>정답률 ${p}%</p><div class="actions"><button class="primary" id="seosulReviewDone">다음 →</button></div></div>`;$('#seosulReviewDone').onclick=()=>window.dispatchEvent(new CustomEvent('testprep:review-group-complete'));return}c.innerHTML=`<div class="result"><div class="score">${score}/${questions.length}</div><h2>${p>=80?'서술형 준비가 잘 되고 있어요.':'틀린 유형을 한 번 더 연습해 보세요.'}</h2><p>정답률 ${p}% · 다시 볼 문제 ${wrongIds.length}개</p><div class="actions"><button class="secondary" id="seosulAgain">새 문제 세트</button></div></div>`;$('#seosulAgain').onclick=()=>{questions=buildSession(sessionGroups);index=0;score=0;wrongIds=[];render()}}
async function start(opts={}){styles();const c=cardEl(),b=barEl();if(c)c.innerHTML='<div class="loading">서술형 문제를 만들고 있어요...</div>';if(b)b.style.width='0';index=0;score=0;wrongIds=[];const sel=window.WillenaAssignedTestPrep?.selection,unitId=opts.unitId||sel?.unitId;if(!unitId)throw new Error('Lesson 정보를 찾지 못했습니다.');const data=await loadBank(unitId),ids=(opts.reviewIds||sel?.reviewIds||[]).map(String);reviewMode=!!(opts.reviewMode||sel?.reviewMode);if(reviewMode&&ids.length)questions=bank.filter(q=>ids.includes(String(q.id)));if(!questions.length&&reviewMode)questions=buildSession(sessionGroups).slice(0,Math.min(10,bank.length));render();return data}
window.WillenaSeosulEngine={start,loadBank,get bank(){return bank},get questions(){return questions}};
})();