(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const REVIEW_EDGE='https://fiieuiktlsivwfgyivai.supabase.co/functions/v1/test-prep-review',API_KEY='sb_publishable_e-K50PquV9gHdfmefG6tmg_o-vVSl0e';
const STATIONS=[
 {k:'vocabulary',label:'단어 학습',desc:'카드 · 뜻 · 철자'},
 {k:'vocab_test',label:'어휘 시험',desc:'정의 · 시험형 어휘 문제'},
 {k:'communication',label:'Communication',desc:'핵심 대화 표현'},
 {k:'grammar',label:'Grammar',desc:'핵심 문법'},
 {k:'sentences',label:'본문외우기',desc:'본문 문장 완성'},
 {k:'reading',label:'Reading',desc:'본문 이해'},
 {k:'constructed_response',label:'서술형',desc:'영작 · 배열 · 대화 · 본문 해석'}
];
const LABEL=Object.fromEntries(STATIONS.map(x=>[x.k,x.label]));
const CONTENT_TOTALS={
 '중1 동아 윤정미':{
  'Lesson 1':{vocabulary:30,vocab_test:30,sentences:28,communication:50,grammar:50,reading:50},
  'Lesson 2':{vocabulary:31,vocab_test:31,sentences:24,communication:50,grammar:50,reading:50},
  'Lesson 3':{vocabulary:36,vocab_test:36,sentences:53,communication:30,grammar:30,reading:30},
  'Lesson 4':{vocabulary:34,vocab_test:34,sentences:27,communication:30,grammar:30,reading:30}
 }
};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=v=>v==null?'—':`${Math.round(Number(v)||0)}%`;
let wrapped=false,resultPatched=false,view={type:'home'},reviewQueue=[];
function scopeFor(plan){const lessons=plan.group?.scope?.lessons;if(Array.isArray(lessons)&&lessons.length)return lessons.filter(x=>x?.lesson);return(plan.units||[]).map(lesson=>({lesson,sections:plan.practice_types||[]}))}
function activeTasks(plan){return(plan.tasks||[]).filter(t=>t.active!==false&&!t.completed_at&&Number(t.progress?.remaining)>0)}
function taskFor(plan,lesson,practice){return activeTasks(plan).filter(t=>String(t.lesson)===String(lesson)&&String(t.practice_type).toLowerCase()===String(practice).toLowerCase()).sort((a,b)=>new Date(a.due_at||'2999-01-01')-new Date(b.due_at||'2999-01-01'))[0]||null}
function realTotal(plan,lesson,practice){return Number(CONTENT_TOTALS[plan.book_label]?.[lesson]?.[practice])||0}
function skillProgress(plan,lesson,practice){const v=plan.summary?.by_lesson_practice?.[`${lesson}||${practice}`]||{},task=taskFor(plan,lesson,practice),target=realTotal(plan,lesson,practice),done=Math.max(0,Number(v.unique)||0),accuracy=done?Math.max(0,Math.min(100,Number(v.accuracy)||0)):0,coverage=target?Math.min(100,done/target*100):0,mastery=target?Math.round(coverage*accuracy/100):0;return{task,target,done,accuracy,coverage:Math.round(coverage),mastery}}
function stationAvailable(plan,lessonObj,st,sections){
 const strict=plan?.group?.scope?.scope_controls_v2===true;
 if(st.k==='sentences')return true;
 if(strict){
  if(st.k==='vocabulary'||st.k==='vocab_test')return sections.has('vocabulary');
  return sections.has(st.k);
 }
 return ['vocabulary','vocab_test','sentences'].includes(st.k)||sections.has(st.k)||!!taskFor(plan,lessonObj.lesson,st.k);
}
function lessonData(plan,lessonObj){const sections=new Set((lessonObj.sections||[]).map(x=>String(x).toLowerCase())),skills=STATIONS.map(st=>{const available=stationAvailable(plan,lessonObj,st,sections);return{...st,available,...skillProgress(plan,lessonObj.lesson,st.k)}}),used=skills.filter(x=>x.available&&x.target>0),mastery=used.length?Math.round(used.reduce((a,b)=>a+b.mastery,0)/used.length):0,tasks=activeTasks(plan).filter(t=>String(t.lesson)===String(lessonObj.lesson));return{...lessonObj,skills,mastery,tasks}}
function examLabel(plan){const g=plan.group||{};return[g.term?`${g.term}학기`:'',g.exam_type==='final'?'기말고사':g.exam_type==='midterm'?'중간고사':plan.exam_name].filter(Boolean).join(' · ')}
function planSchool(plan){return plan.group?.school||window.WillenaTestPrepAuth?.state?.user?.school||'학교 시험'}
function taskShelf(plans){const all=plans.flatMap(p=>activeTasks(p).map(t=>({p,t}))).sort((a,b)=>new Date(a.t.due_at||'2999-01-01')-new Date(b.t.due_at||'2999-01-01'));if(!all.length)return'';return`<div class="tp-task-shelf">${all.slice(0,6).map(({p,t})=>`<button class="tp-task-chip" data-task-plan="${esc(p.id)}" data-task-lesson="${esc(t.lesson)}" data-task-skill="${esc(t.practice_type)}"><span class="arrow">→</span><span class="k">선생님 과제</span><b>${esc(t.title||`${t.lesson} ${LABEL[t.practice_type]||t.practice_type}`)}</b><small>${Number(t.progress?.remaining)||0}개 남음</small></button>`).join('')}</div>`}
function wrongCard(plans){const total=plans.reduce((n,p)=>n+(Number(p.summary?.unresolved_wrong)||0),0),due=plans.reduce((n,p)=>n+(Number(p.summary?.due_review_count)||0),0);return`<button class="tp-wrong-card ${total?'':'no-wrong'}" ${total?'':'disabled'}><span class="tp-wrong-icon">↺</span><span class="tp-wrong-copy"><b>${total?'오답 다시 풀기':'오답 없음'}</b><small>${total?(due?`지금 복습할 문제 ${due}개`:'틀렸던 문제를 다시 풀어 보세요'):'현재 남아 있는 오답이 없어요'}</small></span><span class="tp-wrong-count">${total}<small>개</small></span></button>`}
function lessonCard(plan,l){const d=lessonData(plan,l);return`<button class="tp-lesson-card" data-lesson-plan="${esc(plan.id)}" data-lesson="${esc(l.lesson)}"><span><h3>${esc(l.lesson)}</h3><p>${d.mastery?`Mastery ${d.mastery}%`:'아직 시작하지 않았어요'}</p>${d.tasks.length?`<span class="tp-task-badge">선생님 과제 ${d.tasks.length}</span>`:''}</span><span class="tp-ring" style="--p:${d.mastery}%"><b>${d.mastery}%</b></span></button>`}
function openStats(plan){let bg=$('#tpStatsBg');if(!bg){bg=document.createElement('div');bg.id='tpStatsBg';bg.className='tp-stats-bg';document.body.appendChild(bg);bg.onclick=e=>{if(e.target===bg)bg.classList.remove('open')}}const s=plan.summary||{},pr=s.by_practice||{};bg.innerHTML=`<div class="tp-stats-modal"><div class="tp-stats-head"><h3>내 시험 대비 기록</h3><button class="tp-stats-x">×</button></div><div class="tp-stats-grid"><div class="tp-stat"><b>${pct(s.accuracy)}</b><span>정답률</span></div><div class="tp-stat"><b>${pct(s.first_attempt_accuracy)}</b><span>첫 시도</span></div><div class="tp-stat"><b>${s.unresolved_wrong||0}</b><span>미해결 오답</span></div><div class="tp-stat"><b>${pct(s.correction_rate)}</b><span>오답 회복</span></div><div class="tp-stat"><b>${s.unique_questions||0}</b><span>완료 문제</span></div><div class="tp-stat"><b>${s.sessions||0}</b><span>학습 세션</span></div></div>${STATIONS.map(st=>`<div class="tp-stat-row"><span>${st.label}</span><b>${pct(pr[st.k]?.accuracy)}</b></div>`).join('')}</div>`;$('.tp-stats-x',bg).onclick=()=>bg.classList.remove('open');bg.classList.add('open')}
function renderHome(){const home=$('#assignmentHome'),state=window.WillenaTestPrepAuth?.state;if(!home||!state)return;view={type:'home'};home.style.display='block';const plans=state.plans||[];home.innerHTML=`${taskShelf(plans)}${wrongCard(plans)}${plans.length?plans.map(plan=>`<section class="tp-exam-section"><div class="tp-exam-head"><div><h2>${esc(planSchool(plan))}</h2><p>${esc(examLabel(plan))}</p></div><div class="tp-exam-actions">${plan.exam_date?`<span class="tp-exam-date">${esc(plan.exam_date)}</span>`:''}<button class="tp-records" data-records="${esc(plan.id)}">내 기록</button></div></div><div class="tp-book">${esc(plan.book_label||'')}</div><div class="tp-lessons">${scopeFor(plan).map(l=>lessonCard(plan,l)).join('')}</div></section>`).join(''):'<div class="tp-review-empty">지정된 시험 대비가 없습니다.</div>'}`;$('.tp-wrong-card:not(.no-wrong)',home)?.addEventListener('click',showWrongCenter);$$('[data-task-plan]',home).forEach(b=>b.onclick=()=>launchSkill(b.dataset.taskPlan,b.dataset.taskLesson,b.dataset.taskSkill));$$('[data-lesson-plan]',home).forEach(b=>b.onclick=()=>renderLesson(b.dataset.lessonPlan,b.dataset.lesson));$$('[data-records]',home).forEach(b=>b.onclick=e=>{e.stopPropagation();const p=plans.find(x=>String(x.id)===String(b.dataset.records));if(p)openStats(p)})}
function renderLesson(planId,lesson,focusSkill=null){const home=$('#assignmentHome'),state=window.WillenaTestPrepAuth?.state,plan=state?.plans?.find(p=>String(p.id)===String(planId));if(!home||!plan)return;const l=scopeFor(plan).find(x=>String(x.lesson)===String(lesson));if(!l)return;const d=lessonData(plan,l),shown=d.skills.filter(x=>x.available),next=shown.find(x=>x.task)||shown.find(x=>x.mastery<80)||shown[0];view={type:'lesson',planId:String(planId),lesson:String(lesson),focusSkill:focusSkill||next?.k||null};home.innerHTML=`<button class="tp-back">← 시험 대비</button><div class="tp-lesson-head"><div><h1>${esc(lesson)}</h1><p>${esc(plan.book_label||'')} · 학습 지도</p></div><span class="tp-ring" style="--p:${d.mastery}%"><b>${d.mastery}%</b></span></div><div class="tp-subway">${shown.map((s,i)=>{const current=String(view.focusSkill)===s.k,done=s.mastery>=90;return`<div class="tp-stop ${current?'current':''} ${done?'done':''}" data-skill="${esc(s.k)}"><div class="tp-station">${done?'✓':i+1}</div><div class="tp-stop-copy"><b>${esc(s.label)}</b><small>${esc(s.desc)}</small>${s.task?`<span class="tp-task-badge">선생님 과제 · ${s.task.progress?.remaining||0}개 남음</span>`:''}<div class="tp-mini"><i style="width:${s.mastery}%"></i></div></div><div class="tp-stop-pct">${s.mastery}%<small>${s.target?`${s.done}/${s.target}`:''}${current?' · 지금 여기':''}</small></div></div>`}).join('')}</div><div class="tp-mastery-note">Mastery = 실제 범위에서 풀어 본 비율 × 현재 정답률. 문제를 조금만 풀었다면 정답률이 높아도 Mastery가 크게 오르지 않습니다.</div>`;$('.tp-back',home).onclick=()=>renderHome();$$('.tp-stop',home).forEach(x=>x.onclick=()=>launchSkill(plan.id,lesson,x.dataset.skill))}
async function launchSkill(planId,lesson,skill,opts={}){const api=window.WillenaAssignedTestPrep;if(!api?.startSelection)return;await api.startSelection(planId,lesson,skill,opts)}
async function reviewApi(){const token=window.WillenaAPI?.getLocalAccessToken?.()||localStorage.getItem('sb_access_token')||'';if(!token)throw new Error('로그인이 필요합니다.');const r=await fetch(REVIEW_EDGE,{headers:{Authorization:`Bearer ${token}`,apikey:API_KEY},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok||d.success===false)throw new Error(d.error||'오답을 불러오지 못했습니다.');return d}
function reviewGroups(reviews){const order=STATIONS.map(x=>x.k),m=new Map();for(const r of reviews){const k=[r.plan_id,r.unit_key||'',r.practice_type||''].join('||');if(!m.has(k))m.set(k,{planId:r.plan_id,lesson:r.unit_key,skill:String(r.practice_type||'reading').toLowerCase(),reviews:[]});m.get(k).reviews.push(r)}return[...m.values()].sort((a,b)=>String(a.lesson).localeCompare(String(b.lesson),'en')||order.indexOf(a.skill)-order.indexOf(b.skill))}
async function showWrongCenter(){const home=$('#assignmentHome');if(!home)return;view={type:'wrong'};home.style.display='block';home.innerHTML='<button class="tp-back">← 시험 대비</button><div class="tp-wrong-page-head"><h1>오답 복습</h1><p>틀렸던 문제를 다시 풀고 기억을 확인하세요.</p></div><div class="tp-review-panel"><div class="tp-review-empty">오답을 불러오는 중...</div></div>';$('.tp-back',home).onclick=()=>renderHome();try{const d=await reviewApi(),groups=reviewGroups(d.reviews||[]),n=(d.reviews||[]).length;$('.tp-review-panel',home).innerHTML=n?`<button class="tp-review-start">오답 ${n}개 모두 시작 →</button>${groups.map((g,i)=>`<div class="tp-review-group"><span><b>${esc(g.lesson||'Lesson')} · ${LABEL[g.skill]||esc(g.skill)}</b><small>${g.reviews.length}개${g.reviews.some(x=>x.due_now)?' · 지금 복습할 문제 포함':''}</small></span><button class="tp-review-btn" data-rg="${i}">복습</button></div>`).join('')}`:'<div class="tp-review-empty">남아 있는 오답이 없어요. ✓</div>';$('.tp-review-start',home)?.addEventListener('click',()=>startReview(groups));$$('[data-rg]',home).forEach(b=>b.onclick=()=>startReview([groups[Number(b.dataset.rg)]]) )}catch(e){$('.tp-review-panel',home).innerHTML=`<div class="tp-review-empty">${esc(e.message)}</div>`}}
function startReview(groups){reviewQueue=(groups||[]).filter(Boolean).map(g=>({...g}));nextReviewGroup()}
function nextReviewGroup(){if(!reviewQueue.length){finishReview();return}const g=reviewQueue[0];launchSkill(g.planId,g.lesson,g.skill,{reviewMode:true,reviewIds:g.reviews.map(x=>x.question_id)})}
async function finishReview(){try{const auth=window.WillenaTestPrepAuth,d=await auth?.edge?.('me');if(d?.plans){auth.state.plans=d.plans;auth.state.tasks=d.tasks||[]}}catch(_){}showWrongCenter()}
function patchResult(){if(resultPatched||typeof window.result!=='function')return false;const original=window.result;window.result=function(){const sel=window.WillenaAssignedTestPrep?.selection;if(!sel?.reviewMode)return original.apply(this,arguments);window.WillenaTestPrepAuth?.completeSession?.(score,questions.length,wrongIds);bar.style.width='100%';const p=questions.length?Math.round(score/questions.length*100):0;card.innerHTML=`<div class="tp-review-result"><div class="score">${score}/${questions.length}</div><h2>오답 복습 완료</h2><p>정답률 ${p}%</p><button class="tp-review-next">다음 오답 →</button></div>`;$('.tp-review-next',card).onclick=()=>window.dispatchEvent(new CustomEvent('testprep:review-group-complete'))};resultPatched=true;return true}
function wrap(){if(wrapped)return;const api=window.WillenaAssignedTestPrep;if(!api?.renderHome)return;wrapped=true;const original=api.renderHome.bind(api);api.renderHome=function(){const r=original();queueMicrotask(renderHome);return r};renderHome()}
function onRefresh(){const quiz=$('#assignedQuizPane');if(quiz&&quiz.style.display!=='none')return;if(view.type==='lesson')renderLesson(view.planId,view.lesson,view.focusSkill);else if(view.type==='home')renderHome()}
function boot(){let tries=0;const timer=setInterval(()=>{wrap();patchResult();if((wrapped&&resultPatched)||++tries>120)clearInterval(timer)},50);window.addEventListener('testprep:student-state-refresh',onRefresh);window.addEventListener('testprep:review-group-complete',()=>{if(reviewQueue.length)reviewQueue.shift();nextReviewGroup()})}
window.WillenaTestPrepUX={renderHome,renderLesson,showWrongCenter,launchSkill};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
})();