(function(){
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const CONTENT='https://gxwfsqxyuufqtitspfqg.supabase.co';
const CONTENT_KEY=['sb_publishable_','G-FYhHfDL4OGdL892gY1Zg_','epdbEeqO'].join('');
const CONTENT_HEAD={apikey:CONTENT_KEY,Authorization:`Bearer ${CONTENT_KEY}`};
const TRACK='https://fiieuiktlsivwfgyivai.supabase.co';
const TRACK_KEY='sb_publishable_e-K50PquV9gHdfmefG6tmg_o-vVSl0e';
const STATIONS=[
 {k:'vocabulary',label:'단어 학습',desc:'카드 · 뜻 · 철자'},
 {k:'vocab_test',label:'어휘 시험',desc:'정의 · 시험형 어휘 문제'},
 {k:'communication',label:'Communication',desc:'핵심 대화 표현'},
 {k:'grammar',label:'Grammar',desc:'핵심 문법'},
 {k:'sentences',label:'본문외우기',desc:'본문 문장 완성'},
 {k:'reading',label:'Reading',desc:'본문 이해'},
 {k:'constructed_response',label:'서술형',desc:'영작 · 배열 · 대화 · 본문 해석'}
];
const LABEL=Object.fromEntries(STATIONS.map(x=>[x.k,x.label]));
const CONTENT_TOTALS={
 '중1 동아 윤정미':{
  'Lesson 1':{vocabulary:30,vocab_test:30,sentences:28,communication:50,grammar:50,reading:50},
  'Lesson 2':{vocabulary:31,vocab_test:31,sentences:24,communication:50,grammar:50,reading:50},
  'Lesson 3':{vocabulary:36,vocab_test:36,sentences:53,communication:30,grammar:30,reading:30},
  'Lesson 4':{vocabulary:34,vocab_test:34,sentences:27,communication:30,grammar:30,reading:30}
 }
};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pct=v=>v==null?'—':`${Math.round(Number(v)||0)}%`;
const questionIdCache=new Map();
let wrapped=false,homeHydration=0;
function scopeFor(plan){const lessons=plan.group?.scope?.lessons;if(Array.isArray(lessons)&&lessons.length)return lessons.filter(x=>x?.lesson);return(plan.units||[]).map(lesson=>({lesson,sections:plan.practice_types||[]}))}
function activeTasks(plan){return(plan.tasks||[]).filter(t=>t.active!==false&&!t.completed_at&&Number(t.progress?.remaining)>0)}
function taskFor(plan,lesson,practice){return activeTasks(plan).filter(t=>String(t.lesson)===String(lesson)&&String(t.practice_type).toLowerCase()===String(practice).toLowerCase()).sort((a,b)=>new Date(a.due_at||'2999-01-01')-new Date(b.due_at||'2999-01-01'))[0]||null}
function realTotal(plan,lesson,practice){return Number(CONTENT_TOTALS[plan.book_label]?.[lesson]?.[practice])||0}
function skillProgress(plan,lesson,practice){const v=plan.summary?.by_lesson_practice?.[`${lesson}||${practice}`]||{},task=taskFor(plan,lesson,practice),target=realTotal(plan,lesson,practice),done=Math.max(0,Number(v.unique)||0),accuracy=done?Math.max(0,Math.min(100,Number(v.accuracy)||0)):0,coverage=target?Math.min(100,done/target*100):0,mastery=target?Math.round(coverage*accuracy/100):0;return{task,target,done,accuracy,coverage:Math.round(coverage),mastery}}
function stationAvailable(plan,lessonObj,st,sections){const strict=plan?.group?.scope?.scope_controls_v2===true;if(st.k==='sentences')return true;if(strict){if(st.k==='vocabulary'||st.k==='vocab_test')return sections.has('vocabulary');return sections.has(st.k)}return['vocabulary','vocab_test','sentences'].includes(st.k)||sections.has(st.k)||!!taskFor(plan,lessonObj.lesson,st.k)}
function lessonData(plan,lessonObj){const sections=new Set((lessonObj.sections||[]).map(x=>String(x).toLowerCase())),skills=STATIONS.map(st=>({...st,available:stationAvailable(plan,lessonObj,st,sections),...skillProgress(plan,lessonObj.lesson,st.k)})),used=skills.filter(x=>x.available&&x.target>0),mastery=used.length?Math.round(used.reduce((a,b)=>a+b.mastery,0)/used.length):0,tasks=activeTasks(plan).filter(t=>String(t.lesson)===String(lessonObj.lesson));return{...lessonObj,skills,mastery,tasks}}
function examLabel(plan){const g=plan.group||{};return[g.term?`${g.term}학기`:'',g.exam_type==='final'?'기말고사':g.exam_type==='midterm'?'중간고사':plan.exam_name].filter(Boolean).join(' · ')}
function planSchool(plan){return plan.group?.school||window.WillenaTestPrepAuth?.state?.user?.school||'학교 시험'}
function taskShelf(plans){const all=plans.flatMap(p=>activeTasks(p).map(t=>({p,t}))).sort((a,b)=>new Date(a.t.due_at||'2999-01-01')-new Date(b.t.due_at||'2999-01-01'));if(!all.length)return'';return`<div class="tp-task-shelf">${all.slice(0,6).map(({p,t})=>`<button class="tp-task-chip" data-task-plan="${esc(p.id)}" data-task-lesson="${esc(t.lesson)}" data-task-skill="${esc(t.practice_type)}"><span class="arrow">→</span><span class="k">선생님 과제</span><b>${esc(t.title||`${t.lesson} ${LABEL[t.practice_type]||t.practice_type}`)}</b><small>${Number(t.progress?.remaining)||0}개 남음</small></button>`).join('')}</div>`}
function wrongMount(){return'<div id="tpWrongCardMount" data-review-card-owner="rev49"></div>'}
function lessonCard(plan,l){const d=lessonData(plan,l);return`<button class="tp-lesson-card" data-lesson-plan="${esc(plan.id)}" data-lesson="${esc(l.lesson)}"><span class="tp-lesson-card-copy"><h3>${esc(l.lesson)}</h3><p class="tp-card-accuracy-label">최근 정확도 · 불러오는 중</p><div class="tp-card-coverage"><div class="tp-card-coverage-meta"><span>문제 완료</span><b class="tp-card-coverage-count">—</b></div><div class="tp-card-coverage-track"><i></i></div></div>${d.tasks.length?`<span class="tp-task-badge">선생님 과제 ${d.tasks.length}</span>`:''}</span><span class="tp-ring tp-card-accuracy-ring" style="--p:0%" aria-label="최근 정확도"><b>—</b></span></button>`}
async function contentGet(path){const r=await fetch(CONTENT+path,{headers:CONTENT_HEAD,cache:'no-store'});if(!r.ok)throw new Error(await r.text());return r.json()}
async function lessonQuestionIds(plan,lesson){const key=`${plan.book_key||plan.book_label}::${lesson}`;if(questionIdCache.has(key))return questionIdCache.get(key);const promise=(async()=>{let books=[];if(plan.book_key)books=await contentGet(`/rest/v1/content_books?select=id&source_key=eq.${encodeURIComponent(plan.book_key)}&limit=1`);if(!books[0])books=await contentGet(`/rest/v1/content_books?select=id&title=eq.${encodeURIComponent(plan.book_label||'')}&limit=1`);if(!books[0])return[];let units=await contentGet(`/rest/v1/content_units?select=id,title&book_id=eq.${books[0].id}&title=eq.${encodeURIComponent(lesson)}&limit=1`);if(!units[0]){const m=String(lesson).match(/Lesson\s*(\d+)/i);if(m)units=await contentGet(`/rest/v1/content_units?select=id,title&book_id=eq.${books[0].id}&unit_number=eq.${encodeURIComponent(m[1])}&limit=1`)}if(!units[0])return[];const rows=await contentGet(`/rest/v1/test_prep_questions?select=id&unit_id=eq.${units[0].id}&student_usable=eq.true`);return(rows||[]).map(x=>String(x.id)).filter(Boolean)})();questionIdCache.set(key,promise);try{return await promise}catch(e){questionIdCache.delete(key);throw e}}
async function planCardStats(planId){const token=window.WillenaAPI?.getLocalAccessToken?.()||localStorage.getItem('sb_access_token')||'';if(!token)return[];const r=await fetch(`${TRACK}/rest/v1/rpc/test_prep_card_stats`,{method:'POST',headers:{apikey:TRACK_KEY,Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({p_plan_id:String(planId)}),cache:'no-store'});if(!r.ok)throw new Error(await r.text());const rows=await r.json();return Array.isArray(rows)?rows:[]}
function cardNode(planId,lesson){return $$('.tp-lesson-card').find(x=>String(x.dataset.lessonPlan)===String(planId)&&String(x.dataset.lesson)===String(lesson))||null}
function setRing(card,stat){const ring=$('.tp-card-accuracy-ring',card),b=$('.tp-card-accuracy-ring b',card),label=$('.tp-card-accuracy-label',card),count=Math.max(0,Number(stat?.recent_count)||0),raw=stat?.recent_accuracy,has=raw!=null&&count>0,accuracy=has?Math.max(0,Math.min(100,Math.round(Number(raw)||0))):0;if(ring){ring.style.setProperty('--p',`${accuracy}%`);ring.setAttribute('aria-label',has?`최근 ${count}개 고유 문제 정확도 ${accuracy}%`:'최근 정확도 기록 없음')}if(b)b.textContent=has?`${accuracy}%`:'—';if(label)label.textContent=count?`최근 ${count}문제 정확도`:'아직 푼 문제가 없어요'}
function setCoverage(card,completed,total){const count=$('.tp-card-coverage-count',card),bar=$('.tp-card-coverage-track i',card),safeTotal=Math.max(0,Number(total)||0),safeDone=Math.max(0,Math.min(safeTotal,Number(completed)||0)),coverage=safeTotal?Math.round(safeDone/safeTotal*100):0;if(count)count.textContent=safeTotal?`${safeDone} / ${safeTotal}`:'0 / 0';if(bar)bar.style.width=`${coverage}%`}
async function hydrateLessonCards(plans){const run=++homeHydration;await Promise.all((plans||[]).map(async plan=>{let stats=[];try{stats=await planCardStats(plan.id)}catch(e){console.warn('[REV50a] card accuracy load failed',e)}if(run!==homeHydration)return;const byLesson=new Map((stats||[]).map(x=>[String(x.unit_key),x]));await Promise.all(scopeFor(plan).map(async l=>{const card=cardNode(plan.id,l.lesson);if(!card||run!==homeHydration)return;const stat=byLesson.get(String(l.lesson))||null;setRing(card,stat);try{const ids=await lessonQuestionIds(plan,l.lesson);if(run!==homeHydration||!card.isConnected)return;const attempted=new Set(Array.isArray(stat?.attempted_question_ids)?stat.attempted_question_ids.map(String):[]),completed=ids.reduce((n,id)=>n+(attempted.has(String(id))?1:0),0);setCoverage(card,completed,ids.length)}catch(e){console.warn('[REV50a] DB coverage load failed',e);const count=$('.tp-card-coverage-count',card);if(count)count.textContent='—'}}))}))}
function openStats(plan){let bg=$('#tpStatsBg');if(!bg){bg=document.createElement('div');bg.id='tpStatsBg';bg.className='tp-stats-bg';document.body.appendChild(bg);bg.onclick=e=>{if(e.target===bg)bg.classList.remove('open')}}const s=plan.summary||{},pr=s.by_practice||{};bg.innerHTML=`<div class="tp-stats-modal"><div class="tp-stats-head"><h3>내 시험 대비 기록</h3><button class="tp-stats-x">×</button></div><div class="tp-stats-grid"><div class="tp-stat"><b>${pct(s.accuracy)}</b><span>정답률</span></div><div class="tp-stat"><b>${pct(s.first_attempt_accuracy)}</b><span>첫 시도</span></div><div class="tp-stat"><b>오답 복습</b><span>홈 카드에서 확인</span></div><div class="tp-stat"><b>${pct(s.correction_rate)}</b><span>오답 회복</span></div><div class="tp-stat"><b>${s.unique_questions||0}</b><span>완료 문제</span></div><div class="tp-stat"><b>${s.sessions||0}</b><span>학습 세션</span></div></div>${STATIONS.map(st=>`<div class="tp-stat-row"><span>${st.label}</span><b>${pct(pr[st.k]?.accuracy)}</b></div>`).join('')}</div>`;$('.tp-stats-x',bg).onclick=()=>bg.classList.remove('open');bg.classList.add('open')}
function renderHome(){const home=$('#assignmentHome'),state=window.WillenaTestPrepAuth?.state;if(!home||!state)return;home.style.display='block';const plans=state.plans||[];home.innerHTML=`${wrongMount()}${taskShelf(plans)}${plans.length?plans.map(plan=>`<section class="tp-exam-section"><div class="tp-exam-head"><div><h2>${esc(planSchool(plan))}</h2><p>${esc(examLabel(plan))}</p></div><div class="tp-exam-actions">${plan.exam_date?`<span class="tp-exam-date">${esc(plan.exam_date)}</span>`:''}<button class="tp-records" data-records="${esc(plan.id)}">내 기록</button></div></div><div class="tp-book">${esc(plan.book_label||'')}</div><div class="tp-lessons">${scopeFor(plan).map(l=>lessonCard(plan,l)).join('')}</div></section>`).join(''):'<div class="tp-review-empty">지정된 시험 대비가 없습니다.</div>'}`;$$('[data-task-plan]',home).forEach(b=>b.onclick=()=>launchSkill(b.dataset.taskPlan,b.dataset.taskLesson,b.dataset.taskSkill));$$('[data-lesson-plan]',home).forEach(b=>b.onclick=()=>renderLesson(b.dataset.lessonPlan,b.dataset.lesson));$$('[data-records]',home).forEach(b=>b.onclick=e=>{e.stopPropagation();const p=plans.find(x=>String(x.id)===String(b.dataset.records));if(p)openStats(p)});hydrateLessonCards(plans);window.dispatchEvent(new CustomEvent('testprep:home-rendered'))}
function renderLesson(planId,lesson,focusSkill=null){const home=$('#assignmentHome'),state=window.WillenaTestPrepAuth?.state,plan=state?.plans?.find(p=>String(p.id)===String(planId));if(!home||!plan)return;const l=scopeFor(plan).find(x=>String(x.lesson)===String(lesson));if(!l)return;const d=lessonData(plan,l),shown=d.skills.filter(x=>x.available),next=shown.find(x=>x.task)||shown.find(x=>x.mastery<80)||shown[0];home.innerHTML=`<button class="tp-back">← 시험 대비</button><div class="tp-lesson-head"><div><h1>${esc(lesson)}</h1><p>${esc(plan.book_label||'')} · 학습 지도</p></div><span class="tp-ring" style="--p:${d.mastery}%"><b>${d.mastery}%</b></span></div><div class="tp-subway">${shown.map((s,i)=>{const current=String(focusSkill||next?.k||'')===s.k,done=s.mastery>=90;return`<div class="tp-stop ${current?'current':''} ${done?'done':''}" data-skill="${esc(s.k)}"><div class="tp-station">${done?'✓':i+1}</div><div class="tp-stop-copy"><b>${esc(s.label)}</b><small>${esc(s.desc)}</small>${s.task?`<span class="tp-task-badge">선생님 과제 · ${s.task.progress?.remaining||0}개 남음</span>`:''}<div class="tp-mini"><i style="width:${s.mastery}%"></i></div></div><div class="tp-stop-pct">${s.mastery}%<small>${s.target?`${s.done}/${s.target}`:''}${current?' · 지금 여기':''}</small></div></div>`}).join('')}</div><div class="tp-mastery-note">Mastery = 실제 범위에서 풀어 본 비율 × 현재 정답률. 문제를 조금만 풀었다면 정답률이 높아도 Mastery가 크게 오르지 않습니다.</div>`;$$('.tp-stop',home).forEach(x=>x.onclick=()=>launchSkill(plan.id,lesson,x.dataset.skill))}
async function launchSkill(planId,lesson,skill,opts={}){const api=window.WillenaAssignedTestPrep;if(!api?.startSelection)return;await api.startSelection(planId,lesson,skill,opts)}
function wrap(){if(wrapped)return;const api=window.WillenaAssignedTestPrep;if(!api?.renderHome)return;wrapped=true;const original=api.renderHome.bind(api);api.renderHome=function(){const r=original();queueMicrotask(()=>{if((history.state?.tp||'home')==='home')renderHome()});return r};renderHome()}
function onRefresh(){const nav=history.state?.tp?history.state:{tp:'home'},quiz=$('#assignedQuizPane');if(nav.tp==='practice'||(quiz&&quiz.style.display!=='none'))return;if(nav.tp==='wrong')return;if(nav.tp==='lesson'&&nav.planId&&nav.lesson){if(window.WillenaStudentsRev4?.renderJourney)window.WillenaStudentsRev4.renderJourney(nav.planId,nav.lesson);else if(window.WillenaStudentsRev2?.renderJourney)window.WillenaStudentsRev2.renderJourney(nav.planId,nav.lesson);else renderLesson(nav.planId,nav.lesson,nav.skill||null);return}if(nav.tp==='home')renderHome()}
function boot(){let tries=0;const timer=setInterval(()=>{wrap();if(wrapped||++tries>120)clearInterval(timer)},50);window.addEventListener('testprep:student-state-refresh',onRefresh)}
window.WillenaTestPrepUX={renderHome,renderLesson,launchSkill};
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',boot,{once:true});else boot();
console.log('[REV50a] lesson cards use recent unique accuracy and live DB question coverage');
})();