(function(){
  'use strict';
  let questionShownAt=performance.now(),currentQuestion=null,patchedCheck=false,patchedRecord=false,customAttemptCount=0,refreshTimer=null;
  const LABEL={vocabulary:'Vocabulary',sentences:'Sentences',communication:'Communication',grammar:'Grammar',reading:'Reading'};
  const label=k=>LABEL[k]||k||'Practice';
  const fmtMinutes=ms=>{const m=Math.round((Number(ms)||0)/60000);return m<1?'<1분':`${m}분`};
  function resetQuestionTimer(){questionShownAt=performance.now()}
  function hashId(input){const s=String(input||'');let a=2166136261,b=0x9e3779b9,c=0x85ebca6b,d=0xc2b2ae35;for(let i=0;i<s.length;i++){const x=s.charCodeAt(i);a=Math.imul(a^x,16777619);b=Math.imul(b+x,2246822519);c=Math.imul(c^x,3266489917);d=Math.imul(d+x,668265263)}return `sentence:${[a,b,c,d].map(x=>(x>>>0).toString(16).padStart(8,'0')).join('')}`}
  function patchRecordAttempt(){const auth=window.WillenaTestPrepAuth;if(!auth||patchedRecord||typeof auth.recordAttempt!=='function')return false;const original=auth.recordAttempt.bind(auth);auth.recordAttempt=function(payload){const q=currentQuestion,elapsed=Math.max(0,Math.round(performance.now()-questionShownAt));const enriched={...(payload||{}),targets:Array.isArray(payload?.targets)?payload.targets:(Array.isArray(q?.targets)?q.targets:[]),question_type:payload?.question_type||q?.question_type||null,response_time_ms:payload?.response_time_ms||elapsed};const p=original(enriched);Promise.resolve(p).then(()=>scheduleRefresh()).catch(()=>{});return p};patchedRecord=true;return true}
  function patchCheck(){if(patchedCheck||typeof window.check!=='function')return false;const original=window.check;window.check=function(q){currentQuestion=q||currentQuestion;return original.apply(this,arguments)};patchedCheck=true;return true}
  function watchQuestionCard(){const card=document.getElementById('card');if(!card)return;new MutationObserver(()=>{if(card.querySelector('.prompt')&&card.querySelector('.qnum'))resetQuestionTimer()}).observe(card,{childList:true,subtree:true})}
  async function persistCustom(type,detail){const auth=window.WillenaTestPrepAuth,sel=window.WillenaAssignedTestPrep?.selection;if(!auth||!sel?.plan)return;if(String(auth.state?.plan?.id||'')!==String(sel.plan.id)||String(auth.state?.lesson||'')!==String(sel.lesson))auth.setActivePlan(sel.plan,sel.lesson);const qid=type==='vocabulary'?detail.lexical_entry_id:hashId(`${sel.plan.id}|${sel.lesson}|${detail.passage_id||''}|${detail.sentence||''}`);await auth.recordAttempt({practice_type:type,question_id:qid,selected_answer:type==='vocabulary'?(detail.typed_answer||detail.selected_answer||null):(detail.built_sentence||null),correct_answer:type==='vocabulary'?detail.canonical_text:detail.sentence,is_correct:!!detail.is_correct,question_type:type==='vocabulary'?`vocab_${detail.mode||'practice'}`:'sentence_unscramble',response_time_ms:Number(detail.response_time_ms)||0,targets:type==='vocabulary'?['vocabulary']:['reading_text','sentence_order'],source_label:type==='vocabulary'?detail.canonical_text:detail.passage_title});customAttemptCount++;if(customAttemptCount%2===0)scheduleRefresh()}
  function scheduleRefresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(refreshStats,500)}
  async function refreshStats(){const auth=window.WillenaTestPrepAuth;if(!auth)return;try{await auth.ready;const d=await auth.edge('me');if(d?.plans){auth.state.plans=d.plans;const home=document.getElementById('assignmentHome');if(home&&home.style.display!=='none')renderStats(d.plans)}}catch(e){console.warn('[test-prep] stats refresh failed',e)}}
  function ctaPractice(s){return s?.recommendation?.practice_type||Object.entries(s?.due_by_practice||{}).sort((a,b)=>Number(b[1])-Number(a[1]))[0]?.[0]||'vocabulary'}
  function clickPractice(card,practice){const btn=card.querySelector(`.section-btn[data-section="${CSS.escape(practice)}"]`);if(btn){btn.scrollIntoView({behavior:'smooth',block:'center'});setTimeout(()=>btn.click(),250);return true}return false}
  function style(){if(document.getElementById('tpTrackingStyle'))return;const st=document.createElement('style');st.id='tpTrackingStyle';st.textContent=`
    .tp-track{margin:12px 0 16px;padding:16px;border:1px solid #dce9eb;border-radius:18px;background:linear-gradient(135deg,#f8fcfc,#fff);box-shadow:0 5px 16px rgba(25,119,126,.04)}
    .tp-cta{display:flex;align-items:center;justify-content:space-between;gap:12px;border-radius:15px;padding:13px 14px;background:linear-gradient(135deg,#19777e,#258b91);color:#fff}
    .tp-cta-copy{min-width:0}.tp-cta-kicker{font-size:10px;font-weight:800;opacity:.78;text-transform:uppercase;letter-spacing:.06em}.tp-cta-title{font-size:15px;font-weight:850;line-height:1.3;margin-top:2px}.tp-cta-detail{font-size:10px;opacity:.82;font-weight:650;margin-top:3px}
    .tp-cta-btn{flex:0 0 auto;border:0;background:#fff;color:#19777e;border-radius:11px;padding:10px 12px;font-weight:850;font-size:11px;cursor:pointer}.tp-cta.review{background:linear-gradient(135deg,#cc4779,#e45f90)}.tp-cta.review .tp-cta-btn{color:#c53e71}
    .tp-metrics{display:grid;grid-template-columns:repeat(6,1fr);gap:7px;margin-top:11px}.tp-metric{background:#fff;border:1px solid #e5edef;border-radius:12px;padding:8px 6px;text-align:center}.tp-metric b{display:block;font-size:14px;color:#24343c}.tp-metric span{font-size:9px;color:#7a878e;font-weight:700}.tp-warn{color:#cf477b!important}
    .tp-practice{display:flex;gap:6px;flex-wrap:wrap;margin-top:9px}.tp-chip{font-size:9px;font-weight:750;padding:5px 7px;border-radius:999px;background:#edf8f9;color:#386269}.tp-chip.weak{background:#fff1f6;color:#c84375}.tp-spaced{margin-top:8px;font-size:10px;color:#74838a;font-weight:650}.tp-spaced b{color:#315960}
    @media(max-width:640px){.tp-cta{align-items:flex-start;flex-direction:column}.tp-cta-btn{width:100%}.tp-metrics{grid-template-columns:repeat(3,1fr)}}`;
    document.head.appendChild(st)}
  function renderStats(plans){const home=document.getElementById('assignmentHome');if(!home||home.style.display==='none')return;style();const cards=[...home.querySelectorAll('.exam-card')];cards.forEach((card,i)=>{const plan=plans[i];if(!plan)return;card.querySelector('.tp-track')?.remove();const s=plan.summary||plan.stats||{},rec=s.recommendation||{},practice=ctaPractice(s),due=Number(s.due_review_count)||0;const box=document.createElement('div');box.className='tp-track';const chips=Object.entries(s.by_practice||{}).map(([k,v])=>`<span class="tp-chip ${(v&&v.accuracy!=null&&v.attempts>=4&&v.accuracy<75)?'weak':''}">${label(k)} ${(v&&v.accuracy!=null)?v.accuracy+'%':'-'}</span>`).join('');const next=s.next_review_at?Math.max(1,Math.ceil((new Date(s.next_review_at).getTime()-Date.now())/60000)):null;const buttonText=due?'오답 복습 시작':s.attempts?'계속 학습하기':'지금 시작하기';box.innerHTML=`<div class="tp-cta ${due?'review':''}"><div class="tp-cta-copy"><div class="tp-cta-kicker">지금 할 것</div><div class="tp-cta-title">${rec.title||'Vocabulary부터 시작해요'}</div><div class="tp-cta-detail">${rec.detail||'시험 대비를 시작해 보세요.'}</div></div><button class="tp-cta-btn">${buttonText}</button></div><div class="tp-metrics"><div class="tp-metric"><b>${s.completion==null?'-':s.completion+'%'}</b><span>진행</span></div><div class="tp-metric"><b>${s.accuracy==null?'-':s.accuracy+'%'}</b><span>정답률</span></div><div class="tp-metric"><b>${s.first_attempt_accuracy==null?'-':s.first_attempt_accuracy+'%'}</b><span>첫 시도</span></div><div class="tp-metric"><b class="${s.unresolved_wrong?'tp-warn':''}">${s.unresolved_wrong||0}</b><span>남은 오답</span></div><div class="tp-metric"><b>${s.correction_rate==null?'-':s.correction_rate+'%'}</b><span>오답 회복</span></div><div class="tp-metric"><b>${fmtMinutes(s.active_time_ms)}</b><span>학습 시간</span></div></div>${chips?`<div class="tp-practice">${chips}</div>`:''}<div class="tp-spaced"><b>빠른 오답 복습:</b> 틀리면 10분 후 → 맞으면 20분 후 → 다시 맞으면 40분 후 확인${due?` · 지금 ${due}개 복습할 차례`:next?` · 다음 복습 약 ${next}분 후`:''}</div>`;box.querySelector('.tp-cta-btn').onclick=()=>{if(!clickPractice(card,practice)){const first=card.querySelector('.section-btn');first?.click()}};const book=card.querySelector('.book-name');if(book)book.after(box);else card.prepend(box)})}
  function renderWhenReady(){let tries=0;const timer=setInterval(()=>{const home=document.getElementById('assignmentHome');const ready=home&&(home.querySelector('.exam-card')||home.querySelector('.empty-assign'));if(ready){clearInterval(timer);renderStats(window.WillenaTestPrepAuth?.state?.plans||[])}else if(++tries>24)clearInterval(timer)},125)}
  function bootstrap(){patchRecordAttempt();patchCheck();watchQuestionCard();renderWhenReady();window.addEventListener('testprep:vocab-attempt',e=>persistCustom('vocabulary',e.detail||{}).catch(err=>console.warn('[test-prep] vocab tracking failed',err)));window.addEventListener('testprep:sentence-attempt',e=>persistCustom('sentences',e.detail||{}).catch(err=>console.warn('[test-prep] sentence tracking failed',err)));let tries=0;const timer=setInterval(()=>{patchRecordAttempt();patchCheck();if((patchedRecord&&patchedCheck)||++tries>80)clearInterval(timer)},50);setTimeout(refreshStats,700)}
  if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',bootstrap,{once:true});else bootstrap();
})();
