const es6Sentences = [
  { original: "How was the parade?", chunks: ["How", "was", "the", "parade", "?"] },
  { original: "It was boring.", chunks: ["It", "was", "bor", "ing", "."] },
  { original: "I was bored.", chunks: ["I", "was", "bor", "ed", "."] },
  { original: "He was frightened because he saw a ghost.", chunks: ["He", "was", "frightened", "because", "he saw a ghost."] },
  { original: "He saw a ghost, so he was frightened.", chunks: ["He", "saw", "a ghost,", "so", "he was frightened."] },
  { original: "I’ve seen a flood.", chunks: ["I’ve", "seen", "a", "flood", "."] },
  { original: "I’ve never seen a blizzard.", chunks: ["I’ve", "never", "seen", "a", "blizzard."] },
  { original: "Have you ever experienced a typhoon?", chunks: ["Have", "you", "ever", "experienced", "a typhoon?"] },
  { original: "Yes, I have.", chunks: ["Yes,", "I", "have", ".", ""] },
  { original: "No, I haven’t.", chunks: ["No,", "I", "haven’t", ".", ""] },
  { original: "When there is an earthquake, we must get under a table.", chunks: ["When there is", "an earthquake,", "we must", "get under", "a table."] },
  { original: "When there is an earthquake, we must not use elevators.", chunks: ["When there is", "an earthquake,", "we must not", "use", "elevators."] },
  { original: "What did he say?", chunks: ["What", "did", "he", "say", "?"] },
  { original: "He said he was going to take out the trash.", chunks: ["He said", "he was", "going to", "take out", "the trash."] },
  { original: "Which one is Jim?", chunks: ["Which", "one", "is", "Jim", "?"] },
  { original: "He’s the one who is going through the tunnel.", chunks: ["He’s the one", "who is", "going", "through", "the tunnel."] },
  { original: "Has she already watched a video clip?", chunks: ["Has", "she", "already", "watched", "a video clip?"] },
  { original: "Yes, she has.", chunks: ["Yes,", "she", "has", ".", ""] },
  { original: "No, she hasn’t.", chunks: ["No,", "she", "hasn’t", ".", ""] },
  { original: "He’s already written the email, but he hasn’t sent it yet.", chunks: ["He’s already", "written the email,", "but", "he hasn’t", "sent it yet."] },
  { original: "How long has he owned a tablet?", chunks: ["How", "long", "has he", "owned", "a tablet?"] },
  { original: "He’s owned a tablet since July.", chunks: ["He’s owned", "a tablet", "since", "July", "."] },
  { original: "How long have you been planting flowers?", chunks: ["How", "long", "have you", "been planting", "flowers?"] },
  { original: "I’ve been planting flowers for one hour.", chunks: ["I’ve been", "planting", "flowers", "for", "one hour."] },
  { original: "When was the Eiffel Tower built?", chunks: ["When", "was", "the Eiffel", "Tower", "built?"] },
  { original: "It was started in 1887, and it was finished in 1889.", chunks: ["It was started", "in 1887,", "and", "it was finished", "in 1889."] },
  { original: "What was invented by Thomas Edison?", chunks: ["What was", "invented", "by", "Thomas", "Edison?"] },
  { original: "The light bulb was invented by him in 1879.", chunks: ["The light bulb", "was invented", "by him", "in", "1879."] },
  { original: "If you want to help the environment, what can you do?", chunks: ["If you want", "to help", "the environment,", "what", "can you do?"] },
  { original: "I can plant trees.", chunks: ["I", "can", "plant", "trees", "."] },
  { original: "If we reuse paper, we’ll reduce waste.", chunks: ["If we", "reuse", "paper,", "we’ll reduce", "waste."] },
  { original: "What does she wish she could do?", chunks: ["What does", "she wish", "she", "could do", "?"] },
  { original: "She wishes she could go to space.", chunks: ["She wishes", "she could", "go", "to", "space."] },
  { original: "If you could have one superpower, what would you do?", chunks: ["If you could", "have one", "superpower,", "what would", "you do?"] },
  { original: "I’d travel through time.", chunks: ["I’d", "travel", "through", "time", "."] }
];

export default es6Sentences;