// Shared list definitions for Word Arcade progress calculations

export const LEVEL1_LISTS = [
  { label: 'Easy Animals', file: 'EasyAnimals.json', emoji: '🐯' },
  { label: 'More Animals', file: 'Animals2.json', emoji: '🐼' },
  { label: 'Fruits & Veggies', file: 'Food1.json', emoji: '🍎' },
  { label: 'Meals & Snacks', file: 'Food2.json', emoji: '🍔' },
  { label: 'World Foods', file: 'Food3.json', emoji: '🍣' },
  { label: 'Jobs (Easy)', file: 'EasyJobs.json', emoji: '👩‍🔧' },
  { label: 'Getting Around', file: 'Transportation.json', emoji: '🚗' },
  { label: 'Hobbies (Easy)', file: 'EasyHobbies.json', emoji: '🎨' },
  { label: 'Sports', file: 'Sports.json', emoji: '🏀' },
  { label: 'School Things', file: 'SchoolSupplies.json', emoji: '✏️' },
  { label: 'Action Words (Easy)', file: 'EasyVerbs.json', emoji: '🏃‍♂️' },
  { label: 'Feelings & Emotions', file: 'Feelings.json', emoji: '😊' },
  { label: 'Questions (Basics)', file: 'QuestionsBasics.json', emoji: '❓' },
];

export const LEVEL2_LISTS = [
  { label: 'Animals', file: 'sample-wordlists-level2/AnimalsAdvanced.json', emoji: '🐆', progressKey: 'Level 2 - Animals Advanced' },
  { label: 'Verbs 1', file: 'sample-wordlists-level2/Verbs1.json', emoji: '🗣️', progressKey: 'Level 2 - Verbs 1' },
  { label: 'Verbs 2', file: 'sample-wordlists-level2/Verbs2.json', emoji: '💪', progressKey: 'Level 2 - Verbs 2' },
  { label: 'Verbs 3', file: 'sample-wordlists-level2/Verbs3.json', emoji: '🏃', progressKey: 'Level 2 - Verbs 3' },
  { label: 'Verbs 4', file: 'sample-wordlists-level2/Verbs4.json', emoji: '💬', progressKey: 'Level 2 - Verbs 4' },
  { label: 'Polite Requests (Kids)', file: 'sample-wordlists-level2/PoliteRequestsKids.json', emoji: '🙏', progressKey: 'Level 2 - Polite Requests (Kids)' },
  { label: 'Adjectives 1', file: 'sample-wordlists-level2/Adjectives1.json', emoji: '✨', progressKey: 'Level 2 - Adjectives 1' },
  { label: 'Adjectives 2', file: 'sample-wordlists-level2/Adjectives2.json', emoji: '✨', progressKey: 'Level 2 - Adjectives 2' },
  { label: 'Adjectives 3', file: 'sample-wordlists-level2/Adjectives3.json', emoji: '✨', progressKey: 'Level 2 - Adjectives 3' },
  { label: 'Feelings', file: 'sample-wordlists-level2/Feelings2.json', emoji: '😌', progressKey: 'Level 2 - Feelings Advanced' },
  { label: 'Vegetables', file: 'sample-wordlists-level2/Vegetables.json', emoji: '🥦', progressKey: 'Level 2 - Vegetables' },
  { label: 'Clothing & Accessories', file: 'sample-wordlists-level2/ClothingAccessories.json', emoji: '👔', progressKey: 'Level 2 - Clothing & Accessories' },
  { label: 'School Supplies', file: 'sample-wordlists-level2/SchoolSupplies2.json', emoji: '📐', progressKey: 'Level 2 - School Supplies 2' },
  { label: 'Community Places', file: 'sample-wordlists-level2/CommunityPlaces2.json', emoji: '🏛️', progressKey: 'Level 2 - Community Places' },
  { label: 'Nature & Landforms', file: 'sample-wordlists-level2/NatureLandforms.json', emoji: '🏔️', progressKey: 'Level 2 - Nature & Landforms' },
  { label: 'Kitchen Appliances', file: 'sample-wordlists-level2/KitchenAppliances.json', emoji: '🍳', progressKey: 'Level 2 - Kitchen Appliances' },
  { label: 'Art & Culture', file: 'sample-wordlists-level2/ArtCulture.json', emoji: '🎨', progressKey: 'Level 2 - Art & Culture' },
  { label: 'Rare Animals', file: 'sample-wordlists-level2/RareAnimals.json', emoji: '🦋', progressKey: 'Level 2 - Rare Animals' },
  { label: 'Weather', file: 'sample-wordlists-level2/Weather.json', emoji: '⛈️', progressKey: 'Level 2 - Weather' },
  { label: 'Home Rooms', file: 'sample-wordlists-level2/HomeRooms.json', emoji: '🏠', progressKey: 'Level 2 - Home Rooms' },
  { label: 'Musical Instruments', file: 'sample-wordlists-level2/MusicalInstruments.json', emoji: '🎸', progressKey: 'Level 2 - Musical Instruments' },
];

export const LEVEL3_LISTS = [
  { label: 'Verbs 5', file: 'sample-wordlists-level3/Verbs5.json', emoji: '🗣️', progressKey: 'Level 3 - Verbs 5' },
  { label: 'Daily Life', file: 'sample-wordlists-level3/Activities1.json', emoji: '🏠', progressKey: 'Level 3 - Daily Life' },
  { label: 'Verbs 6', file: 'sample-wordlists-level3/Verbs6.json', emoji: '💪', progressKey: 'Level 3 - Verbs 6' },
  { label: 'Playing Outside', file: 'sample-wordlists-level3/Activities2.json', emoji: '🌳', progressKey: 'Level 3 - Playing Outside' },
  { label: 'Verbs 7', file: 'sample-wordlists-level3/Verbs7.json', emoji: '🏃', progressKey: 'Level 3 - Verbs 7' },
  { label: 'Being Creative', file: 'sample-wordlists-level3/Activities3.json', emoji: '🎨', progressKey: 'Level 3 - Being Creative' },
  { label: 'Verbs 8', file: 'sample-wordlists-level3/Verbs8.json', emoji: '💬', progressKey: 'Level 3 - Verbs 8' },
  { label: 'Adjectives 4', file: 'sample-wordlists-level3/Adjectives4.json', emoji: '✨', progressKey: 'Level 3 - Adjectives 4' },
  { label: 'Adjectives 5', file: 'sample-wordlists-level3/Adjectives5.json', emoji: '✨', progressKey: 'Level 3 - Adjectives 5' },
  { label: 'Adjectives 6', file: 'sample-wordlists-level3/Adjectives6.json', emoji: '✨', progressKey: 'Level 3 - Adjectives 6' },
];

export const LEVEL4_LISTS = [
  { label: 'Phrasal Verbs 1 (Kids)', file: 'sample-wordlists-level4/PhrasalVerbsKids1.json', emoji: '🧩', progressKey: 'Level 4 - Phrasal Verbs Kids 1' },
  { label: 'Phrasal Verbs 2 (Kids)', file: 'sample-wordlists-level4/PhrasalVerbsKids2.json', emoji: '🧩', progressKey: 'Level 4 - Phrasal Verbs Kids 2' },
  { label: 'Classroom Phrases (Kids)', file: 'sample-wordlists-level4/ClassroomPhrasesKids.json', emoji: '🏫', progressKey: 'Level 4 - Classroom Phrases Kids' },
  { label: 'Daily Routines 2', file: 'sample-wordlists-level4/DailyRoutines2.json', emoji: '🕒', progressKey: 'Level 4 - Daily Routines 2' },
  { label: 'Chores (Kids)', file: 'sample-wordlists-level4/ChoresKids.json', emoji: '🧹', progressKey: 'Level 4 - Chores Kids' },
  { label: 'Playground Actions', file: 'sample-wordlists-level4/PlaygroundActions.json', emoji: '🎠', progressKey: 'Level 4 - Playground Actions' },
  { label: 'Sports & Hobbies 2 (Kids)', file: 'sample-wordlists-level4/SportsHobbiesKids2.json', emoji: '🎯', progressKey: 'Level 4 - Sports & Hobbies Kids 2' },
];

export const PHONICS_LISTS = [
  { label: 'Short A Sound', file: 'phonics-lists/short-vowels/short-a.json', emoji: '🐱', progressKey: 'Phonics - Short A Sound' },
  { label: 'Short E Sound', file: 'phonics-lists/short-vowels/short-e.json', emoji: '🥚', progressKey: 'Phonics - Short E Sound' },
  { label: 'Short I Sound', file: 'phonics-lists/short-vowels/short-i.json', emoji: '🏠', progressKey: 'Phonics - Short I Sound' },
  { label: 'Short O Sound', file: 'phonics-lists/short-vowels/short-o.json', emoji: '🐕', progressKey: 'Phonics - Short O Sound' },
  { label: 'Short U Sound', file: 'phonics-lists/short-vowels/short-u.json', emoji: '☀️', progressKey: 'Phonics - Short U Sound' },
  { label: 'Long A Sound', file: 'phonics-lists/long-vowels/long-a.json', emoji: '🍰', progressKey: 'Phonics - Long A Sound' },
  { label: 'Long E Sound', file: 'phonics-lists/long-vowels/long-e.json', emoji: '🐝', progressKey: 'Phonics - Long E Sound' },
  { label: 'Long I Sound', file: 'phonics-lists/long-vowels/long-i.json', emoji: '🍦', progressKey: 'Phonics - Long I Sound' },
  { label: 'Long O Sound', file: 'phonics-lists/long-vowels/long-o.json', emoji: '🌊', progressKey: 'Phonics - Long O Sound' },
  { label: 'Long U Sound', file: 'phonics-lists/long-vowels/long-u.json', emoji: '🐮', progressKey: 'Phonics - Long U Sound' },
  { label: 'Long A: AI, AY', file: 'phonics-lists/long-vowels/long-a-ai-ay.json', emoji: '☔', progressKey: 'Phonics - Long A: AI, AY' },
  { label: 'Long O: OA, OE', file: 'phonics-lists/long-vowels/long-o-oa-oe.json', emoji: '⛵', progressKey: 'Phonics - Long O: OA, OE' },
  { label: 'Blend: BL, BR', file: 'phonics-lists/consonant-blends/blend-br-bl.json', emoji: '🎈', progressKey: 'Phonics - Blend: BL, BR' },
  { label: 'Blend: CL, CR', file: 'phonics-lists/consonant-blends/blend-cr-cl.json', emoji: '☁️', progressKey: 'Phonics - Blend: CL, CR' },
  { label: 'Blend: DR, FL, FR', file: 'phonics-lists/consonant-blends/blend-dr-fl-fr.json', emoji: '🌸', progressKey: 'Phonics - Blend: DR, FL, FR' },
  { label: 'Blend: GL, GR', file: 'phonics-lists/consonant-blends/blend-gr-gl.json', emoji: '🍇', progressKey: 'Phonics - Blend: GL, GR' },
  { label: 'Blend: PL, PR', file: 'phonics-lists/consonant-blends/blend-pl-pr-sc.json', emoji: '🌳', progressKey: 'Phonics - Blend: PL, PR' },
  { label: 'Blend: SK, SL, SM, SN, SP, ST, SW', file: 'phonics-lists/consonant-blends/blend-sk-sl-sm-sn-sp-st-sw.json', emoji: '⭐', progressKey: 'Phonics - Blend: SK, SL, SM, SN, SP, ST, SW' },
  { label: 'Blend: TR, TW', file: 'phonics-lists/consonant-blends/blend-tr-tw.json', emoji: '🎄', progressKey: 'Phonics - Blend: TR, TW' },
  { label: 'CH, SH Words', file: 'phonics-lists/more/ch-sh.json', emoji: '🪑', progressKey: 'Phonics - CH, SH Words' },
  { label: 'TH, WH Words', file: 'phonics-lists/more/th-wh.json', emoji: '⚡', progressKey: 'Phonics - TH, WH Words' },
  { label: 'CK, NG, MP Endings', file: 'phonics-lists/more/ck-ng-mp.json', emoji: '🎵', progressKey: 'Phonics - CK, NG, MP Endings' },
];
