(()=>{
'use strict';
const $=(s,r=document)=>r.querySelector(s),$$=(s,r=document)=>[...r.querySelectorAll(s)];
const far=$('#far'),mid=$('#mid'),near=$('#near');
let currentUserId='',overviewTimer=0,currentScope='global',currentMetric='super',visibleCount=5,currentData=null;
const classCache=new Map(),globalCache=new Map();
function addShapes(layer,specs){if(!layer)return;specs.forEach(([type,x,y,size,color,rot=0])=>{const e=document.createElement('span');e.className=`shape ${type}`;e.style.left=x+'%';e.style.top=y+'px';e.style.width=size+'px';e.style.height=(type==='pillshape'?Math.max(14,Math.round(size*.28)):size)+'px';if(type==='ringshape'||type==='plusshape')e.style.color=color;else e.style.background=color;if(rot)e.style.transform=`rotate(${rot}deg)`;layer.appendChild(e)})}
addShapes(far,[['circle',5,80,14,'#ff9bc5'],['pillshape',46,118,38,'#a9c4ff',12],['ringshape',88,150,28,'#82dfe5'],['diamond',18,210,16,'#b7afff'],['circle',54,245,10,'#9fe6bf'],['plusshape',76,275,20,'#ffd76f'],['ringshape',32,312,20,'#ffb9d7'],['circle',72,340,12,'#9fe6bf'],['diamond',92,378,13,'#72dce3'],['pillshape',11,410,54,'#ffd76f',-15],['circle',48,448,11,'#b7afff'],['ringshape',86,470,24,'#ff9bc5'],['plusshape',6,505,16,'#82dfe5'],['diamond',34,540,14,'#72dce3'],['pillshape',72,566,40,'#9fe6bf',8],['plusshape',64,600,18,'#9b8cff'],['circle',8,665,16,'#a9c4ff'],['ringshape',47,696,18,'#ffd76f'],['diamond',89,730,18,'#ffb9d7'],['circle',58,760,10,'#82dfe5'],['ringshape',20,790,26,'#9fe6bf'],['pillshape',43,824,44,'#a9c4ff',-11],['plusshape',77,860,18,'#72dce3'],['diamond',13,895,12,'#b7afff'],['circle',82,930,13,'#ffd76f'],['ringshape',54,962,20,'#72dce3'],['pillshape',28,990,46,'#ff9bc5',20],['plusshape',91,1028,16,'#9fe6bf'],['diamond',72,1060,16,'#b7afff'],['circle',18,1098,11,'#ffb9d7'],['circle',62,1130,12,'#82dfe5'],['pillshape',38,1164,42,'#ffd76f',10],['ringshape',9,1200,24,'#ffd76f'],['diamond',49,1236,14,'#72dce3'],['plusshape',87,1270,20,'#ff9bc5']]);
addShapes(mid,[['circle',4,170,34,'#ff92bc'],['diamond',50,205,20,'#a9c4ff'],['ringshape',84,240,46,'#72dce3'],['pillshape',8,278,68,'#9fe6bf',-10],['diamond',24,315,24,'#ffd76f'],['circle',52,348,24,'#ffb9d7'],['plusshape',71,380,30,'#9b8cff'],['ringshape',91,414,34,'#ffd76f'],['circle',60,445,28,'#9fe6bf'],['diamond',35,486,22,'#72dce3'],['pillshape',7,525,82,'#a9c4ff',15],['plusshape',48,558,24,'#9fe6bf'],['diamond',88,590,26,'#ff9ec7'],['circle',62,626,26,'#ffd76f'],['ringshape',15,665,40,'#8fe3e8'],['pillshape',77,700,72,'#b7afff',12],['plusshape',60,735,28,'#ffd76f'],['diamond',29,774,20,'#72dce3'],['circle',87,815,38,'#9fe6bf'],['ringshape',8,852,34,'#ff92bc'],['diamond',67,890,28,'#ff9ec7'],['plusshape',45,924,24,'#9b8cff'],['ringshape',28,960,38,'#a9c4ff'],['circle',8,996,26,'#72dce3'],['pillshape',76,1035,78,'#ffd76f',-18],['diamond',42,1074,22,'#9fe6bf'],['plusshape',8,1115,26,'#ff92bc'],['ringshape',91,1152,34,'#a9c4ff'],['circle',70,1190,30,'#72dce3'],['pillshape',34,1230,70,'#ff9ec7',14]]);
addShapes(near,[['ringshape',66,90,76,'#8fe3e8'],['diamond',10,180,34,'#ff9bc5'],['plusshape',88,275,44,'#72dce3'],['circle',72,365,58,'#ffd76f'],['ringshape',5,455,64,'#9b8cff'],['pillshape',80,545,106,'#a9c4ff',14],['diamond',14,640,42,'#9fe6bf'],['plusshape',82,735,46,'#ff9ec7'],['circle',88,835,72,'#9fe6bf'],['ringshape',18,930,62,'#ffd76f'],['diamond',70,1025,40,'#ff9bc5'],['pillshape',6,1120,112,'#ff9ec7',-12],['plusshape',88,1210,42,'#72dce3']]);
async function jsonFetch(url,opts){const r=await WillenaAPI.fetch(url,opts);const d=await r.json().catch(()=>({}));return{r,d}}
async function getSession(){let x=await jsonFetch(`/.netlify/functions/supabase_auth?action=whoami&_=${Date.now()}`,{cache:'no-store'});if(x.r.ok&&x.d.success)return x.d;try{const ref=await jsonFetch(`/.netlify/functions/supabase_auth?action=refresh&_=${Date.now()}`,{cache:'no-store'});if(ref.r.ok&&ref.d.success){if(ref.d.access_token&&WillenaAPI.setLocalTokens)WillenaAPI.setLocalTokens(ref.d.access_token,'');x=await jsonFetch(`/.netlify/functions/supabase_auth?action=whoami&_=${Date.now()}`,{cache:'no-store'});if(x.r.ok&&x.d.success)return x.d}}catch{}return null}
function firstLetter(v){return String(v||'Student').trim().charAt(0).toUpperCase()||'S'}
function applyProfile(name,avatar,cls){const n=name||'Student';if($('#profileName'))$('#profileName').textContent=n;if($('#headerName'))$('#headerName').textContent=n;const av=avatar||firstLetter(n);if($('#profileAvatar'))$('#profileAvatar').textContent=av;if($('.avatar'))$('.avatar').textContent=av;if(cls&&$('#headerClass'))$('#headerClass').textContent=cls}
function applyOverview(ov){if(!ov)return;const stars=Number(ov.stars),pts=Number(ov.points);if(Number.isFinite(stars)&&$('#headerStars'))$('#headerStars').textContent=`⭐ ${stars.toLocaleString()}`;if(Number.isFinite(pts)&&$('#headerPoints'))$('#headerPoints').textContent=`+ ${pts.toLocaleString()}`}
async function loadOverview(){try{const {r,d}=await jsonFetch(`/.netlify/functions/progress_summary?section=overview&_=${Date.now()}`);if(r.ok)applyOverview(d)}catch(e){console.warn('[dashboard] overview',e)}}
function scheduleOverview(){clearTimeout(overviewTimer);overviewTimer=setTimeout(loadOverview,300)}
function updateTabUI(scope){$$('.scope-tabs .tab').forEach(btn=>{const active=btn.dataset.scope===scope;btn.classList.toggle('active',active);btn.setAttribute('aria-selected',active?'true':'false')})}
function updateMetricUI(metric){$$('.metric-tab').forEach(btn=>{const active=btn.dataset.metric===metric;btn.classList.toggle('active',active);btn.setAttribute('aria-selected',active?'true':'false')});const c=$('#metricCaption');if(c)c.textContent=metric==='points'?'Points':metric==='stars'?'Stars':'Super Points'}
function normalizeEntries(raw){return (Array.isArray(raw)?raw:[]).map(e=>({...e,name:e.name||'Student',stars:Number(e.stars)||0,points:Number(e.points)||0,superScore:Number.isFinite(Number(e.superScore))?Number(e.superScore):Math.round(((Number(e.stars)||0)*(Number(e.points)||0))/1000)}))}
function sortedEntries(data){const list=normalizeEntries(data?.leaderboard);return list.sort((a,b)=>{if(currentMetric==='points')return b.points-a.points||b.stars-a.stars||String(a.name).localeCompare(String(b.name));if(currentMetric==='stars')return b.stars-a.stars||b.points-a.points||String(a.name).localeCompare(String(b.name));return b.superScore-a.superScore||b.stars-a.stars||b.points-a.points||String(a.name).localeCompare(String(b.name))})}
function metricText(e){if(currentMetric==='points')return `${e.points.toLocaleString()} 🪙`;if(currentMetric==='stars')return `${e.stars.toLocaleString()} ⭐`;return `${e.superScore.toLocaleString()} ⚡`}
function renderLeaderboard(){const rows=$('#leaderRows'),more=$('#leaderMore');if(!rows)return;const data=currentData,scope=currentScope,list=sortedEntries(data);if($('#leaderClass'))$('#leaderClass').textContent=scope==='class'?(data?.class?`${data.class} · THIS MONTH`:'MY CLASS · THIS MONTH'):'EVERYBODY · THIS MONTH';if(!list.length){rows.innerHTML=`<div class="loading">No ${scope==='class'?'class ':''}leaderboard data yet.</div>`;if(more)more.hidden=true;return}const shown=list.slice(0,visibleCount);rows.innerHTML=shown.map((e,i)=>`<div class="row${e.self?' self':''}"><div class="rank">${i+1}</div><div class="name">${e.name}${e.self?' · You':''}</div><div class="score">${metricText(e)}</div></div>`).join('');if(more){more.hidden=visibleCount>=list.length;more.textContent=visibleCount+5>=list.length?'Show all':'More'}}
async function fetchLeaderboard(scope,forceRefresh=false){const section=scope==='global'?'leaderboard_stars_global':'leaderboard_stars_class',cache=scope==='global'?globalCache:classCache,key=`month_${currentUserId}`;if(!forceRefresh&&cache.has(key))return cache.get(key);const bypass=forceRefresh?'&bypass_cache=1':'',userParam=scope==='class'?`&u=${encodeURIComponent(currentUserId)}`:'';let {r,d}=await jsonFetch(`/.netlify/functions/progress_summary?section=${section}&timeframe=month${bypass}${userParam}`);if((!r.ok||!d.success)&&forceRefresh)({r,d}=await jsonFetch(`/.netlify/functions/progress_summary?section=${section}&timeframe=month${userParam}`));if(!r.ok||!d.success)throw new Error(d.error||`HTTP ${r.status}`);cache.set(key,d);return d}
async function loadLeaderboard(scope=currentScope,forceRefresh=false){const rows=$('#leaderRows');if(!rows||!currentUserId)return;currentScope=scope;visibleCount=5;updateTabUI(scope);rows.innerHTML='<div class="loading">Loading leaderboard…</div>';const more=$('#leaderMore');if(more)more.hidden=true;try{currentData=await fetchLeaderboard(scope,forceRefresh);renderLeaderboard()}catch(e){console.error('[dashboard] leaderboard',e);rows.innerHTML='<div class="loading">Could not load the leaderboard.</div>'}}
async function bootIdentity(){if(!window.WillenaAPI){location.replace('/students/signin.html?next='+encodeURIComponent(location.pathname));return}try{const who=await getSession();if(!who){location.replace('/students/signin.html?next='+encodeURIComponent(location.pathname));return}currentUserId=who.user_id||who.id||'';let name=who.name||who.full_name||who.username||who.display_name||'',avatar='',cls='';try{const [{r:pr,d:pd},{r:or,d:od}]=await Promise.all([jsonFetch(`/.netlify/functions/supabase_auth?action=get_profile_name&_=${Date.now()}`),jsonFetch(`/.netlify/functions/progress_summary?section=overview&_=${Date.now()}`)]);if(pr.ok&&pd.success){name=pd.name||pd.username||name;avatar=pd.avatar||'';cls=pd.class||''}if(or.ok)applyOverview(od)}catch{}applyProfile(name,avatar,cls);await loadLeaderboard('global',true)}catch(e){console.error('[dashboard] identity',e);location.replace('/students/signin.html?next='+encodeURIComponent(location.pathname))}}
function settings(){const modal=$('#settingsModal'),open=$('#openSettings'),close=$('#closeSettings');if(!modal||!open||!close)return;const show=()=>{modal.classList.add('open');modal.setAttribute('aria-hidden','false');document.body.classList.add('modal-open')},hide=()=>{modal.classList.remove('open');modal.setAttribute('aria-hidden','true');document.body.classList.remove('modal-open')};open.addEventListener('click',show);$('.avatar')?.addEventListener('click',show);close.addEventListener('click',hide);modal.addEventListener('click',e=>{if(e.target===modal)hide()});document.addEventListener('keydown',e=>{if(e.key==='Escape')hide()});$('#profileEditBtn')?.addEventListener('click',()=>location.href='/students/profile.html');$('#logoutBig')?.addEventListener('click',async()=>{try{WillenaAPI.clearLocalTokens?.();await WillenaAPI.fetch('/.netlify/functions/supabase_auth?action=logout',{method:'POST'})}catch{}location.href='/students/login.html'});const lang=$('#languageSelect');if(lang&&window.StudentLang){lang.value=StudentLang.getLang()==='ko'?'ko':'en';lang.addEventListener('change',()=>StudentLang.setLang(lang.value))}const dark=$('#darkToggle');dark?.addEventListener('change',()=>window.StudentTheme?.toggle());const motion=$('#motionToggle');motion?.addEventListener('change',()=>{document.body.classList.toggle('no-motion',!motion.checked)});const music=$('#musicToggle');if(music){try{music.checked=localStorage.getItem('wa.audio.music.enabled')==='1'}catch{}music.addEventListener('change',()=>{try{localStorage.setItem('wa.audio.music.enabled',music.checked?'1':'0');window.dispatchEvent(new CustomEvent('wa:audio-settings-changed',{detail:{music:music.checked}}))}catch{}})}}
$$('.scope-tabs .tab').forEach(btn=>btn.addEventListener('click',()=>loadLeaderboard(btn.dataset.scope||'global',false)));
$$('.metric-tab').forEach(btn=>btn.addEventListener('click',()=>{currentMetric=btn.dataset.metric||'super';visibleCount=5;updateMetricUI(currentMetric);renderLeaderboard()}));
$('#leaderMore')?.addEventListener('click',()=>{visibleCount+=5;renderLeaderboard()});
window.addEventListener('points:update',e=>{if(Number.isFinite(Number(e.detail?.total))&&$('#headerPoints'))$('#headerPoints').textContent=`+ ${Number(e.detail.total).toLocaleString()}`;else scheduleOverview()});
window.addEventListener('stars:optimistic-bump',scheduleOverview);window.addEventListener('stars:refresh',()=>{scheduleOverview();classCache.clear();globalCache.clear();if(currentUserId)loadLeaderboard(currentScope,true)});window.addEventListener('session:ended',()=>{scheduleOverview();classCache.clear();globalCache.clear();if(currentUserId)loadLeaderboard(currentScope,true)});window.addEventListener('focus',()=>{loadOverview();if(currentUserId){classCache.clear();globalCache.clear();loadLeaderboard(currentScope,false)}});
updateTabUI('global');updateMetricUI('super');settings();bootIdentity();
})();