(function(){
'use strict';
var loadQuestionBank=window.loadQuestionBank;
var root=document.querySelector("#app"),langBtn=document.querySelector("#languageBtn"),brandSubtitle=document.querySelector("#brandSubtitle"),footerText=document.querySelector("#footerText");
var bank=[],lang="ko";
function clamp(v,a,b){return Math.max(a,Math.min(b,v))}
function shuffle(a){return a.slice().sort(function(){return Math.random()-.5})}
var T={en:{brand:"Free Level Test",footer:"Willena English · Staging assessment",welcomeTitle:"Level Test",start:"Start",grade:"What school stage is the learner in?",years:"How long has the learner studied English?",listening:"Include listening questions?",listenYes:"Yes — include listening",listenNo:"No — skip listening",listenHint:"Use headphones or a quiet place.",length:"How detailed should the test be?",preschool:"Preschool",e12:"Elementary 1–2",e34:"Elementary 3–4",e56:"Elementary 5–6",middle:"Middle school",older:"High school or adult",none:"Not yet",under1:"Less than 1 year",y12:"1–2 years",y35:"3–5 years",over5:"More than 5 years",q20:"Quick · 20 questions",q30:"Standard · 30 questions",q40:"Detailed · 40 questions",back:"Back",question:"Question",next:"Next",result:"Your estimated level",broad:"This is a broad starting point based on the adaptive questions.",answered:"Questions answered",correct:"Correct answers",level:"Level",can:"Suggested starting point",retry:"Try again",home:"Back to start",loadFail:"Could not load the test",step:"Setup",unscramble:"Tap the words to put the sentence in the correct order.",tapUndo:"Tap a placed piece to move it back.",listenInstruction:"Listen and choose the best answer.",play:"Play audio",playing:"Playing…",playsLeft:"plays left"},ko:{brand:"무료 영어 레벨 테스트",footer:"Willena English · 스테이징 진단 테스트",welcomeTitle:"레벨 테스트",start:"시작하기",grade:"학생의 현재 학교 단계는 무엇인가요?",years:"영어를 얼마나 오래 공부했나요?",listening:"듣기 문제를 포함할까요?",listenYes:"네 — 듣기 포함",listenNo:"아니요 — 듣기 제외",listenHint:"이어폰을 사용하거나 조용한 곳에서 응시하세요.",length:"어느 정도 자세한 테스트를 원하시나요?",preschool:"유치원",e12:"초등학교 1–2학년",e34:"초등학교 3–4학년",e56:"초등학교 5–6학년",middle:"중학교",older:"고등학생 또는 성인",none:"아직 배우지 않음",under1:"1년 미만",y12:"1–2년",y35:"3–5년",over5:"5년 이상",q20:"간단 · 20문제",q30:"기본 · 30문제",q40:"자세히 · 40문제",back:"뒤로",question:"문제",next:"다음",result:"예상 영어 단계",broad:"적응형 문제 결과를 바탕으로 한 대략적인 시작 단계입니다.",answered:"푼 문제",correct:"정답",level:"단계",can:"추천 시작 단계",retry:"다시 하기",home:"처음으로",loadFail:"테스트를 불러올 수 없습니다",step:"설정",unscramble:"단어를 눌러 올바른 순서로 문장을 만드세요.",tapUndo:"놓은 조각을 누르면 다시 아래로 이동합니다.",listenInstruction:"음성을 듣고 가장 알맞은 답을 고르세요.",play:"음성 듣기",playing:"재생 중…",playsLeft:"회 남음"}};
function tx(k){return T[lang][k]||k}
var S={view:"setup",setupStep:0,setup:{grade:null,years:null,listening:null,length:null},ability:2,maxQ:30,used:new Set(),answers:[],current:null,selected:null,scramblePool:[],wrongByLevel:{},typeCounts:{},translationCount:0,playsLeft:0,isSpeaking:false};
function chrome(){document.documentElement.lang=lang;langBtn.textContent=lang==="ko"?"English":"한국어";brandSubtitle.textContent=tx("brand");footerText.textContent=tx("footer")}
langBtn.onclick=function(){lang=lang==="en"?"ko":"en";chrome();render()};
function screen(html,dir){dir=dir||"forward";if(window.speechSynthesis)window.speechSynthesis.cancel();root.classList.add("is-swapping");root.innerHTML='<section class="screen screen-safe-in '+(dir==="back"?"from-left":"from-right")+'">'+html+'</section>';var next=root.querySelector(".screen");requestAnimationFrame(function(){requestAnimationFrame(function(){if(next)next.classList.add("screen-safe-ready");root.classList.remove("is-swapping")})});setTimeout(function(){if(next)next.classList.add("screen-safe-ready");root.classList.remove("is-swapping")},420)}
function startAbility(years,grade){var yearBase={0:1,1:1.8,2:2.7,4:4,6:5.3},stageAdjustment={1:0,2:0,4:.25,6:.5,8:.75,9:1};return clamp((yearBase[Number(years)]==null?1:yearBase[Number(years)])+(stageAdjustment[Number(grade)]==null?0:stageAdjustment[Number(grade)]),1,7)}
function expected(a,d){return 1/(1+Math.exp((d-a)*1.1))}
function confidenceFactor(){return Math.max(.28,1-(S.answers.length*.035))}
function wrongPenalty(level){return Math.pow(.8,S.wrongByLevel[level]||0)}
function optionButtons(items,key){return '<div class="setup-options" data-key="'+key+'">'+items.map(function(item){return '<button class="setup-option" data-value="'+item[0]+'">'+item[1]+'<span>→</span></button>'}).join("")+'</div>'}
function setup(dir){dir=dir||"forward";var step=S.setupStep;document.body.classList.toggle("welcome-mode",step===0);if(step===0){screen('<div class="welcome-layout"><img class="welcome-logo" src="/Assets/Images/Logo.png?v=20260728-8" alt="Willena English Academy"><div class="welcome-panel"><h1>'+tx("welcomeTitle")+'</h1><button class="welcome-start" id="welcomeStart" type="button">'+tx("start")+'</button></div></div>',dir);return}var meta='<div class="setup-progress"><span>'+tx("step")+' '+step+' / 4</span><div><i style="width:'+(step/4*100)+'%"></i></div></div>';if(step===1){screen(meta+'<h2>'+tx("grade")+'</h2>'+optionButtons([[1,tx("preschool")],[2,tx("e12")],[4,tx("e34")],[6,tx("e56")],[8,tx("middle")],[9,tx("older")]],"grade")+'<div class="actions"><button class="btn btn-ghost" id="back">'+tx("back")+'</button></div>',dir);return}if(step===2){screen(meta+'<h2>'+tx("years")+'</h2>'+optionButtons([[0,tx("none")],[1,tx("under1")],[2,tx("y12")],[4,tx("y35")],[6,tx("over5")]],"years")+'<div class="actions"><button class="btn btn-ghost" id="back">'+tx("back")+'</button></div>',dir);return}if(step===3){screen(meta+'<h2>'+tx("listening")+'</h2><p class="setup-hint">'+tx("listenHint")+'</p>'+optionButtons([[1,tx("listenYes")],[0,tx("listenNo")]],"listening")+'<div class="actions"><button class="btn btn-ghost" id="back">'+tx("back")+'</button></div>',dir);return}screen(meta+'<h2>'+tx("length")+'</h2>'+optionButtons([[20,tx("q20")],[30,tx("q30")],[40,tx("q40")]],"length")+'<div class="actions"><button class="btn btn-ghost" id="back">'+tx("back")+'</button></div>',dir)}
root.addEventListener("click",function(e){var welcome=e.target.closest("#welcomeStart");if(welcome&&S.view==="setup"&&S.setupStep===0){S.setupStep=1;setup();return}var back=e.target.closest("#back");if(back){S.setupStep=Math.max(0,S.setupStep-1);setup("back");return}var b=e.target.closest(".setup-option");if(b){var holder=b.closest(".setup-options"),key=holder?holder.getAttribute("data-key"):null;if(!key)return;S.setup[key]=Number(b.getAttribute("data-value"));b.classList.add("choice-pulse");if(S.setupStep===4){startTest();return}S.setupStep++;setup();return}var play=e.target.closest("#playAudio");if(play){playListening();return}var token=e.target.closest(".scramble-token");if(token&&S.current&&S.current.type==="sentence_unscramble"){if(token.getAttribute("data-chosen")!==null)S.selected.splice(Number(token.getAttribute("data-chosen")),1);else{var uid=token.getAttribute("data-uid"),item=S.scramblePool.find(function(x){return x.uid===uid});if(item)S.selected.push(item)}updateScrambleUI();return}var choice=e.target.closest(".choice");if(choice){Array.prototype.forEach.call(document.querySelectorAll(".choice"),function(x){x.classList.remove("selected")});choice.classList.add("selected");S.selected=choice.getAttribute("data-value");var next=document.querySelector("#next");if(next)next.disabled=false;return}if(e.target.closest("#next"))submit();if(e.target.closest("#retry")||e.target.closest("#home")){S.view="setup";S.setupStep=0;S.setup={grade:null,years:null,listening:null,length:null};render()}});
function startTest(){document.body.classList.remove("welcome-mode");S.view="test";S.ability=startAbility(S.setup.years,S.setup.grade);S.maxQ=S.setup.length;S.used=new Set();S.answers=[];S.current=null;S.selected=null;S.scramblePool=[];S.wrongByLevel={};S.typeCounts={};S.translationCount=0;S.playsLeft=0;S.isSpeaking=false;nextQuestion()}
function listeningLimit(){return S.maxQ<=20?5:S.maxQ<=30?8:10}
function typePenalty(q){var used=S.typeCounts[q.type]||0,penalty=used*.8;if(q.type==="listening"&&used>=listeningLimit())penalty+=100;if(q.translation){var maxTranslations=S.ability<=3?Math.max(1,Math.floor(S.maxQ*.1)):Math.max(2,Math.floor(S.maxQ*.2));if(S.translationCount>=maxTranslations)penalty+=20;else penalty+=2}return penalty}
function pickQuestion(){var target=clamp(Math.round(S.ability),1,10),pool=bank.filter(function(q){return !S.used.has(q.id)&&(S.setup.listening===1||q.type!=="listening")});if(!pool.length)return null;var nearest=Math.min.apply(null,pool.map(function(q){return Math.abs(q.level-target)}));pool=pool.filter(function(q){return Math.abs(q.level-target)===nearest});return pool.map(function(q){return{q:q,d:typePenalty(q)+Math.random()*.45}}).sort(function(a,b){return a.d-b.d})[0].q}
function nextQuestion(){if(S.answers.length>=S.maxQ){finish();return}S.current=pickQuestion();if(!S.current){finish();return}S.used.add(S.current.id);S.isSpeaking=false;S.playsLeft=S.current.type==="listening"?(Number(S.current.metadata&&S.current.metadata.max_plays)||2):0;if(S.current.type==="sentence_unscramble"){S.selected=[];S.scramblePool=shuffle(S.current.tokens.map(function(text,index){return{text:text,uid:index+"-"+Math.random()}}))}else{S.selected=null;S.scramblePool=[]}renderTest()}
function scrambleParts(){var chosen=Array.isArray(S.selected)?S.selected:[],used=new Set(chosen.map(function(x){return x.uid})),available=S.scramblePool.filter(function(x){return !used.has(x.uid)});return{chosen:chosen,available:available}}
function renderScramble(){var parts=scrambleParts(),chosen=parts.chosen,available=parts.available,meaning=S.current&&S.current.meaning||"";return '<p class="prompt scramble-instruction">'+tx("unscramble")+'</p>'+(meaning?'<div class="scramble-meaning"><strong>'+escText(meaning)+'</strong></div>':"")+'<div class="scramble-answer '+(chosen.length?"has-tokens":"")+'">'+(chosen.map(function(x,i){return '<button class="scramble-token chosen" data-chosen="'+i+'">'+escText(x.text)+'</button>'}).join("")||'<span>'+tx("tapUndo")+'</span>')+'</div><div class="scramble-bank">'+available.map(function(x){return '<button class="scramble-token" data-uid="'+escAttr(x.uid)+'">'+escText(x.text)+'</button>'}).join("")+'</div>'}
function updateScrambleUI(){var card=root.querySelector(".question-card");if(!card)return;card.innerHTML=renderScramble();var next=root.querySelector("#next");if(next)next.disabled=S.selected.length!==S.current.tokens.length}
function listeningMarkup(q){return '<div class="listening-panel"><div class="listening-icon" aria-hidden="true">🎧</div><p>'+tx("listenInstruction")+'</p><button class="listen-button" id="playAudio" type="button" '+(S.playsLeft<=0||S.isSpeaking?'disabled="disabled"':'')+'><span>'+ (S.isSpeaking?tx("playing"):tx("play"))+'</span></button><small id="playsRemaining">'+S.playsLeft+' '+tx("playsLeft")+'</small></div><p class="prompt listening-question">'+escText(q.q)+'</p>'}
function renderTest(){document.body.classList.remove("welcome-mode");var q=S.current,n=S.answers.length+1,isScramble=q.type==="sentence_unscramble",isListening=q.type==="listening";screen('<div class="question-meta"><span>'+tx("question")+' '+n+'</span><span>'+n+' / '+S.maxQ+'</span></div><div class="progress"><i style="width:'+(S.answers.length/S.maxQ*100)+'%"></i></div><div class="question-card" data-question-level="'+escAttr(q.level)+'">'+(isScramble?renderScramble():(isListening?listeningMarkup(q):'<p class="prompt">'+escText(q.q)+'</p>')+'<div class="choices">'+shuffle(q.choices).map(function(c){return '<button class="choice" data-value="'+escAttr(c)+'">'+escText(c)+'</button>'}).join("")+'</div>')+'</div><div class="actions"><button class="btn btn-primary" id="next" '+(isScramble&&S.selected.length===q.tokens.length?'':'disabled="disabled"')+'>'+tx("next")+' →</button></div>')}
function chooseVoice(langCode){var voices=speechSynthesis.getVoices();return voices.find(function(v){return v.lang===langCode&&/Samantha|Ava|Google US English|Microsoft/i.test(v.name)})||voices.find(function(v){return v.lang&&v.lang.indexOf("en")===0})||null}
function playListening(){if(!S.current||S.current.type!=="listening"||S.playsLeft<=0||S.isSpeaking)return;var transcript=String(S.current.metadata&&S.current.metadata.transcript||"").trim();if(!transcript||!("speechSynthesis"in window)){replaceBrokenListening();return}speechSynthesis.cancel();var utterance=new SpeechSynthesisUtterance(transcript);utterance.lang=S.current.metadata&&S.current.metadata.lang||"en-US";utterance.rate=Number(S.current.metadata&&S.current.metadata.rate)||.9;var voice=chooseVoice(utterance.lang);if(voice)utterance.voice=voice;S.isSpeaking=true;S.playsLeft--;refreshListenButton();utterance.onend=function(){S.isSpeaking=false;refreshListenButton()};utterance.onerror=function(){S.isSpeaking=false;refreshListenButton();if(S.playsLeft===0)replaceBrokenListening()};setTimeout(function(){speechSynthesis.speak(utterance)},50)}
function refreshListenButton(){var b=document.querySelector("#playAudio"),remaining=document.querySelector("#playsRemaining");if(b){b.disabled=S.playsLeft<=0||S.isSpeaking;var span=b.querySelector("span");if(span)span.textContent=S.isSpeaking?tx("playing"):tx("play")}if(remaining)remaining.textContent=S.playsLeft+' '+tx("playsLeft")}
function replaceBrokenListening(){S.used.add(S.current.id);S.current=null;nextQuestion()}
function escText(s){return String(s).replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/>/g,"&gt;")}
function escAttr(s){return escText(s).replace(/"/g,"&quot;")}
function submit(){var q=S.current,isScramble=q.type==="sentence_unscramble",selectedAnswer=isScramble?S.selected.map(function(x){return x.text}):S.selected,ok=isScramble?JSON.stringify(selectedAnswer)===JSON.stringify(q.tokens):selectedAnswer===q.a,e=expected(S.ability,q.level),delta=.95*confidenceFactor()*((ok?1:0)-e);if(ok)delta*=wrongPenalty(q.level);else S.wrongByLevel[q.level]=(S.wrongByLevel[q.level]||0)+1;S.ability=clamp(S.ability+delta,1,10);S.typeCounts[q.type]=(S.typeCounts[q.type]||0)+1;if(q.translation)S.translationCount++;S.answers.push({id:q.id,level:q.level,type:q.type,correct:ok,selected:selectedAnswer,answer:q.a});nextQuestion()}
function descriptor(l){var en=["First words and simple answers","Basic questions and present actions","Everyday routines and simple sentence patterns","Time, place and common present-tense language","Past, future and advice","Comparisons, plans and present perfect","Longer sentence patterns and passive forms","Conditionals and connected ideas","Complex grammar and implied meaning","Relative clauses and advanced sentence control"],ko=["기초 단어와 간단한 대답","기초 질문과 현재 동작 표현","일상생활과 간단한 문장 패턴","시간, 장소와 기본 현재 시제","과거, 미래와 조언 표현","비교급, 계획과 현재완료","긴 문장 패턴과 수동태","조건문과 연결된 생각 표현","복잡한 문법과 함축적 의미","관계절과 고급 문장 활용"];return(lang==="ko"?ko:en)[l-1]}
function finish(){if(window.speechSynthesis)window.speechSynthesis.cancel();var l=clamp(Math.round(S.ability),1,10),correct=S.answers.filter(function(x){return x.correct}).length;S.result={l:l,correct:correct};S.view="result";render()}
function result(){document.body.classList.remove("welcome-mode");var l=S.result.l,correct=S.result.correct;screen('<span class="eyebrow">'+tx("result")+'</span><div class="result-title">'+tx("level")+' '+l+'</div><p class="lead">'+tx("broad")+'</p><div class="result-grid"><div class="result-card"><span>'+tx("answered")+'</span><strong>'+S.answers.length+'</strong></div><div class="result-card"><span>'+tx("correct")+'</span><strong>'+correct+'</strong></div></div><div class="can-do"><h3>'+tx("can")+'</h3><p style="margin-bottom:0">'+descriptor(l)+'</p></div><div class="actions"><button class="btn btn-primary" id="retry">'+tx("retry")+'</button><button class="btn btn-ghost" id="home">'+tx("home")+'</button></div>')}
function render(){if(S.view==="test")renderTest();else if(S.view==="result")result();else setup()}
if(typeof loadQuestionBank!=="function"){screen('<h2>'+tx("loadFail")+'</h2><p class="error">페이지를 새로고침해 주세요.</p>');return}
chrome();render();
loadQuestionBank().then(function(x){bank=x}).catch(function(e){screen('<h2>'+tx("loadFail")+'</h2><p class="error">'+escText(e.message)+'</p>')});
})();