import{loadQuestionBank}from"./question-loader.js";
import{Storage}from"./storage.js";
const root=document.querySelector("#app"),langBtn=document.querySelector("#languageBtn"),brandSubtitle=document.querySelector("#brandSubtitle"),footerText=document.querySelector("#footerText");
let bank=[],lang="en";
const clamp=(v,a,b)=>Math.max(a,Math.min(b,v)),shuffle=a=>[...a].sort(()=>Math.random()-.5);
const T={en:{brand:"Free Level Test",footer:"Willena English · Staging assessment",tag:"Adaptive English test",title:"Find the right starting level",intro:"Answer one question at a time. The test quietly adjusts the difficulty as you go.",grade:"School stage",years:"Years studying English",preschool:"Preschool",e12:"Elementary 1–2",e34:"Elementary 3–4",e56:"Elementary 5–6",middle:"Middle school",older:"High school or adult",none:"Not yet",under1:"Less than 1 year",y12:"1–2 years",y35:"3–5 years",over5:"More than 5 years",length:"Test length",q20:"Quick · 20 questions",q30:"Standard · 30 questions",q40:"Detailed · 40 questions",start:"Start test",question:"Question",next:"Next",result:"Your estimated level",broad:"This is a broad starting point based on the adaptive questions.",answered:"Questions answered",correct:"Correct answers",level:"Level",can:"Suggested starting point",retry:"Try again",home:"Back to start",loadFail:"Could not load the test",previous:"Previous result"},ko:{brand:"무료 영어 레벨 테스트",footer:"Willena English · 스테이징 진단 테스트",tag:"적응형 영어 테스트",title:"알맞은 영어 시작 단계를 찾아보세요",intro:"한 번에 한 문제씩 풀어 보세요. 답변에 따라 다음 문제의 난이도가 자동으로 조절됩니다.",grade:"학교 단계",years:"영어 학습 기간",preschool:"유치원",e12:"초등학교 1–2학년",e34:"초등학교 3–4학년",e56:"초등학교 5–6학년",middle:"중학교",older:"고등학생 또는 성인",none:"아직 배우지 않음",under1:"1년 미만",y12:"1–2년",y35:"3–5년",over5:"5년 이상",length:"테스트 길이",q20:"간단 · 20문제",q30:"기본 · 30문제",q40:"자세히 · 40문제",start:"테스트 시작",question:"문제",next:"다음",result:"예상 영어 단계",broad:"적응형 문제 결과를 바탕으로 한 대략적인 시작 단계입니다.",answered:"푼 문제",correct:"정답",level:"단계",can:"추천 시작 단계",retry:"다시 하기",home:"처음으로",loadFail:"테스트를 불러올 수 없습니다",previous:"이전 결과"}};
const tx=k=>T[lang][k]||k;
let S={view:"setup",ability:2,maxQ:30,used:new Set(),answers:[],current:null,selected:null,wrongByLevel:{}};
function chrome(){document.documentElement.lang=lang;langBtn.textContent=lang==="en"?"한국어":"English";brandSubtitle.textContent=tx("brand");footerText.textContent=tx("footer")}
langBtn.onclick=()=>{lang=lang==="en"?"ko":"en";chrome();render()};
function screen(html){root.innerHTML=`<section class="screen">${html}</section>`}
function startAbility(years,grade){return clamp(1+(+years*1.15)+((+grade-1)*.45),1,9.2)}
function expected(a,d){return 1/(1+Math.exp((d-a)*1.1))}
function confidenceFactor(){return Math.max(.28,1-(S.answers.length*.035))}
function wrongPenalty(level){return Math.pow(.8,S.wrongByLevel[level]||0)}
function history(){const a=Storage.load().attempts||[];if(!a.length)return"";const x=a[0];return `<div class="history-card"><strong>${tx("previous")}</strong><div>${tx("level")} ${x.level} · ${new Date(x.date).toLocaleDateString(lang==="ko"?"ko-KR":"en-GB")}</div></div>`}
function setup(){screen(`<span class="eyebrow">${tx("tag")}</span><h1>${tx("title")}</h1><p class="lead">${tx("intro")}</p><div class="stack"><label><span class="field-label">${tx("grade")}</span><select id="grade" class="field"><option value="1">${tx("preschool")}</option><option value="2">${tx("e12")}</option><option value="4">${tx("e34")}</option><option value="6">${tx("e56")}</option><option value="8">${tx("middle")}</option><option value="9">${tx("older")}</option></select></label><label><span class="field-label">${tx("years")}</span><select id="years" class="field"><option value="0">${tx("none")}</option><option value="1">${tx("under1")}</option><option value="2">${tx("y12")}</option><option value="4">${tx("y35")}</option><option value="6">${tx("over5")}</option></select></label><label><span class="field-label">${tx("length")}</span><select id="length" class="field"><option value="20">${tx("q20")}</option><option value="30" selected>${tx("q30")}</option><option value="40">${tx("q40")}</option></select></label></div><div class="actions"><button class="btn btn-primary" id="start">${tx("start")} →</button></div>${history()}`);document.querySelector("#start").onclick=()=>{S={view:"test",ability:startAbility(document.querySelector("#years").value,document.querySelector("#grade").value),maxQ:+document.querySelector("#length").value,used:new Set(),answers:[],current:null,selected:null,wrongByLevel:{}};nextQuestion()}}
function pickQuestion(){const target=clamp(Math.round(S.ability),1,10);let pool=bank.filter(q=>!S.used.has(q.id));if(!pool.length)return null;return pool.map(q=>({q,d:Math.abs(q.level-target)+Math.random()*.45})).sort((a,b)=>a.d-b.d)[0].q}
function nextQuestion(){if(S.answers.length>=S.maxQ){finish();return}S.current=pickQuestion();if(!S.current){finish();return}S.used.add(S.current.id);S.selected=null;renderTest()}
function renderTest(){const q=S.current,n=S.answers.length+1;screen(`<div class="question-meta"><span>${tx("question")} ${n}</span><span>${n} / ${S.maxQ}</span></div><div class="progress"><i style="width:${(S.answers.length/S.maxQ)*100}%"></i></div><div class="question-card"><p class="prompt">${q.q}</p><div class="choices">${shuffle(q.choices).map(c=>`<button class="choice" data-value="${esc(c)}">${c}</button>`).join("")}</div></div><div class="actions"><button class="btn btn-primary" id="next" disabled>${tx("next")} →</button></div>`);const next=document.querySelector("#next");document.querySelectorAll(".choice").forEach(b=>b.onclick=()=>{document.querySelectorAll(".choice").forEach(x=>x.classList.remove("selected"));b.classList.add("selected");S.selected=b.dataset.value;next.disabled=false});next.onclick=submit}
function esc(s){return String(s).replaceAll("&","&amp;").replaceAll('"',"&quot;")}
function submit(){const q=S.current,ok=S.selected===q.a,e=expected(S.ability,q.level);let delta=.95*confidenceFactor()*((ok?1:0)-e);if(ok)delta*=wrongPenalty(q.level);else S.wrongByLevel[q.level]=(S.wrongByLevel[q.level]||0)+1;S.ability=clamp(S.ability+delta,1,10);S.answers.push({id:q.id,level:q.level,correct:ok,selected:S.selected,answer:q.a});nextQuestion()}
function descriptor(l){const en=["First words and simple answers","Basic questions and present actions","Everyday routines and simple sentence patterns","Time, place and common present-tense language","Past, future and advice","Comparisons, plans and present perfect","Longer sentence patterns and passive forms","Conditionals and connected ideas","Complex grammar and implied meaning","Relative clauses and advanced sentence control"];const ko=["기초 단어와 간단한 대답","기초 질문과 현재 동작 표현","일상생활과 간단한 문장 패턴","시간, 장소와 기본 현재 시제","과거, 미래와 조언 표현","비교급, 계획과 현재완료","긴 문장 패턴과 수동태","조건문과 연결된 생각 표현","복잡한 문법과 함축적 의미","관계절과 고급 문장 활용"];return(lang==="ko"?ko:en)[l-1]}
function finish(){const l=clamp(Math.round(S.ability),1,10),correct=S.answers.filter(x=>x.correct).length,attempt={date:new Date().toISOString(),level:l,title:`Level ${l}`,questionIds:S.answers.map(x=>x.id)};Storage.addAttempt(attempt);S.result={l,correct};S.view="result";render()}
function result(){const {l,correct}=S.result;screen(`<span class="eyebrow">${tx("result")}</span><div class="result-title">${tx("level")} ${l}</div><p class="lead">${tx("broad")}</p><div class="result-grid"><div class="result-card"><span>${tx("answered")}</span><strong>${S.answers.length}</strong></div><div class="result-card"><span>${tx("correct")}</span><strong>${correct}</strong></div></div><div class="can-do"><h3>${tx("can")}</h3><p style="margin-bottom:0">${descriptor(l)}</p></div><div class="actions"><button class="btn btn-primary" id="retry">${tx("retry")}</button><button class="btn btn-ghost" id="home">${tx("home")}</button></div>`);document.querySelector("#retry").onclick=()=>{S.view="setup";render()};document.querySelector("#home").onclick=()=>{S.view="setup";render()}}
function render(){S.view==="test"?renderTest():S.view==="result"?result():setup()}
loadQuestionBank().then(x=>{bank=x;chrome();render()}).catch(e=>screen(`<h2>${tx("loadFail")}</h2><p class="error">${e.message}</p>`));